### ISSUE TITLE
Ability to enforce more than one review before merging.

### ISSUE THREAD

**Issue by mrbinky3000** [isaacs/github#1001]
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/

> "Repository administrators can enforce required reviews so that pull requests must have **at least one** approved review before they are merged."

Can I request a feature?

Simply change "at least one approved review" into "at least X approved reviews" where X is a number that we can set.  

This is not confusing.

Basically, X people have to approve a PR.  After the X threshold is reached, the normal process of merging a PR that exists today can continue.

It's as simple as turning the hard coded constant of 1 in your code into a variable.  There's obviously an if statement someplace in your code that compares the number of approved reviews to the number 1.   Just change all those checks from "1" to X!  Easy!  😊

Thanks!

- Matt

**Comment by djshapiro** [comment]
+1

**Comment by nicholasbaileyrally** [comment]
+1 for removing arbitrary hard coded constants!

**Comment by AlecBenzer** [comment]
+1 as a nice feature, but I think it's a little naive to assume "just" replacing a constant with a user-configurable value is easy. There's likely a lot of plumbing involved.

**Comment by JT-Bruch** [comment]
+1 This would be really nice, our company has a policy of at least 2 approvers before merging and being able to set this would allow us to remove some additional checks & overhead that we have to deal with.

**Comment by yelizariev** [comment]
This can be easily implemented via status check. I wonder, is there ready solution?

https://developer.github.com/v3/guides/building-a-ci-server/
https://developer.github.com/v3/pulls/reviews/

**Comment by ulfgebhardt** [comment]
Bump - this feature is required for Open Source Projects with People of different Knowledge Levels.

**Comment by geonerd81** [comment]
+1 agree w/ all points above.  This feature would be great.  Additionally, being able to have organization 'levels' of required pr reviewers, e.g., something like basic (1 required reviewer) vs. critical (x reviewers)

**Comment by gitmlynch** [comment]
@yelizariev Forgive me, I don't see how the links you provided point to a status check based solution.

**Comment by yelizariev** [comment]
@gitmlynch I don't know any ready to use solution, so my links cannot point to them. 
My suggestion is to create status check (first link) which will get information about reviews (second link) and set appropriate status of a PR

**Comment by ulfgebhardt** [comment]
Have seen this in a Project:
https://pullapprove.com/salesagility/SuiteCRM/pull-request/4994/

**Comment by gitmlynch** [comment]
@ulfgebhardt, thanks. That's an interesting service, though seems like an expensive solution to this specific problem.

**Comment by THEhEROLocker** [comment]
I wrote a little something referring to the links posted by @yelizariev . https://github.com/THEhEROLocker/GithubCI-PullRequest-count-control

**Comment by woodyspawnshop** [comment]
Another case to consider would be if multiple teams are requested for review (especially in light of `CODEOWNERS`) one may want to require _n_ approval(s) from each team.

**Comment by evertonfraga** [comment]
@ulfgebhardt thanks for the suggestion, that seems like a nice polyfill for the open source repositories I work on.

**Comment by ehamiter** [comment]
👍

**Comment by sridhar-vadlamani-ck** [comment]
This seems to have been implemented. However, it's not available via the API yet.

**Comment by gtlambert** [comment]
@sridhar-vadlamani-ck how can I implement this in my project?

**Comment by sridhar-vadlamani-ck** [comment]
@gtlambert If you protect your default branch, there is now an option to specify the number of required reviews.

![image](https://user-images.githubusercontent.com/26975170/37615866-7f3c0e38-2b6b-11e8-9882-b6b5cbdf49fc.png)

**Comment by ulfgebhardt** [comment]
@mrbinky3000 please close

**Comment by GaboFDC** [comment]
Since when was this added? We have waiting for this long ago, and suddendly it appeared. I didn't say any post about this in announcements (https://blog.github.com/category/announcements/)
Is there any other place where they inform about this features?

**Comment by evertonfraga** [comment]
I saw this on monday or so. pretty sure it’s new.

**Comment by aanich-assf** [comment]
@sridhar-vadlamani-ck Thank you for screen-shotting that setting! Very helpful.

There is one thing that I would LOVE to see in addition to this feature.

![screen shot 2018-04-20 at 10 49 18 am](https://user-images.githubusercontent.com/37088337/39066049-9af57ae8-4488-11e8-96f3-64eba86ee055.png)

If the Pull Request does not meet the amount of require approving review, it should not show `Approved`. Instead it should show `Needs X Approvals` or `Review Requested`. This would make it 100% easier to glance over the existing PRs and see if one is close to meeting the approval requirements.

**Comment by BrianChristman** [comment]
Our company has a policy that we require 2 reviewers approval but the selection isn't showing for us.  We're currently running GitHub Enterprise 2.13.1.  When will this feature be available for us to use?  Is there documentation that shows when this has been added to GHE?

**Comment by taupecat** [comment]
+1 @BrianChristman

**Comment by sridhar-vadlamani-ck** [comment]
@BrianChristman You can implement a simple webhook which is `required` in order for Pull Requests to pass.

**Comment by TeresaP** [comment]
@sridhar-vadlamani-ck Can you explain how to do that? I've tried looking for wikis but came up empty.

**Comment by clarkbw** [comment]
@sridhar-vadlamani-ck https://developer.github.com/v3/repos/branches/#get-branch-protection

use `application/vnd.github.luke-cage-preview+json` in the accept header
