### ISSUE TITLE
Add ability to pin comments in really long issue threads

### ISSUE THREAD

**Issue by danny-andrews** [isaacs/github#1008]
There are some issues which have been solved for a long time, but the threads are [so long](https://github.com/webpack/webpack/issues/2867) that people have a difficult time finding the solution. Leaving a final comment and closing the discussion works, but feels heavy-handed and prevents people from adding more info/voicing confusion over the proposed solution. It would be nice for collabs to have a way to pin a comment which is the "tried-and-true" way to solve a certain issue.

**Comment by cirosantilli** [comment]
Possible alternative: sort comments by upvote: https://github.com/isaacs/github/issues/601

Current workaround: edit the post description

**Comment by danny-andrews** [comment]
> Current workaround: edit the post description

That's a nice workaround. I like it.
