### ISSUE TITLE
Option to subscribe to certain repos with an alternate email address

### ISSUE THREAD

**Issue by sparr** [isaacs/github#1018]
I am part of some organizations which also, separately, provide me with an email account. I would like notifications about projects in those organizations to go to the email account in question. I can already specify multiple email addresses in my account settings on github. I want to be able to attach those email addresses to subscriptions at the level of individual items, or repos, or orgs.

**Comment by jmarshall** [comment]
You can at the organisation level, under Personal Settings :: Notifications.

Occasionally it would be nice at an individual repository level, but this is most of the way there.

**Comment by sparr** [comment]
That's actually exactly what I need. Thank you!
