### ISSUE TITLE
can only fork a repository once

### ISSUE THREAD

**Issue by aspiers** [isaacs/github#1094]
AFAICS once you've forked a repository, you can't fork it again to another private repository.  This would be useful if there was an upstream "template" repository of some sort which was designed to be cloned and changed in divergent ways, for example https://github.com/fghaas/presentation-template.  In that case you still might want to submit pull requests changing the template, and those submissions would ideally not be restricted to coming from a single fork.

**Comment by AlecBenzer** [comment]
FYI, the instructions at https://help.github.com/articles/duplicating-a-repository/ can help with this (and are in fact neccesary anyway if you want to make a private fork of a public repository).

**Comment by mwarkentin** [comment]
This is a thing now: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository
