### ISSUE TITLE
An option for maintainers to provide OOTO message

### ISSUE THREAD

**Issue by trivikr** [isaacs/github#1095]
This request is coming from https://github.com/buzinas/tslint-eslint-rules/pull/255
- The requestor originally created https://github.com/buzinas/tslint-eslint-rules/issues/251 to check which issues he and his friends can work on as part of a hackathon
- As a test pull request, https://github.com/buzinas/tslint-eslint-rules/pull/255 was posted

The maintainer was on vacation and there was no response on the Pull Request.
So requestor and his friends moved to other Open Source projects assuming that project is abandoned. The pull request was reviewed and merged after a month.

**Problem Description**: There are many Github projects which are maintained by few people. They might not be able to respond to issues/PRs because of several reasons (most maintainers have a full-time job)
**Fix suggestion**: Is there an easy option for maintainers to provide OOTO message to issues/PRs? If not, can you provide one?

**Comment by trivikr** [comment]
Response from Alex (GitHub Staff) over email:

```
Hey Trivikram,

I've added this to our internal feature request list, though I can't say if/when the feature might be added.

Thanks for the feedback,
Alex
```

**Comment by trivikr** [comment]
Update from Alex (Github Staff) over email in Aug 2018:

```
Hi Trivikram,

Thanks for following up on this request! We have not yet implemented a feature like this, but I have added a note to our internal list documenting your continued support.

I can't say when the team will be able to implement this feature, but thank you again for reaching out!

Cheers,
Alex
```

**Comment by orrc** [comment]
I believe this is covered by the "busy" option in profile status, which was added a couple of months ago:
https://help.github.com/en/articles/personalizing-your-profile#setting-a-status

**Comment by trivikr** [comment]
Closing, as this option is kind-of covered by "busy" option in profile status
