### ISSUE TITLE
A single private `_self` repo for all accounts

### ISSUE THREAD

**Issue by adrianhopebailie** [isaacs/github#1096]
As the array of tools and integrations on Github grow it seems feasible to migrate a lot of personal tools onto the platform, e.g.

1. Projects for personal kanban boards
2. Issues for personal todo lists
3. Wiki for personal notes etc

Unfortunately this is not information that most users would want to make public and yet the monthly fee for private repos seems like a steep price for this single repo, especially if the majority of users are also part of organizations paying for Github accounts on their behalf.

## Proposal

Allow all users to create a single private repo for this purpose (perhaps lock the repo name to _self) and if necessary apply some other restrictions (size limits etc) that incentivize them to pay for a private repo if they need it for other purposes.

**Comment by adrianhopebailie** [comment]
Response from GitHub:

> Hi Adrian,

> Thanks for your feedback! We're always working to improve GitHub and we consider every suggestion we receive. I've sent along your suggestions to the appropriate teams!

> Thanks for the idea!

> Best,
> Kimmy

**Comment by erkinalp** [comment]
Why not name the repository the same as username like C++/Java/C# constructors?

**Comment by gloomgarden** [comment]
Now that everyone can create private repos, this should be closed.
