### ISSUE TITLE
Github PR takes some time to update diff from forked private branches

### ISSUE THREAD

**Issue by trivikr** [isaacs/github#1098]
Hi,

We noticed this issue in some of the pull requests given below:
- https://github.com/nodejs/node/pull/16246#issuecomment-337285466
- https://github.com/nodejs/node/pull/16305

Github PR states
`Add more commits by pushing to the <private> branch on <username>/<forked-project-name>.`

The diff from forked private branch takes some time to appear. New developers may spend that time investigating what's going wrong.

If fetching of diff is taking time, may be "Files changed" section of Github PR can show a loading symbol?

Regards,
Trivikram

**Comment by trivikr** [comment]
Email sent to support@github.com

**Comment by trivikr** [comment]
Update: Github was experiencing a large queue backlog which was delaying commits from appearing in PRs https://status.github.com/messages/2017-10-17

I've asked if fetching of diff is taking time, if "Files changed" section of Github PR can show a loading symbol or something similar to indicate the delay.

**Comment by dead-H** [comment]
test
