### ISSUE TITLE
Rename repo event

### ISSUE THREAD

**Issue by jakirkham** [isaacs/github#1108]
Would be nice if the [`repository` event]( https://developer.github.com/v3/activity/events/types/#repositoryevent ) (or similar event) could be sent went a repo is renamed.

Edit: Also emailed GitHub support asking for this and included a link back to this issue.

**Comment by hschne** [comment]
Searching for `github api repository renamed event` and I land here. 

Since this has been open since 2017: Is this still the status quo? There is no repository event sent on renaming the repository? 

Would be nice if there was :heart:

**Comment by mc422** [comment]
Search for `Github webhook repository rename event` too.

Would be nice to have this event under repository

**Comment by hatboysam** [comment]
Just found this via Google but it should be closed, `repository.renamed` exists now
