### ISSUE TITLE
[Bug] Wrong commit recognition of the tag

### ISSUE THREAD

**Issue by sebres** [isaacs/github#1109]
### Issue:
If you target a **tag** (e. g. by selecting in the select-box "Branch") on the project main page (e. g. "\<\> Code"), you'll see a wrong commit as "Latest commit".

For example: https://github.com/fail2ban/fail2ban/tree/0.10.1 shows as the latest commit [b698a749029af2c216268aa29a1228f21e87bfb7](https://github.com/fail2ban/fail2ban/commit/b698a749029af2c216268aa29a1228f21e87bfb7), but actually [351abeb4ff77dfca4049e7401553900b46e8db40](https://github.com/fail2ban/fail2ban/commit/351abeb4ff77dfca4049e7401553900b46e8db40) is the latest commit of tag 0.10.1.

This results in **wrong content of each file** belonging this tag.
E.g. view of [README.md](https://github.com/fail2ban/fail2ban/blob/0.10.1/README.md) or [ChangeLog](https://github.com/fail2ban/fail2ban/blob/0.10.1/ChangeLog) show the obsolete content.

### Observed behavior:
You don't see the last commit of the release tag, and therefore each link points to obsolete content of any file within...

### Expected behavior:
You see the current commit of the tags, as well as the current content of the files within the tag.

**Comment by AlecBenzer** [comment]
When looking at the GitHub UI, I see a *branch* in that repo called 0.10.1, but there's no 0.10.1 tag as far as I can tell (and in fact there could not be given that the branch exists, since branches and tag share a namespace AFAIK).

However, when I clone the repo locally, 0.10.1 does appear as a tag.

I'm not sure why GitHub sees this tag as actually being a branch. Was there once a branch called '0.10.1' on the repo?

**Comment by szepeviktor** [comment]
> there could not be given that the branch exists, since branches and tag share a namespace

It may be the cause of confusion.

**Comment by sebres** [comment]
> However, when I clone the repo locally, 0.10.1 does appear as a tag, not a branch.

This is a tag (even created within github, using "Draft a new release" button).

> When looking at the GitHub UI, I see a branch in that repo called 0.10.1, but there's no 0.10.1 tag
> I'm not sure why GitHub sees this tag as actually being a branch. 

It's not just this tag affected.
Github has currently this behavior for all tags, **that don't contain slash ('/') character**...
If you check this with `git tag -l` you'll see many many other tags, however you'll not be able to find in this githab list some tag without slash...

> Was there once a branch called '0.10.1' on the repo?

Never

**Comment by AlecBenzer** [comment]
> Github has currently this behavior for all tags, that don't contain slash ('/') character...

Wow, wtf.... this has been reported to support@github.com already, right? Curious what they say. If that's really what's happening that's super weird.

**Comment by sebres** [comment]
> If that's really what's happening that's super weird.

I don't know what really happening there (I don't have a source code of github :)), but it is the current state of the art. At least in this repository... ATM no time to check it everywhere.

**Comment by sebres** [comment]
Another interesting thing is that the other release-tags (without `/` char) are not visible on github at all (neither in branch-list, nor in tag-list).
But we can build an URL (e. g. [https://github.com/fail2ban/fail2ban/tree/0.9.6](https://github.com/fail2ban/fail2ban/tree/0.9.6)) , which is callable and seems to use correct last commit (

**Comment by sebres** [comment]
BTW still no reaction from github until now.

**Comment by sebres** [comment]
New findings: I've pushed the tags 0.10.1 (and 0.10.0) to my own fork right now.
Both tags are invisible, but the https://github.com/sebres/fail2ban/tree/0.10.1 shows the correct commit [351abeb], as well as the correct content there.

Confused!?...

**Comment by sebres** [comment]
So, I got an answer from github-support, below you'll find it together with my answer:

<blockquote type="cite" style="padding-left: 5px; border-left: #1010ff 2px solid; margin-left: 5px">
02 Nov 2017 15:45, @staceb wrote:
<p>Hey Serg,</p>
<p>The <a href="https://github.com/fail2ban/fail2ban/blob/0.10.1/ChangeLog" target="_blank" rel="noreferrer">https://github.com/fail2ban/fail2ban/blob/0.10.1/ChangeLog</a> link takes you to the latest version of the ChangeLog file on tag 0.10.1.</p>
</blockquote>
<p>You are wrong here, the latest version of the file ChangeLog (in this tag) is 351abeb4ff77dfca4049e7401553900b46e8db40 (but also the README.md and several other files).</p>
<p>The version that we see is another version.<br>In-between I made more tests (see the whole discussion under <a href="https://github.com/isaacs/github/issues/1109" target="_blank" rel="noreferrer">isaacs/github/#1109</a>): <br>for example you can test another link (the same tag/commit in my own fork), where it works:</p>
<p>Thus compare:<br>1. <a href="https://github.com/sebres/fail2ban/tree/0.10.1" target="_blank" rel="noreferrer">https://github.com/sebres/fail2ban/tree/0.10.1<br></a>with the same in fork:<br>2. <a href="https://github.com/fail2ban/fail2ban/tree/0.10.1" target="_blank" rel="noreferrer">https://github.com/fail2ban/fail2ban/tree/0.10.1</a></p>
<p>What did you see there?</p>

```diff
+1. Tag: 0.10.1
-2. Branch: 0.10.1
+1. Latest commit 351abeb
-2. Latest commit b698a74
+1. in the README: FAIL2BAN v0.10.1 2017/10/12
-2. in the README: FAIL2BAN v0.10.1 2016/??/??
...
-2. each link on file show the wrong content (another version).
```
<blockquote type="cite" style="padding-left: 5px; border-left: #1010ff 2px solid; margin-left: 5px">
<p>The commit you see there is the commit of the last time that file was edited on the tag, rather than the tagged commits itself.</p>
<p><a href="https://github.com/fail2ban/fail2ban/commits/0.10.1/ChangeLog" target="_blank" rel="noreferrer">https://github.com/fail2ban/fail2ban/commits/0.10.1/ChangeLog</a></p>
<p>Sorry for the confusion on that one and let me know if you need anything else.</p>
</blockquote>
As already said, just take a look under <a href="https://github.com/isaacs/github/issues/1109" target="_blank" rel="noreferrer">isaacs/github/#1109</a> resp. try to clone this repo <br>(fail2ban/fail2ban) and try to see which commit it is:</p>

```bash
$ git show-ref --tags 0.10.1
351abeb4ff77dfca4049e7401553900b46e8db40 refs/tags/0.10.1
$ git rev-list -1 0.10.1
351abeb4ff77dfca4049e7401553900b46e8db40
```
<blockquote type="cite" style="padding-left: 5px; border-left: #1010ff 2px solid; margin-left: 5px">
<p>Cheers<br> Stacey</p>
</blockquote>

**Comment by sebres** [comment]
I found now what it is: there was indeed still a old branch (with name 0.10.1) there. No idea how this branch was created.
After removing of this branch, it looks good now.

**Comment by sebres** [comment]
JBTW I was a bit wrong with my conclusion for invisibility of some tags in the tag-list on `<> Code` page:
The tag seems to be invisible if the name:
- either does not contain any letter (in our case only nummer and dot);
- or does not start from the letter (in our case only starts from nummer).
It doesn't matter currently, whenever the tag was released (over github interface) or just pushed via git.
