### ISSUE TITLE
Contributions to organisations that you are not longer member of

### ISSUE THREAD

**Issue by sielay** [isaacs/github#1114]
It's more a question of the opinion. Imagine a situation that I have been responsible for few projects which a) are open source b) are public c) are maintained by some organization (mostly some company that publish their code). After I stopped working in that organization I have been removed from their GH team. This moment my profile lacks any data about my contribution to those projects, even when 100% code was made by me and my contribution is still visible in that project to the public. I think it punishes a bit contributors for moving in their career.

**Comment by ericnewton76** [comment]
Contributions should be permanent, and not tied to a database query... 👍

**Comment by sielay** [comment]
Maybe they should use blockchain for it ;)

**Comment by clarkbw** [comment]
Feels like this is a dupe of https://github.com/isaacs/github/issues/1138

**Comment by TPS** [comment]
Yep.  _(@clarkbw You __do__ have the power to solve that, you know.…)_
