### ISSUE TITLE
Sometimes resolving merge conflicts using the web editor needs to be done twice 

### ISSUE THREAD

**Issue by xoviat** [isaacs/github#1116]

**Comment by jmendezv** [comment]
Not some times. Always!!!

**Comment by carver** [comment]
Some problem, here, essentially always. Here's an example: https://github.com/ethereum/web3.py/pull/523/

**Comment by efc-awebb** [comment]
Literally every single time. There's no indication that the first one does anything, ever.

**Comment by efc-awebb** [comment]
I've reported this to Github Support and linked them to this issue, and got this response:

> Thanks for reaching out to GitHub Support to report this. We're sorry for the trouble!
>
> We're currently investigating similar reports regarding this issue, and I've added your report to our list.
>
> While we don't yet have a specific ETA on a fix, we'll be sure to update you as soon as there's any news to share.

**Comment by efc-awebb** [comment]
@xoviat Github reports this as resolved.

**Comment by jgadbois** [comment]
I'm still experiencing this issue.

**Comment by carver** [comment]
> I'm still experiencing this issue.

Ditto. What's the ditto emoji? :+1: felt wrong

**Comment by samdark** [comment]
Still experiencing it as well.

**Comment by efc-awebb** [comment]
I haven't gotten a chance to test it one way or another in my organization since they reported a fix, but I've responded to their email on this letting them know others are still reporting it as unresolved. Hopefully they'll take another look.
