### ISSUE TITLE
Feature: Add tags to repos

### ISSUE THREAD

**Issue by hachesilva** [isaacs/github#114]
Hi guys.
I have a very simple and useful feature request: the abilty to add tags/categories to repos.

In the past I requested the ability to tag starred and watched repos, but maybe you should let authors to tag their own repos, and repo-watchers and repo-starrers to filter/sort repos by tags.

**Comment by tradeli** [comment]
This would be great! This functionality would come handy for people like me that heavily uses open source projects. I have so many on my want to use list, but they all need to keep in Watch/Starred lists, which is no pratical.

**Comment by TPS** [comment]
https://help.github.com/en/articles/about-topics
