### ISSUE TITLE
Clicking the same link multiple times should not push states to browser history stack multiple times

### ISSUE THREAD

**Issue by golopot** [isaacs/github#1141]
### How to reproduce:
1. Go to https://github.com/isaacs/github
2. Click README.md 5 times rapidly(You might need to throttle network connection speed). Wait for page load.
### Unexpected:
Browser history has 5 entries for README.md
This is bad because you have to click go back 5 times.
### What is expected:
There should be only 1 entry in history stack. A traditional link works like this.
### Who is affected:
I use the touchpad on my laptop, and I often accidentally double click.

**Comment by NobbZ** [comment]
The behaviour you describe is how I expect the history to work.

**Comment by golopot** [comment]
Maybe too minor to fix.
