### ISSUE TITLE
Allow HTML file for a readme

### ISSUE THREAD

**Issue by cbrnrd** [isaacs/github#1144]
This would keep markdown as an option, but add HTML (and some CSS) as a readme type. This could make readme's have a bit more personality. Obviously, javascript wouldn't run as it could be dangerous.

**Comment by kingbuzzman** [comment]
👎

**Comment by kingbuzzman** [comment]
I disagree, respectfully. As someone thats very aware of brand, i would hate it if someone else came and stepped all over my look and feel, tarnishing my site over their inability to close a tag.. at any rate, bad idea. If you want custom style, they've address this with github pages, if you want to change their ui in your readme... i doubt we'll ever see that

**Comment by clarkbw** [comment]
You can embed some HTML in your README markdown file.  Otherwise you can use pages https://pages.github.com/ to create your own custom HTML and CSS. I don't think this request is going to happen.

**Comment by dawhum** [comment]
An interesting use case for this would be embedding Trello cards.
