### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by veysiertekin** [isaacs/github#1148]
This may includes three sections:
- Copy button for gist files [near at 'Raw' button]
- Copy button for embedded gists [near at 'view raw' button]
- Copy button for inline code snippets in markdowns (this may be more challenging)

This feature will solve lots of mouse/trackpad issues and give more time for the focusing on the tasks to developers.

Thank you for all your work.

**Comment by Mottie** [comment]
The [Refined GitHub](https://github.com/sindresorhus/refined-github) extension does most of this for you.
