### ISSUE TITLE
Milestones can't be viewed in archived repositories

### ISSUE THREAD

**Issue by strugee** [isaacs/github#1149]
Just sent this off to GitHub support:

> Basically, what the subject says. To further clarify, I am talking about the exact URLs for milestones, _not_ filters for milestones in the issue tracker. For example, https://github.com/strugee/HelloWorld3/milestone/1.
> 
> Happy holidays <3

**Comment by strugee** [comment]
Response from GitHub support:

> Hey Alex,
> 
> Thanks so much for writing in. Hmm, that doesn't look so helpful. I've asked the engineering team to take a look, thanks for letting us know!
> 
> All the best,
> Rachel
> GitHub Support

**Comment by clarkbw** [comment]
Should be fixed! ✨

**Comment by strugee** [comment]
Can confirm!
