### ISSUE TITLE
protected branches: make "no force pushing" optional

### ISSUE THREAD

**Issue by olets** [isaacs/github#1163]
Protected branches are great. But what I often want is the ability to protect a branch from deletion while still allowing force pushing. 

I can see how in theory "can't delete" should imply "can't force push" - the old branch would be deleted by force push. But surely GitHub can distinguish between a `push :` and a `push --force`/`push --force-with-lease`.

It'd be great to separate out "don't allow force pushing" and "don't allow deletion".

**Comment by olets** [comment]
From GitHub:

> I agree that sometimes a force push can be useful or necessary. I've recorded your feedback on this for our product team—I can't make any promises of when these options might be separated out though.

**Comment by StephanBijzitter** [comment]
But what if I create an empty branch (no history) and force push it with the same name as the protected branch on origin? The branch is not deleted... but there's also nothing in it anymore.

I guess as an optional feature, it can't hurt. But for now, I (personally) am fine with just temporarily un-protecting the branch whenever it's needed.

**Comment by gssleap** [comment]
:+1:
I want to have protected branches for automated deployment (e.g. prod, integrate, etc.) that admins can force-push to but others can't touch. When we cut a release, it's

```bash
% git checkout integrate
% git reset --hard master
% echo $VERSION > versionfile; git add versionfile; git commit -m "version=$VERSION"
% git tag v$VERSION
% git push --force origin integrate
```

What I do now is to unprotect the branch before the force push, then protect it again. It would be nice not to have to mess with that, especially since everything else is easy to script.

**Comment by MiguelBamberino** [comment]
is there any update on this feature ? it would be really good to be able to separate these features

**Comment by olets** [comment]
@MiguelBamberino this isn't an official support request list (there is no official support request list), so GitHub won't be responding with any updates

**Comment by eygraber** [comment]
Another use case is a long lived feature branch base, that will have other feature branches merged into it. I want to keep all the protected branch restrictions, but in order to keep it cleanly up to date with master, I have to rebase and force push.

**Comment by Vadorequest** [comment]
My use case is different, but the result is similar. I don't want developers to force push on some branches, but I want to keep that ability, especially as I rebase things that change commits and need a force push to be applied on the remote. It's boring to disable the protection when I need to force push. I'm admin, and I wish I could just force push that branch.

**Comment by mxcosu** [comment]
Also checking on the status of this

**Comment by ljharb** [comment]
This has already happened - there’s an “allow force pushes” checkbox now.

**Comment by mxcosu** [comment]
> This has already happened - there’s an “allow force pushes” checkbox now.

Thanks I actually found this right afterwards. Should’ve updated the comment. Thanks

**Comment by mxcosu** [comment]
> This has already happened - there’s an “allow force pushes” checkbox now.

Thanks I actually found this right afterwards. Should’ve updated the comment. Thanks

Can we mark this as resolved to avoid someone else Being confused?

**Comment by ljharb** [comment]
ping @olets

**Comment by olets** [comment]
🎉
