### ISSUE TITLE
Submodule relative path doesn't create hyperlink

### ISSUE THREAD

**Issue by DavidUser** [isaacs/github#1171]
https://github.com/DavidUser/submodule-link-bug

![image](https://user-images.githubusercontent.com/6628028/35658924-c9097d98-06ea-11e8-91ec-f192d71b7f0f.png)

![image](https://user-images.githubusercontent.com/6628028/35658940-de29f0cc-06ea-11e8-97c4-6c4354974f0e.png)

**Comment by hsandt** [comment]
Maybe same cause as broken relative hyperlinks to submodule in README: https://github.com/github/markup/issues/1068

**Comment by siminapasat** [comment]
👋 PM at GitHub here. We shipped a fix for this - git submodules defined using relative paths are now clickable in the UI, making it easy to navigate to the linked repository. Happy linking!

**Comment by jotix16** [comment]
@siminapasat any example? 
Normally the name of a submodule is smth like **sub_name@ f8255ec**.  But clicking on [sub_name]() brings me to a page not found in Github. 

Am I doing something wrong?
