### ISSUE TITLE
Feature request: Ignore certain files from PR, but not commit

### ISSUE THREAD

**Issue by Pyrolistical** [isaacs/github#1186]
There are files like package-lock.json which are really long and are not intended for human review. These files need to be committed, but they pollute the PR.

What would be nice is a .githubignore file that would allow us to specify which files should be ignore in the PR, and maybe hidden away behind another click. This would make the +/- stats make more sense

**Comment by melissachang** [comment]
Actually, this already exists. See https://github.com/github/linguist#generated-code and https://github.com/DataBiosphere/data-explorer/pull/49

And, package-lock.json should [automatically be ignored](https://github.com/github/linguist/blob/c2d31700647729dd1ce0b623ac5128ad2aa2ec89/lib/linguist/generated.rb#L356). It's automatically ignored in my repo.

**Comment by Pyrolistical** [comment]
oh nice, thanks

**Comment by notquiteamonad** [comment]
I wonder if a new case could be made for this, with stronger suppression. Projects using [Yarn 2](https://yarnpkg.com) can, in a PR that adds dependencies, add hundreds of zip files to a repo. Their diffs are not shown but each takes up a file's space in the changes tab and so it can be difficult to find the actually modified (by a human) files. If this could be automatically identified and the empty diffs replaced with something like "+ 156 generated changed files" at the bottom, it'd make these PRs much easier to review.
