### ISSUE TITLE
Typing in text areas is horrendously slow

### ISSUE THREAD

**Issue by jonathanong** [isaacs/github#119]
As I type this on my iPhone, each character takes about 300ms to register. The same happens on my Mac, either Safari or Chrome.

Please tone down the javascript!

**Comment by emanuil-tolev** [comment]
Started happening to me in 2015, Chrome on Ubuntu Linux 14.04 LTS, but it only happens *on some github issues*, in particular on a private project I'm collaborating on! E.g. the text box in this issue - fine.

**Comment by TPS** [comment]
@jonathanong, et all: I believe this issue's obsolete.…  Comments?
