### ISSUE TITLE
Git clone from Terminal not working to clone a private Repository

### ISSUE THREAD

**Issue by emzubair** [isaacs/github#1193]
I want to clone form a Github Repository, which is private, I've rights to access the repository but every time when I try to clone from the repo it fails & shows the following errors.
remote: Repository not found.
fatal: repository 'https://github.com/repoURL/repoName.git/' not found

But I can clone & pull code using Xcode & SourceTree, can you tell me what's the issue here ?

**Comment by NobbZ** [comment]
AFAIK you need to use either SSH URL (git@github...) Or provide username and password in the URL (https://user:password@github...)

**Comment by emzubair** [comment]
I resolved the issue, when we click clone/download button it gives pubic URL to clone the project, so in case of private repo that doesn't work, so by adding username is the url it solved my issue.

**Comment by zixuan75** [comment]
@wfarr lol!
