### ISSUE TITLE
HTTP/2 on Github Pages

### ISSUE THREAD

**Issue by cben** [isaacs/github#1204]
Seems this already works and can be closed, just wanted an outlet for discussing this without spamming #156.
I'm seeing all HTTPS requests, both on github.io (whether you have CNAME or not) and on custom domains, getting HTTP/2 responses :tada:

- Didn't test custom apex domain, that goes to different servers so may differ?

Not sure how new this is.
Fastly have [supported HTTP/2 since Nov 2016](https://www.fastly.com/blog/http2-now-general-availability).
Apparently on Dec, 2017 someone [still didn't see HTTP/2](https://www.reddit.com/r/github/comments/7gxrs9/http2_on_github_pages/).

- #289 bug where directories without trailing / redirect from https: HTTP/2 to unsecure http: still happens :frowning:

**Comment by myshov** [comment]
@cben hi! I've just created test project on Github Pages and http/2 doesn't work in my case

**Comment by cben** [comment]
Closing as I intended originally, works afaict.
