### ISSUE TITLE
Estimate time for issue

### ISSUE THREAD

**Issue by sergiodosreisjr** [isaacs/github#1209]
For teams working with Scrum, it would be very important to assign an estimated time or story point for each issue. Thus we could have a sum of the estimated times per column in the project (kanban), making it easier in the sprint planning process.

**Comment by cirosantilli** [comment]
Possible duplicate of: https://github.com/isaacs/github/issues/655

**Comment by sergiodosreisjr** [comment]
Ok, Issue #655 basically covers the same functionality, even with more detail. To complement, I think that the sum of the size of the issues can be included in the title of the columns of the projects, as the example of the image below. Is there any forecast for this implementation?

![exemplo github](https://user-images.githubusercontent.com/31665230/38102441-9f145ecc-3359-11e8-991a-e6ea112cdd0c.png)

**Comment by gamcoh** [comment]
Hi, here's a script for that, you just need to write the time in the body of each issues

https://github.com/gamcoh/Github-Automation-Tools
