### ISSUE TITLE
Filter cards by milestone on a project board

### ISSUE THREAD

**Issue by sergiodosreisjr** [isaacs/github#1220]
We used the milestones to control our sprints and it would be very useful to create a filter by milestone on the project board. 

![milestone](https://user-images.githubusercontent.com/31665230/38556880-90259cb8-3ca1-11e8-80b8-7c818c1cf2f4.png)

**Comment by gilorlev** [comment]
I can't agree more. 

That would be great

**Comment by ikbenmacje** [comment]
+1 I would also really appreciate this!

**Comment by berndtlindner** [comment]
Would really be great to have this feature

**Comment by nicholasmoy** [comment]
+1 this would be great!

**Comment by joshcastle** [comment]
+1 yes! Would love this!

**Comment by relu69** [comment]
+1 It is useful!

**Comment by mpp-doric** [comment]
+1

**Comment by 2binfree** [comment]
+1

**Comment by GiantsLoveDeathMetal** [comment]
+1

**Comment by ramyala** [comment]
+1

**Comment by Ancker** [comment]
How many + does this need for a simple add?

**Comment by ndewhurst** [comment]
+1

**Comment by Gildewarz777** [comment]
+999999999999999999999999

**Comment by coumarc9** [comment]
+1

**Comment by vinayakdatar** [comment]
+1

**Comment by IvanPetkow** [comment]
+42
I need this feature! Really wonder why it is not implemented yet...

**Comment by ivanhanzlicek** [comment]
Was just looking for the right filter syntax, and aha, there is none. Would be really helpful.

**Comment by nikhilxb** [comment]
+1

**Comment by FloLecoeuche** [comment]
+1

**Comment by mkbeyer** [comment]
yes! +1

**Comment by HelleHM** [comment]
+1

**Comment by annagree** [comment]
+1

**Comment by mp-vayyar** [comment]
+1

**Comment by YannBeauxis** [comment]
+1

**Comment by aarongifford** [comment]
+1

**Comment by phayes** [comment]
This is really really needed

**Comment by pieterclaerhout** [comment]
+10000

**Comment by jpaarhuis** [comment]
+1337

**Comment by estevez-dev** [comment]
I really need this!!

**Comment by rienswagerman** [comment]
+1

**Comment by Gaen** [comment]
+1

**Comment by kunlabora-healthdata** [comment]
+1

**Comment by unlikelyzero** [comment]
+1

**Comment by nicktc** [comment]
+1

**Comment by austintruchan** [comment]
+1

**Comment by kde713** [comment]
👍

**Comment by zitoloco** [comment]
+1

**Comment by rugger-sr** [comment]
+1

**Comment by lovromazgon** [comment]
+1

**Comment by bjarkih** [comment]
This is a massive limitation of the current GitHub Project feature, and means you can essentially can't use milestones and projects together in any practical sense.

**Comment by LucyGoosey** [comment]
Another +1 here, from what I can see there is no way to determine what milestone an issue belongs to quickly and easily from the projects view.

**Comment by AnthonySaldana** [comment]
+1000  yo! Geez good lord c'mon just let us filter by everything!
Github is smooth af but lacking in features

**Comment by csinobas** [comment]
+1

**Comment by coreygans** [comment]
Even exposing the milestone on the card view would make it easier to organize cards on the project view. I use columns for sprint planning too and this would be a huge improvement.

**Comment by MRayermannMSFT** [comment]
+1

**Comment by heathdutton** [comment]
+1 
I assumed this would be there.

**Comment by chibimi** [comment]
One more +1 to the list

**Comment by staticinteger** [comment]
I also +1 this

**Comment by dennispo** [comment]
+10^99

**Comment by n8behavior** [comment]
Apparently 8 months of begging is not enough for GitHub to even **acknowledge** the issue...lol

:+1:

**Comment by realthargor** [comment]
+1

**Comment by amburan** [comment]
Another +1 from me!

**Comment by smeijer** [comment]
Definitely required. I'm currently creating a board per milestone. That can't be the right way to manage this! I need to somehow make the board (automatically) filter by the current milestone, and move to the next once the milestone has been completed.

**Comment by jduncan-rva** [comment]
+1 

Was really surprised this didn't just work. Please prioritize!

**Comment by wieseljonas** [comment]
+1

**Comment by bpatram** [comment]
I think an issue that might be blocking this is the fact that projects can be set at the organizational level but milestones cannot (https://github.com/dear-github/dear-github/issues/93). Using the suggested implementation (`milestone:"name"`) would cause issues if a project was linked to multiple repos that each have milestones of the same name. In this case probably `milestone:org/repo/name` and `milestone:org/name` would be better.

**Comment by jonoomph** [comment]
+1

**Comment by adampiskorski** [comment]
+1

**Comment by marchy** [comment]
+1

**Comment by halafi** [comment]
+1

**Comment by danleighton** [comment]
Oh my goodness me we do need this!!

+1

!

**Comment by achalshah20** [comment]
+1. 
This is like must feature. Can we prioritize this?

**Comment by benverine** [comment]
+1

Would definitely appreciate this.

**Comment by msmith046** [comment]
+1
This type of thing makes people move to worse tools like Jira

**Comment by dcrnojevac** [comment]
+1

**Comment by kMikaZu** [comment]
+1

**Comment by elenatorro** [comment]
+1

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by kMikaZu** [comment]
Now that Waffle.io become deprecated, I think it's time for GitHub to move on with this Feature Request. It's actually unbelievable that such a normal FR still wasn't implemented...

**Comment by smcoll** [comment]
GitHub Developer Support said, today:

> Checking our roadmap for the year ahead, filtering cards by milestone and assigning size/weight/estimates to a card are not currently listed I'm afraid.
> 
> This doesn't indicate a firm no for implementation, only that they're not mentioned as planned on our roadmap as yet. We'll pass your requests onto the team to consider.
> 
> I can't promise if or when we'd add these but we'll make sure the request is in the right hands.

**Comment by lukwro** [comment]
any news about this feature? Will be great to have it. Sprint planning with it will be much easier.

**Comment by fakestarbaby** [comment]
+1

**Comment by mebster** [comment]
+1

**Comment by kristianfantin** [comment]
+4

**Comment by n8behavior** [comment]
+1 This is the only feature left keeping me from completely dumping jira

**Comment by DanielOrtegaZ** [comment]
+1

**Comment by stephancom** [comment]
👍

**Comment by mreekie** [comment]
+1

**Comment by icodeforyou** [comment]
+1

**Comment by jamespember** [comment]
+1

**Comment by codeninja** [comment]
+1

**Comment by clausmullie** [comment]
+1

**Comment by cheersevans** [comment]
+1

**Comment by maciej-lasyk** [comment]
+1

**Comment by mika666** [comment]
+1

**Comment by stejacks** [comment]
+1

**Comment by potiuk** [comment]
+1

**Comment by despiegk** [comment]
+1

**Comment by jofemodo** [comment]
+1, please

**Comment by Xymmer** [comment]
+ a few googolplexes

**Comment by ruuts** [comment]
+1

**Comment by nicolelenzen** [comment]
+1

**Comment by lukehefson** [comment]
We just shipped this change! 🎉 

https://github.blog/changelog/2019-05-30-milestones-in-project-cards/

![testing](https://user-images.githubusercontent.com/1469659/58694345-b3655980-838a-11e9-8c97-32a499ca74a4.gif)

cc/ @TPS (in case you might like to close this now 😄)

**Comment by TPS** [comment]
@lukehefson Thanks for work & notifying me! 🙇🏾‍♂️  [_(Just FYI, there're several more collaborators recently, including a fellow staff member, so it doesn't hurt to flag a few, just in case I'm not available.)_](https://github.com/isaacs/github/issues/1472)

**Comment by danleighton** [comment]
Wonderful! Thank you!

**Comment by vatervonacht** [comment]
@lukehefson Thanks for the update.  How long before this feature finds its way into GHE?

**Comment by lukehefson** [comment]
@vatervonacht It'll land in 2.18.0 🙌

**Comment by RdeWilde** [comment]
That is awesome. Will we also have the ability to add milestones as a card?

**Comment by lukehefson** [comment]
> Will we also have the ability to add milestones as a card?

@RdeWilde I'd love to know a bit more about how you might imagine this might work or look? Thanks!

**Comment by RdeWilde** [comment]
@lukehefson As everyone uses the project board and issues in their own way, I can only answer it how it could work for myself, but ofcourse it isn't limited to that.

We have a repository per client project. One project has multiple issues (too bad). It can also have a project board with all the issues listed, giving a good few of the project's progress. As a company we'd work with (bi-)weekly sprints, so we can't do all the issues in one sprint. It makes sense to create milestones, grouping the issues logically and creating efficient workloads. As we have multiple client projects, we'd have multiple milestones. If we could track this in the organizational project board, we have a bright overview of the progress on our sprint.

As how it would look, I'd like to see a progress bar or like a checklist (2 out of 5). As Github does not support storypoints, I think both could be considered equal. Optionally you could show the due date.

**Comment by IdanAdar** [comment]
Is this available in GitHub Enterprise 2.16.15? The filtering is not working.

**Comment by zoechi** [comment]
Why does `no:milestones` not work here. What about supporting the same filters as in the issues view?

**Comment by labrose** [comment]
Oops - looks like we had forgotten to add support for `no:milestone` when we added milestone filtering support to the Project board. If you take a look, it should work now!

We're still missing a couple other pieces of filtering to get to parity with the Issues list (`mentions:foo` comes to mind), but definitely something we're discussing.
