### ISSUE TITLE
New unread notification but the notification refers to a deleted post and we cannot "read it".

### ISSUE THREAD

**Issue by AlexisTM** [isaacs/github#1222]
It is not possible to disable the blue dot saying `unread notification` as the topic the notification is about has been deleted.

The related topic: `https://github.com/orgs/NVIDIAGameWorks/teams/gameworks_eula_access/discussions/11`

![image](https://user-images.githubusercontent.com/6976744/38661014-a5ca895e-3e2f-11e8-830a-4b2d45a66dec.png)

**Comment by AndrewMast** [comment]
Maybe have a "X" icon to "ignore" the notification? (aka hides the notification)

**Comment by wizzup** [comment]
In my case, I don't even have the unread item to read

![img](https://user-images.githubusercontent.com/342500/54665290-3eb7a880-4b19-11e9-9673-b577c694d1da.png)

**Comment by nigredo-tori** [comment]
@wizzup, same here. Returning any notification to unread and reading it removes the blue dot, but it returns on page reload.

**Comment by AlexisTM** [comment]
The issue is also fixed for me;

**Comment by cnd** [comment]
issue is not fixed for me

**Comment by cnd** [comment]
I mean it's gone when I clicked All notifications -> Mark all as read.
But it's really not intuitive still... I state that it's still being a bug there.

Just don't notify me about something I can't see.

**Comment by becca** [comment]
this should now be fixed 🤞. if you bump into this problem today a refresh should work. please keep me posted if this surfaces again.

**Comment by MarcDahlem** [comment]
@AlexisTM It happens to me again:

![grafik](https://user-images.githubusercontent.com/2813850/116002260-2c15d480-a5f9-11eb-905a-434b0cecae0f.png)
