### ISSUE TITLE
Display binary file size in pull requests, and show warning over a certain threshold 

### ISSUE THREAD

**Issue by aguibert** [isaacs/github#1239]
Recently a co-worker accidentally added a large (88MB) binary in their commit.  The rest of the PR was quite large, and the binary file was understandably un-noticed in the PR.

It looked like this:
![screen shot 2018-05-08 at 10 53 28 am](https://user-images.githubusercontent.com/5427967/39768153-23a17cd8-52ae-11e8-9502-26207c7e05d6.png)

I would like to request two things:
1. Show file size of binary files in a PR
2. If a binary is being added and is larger than some threshold (e.g. >1MB) make the file size text much larger so its easier for a reviewer to notice it.  For example:
# ⚠️ 50MB ⚠️

**Comment by clarkbw** [comment]
https://blog.github.com/changelog/2018-10-09-filesize-diffs/ 🚢 

Warnings are custom and can be done with an App and the Checks API
