### ISSUE TITLE
Push with 100+ refs fails with "remote: Internal Server Error"

### ISSUE THREAD

**Issue by lucamilanesio** [isaacs/github#1253]
I've already opened a ticket with GitHub Support, however, it is worth tracing the issue here as well.

GitHub seems quite limited in terms of the number of refs that can be pushed at once.
When a repository contains 100+ refs, a single push would return a "remote: Internal Server Error". Because this is returned as textual output of the Git command, it is NOT a networking issue but rather a genuine 500 Internal Server Error failure on the GitHub backend services.

See below the steps to reproduce the problem:

__Take any GitHub repos with 100+ of refs and clone it locally__

```shell
$ git clone --mirror https://github.com/spdk/spdk.git
Cloning into bare repository 'spdk.git'...
remote: Counting objects: 215537, done.
remote: Compressing objects: 100% (9449/9449), done.
remote: Total 215537 (delta 9765), reused 2052 (delta 1951), pack-reused 204135
Receiving objects: 100% (215537/215537), 54.30 MiB | 1.75 MiB/s, done.
Resolving deltas: 100% (166755/166755), done.
Checking connectivity... done.
```

__Create a brand new empty repo on GitHub (e.g. https://github.com/lucamilanesio/test_spdk.git in the example below) and push to it__

```shell
$ git push --mirror https://github.com/lucamilanesio/test_spdk.git
Counting objects: 215537, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (47508/47508), done.
Writing objects: 100% (215537/215537), 54.23 MiB | 6.45 MiB/s, done.
Total 215537 (delta 166755), reused 215537 (delta 166755)
remote: Resolving deltas: 100% (166755/166755), done.
remote: Internal Server ErrorEverything up-to-date
```

This is currently blocking *ANY* push of medium to large repos to GitHub.

**Comment by paladox** [comment]
Any progress in this being fixed @lucamilanesio ?

**Comment by lucamilanesio** [comment]
Seems a much bigger issue with their architecture. We’ll need to implement a workaround I’m afraid

**Comment by lucamilanesio** [comment]
I am very happy to say **THANK YOU to the GitHub Team**: this issue has now been resolved.

**Comment by mightystoosh** [comment]
> I am very happy to say **THANK YOU to the GitHub Team**: this issue has now been resolved.

Do you happen to know which version of GitHub Enterprise this was fixed in?

**Comment by lucamilanesio** [comment]
> > I am very happy to say **THANK YOU to the GitHub Team**: this issue has now been resolved.
> 
> Do you happen to know which version of GitHub Enterprise this was fixed in?

The issue was on github.com, not GitHub:Enterprise

**Comment by AndersBillLinden** [comment]
I still got this.

**Comment by madebyfabian** [comment]
> I still got this.

Yeah, also got this at about a minute ago :/

**Comment by kaonlo** [comment]
Also got this error just now...

**Comment by Xiaokun-Xu** [comment]
Me too...

**Comment by richiksc** [comment]
Received this error on a push with 18 refs.

**Comment by erfling** [comment]
I have it too. I bet none of us **STILL** have it. I think GH is down

**Comment by gitsobek** [comment]
I hope they fix it quickly.

**Comment by trolleyman** [comment]
Oh wow yeah same here

**Comment by madebyfabian** [comment]
Now it's gone for me. Pushing works

**Comment by Xiaokun-Xu** [comment]
works for me now

**Comment by mttcnnff** [comment]
Not working for me currently

**Comment by RamonvdW** [comment]
Happy to see the problem is solved.

**Comment by TheSecurityDev** [comment]
Wow. I was glad to see I wasn't the only one having the problem since all the comments were within 10 minutes ago. But now it works :) Must have been a temporary internal error.

**Comment by ppoptani** [comment]
It's not resolved for us. Is anyone still facing the issue?

**Comment by vanthuyphan** [comment]
I have the same issue right now

**Comment by rajatinteros** [comment]
Same here!

**Comment by NeonSky** [comment]
They are on it.
https://www.githubstatus.com/

**Comment by mishazakharov** [comment]
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: Internal Server Error
 ! [remote failure]  master -> master (remote failed to report status)

**Comment by yeviko** [comment]
Same here!
remote: Resolving deltas: 100% (14/14), completed with 10 local objects.
remote: Internal Server Error
Everything up-to-date

**Comment by kmc7468** [comment]
Same

**Comment by ben7th** [comment]
RUA!!!

![image](https://user-images.githubusercontent.com/322486/75267193-e1e86600-5830-11ea-9fcb-bf86e7d13f8e.png)

**Comment by s9gf4ult** [comment]
I see the same issue.

**Comment by mhanna** [comment]
same same

**Comment by johnrufusj** [comment]
interesting I had the same error a few times trying to push and then the 4th or so time it worked.

**Comment by niksmac** [comment]
Still facing the issue

**Comment by AkshayRumbleOn** [comment]
same here

**Comment by matthew-mcginty** [comment]
Same issue

**Comment by vedantipargaonkar** [comment]
Same Issue

**Comment by Debikasarkar713** [comment]
same, pushing up but no changes on the PR.

**Comment by nickzuber** [comment]
Just worked for me

**Comment by MattMunnsFD** [comment]
Worked eventually. Had to wait 5-10min

**Comment by platro** [comment]
same

**Comment by viktorsmakhtin** [comment]
same

**Comment by michaelmcmanus1** [comment]
Just got this issue now! Been working fine all day until last commit.

**Comment by Ahmed-Aboud** [comment]
just worked now 🥳

**Comment by wambuimwangi** [comment]
Fixed

**Comment by dalygbarron** [comment]
fellas my computer is going wild please help this

**Comment by sinhaashish** [comment]
same issue 
```
ashish@minio:~/code/go/src/github.com/miniohq/subnet$ git push origin update-card-management  --force
Counting objects: 18, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (16/16), done.
remote: Internal Server Error
To github.com:sinhaashish/subnet.git
 ! [remote failure]    update-card-management -> update-card-management (remote failed to report status)
error: failed to push some refs to 'git@github.com:sinhaashish/subnet.git'

**Comment by JunchengL** [comment]
ok now

**Comment by platro** [comment]
just worked now

**Comment by jeff1010322** [comment]
Looks like Github just had some outage or something as everyone commenting now.  Not really related to this original issue.

**Comment by beyrerdn** [comment]
This just starting working. Woo!

**Comment by idiaz-t4m** [comment]
It's working now : )

**Comment by curow** [comment]
yeah~

**Comment by yeviko** [comment]
Yes!

**Comment by sadiqrajani** [comment]
I still got this. Is anyone still facing the issue?

**Comment by sinhaashish** [comment]
its working :)

**Comment by AndreyKrivcov** [comment]
Already fixed)

**Comment by Debikasarkar713** [comment]
Still not working for me able to push up but no changes to the PR itself.

**Comment by gc** [comment]
Hello friends googling and having this issue. Spent 5 mins googling what was wrong and then noticed all the comments here :) For once stackoverflow didnt help

**Comment by DChalcraft** [comment]
Working again for me, cheers

**Comment by victor2105** [comment]
its working, thanks!

**Comment by GhitaB** [comment]
Before commenting here make sure you turn off notifications. :)) My mobile is vibrating for some minutes now.

**Comment by sinhaashish** [comment]
I got this while commenting 
![Screenshot from 2020-02-25 22-16-23](https://user-images.githubusercontent.com/13465383/75267681-8f9d4a00-581c-11ea-8554-2473529f6b5d.png)

**Comment by dalygbarron** [comment]
can this also happen if I have got less that 100 refs? My computer is not working...

**Comment by Debikasarkar713** [comment]
working now.

**Comment by mazhigbee-pb** [comment]
Things are looking like they're back to normal, still not seeing my commits show up in PR view, but they are on my branches now. https://www.githubstatus.com/incidents/xp2qc958g4wt

**Comment by GhitaB** [comment]
git push worked for me now, but the github calendar on my profile is not updated. #when-you-just-want-some-green :))

**Comment by dalygbarron** [comment]
working now

**Comment by renato-bvdash** [comment]
Getting this error right now... help?

**Comment by fescobar** [comment]
Me too. I'm becoming unproductive haha

**Comment by BHyeonKim** [comment]
Working now!

**Comment by davidvader** [comment]
💀

**Comment by antocapp** [comment]
I am seeing the error right now

`Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 321 bytes | 321.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: Internal Server Error`

**Comment by astutejoe** [comment]
Wtf lol, not working here

**Comment by colfrog** [comment]
Yup, working as of now! Thank you!

**Comment by derekjanni** [comment]
fixed now - if you're still seeing it, close your term and restart!

**Comment by bartimez** [comment]
I'm seeing this error as well 

`remote: Resolving deltas: 100% (15/15), completed with 9 local objects.
remote: Internal Server Error
To github.com:bartimez/ats.git
 ! [remote failure]      i_171369649_soft_migration_backend -> i_171369649_soft_migration_backend (remote failed to report status)
error: failed to push some refs to 'git@github.com:bartimez/ats.git'`

**Comment by lourdrivera123** [comment]
Seeing the error here also.

**Comment by Delgus** [comment]
Подсчет объектов: 6, готово.
Delta compression using up to 2 threads.
Сжатие объектов: 100% (5/5), готово.
Запись объектов: 100% (6/6), 511 bytes | 511.00 KiB/s, готово.
Total 6 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: Internal Server Error
To github.com:Delgus/jokebot.git
 ! [remote failure]  master -> master (remote failed to report status)
error: не удалось отправить некоторые ссылки в «git@github.com:Delgus/jokebot.git»

**Comment by bthaw2018** [comment]
looks like its down
https://www.githubstatus.com/

**Comment by jenigrace** [comment]
Same, not working for me. 😄

**Comment by yuchen93** [comment]
still getting this error just now

**Comment by kenshin12269** [comment]
me too. not working..

**Comment by MaheKarim** [comment]
Still Not Working , Please Solve ASAP

**Comment by HamaniKhalil** [comment]
> They are on it.
> https://www.githubstatus.com/

Just check the link ! You can also subscribe to the incident so you can be notified when it's  resolved. Don't panic people, just take the opportunity for a break 😄

**Comment by camburley** [comment]
<img width="1426" alt="Screen Shot 2020-02-25 at 12 58 35 PM" src="https://superwall.s3.us-east-2.amazonaws.com/content/Screen+Shot+2020-02-25+at+12.58.35+PM.png">

**Comment by yusifk88** [comment]
so i don't know if this is the solution but i got it work by disconnecting from my WiFi and connecting again

**Comment by Xoshbin** [comment]
Just worked now

**Comment by arnabdutta2194** [comment]
$ git push origin master
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 264 bytes | 264.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: Internal Server Error
Everything up-to-date

**Comment by NicolasThou** [comment]
How can we manage to make github works ?

**Comment by slyt** [comment]
I'm getting Push failed as well:

Failed with error: Counting objects: 9, done. Delta compression using up to 4 threads. Compressing objects: 12% (1/8) Compressing objects: 25% (2/8) Compressing objects: 37% (3/8) Compressing objects: 50% (4/8) Compressing objects: 62% (5/8) Compressing objects: 75% (6/8) Compressing objects: 87% (7/8) Compressing objects: 100% (8/8) Compressing objects: 100% (8/8), done. Writing objects: 11% (1/9) Writing objects: 22% (2/9) Writing objects: 33% (3/9) Writing objects: 44% (4/9) Writing objects: 55% (5/9) Writing objects: 66% (6/9) Writing objects: 77% (7/9) Writing objects: 88% (8/9) Writing objects: 100% (9/9) Writing objects: 100% (9/9), 3.13 KiB | 3.13 MiB/s, done. Total 9 (delta 5), reused 0 (delta 0) remote: Resolving deltas: 0% (0/5) remote: Resolving deltas: 20% (1/5) remote: Resolving deltas: 40% (2/5) remote: Resolving deltas: 60% (3/5) remote: Resolving deltas: 80% (4/5) remote: Resolving deltas: 100% (5/5) remote: Resolving deltas: 100% (5/5), completed with 5 local objects. remote: Internal Server Error Done

**Comment by nivapo95** [comment]
I just tried to push multiple times and it worked every 1/10 attempts
They are investigating this, but it doesn't seem to be a consistent error so re-trying it should work :)

Follow the status here:

https://www.githubstatus.com/

**Comment by kblicharski** [comment]
Worked eventually for me by running:

`while [[ $? -ne 0 ]]; do sleep 30 && git push; done`

Seems like the error is highly intermittent.

**Comment by kblicharski** [comment]
Also worth noting that it took me many tries to even post a comment on this issue thread -- was receiving "You can't comment at this time.
" and  "You can’t perform that action at this time" errors, but clicking comment repeatedly eventually went through.

**Comment by serome111** [comment]
```
Counting objects: 859, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (824/824), done.
Writing objects: 100% (859/859), 47.41 MiB | 5.63 MiB/s, done.
Total 859 (delta 126), reused 2 (delta 1)
remote: Resolving deltas: 100% (126/126), completed with 23 local objects.
remote: Internal Server Error
Everything up-to-date
```

**Comment by JuanRangel** [comment]
I got the same error 3 times in a row, but it now was pushed. :-)

**Comment by victorbrodsky** [comment]
It worked now!

**Comment by wiwi1212** [comment]
No working for me either, same error

**Comment by juliannehalversen** [comment]
having this same issue

**Comment by EdwinWenink** [comment]
I could push just now after failing several times

**Comment by dnajar2** [comment]
Able to push now!

**Comment by cinava** [comment]
It worked now!

**Comment by juliannehalversen** [comment]
Works after restarting terminal for me.

**Comment by GusGF** [comment]
Same here but just worked. Seems intermittent, works one minute fails another. Just keep trying.

**Comment by wiwi1212** [comment]
Just start working !

**Comment by tonioteran** [comment]
works for me now

**Comment by matiassallee** [comment]
It works for me now! It seems to be intermittent

**Comment by bawantha** [comment]
works

**Comment by vvmspace** [comment]
Again: Delta compression using up to 4 threads. Total 10 (delta 6), reused 0 (delta 0) remote: Internal Server Error

**Comment by katiedrax** [comment]
not working for me

**Comment by reibusintl-eb** [comment]
`Enumerating objects: 99, done.
Counting objects: 100% (99/99), done.
Delta compression using up to 8 threads
Compressing objects: 100% (61/61), done.
Writing objects: 100% (61/61), 12.25 KiB | 432.00 KiB/s, done.
Total 61 (delta 51), reused 0 (delta 0)
remote: Resolving deltas: 100% (51/51), completed with 23 local objects.
remote: Internal Server Error
Everything up-to-date
`
is not working for me. tried restarting my git bash and pushing multiple times

**Comment by orlandobarrera6** [comment]
I'm getting the same error

remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: Internal Server Error

**Comment by EliezerIsrael** [comment]
Same

**Comment by lcford2** [comment]
I also am getting the same error right now.

**Comment by Anabra** [comment]
Same

**Comment by EliezerIsrael** [comment]
Failed five times, and then I tried to push again, and it worked.

**Comment by jsanchez00** [comment]
Me too.

```
remote: Resolving deltas: 100% (12/12), completed with 12 local objects.
remote: Internal Server Error
Everything up-to-date
```

**Comment by xcao38** [comment]
Failed

**Comment by hylimR** [comment]
Faced same error in cli, but able to push when i used their github for desktop client.

**Comment by xcao38** [comment]
working now

**Comment by awongwork** [comment]
This is the second time I've encountered this problem this week.  I find that whenever someone else merge code to the same repo, then some thing somehow gets reset the error goes away.

**Comment by reibusintl-eb** [comment]
update: after pushing ~10 times it randomly worked for me

**Comment by vvmspace** [comment]
Works. Please fix.

**Comment by vanss2** [comment]
worked after closing terminal and restarting github desktop (mac)

**Comment by orlandobarrera6** [comment]
Yeah I kept pushing the comimits and it eventually worked. two weeks ago npm went down and now github. SOMETHING IS UP EVERYBODY!

**Comment by jelleschutter** [comment]
https://www.githubstatus.com

**Comment by SynergentDev** [comment]
Getting this error when pushing a large batch of tags with:

$ git push --tags
Enumerating objects: 6088, done.
Counting objects: 100% (6033/6033), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5893/5893), done.
Writing objects: 100% (6008/6008), 1.10 MiB | 3.84 MiB/s, done.
Total 6008 (delta 165), reused 5894 (delta 115), pack-reused 0
remote: Resolving deltas: 100% (165/165), completed with 11 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/******.git
remote: Internal Server Error
Everything up-to-date

**Comment by ievajas** [comment]
Keep getting the same as mentioned above:
```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 285 bytes | 285.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: Internal Server Error
Everything up-to-date
```

**Comment by joakiti** [comment]
Delta compression using up to 12 threads
Compressing objects: 100% (48/48), done.
Writing objects: 100% (48/48), 174.36 KiB | 10.26 MiB/s, done.
Total 48 (delta 32), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (32/32), completed with 27 local objects.
remote: Internal Server Error
Everything up-to-date

**Comment by Trond-Hillestad** [comment]
This is still a issue for some of my repos I want to mirror. Tried several times for some days... 

git push --mirror https://<my-new-git-repo>
Enumerating objects: 12867, done.
Counting objects: 100% (8528/8528), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4983/4983), done.
Writing objects: 100% (7549/7549), 3.59 MiB | 2.87 MiB/s, done.
Total 7549 (delta 4745), reused 4346 (delta 2385), pack-reused 0
remote: Resolving deltas: 100% (4745/4745), completed with 442 local objects.
remote: Internal Server Error
Everything up-to-date

Any idea how to solve this?

**Comment by sarathka** [comment]
can anyone pls help me on this issue :
Enumerating objects: 189258, done.
Counting objects: 100% (189258/189258), done.
Delta compression using up to 8 threads
Compressing objects: 100% (36461/36461), done.
Writing objects: 100% (189258/189258), 202.00 MiB | 202.59 MiB/s, done.
Total 189258 (delta 139022), reused 189258 (delta 139022), pack-reused 0
remote: Resolving deltas: 100% (139022/139022), done.
**remote: Internal Server Error**
Everything up-to-date

**Comment by ievajas** [comment]
> can anyone pls help me on this issue :
> Enumerating objects: 189258, done.
> Counting objects: 100% (189258/189258), done.
> Delta compression using up to 8 threads
> Compressing objects: 100% (36461/36461), done.
> Writing objects: 100% (189258/189258), 202.00 MiB | 202.59 MiB/s, done.
> Total 189258 (delta 139022), reused 189258 (delta 139022), pack-reused 0
> remote: Resolving deltas: 100% (139022/139022), done.
> **remote: Internal Server Error**
> Everything up-to-date



I had this issue about a month ago.
It went away after a day. Just used 'git push'.

**Comment by rjmacarthy** [comment]
Still fails

```
Enumerating objects: 48497, done.
Counting objects: 100% (48497/48497), done.
Delta compression using up to 16 threads
Compressing objects: 100% (14846/14846), done.
Writing objects: 100% (48497/48497), 17.71 MiB | 1.08 MiB/s, done.
Total 48497 (delta 33495), reused 48481 (delta 33489)
remote: Resolving deltas: 100% (33495/33495), done.
remote: Internal Server Error
Everything up-to-date
```

**Comment by JonathanWilson1** [comment]
Following this [this](https://github.community/t/push-fails-when-pushed-with-mirror-option-and-repo-contains-1000s-of-refs-in-refs-replace/151345) example I was able to get 74092 objects pushed

`git for-each-ref --format="%(refname)" --sort='authordate' | xargs git push REMOTE_URL`
