### ISSUE TITLE
Syntax for MIPS Assembly Language

### ISSUE THREAD

**Issue by alichtman** [isaacs/github#1263]
I noticed that `.asm` files have syntax highlighting, but MIPS files (uses the `.s` extension) do not. I know it's not a hugely popular language, but it should have syntax highlighting.

**Comment by allejo** [comment]
See [github/linguist](https://github.com/github/linguist) for new language support.

**Comment by alichtman** [comment]
Found a closed thread on `linguist` about the issues with Assembly syntax highlighting. 

Closing this.
