### ISSUE TITLE
Microsoft is acquiring GitHub

### ISSUE THREAD

**Issue by szepeviktor** [isaacs/github#1266]
Will GitHub still use open-source software?
https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/

**Comment by joelhandwell** [comment]
I think this is also a chance to open source Github itself. When Xamarin was acquired by Microsoft, it was surprise to me that they open sourced it and I never expected that. Who knows Microsoft will finally [open source Github](https://github.com/dear-github/dear-github/issues/304)?

**Comment by erkinalp** [comment]
No, this is a chance to opensource _Windows_.

**Comment by magicgoose** [comment]
> No, this is a chance to opensource Windows.

I don't see how is it even related.  
If they can opensource Windows now, they could do it before as well.
