### ISSUE TITLE
Allow users to customize which projects show up in Contributions list

### ISSUE THREAD

**Issue by tybenz** [isaacs/github#127]
I love the new user profile page. But I'm annoyed that I have no control over which projects are displayed under "Respositories contributed to".

It would be awesome if github allowed us to curate/tweak the repositories that show up on our profile pages.

**Comment by JohnMaguire** [comment]
Seriously, makes no sense. I'd also settle for it not being limited to only 5 repositories.

**Comment by Aaron1011** [comment]
This has been added: https://github.com/blog/2191-pin-repositories-to-your-github-profile

**Comment by TPS** [comment]
@tybenz @cirosantilli As @Aaron1011 [mentioned](#issuecomment-226662246), this is solved, right?
