### ISSUE TITLE
invisible button in the top left, to the left of the github logo

### ISSUE THREAD

**Issue by rotcivegaf** [isaacs/github#1285]
At alt + shift + tab in the github logo next to the search box, I found a strange button.
Apparently nothing special, just show the message "Skip to content".
![b](https://user-images.githubusercontent.com/7088778/41624646-c70c9cfe-73ec-11e8-8f1f-8095ffb3d2bf.png)

**Comment by cirosantilli** [comment]
possible duplicate of: https://github.com/isaacs/github/issues/890

**Comment by rotcivegaf** [comment]
yes, its duplicate, sorry i dont see

**Comment by cirosantilli** [comment]
No worries.
