### ISSUE TITLE
WTF, I cannot clone any repository. error 504.

### ISSUE THREAD

**Issue by lzl124631x** [isaacs/github#1299]
```
fatal: unable to access 'https://github.com/lzl124631x/svg_viewer.git': The requested URL returned error: 504
```

**Comment by QuentinMcCarthy** [comment]
I'm getting the exact same problem. I can't fetch, I can't push, I can't clone.

**Comment by Winton1992** [comment]
The same!!!!!! I am not able to push my code !!!!!!!!!!!!

**Comment by Winton1992** [comment]
Now it works.

**Comment by lzl124631x** [comment]
Cheers.

**Comment by pnykamp** [comment]
I just got the same too, for a repository I just committed to a few minutes ago. I'm going to wait and try again in case its a problem on the GitHub side.
