### ISSUE TITLE
Repository shows NaN releases 

### ISSUE THREAD

**Issue by aslafy-z** [isaacs/github#1301]
I just saw this strange behavior on [renovatebot/renovate](https://github.com/renovatebot/renovate) repository.
It shows NaN error only in the first header showing the count. However we can see there are more than 1700 releases.

![2018-07-13-163642_573x239_scrot](https://user-images.githubusercontent.com/8191198/42697277-f1d97e44-86ba-11e8-8207-94bd3d4aa4ed.png)

I seen this glitch only on the main repository page.

**Comment by cirosantilli** [comment]
Can't reproduce locally on Chromium 66 Ubuntu 18.04 and neither can archive.is: http://archive.is/vXATj

Does it happen every time? What is your browser version?

**Comment by aslafy-z** [comment]
Oh I just figured out it was due to a Chrome plugin: "Refined Github". I'm gonna report to upstream. Sorry for the trouble. Closing this.
