### ISSUE TITLE
GitHub cannot open via firefox

### ISSUE THREAD

**Issue by dvdvideo1234** [isaacs/github#1319]
![image](https://user-images.githubusercontent.com/9112662/43882403-37865a7c-9bb8-11e8-8adb-9b6fca99a578.png)

git.exe push --thin --progress "origin" neural_net:neural_net

fatal: unable to access 'https://github.com/dvdvideo1234/ZeroBraneEduPack.git/': SSL certificate problem: self signed certificate in certificate chain

git did not exit cleanly (exit code 128) (1482 ms @ 09-08-2018 09:40:52)

**Comment by NobbZ** [comment]
I do assume this is an older version of Windows?

Please try the script available at https://gist.github.com/DylanLacey/011124077d0a8c41e31a

**Comment by eladkarako** [comment]
or `git -c http.sslVerify=false ...`
