### ISSUE TITLE
An option to disable all merge buttons

### ISSUE THREAD

**Issue by trivikr** [isaacs/github#1325]
Hi,

As of August 2018, at least one option must be enabled for the merge buttons
![disable-merge-button](https://user-images.githubusercontent.com/16024985/44157643-cb702480-a067-11e8-915d-8f66016afbdc.png)

In one of my projects, we don't use Github's merge buttons and have scripts written to merge the commits. These scripts do an additional checks required before merging. We don't want collaborators to merge commits in the repo without the additional checks done, and the presence of at least one merge button creates that confusion.

Please provide an option in the settings to disable all merge buttons for Github repos.

Regards,
Trivikram

**Comment by trivikr** [comment]
Sent an email to support@github.com with a link to this issue

**Comment by trivikr** [comment]
Response from Github support:

```
Hi Trivikram,

Thanks for your feedback! I can't promise that we will be able to implement a feature for disabling all merges on GitHub.com, but I have added this to our internal list for consideration.

Apologies for any inconvenience, and thank you again for reaching out with this request on how we can make GitHub work better for you!

Cheers,
GitHub Support
```

**Comment by oprogramador** [comment]
@trivikr 

you can just use protected branches

**Comment by TPS** [comment]
Duplicates #5
