### ISSUE TITLE
For .json files, don't render comments as red

### ISSUE THREAD

**Issue by melissachang** [isaacs/github#1331]
Even though comments aren't part of the JSON spec, many people use them; many applications support them.

**Comment by eladkarako** [comment]
@melissachang 

<h2>

```json
{
/* never use comments in a JSON */
}
```

</h2>

<hr/>

anyway..

you may use the JavaScript-scheme: <code>\`\`\`js</code> instead of the <code>\`\`\`json</code> one.

```js
{
/* less horrible */
}
```

<hr/>

**Comment by melissachang** [comment]
I'm not talking about JSON in markdown, I'm talking about an actual .json file.

**Comment by esr360** [comment]
Comments inside a JSON file are not legal. Red text is used to highlight illegal code. You should be directing your concerns to the people who handle the JSON spec and request that they allow comments.

**Comment by clarkbw** [comment]
This is how linguist handles json
