### ISSUE TITLE
Cannot add comments on lines of code anymore

### ISSUE THREAD

**Issue by SeanMeh** [isaacs/github#1338]
In a PR, when I attempt to add a comment to a line of code, I get the following error message:

`Start commit oid is not part of the pull request`

The comment does not get applied.

This occurs in two different repos I have access to; I haven't tested any other repos.

This is when I click the little blue `[+]` at the start of a line of code in order to add a comment.  This occurs when adding a single comment or starting a review.  As is, I have no means to my knowledge of leaving comments on lines of codes on a commit or in a PR.  Unfortunately this results in a lack of clarity when leaving comments, because I have to leave references to which lines of code I'm talking about in my PR-level comments.

**Comment by SeanMeh** [comment]
I just tried this again today on another PR and it seems to be working now.  Not sure what's going on.

**Comment by brainbugged** [comment]
I believe started seeing this problem a month back as well.

**Comment by jaymiethomas** [comment]
I've just encountered this too, though as far as I can see, the code certainly is part of the PR.

**Comment by jhaydt** [comment]
seeing the same in my jhaydtw account (can't sign in right now as jhaydtw cuz cell is elsewhere and the account uses 2FA). Very frustrating.

**Comment by mmakarin** [comment]
Same here

**Comment by lancestarr** [comment]
This just happened to me, and when I scrolled to the top, there was a message saying that the pull request was out of date. After refreshing, I was able to enter a comment.

**Comment by tinuroth** [comment]
had it several times, too... on GitHub enterprise. I am under the impression that this problem was introduced with a recent release of GitHub, or at least it was made worse.

**Comment by JonnyCBB** [comment]
Same problem here just now

**Comment by gal3** [comment]
Same here

**Comment by pinalbhatt** [comment]
me too seeing same problem,  not sure how to resolve it

**Comment by nonno** [comment]
It just happened to me too but because of something that I did. I did a new commit on a PR, but I didn't like to keep all the commits so I did a reset-mixed and a push-force of a new, single commit (something that I usually do when it's time to merge to master, not earlier). Now GitHub is linked to a branch that doesn't exist anymore and the new one (same name) is seen as a new branch without PR. Perhaps you had the same problem because some of your colleagues did the same.

**Comment by codenameDuchess** [comment]
This has been happening to us as well and we've not found a way around it. With no "outdated .. refresh" message at the top.

**Comment by cbaker-imb** [comment]
I'm seeing the same problem also.

**Comment by a9db0** [comment]
Another "me too".  Annoying to not be able to comment on a questionable line of code that is part of a diff in a pull request / commit review.

**Comment by vegaskev** [comment]
I'm seeing the same problem as well as of just now.  I tried in two different diffs and saw the same message

> **Start commit oid is not part of the pull request**

**Comment by ricardoanjinho** [comment]
Same here, same scenario (upon  'Add Single Comment' as well as 'Add Review Comment'). Cheers

**Comment by AndrewLeeCHCH** [comment]
Same.

**Comment by bcb37** [comment]
Same

**Comment by Shivam101** [comment]
Same

**Comment by thesmart** [comment]
This is kind of the entire reason to use Github. Is there an ETA for a fix?

**Comment by ld100** [comment]
Got the same issue today and it drives me crazy.
We've just migrated a project from Bitbucket to Github and despite my love for Github, pull requests functionality feels like hassle comparing to BB.

**Comment by clarkbw** [comment]
A fix landed yesterday. Please let us know if you continue to see this issue and I’ll reopen. Thanks!

**Comment by calebcordry** [comment]
Hello @clarkbw I am still currently having this issue.

**Comment by teedr** [comment]
Same

**Comment by jeremylt** [comment]
I am just starting to experience this issue today.

**Comment by clarkbw** [comment]
Ok, let’s narrow this down. 

You seeing this exact message: `Start commit oid is not part of the pull request` when trying to comment on the first commit of a PR?

**Comment by clarkbw** [comment]
If you’re seeing another issue than above please contact support with the PR in question and a description of the problem.

**Comment by mzw4** [comment]
Same issue here, just contacted support

**Comment by nheagy** [comment]
@clarkbw getting this error on this PR, making me unable to leave review comments. https://github.com/wordpress-mobile/WordPress-iOS/pull/10584/files

**Comment by kuwantum** [comment]
Just encountered this for the first time

**Comment by cnwalker** [comment]
Also encountered for the first time

**Comment by gpadak** [comment]
On behalf of @clarkbw I'd like to update you all that the fix mentioned in https://github.com/isaacs/github/issues/1338#issuecomment-445093181 has been revisited and the follow up PR to address the issue landed and deployed about 6 hours ago. If you continue to see any recurrence please [contact GitHub Support](https://github.com/contact).

**Comment by nheagy** [comment]
Worked for me! Thanks 🥇

**Comment by jeremylt** [comment]
All's quiet on the western front! Thank you!

**Comment by clarkbw** [comment]
🎉

**Comment by simiyu1** [comment]
Wait... why am I hitting this 3 days after resolution?

am trying to comment after clicking on the plus... 
![screenshot 2018-12-10 at 20 31 25](https://user-images.githubusercontent.com/17185082/49749989-cee48700-fcba-11e8-88dc-b36a11743552.png)

only markdown is the ~ and this is the second comment in part of the review...

**Comment by adamwiw** [comment]
![image](https://user-images.githubusercontent.com/15068903/49896399-3ddbf000-fe21-11e8-8625-0c168f6ce0b9.png)

**Comment by yjerem** [comment]
A force push by the PR owner seems to have fixed it for us:

(Warning: these commands can be destructive, don't use them unless you know what they're doing!)

```sh
$ git commit --allow-empty -m test
$ git push
$ git reset --hard HEAD^
$ git push -f
```
