### ISSUE TITLE
Ability to find Issues/PRs where I have left a comment

### ISSUE THREAD

**Issue by mehulkar** [isaacs/github#1343]
If you participate occasionally in otherwise busy projects, it can be very difficult to find your contributions. I would like to be able to filter Issues/PRs by Commenters (similar to how I can filter by an Author).

**Comment by jmarshall** [comment]
You can do this by [typing `commenter:mehulkar`](https://help.github.com/articles/searching-issues-and-pull-requests/#search-by-commenter) into the Issues/PRs Filters text box.

**Comment by mehulkar** [comment]
oh, cool, thanks!
