### ISSUE TITLE
github should have a real place to file issues

### ISSUE THREAD

**Issue by StefanKarpinski** [isaacs/github#1355]
@github, don't you think it's kind of ridiculous that the "official way" to submit [papercuts](https://blog.github.com/2018-08-28-announcing-paper-cuts/) is to file them on some random dude's github repo? (Sorry @isaacs and thank you for the service.)

**Comment by Mottie** [comment]
Duplicate of #1339 and #6.

**Comment by StefanKarpinski** [comment]
So it is.
