### ISSUE TITLE
Pull requests: internal discussion anchor links do not work for collapsed discussions

### ISSUE THREAD

**Issue by OliverJAsh** [isaacs/github#1357]
1. Get a PR link of `pull/${NUMBER}#discussion_${DISCUSSION_ID}`, where the given discussion is collapsed
2. Add the link to an issue (or anywhere in the GitHub interface)
3. Click on the link via the issue

I expect the browser to jump to the discussion, and the discussion to be expanded.

Actual: nothing happens.

The link does work when it is copied and pasted into a new tab. That is, when the link is navigated to as a browser navigation, rather than an in-app navigation.

https://github.com/unsplash/react-progressive-enhancement/pull/7#discussion_r194357494

**Comment by clarkbw** [comment]
Can you give a specific example link of this? Thx

**Comment by clarkbw** [comment]
I'm jumped to this, but I'm guessing you aren't...
<img width="857" alt="screen shot 2018-10-04 at 12 05 34 pm" src="https://user-images.githubusercontent.com/2134/46496824-d759a680-c7cd-11e8-97fe-eb8af567532f.png">

**Comment by OliverJAsh** [comment]
When you click the link in app, rather than loading the link directly?

**Comment by clarkbw** [comment]
> When you click the link in app, rather than loading the link directly?

I followed from the link you posted https://github.com/isaacs/github/issues/1357#issuecomment-426997412

**Comment by OliverJAsh** [comment]
This works for me now. Odd…

**Comment by OliverJAsh** [comment]
Ah, I realised this bug is still occurring, however only if the linked comment is lazy loaded https://github.com/isaacs/github/issues/1544
