### ISSUE TITLE
Search For 'Non-Archived' Repositories

### ISSUE THREAD

**Issue by eladkarako** [isaacs/github#1363]
Archived ones is already available, 
would like to have an ability to look for the 'non-archived' repositories as well, 

I would probably script it together using the Github-API, 
(all minus archived) and generate a web-page with the links to the repositories (maybe in a Chrome-extension)...
...but it would probably be much more natural to have this in github itself.

**Comment by clarkbw** [comment]
From an org / user?  Use the syntax `archived:true` or `archived:false`

https://github.com/clarkbw?utf8=%E2%9C%93&tab=repositories&q=archived%3Afalse&type=&language=

https://github.com/clarkbw?utf8=%E2%9C%93&tab=repositories&q=archived%3Atrue&type=&language=
