### ISSUE TITLE
Grouped repositories within an organisation

### ISSUE THREAD

**Issue by ryansmith94** [isaacs/github#1369]
I've noticed that for projects with multiple repositories we create a new organisation in order to group the repositories, but this makes it harder to manage the members of the organisation. Ideally organisations would have some way to group repositories.

**Comment by cirosantilli** [comment]
Related: https://github.com/isaacs/github/issues/302

**Comment by ryansmith94** [comment]
Closing and following #302 thanks @cirosantilli
