### ISSUE TITLE
"Topics" tag links bug

### ISSUE THREAD

**Issue by rnand** [isaacs/github#1374]
"Topics" tags is not linking properly.

What is expected:

"Topics" that we specify for repositories are clickable links. When the user click them, the link should point to https://github.com/topics/[clicked_topic]

What happens:

If you are under the repositories tab in your profile page, and click on any of the "topics" it will link to the same page, as in the current page reloads (the link src is https://github.com/[my_profile]?tab=repositories).

Where this issue occurs:
It occurs if you are here: My profile > Repositories tab

**Comment by rnand** [comment]
Reply from support@github.com:

> Thanks for the bug report—I've created an issue for our engineering team so they can investigate. I can't promise an ETA, but we'll follow up as soon as there's any news.

**Comment by clarkbw** [comment]
Fixed!
