### ISSUE TITLE
react-native i try to Authentication with facebook but i have problem pls help me

### ISSUE THREAD

**Issue by RobbieReyes1** [isaacs/github#1396]
my code

![image](https://user-images.githubusercontent.com/42710810/47604948-6c953700-da2a-11e8-98a3-755802132f8e.png)

and this error

![screenshot_1540648545](https://user-images.githubusercontent.com/42710810/47604951-761e9f00-da2a-11e8-9cf1-a83f53d7fb7c.png)

**Comment by Haroenv** [comment]
looks like your token is invalid, which gives that error. Note however that this repository is not for asking questions, check out https://stackoverflow.com/questions/tagged/react-native?mixed=1
