### ISSUE TITLE
One commit to apply multiple PR review suggestions

### ISSUE THREAD

**Issue by SWH30** [isaacs/github#1399]
I understand PR Review Suggestions are in Beta at the moment so this may be something that's already in the works but I can't find any information indicating that's the case.

Currently, if someone reviews your Pull Request they can now add 'suggestions' which are changes to the code which can be automatically applied in the GUI.

However, lets say there are many suggestions. Currently, the developer will have to apply each one individually, which in turn creates a new commit for each suggestion. 

Personally, I think it would be beneficial to be able to group/squash suggestions into one commit (a bit like squashing review comments into one review).

**Comment by mattyoho** [comment]
This shipped on November 7th: https://blog.github.com/changelog/2018-11-07-batching-suggested-changes/

Thanks for the feedback!
