### ISSUE TITLE
GitHub pages custom domain should verify account ownership

### ISSUE THREAD

**Issue by coderpatros** [isaacs/github#1405]
[This mug](https://github.com/KamiGaje123) has hijacked a bunch of custom github page domain names that have been left with dangling dns records.

I know that ultimately it should be up to the user to clean up old DNS records if they aren't using them. But it's clearly something that is being abused.

Maybe a custom TXT record that verifies the github account?

**Comment by yoannchaudet** [comment]
Happy to report that this is something we are currently working on! We are planning on shipping this feature this quarter.

**Comment by coderpatros** [comment]
That is fantastic news @yoannchaudet

**Comment by yoannchaudet** [comment]
This has just [shipped today](https://github.blog/changelog/2021-11-01-domain-verification-for-github-pages/)!
