### ISSUE TITLE
Prefill new "Releases" with query parameters

### ISSUE THREAD

**Issue by sindresorhus** [isaacs/github#1410]
GitHub supports [prefilling issues using query parameters](https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/). It would be *very* useful if this worked when creating new "Releases" too. Then scripts could pre-generate the release notes for new releases based on the commits and just open it for the user to edit and then publish it.

For example: https://github.com/chalk/chalk/releases/new?tag=v1.0.0&title=Foo&body=Notes would prefill the tag, title, and body fields. Since it works with issues, I kinda expected this to work with Releases too and was surprised when it didn't.

The alternative is using the GitHub API to create the actual release, but this is more complicated and requires either creating a login flow or requiring the user to get an access token, both of which are too much overhead for simple tools.

My specific use-case is being able to open a prefilled "Releases" entry for the user after publishing an npm package version with https://github.com/sindresorhus/np

**Comment by AraHaan** [comment]
what I would like is for user software to be able to get the latest release version (the one released the most recently in case the name of the release does not list it first) like to a place like for example:

``https://github.com/<user>/<repo>/releases/latest``

Or a way to get that from software without the github api, so the software would know that version: 0.16.0 or whatever was just released and the software itself can download it and auto apply the said update (like what most professional software does at least on Windows like Windows downloding it’s own updates).

**Comment by sindresorhus** [comment]
@AraHaan Please open a separate issue. This is totally unrelated.

**Comment by AraHaan** [comment]
#1417

**Comment by mattyoho** [comment]
:wave: @sindresorhus 

We've just added support for pre-filling the fields of the new Release form via query parameters. The supported parameters are:

<dl>
  <dt>tag</dt>
  <dd>The tag name for the Release.</dd>
  <dt>target</dt>
  <dd>The branch name or commit oid to point the Release's tag at, if the tag doesn't already exist.</dd>
  <dt>title</dt>
  <dd>The name of the Release.</dd>
  <dt>body</dt>
  <dd>The description text of the Release.</dd>
  <dt>prerelease</dt>
  <dd>Whether the Release should be tagged as a pre-release; valid values are "1" or "true".</dd>
</dl>

Hopefully this does the trick!

**Comment by sindresorhus** [comment]
Thank you! That was super-fast. 🙌

---

<sub>For Node.js usage, I made a simple module to make it easier to use: https://github.com/sindresorhus/new-github-release-url</sub>
