### ISSUE TITLE
Ability to list projects I'm watching for releases only

### ISSUE THREAD

**Issue by char-iot** [isaacs/github#1422]
applause for the victory of #410

when I tried to list projects I'm watching for releases only under https://github.com/watching

there isn't an option built for it yet. Can't that hard. pls add this feature soon. It's like a corresponding feature to #410.

**Comment by aldem** [comment]
Indeed, no projects which are watched for releases only are listed, though they should be.

**Comment by zxzzz8** [comment]
It feels to me like a very basic and critical option to see what you watch, and the watch-releases-only is no exception....

correct me if im wrong, but there is no way currently to know what you watch[release-only] other then see it on each repository specifically, r?

coz that means that if i forgot about a repository i watched[release-only], i don't have any way to find about it (other then when they make a release i guess....), r?

**Comment by wens07** [comment]
yes,  i also found myself about needing this feature,  please add this feature.

**Comment by SmbKiwi** [comment]
I agree. I'd like a list of the projects I'm watching as well.

**Comment by pm-pm** [comment]
I would like to have this useful feature too.

**Comment by neobiotics** [comment]
Count me in, this would be good.

**Comment by IceCodeNew** [comment]
Count me in.

**Comment by testiramsve** [comment]
I'm using newreleases.io for tracking my favorite projects. It has nice project listing, plus it notifies about tags, too. It has many other features that I need, it's much more advanced than this simple GitHub option. Check out the screenshots.

<img width="1254" alt="screen shot 2019-03-08 at 3 57 54 pm" src="https://user-images.githubusercontent.com/42513914/54037944-a12ab380-41bf-11e9-8e70-d71fd0a9c9e7.png">
<img width="1243" alt="screen shot 2019-03-08 at 4 16 30 pm" src="https://user-images.githubusercontent.com/42513914/54037956-a982ee80-41bf-11e9-8125-f11862df689a.png">

**Comment by karolina1819** [comment]
I'm using newreleases.io for tracking my favorite projects. It has nice project listing, plus it notifies about tags, too. It has many other features that I need, it's much more advanced than this simple GitHub option. Check out the screenshots.

<img width="250" alt="NewReleases project listing" src="https://user-images.githubusercontent.com/21146414/54038085-f9fa4c00-41bf-11e9-97a8-a40093029660.png">
<img width="250" alt="NewReleases project" src="https://user-images.githubusercontent.com/21146414/54038091-fbc40f80-41bf-11e9-8390-85c60c1abcc2.png">

**Comment by sophiebremer** [comment]
It looks like is has been added. I have now a list with release only subscriptions: https://github.com/watching
So the issue is probably solved and can be closed.

**Comment by TomasHubelbauer** [comment]
FYI as far as I can tell there is no API method for this yet.

**Comment by dufferzafar** [comment]
Yeah, there doesn't seem to be any API for either llisting the currently watched release-only repositories or for making a new release only subscription to a repo.
