### ISSUE TITLE
Deprecated repo option that makes it obvious the repo has been deprecated

### ISSUE THREAD

**Issue by dylang** [isaacs/github#144]
We're never going to delete our deprecated repos, but putting a line in the readme, no matter how big the text is, is going to be ignored by users.

I would like a standard way to mark a repo as deprecated. It would change the icon or text in the list of repos (strikeout?), and maybe a "deprecated" background image. 

The readme could be used to point to the replacement or have an explanation. 

**For example, which repos within each of these orgs are still in use, and which are deprecated?**
- https://github.com/npm
- https://github.com/gruntjs
- https://github.com/jquery

_edit: spelling, formating_

**Comment by jantman** [comment]
This would be good. #312 might provide the basis for it...

**Comment by rdodev** [comment]
Wholeheartedly concur. This should be implemented asap.

**Comment by Tafkas** [comment]
Good idea

**Comment by nmdguerreiro** [comment]
+1

**Comment by mejwaller** [comment]
+1

**Comment by FokkeZB** [comment]
+1

**Comment by mcongrove** [comment]
+1

**Comment by mattapperson** [comment]
+1

**Comment by vivekgidmare** [comment]
+1

**Comment by davetownsend** [comment]
yea, totally.

**Comment by tonylukasavage** [comment]
+1

**Comment by smarru** [comment]
+ 1, a very useful feature to mitigate unnecessary cluttering.

**Comment by john-dalsgaard** [comment]
+1

**Comment by Krozark** [comment]
+1

**Comment by Delapouite** [comment]
I also encountered this problem, relying on an old  vim plugin instead of finding the maintained one : https://github.com/kien/ctrlp.vim (2013) -> https://github.com/ctrlpvim/ctrlp.vim (2015)

**Comment by aisthesis** [comment]
+1

**Comment by mscappini** [comment]
+1

**Comment by KP** [comment]
I would add that a banner might be able to display other statuses like:

Red banner: Abandoned / deprecated
Yellow banner: No longer in active development. Minor fixes.
Green banner: Active development. Stable.
Light green banner: Early development. Unstable.

Users would control the categorization of the repo but if a repo had little activity over time, they would be prodded to confirm the repo's status.

**Comment by FokkeZB** [comment]
+100

**Comment by bradybd** [comment]
+1 to @KP's proposal

**Comment by Rich-Harris** [comment]
This would be hugely valuable, particularly @KP's idea of being prodded by Github to confirm the status of a repo

**Comment by leo** [comment]
+1

**Comment by mburns** [comment]
+1

**Comment by fbender** [comment]
+1

Has anybody contacted GH for this? Did they say anything?

**Comment by nemoDreamer** [comment]
:+1:

**Comment by lski** [comment]
+1 for this and also an extra +1 for @KP idea

For now though Im going to do the dirty hack of renaming the repo to -DEPRECATED-myreponame this makes it immediately obvious to anyone looking at it that its deprecated. I will then be briefly updating my Readme.md to say its deprecated too.

But most importantly as GitHub creates a redirect from the original repo name to the new -DEPRECATED- name, it will still work for those with the original alias.

I have done a test repo to check it works. It seems to work fine with new/old clones/pushes/pulls etc, although if anything can think of a good reason (other than it looks ugly :P) that this is a stupid idea let me know :)

Note: Obviously you cant reuse the original repo name (although if you could flag the original as deprecated you wouldnt be able to reuse the repo name again anyway) and doesnt quite fix the issue of @palewire of public_repositories but at least you could filter them out easier.

Just a thought anyway until they implement this :)

**Comment by macdonst** [comment]
+1

**Comment by sebbo2002** [comment]
+1

**Comment by Fank** [comment]
+1

**Comment by etspaceman** [comment]
+1

**Comment by nano2K** [comment]
+1

**Comment by mindplay-dk** [comment]
+1 

Arrived here while searching for a way to flag a couple of older projects as discontinued...

**Comment by vermorel** [comment]
+1 to @KP proposal. Half of the public repos of my companies are discontinued, merely kept around for archival purposes.

**Comment by fgregg** [comment]
+1

**Comment by nazrdogan** [comment]
+1

**Comment by chaner** [comment]
+1

**Comment by ibihim** [comment]
+1

**Comment by musically-ut** [comment]
+1

For what its worth, I created a chrome/firefox plugin because I have spent hours working on bug fixes to repositories which had been forked and were prospering elsewhere: https://github.com/musically-ut/lovely-forks

**Comment by nemoDreamer** [comment]
Sweeeeeet stuff, @musically-ut !

Btw, I also reached out to Github to ask them if they had an eye on this unofficial issue repo, and they added this particular issue to their TODO list. :wink:

**Comment by phillipgajadhar** [comment]
+1

**Comment by dowens-gd** [comment]
+1

**Comment by mindplay-dk** [comment]
As a work-around, I guess, create an organization like `yourname-deprecated` and move all of your deprecated repos our of your primary company/user space.

Would that work? Github maintains redirects/aliases both for old URLs and git repos, right?

**Comment by FokkeZB** [comment]
Nice idea, but I don't think the organisation name really stands out:

![screen shot 2015-11-17 at 10 16 28](https://cloud.githubusercontent.com/assets/2699409/11207229/4aa47efa-8d14-11e5-8e57-80573c4ff381.png)

**Comment by DaoWen** [comment]
+1

**Comment by nmiddleweek** [comment]
:+1:

**Comment by vmfo22** [comment]
+1

**Comment by krschultz** [comment]
+1

**Comment by klingenm** [comment]
+1

**Comment by twpayne** [comment]
+1 Being able to mark repos as deprecated would be a great help to both developers and users.

**Comment by garydamm** [comment]
+1

**Comment by fabdsp** [comment]
:+1:

**Comment by mikaelrandy** [comment]
:+1:

**Comment by tylerbuchea** [comment]
:+1:

**Comment by zessx** [comment]
:+1:

**Comment by anantsubramanian** [comment]
+1

**Comment by samstr** [comment]
:+1:

**Comment by mcplanner** [comment]
+1

**Comment by jacksonj04** [comment]
:+1:

**Comment by ProLoser** [comment]
Marking a repo as deprecated seems arbitrary as you have to come up with a bunch of business logic around what constitutes deprecation. Do you auto un-deprecate if you commit recently? What if alternative forks are more active? See #562

**Comment by dylang** [comment]
@ProLoser it wouldn't be automatic, it would be a manual setting only available to the owner(s).

**Comment by alexcarpenter** [comment]
+1

**Comment by stephengroat** [comment]
+1

**Comment by XGProyect** [comment]
+1

**Comment by eliecharra** [comment]
+1

**Comment by jnm2** [comment]
+1

**Comment by jhasse** [comment]
+1

**Comment by mlbright** [comment]
+1

**Comment by cnadiminti** [comment]
+1

**Comment by dtkahl** [comment]
+1

**Comment by agilecreativity** [comment]
+1

**Comment by Sorackb** [comment]
+1

**Comment by schaloner** [comment]
+1

**Comment by cafarm** [comment]
+1

**Comment by gotdibbs** [comment]
+1

**Comment by mwhitis** [comment]
+1 since I'm not the only one still looking for it.

**Comment by Kupla** [comment]
+1

**Comment by davidgardner11** [comment]
+1

**Comment by XGProyect** [comment]
+1

**Comment by TPS** [comment]
I suppose once this is done, it should disable PRs (pull-requests), just like issues already can be disabled.

**Comment by jasonrogena** [comment]
+1

**Comment by MetaAshley** [comment]
+1

**Comment by razumzhiro** [comment]
+1

**Comment by owebia** [comment]
+1

**Comment by maximveksler** [comment]
Would totally use this. Came here because I was looking for a solution. Probably as a work around going to edit the name of the project from **project-name** to **--DEPRECATED--project-name**

**Comment by clcpolevaulter** [comment]
👍

**Comment by meustrus** [comment]
:+1:

**Comment by natedunn** [comment]
+1

**Comment by kfirufk** [comment]
+1 👍

**Comment by ellavas** [comment]
+1

**Comment by LucasKovacs** [comment]
How long are we going to wait for this feature to be developed? :(

**Comment by stramel** [comment]
:+1:

**Comment by itinsley-lux** [comment]
👍

**Comment by Antwnis** [comment]
+1

**Comment by havstrucker** [comment]
:+1:

**Comment by damianh** [comment]
Happy Birthday, 3 years old this week! 🎉 🎈

**Comment by ajs6f** [comment]
👍

**Comment by mohierf** [comment]
:+1:

**Comment by amZotti** [comment]
👍

**Comment by bkemper** [comment]
👍

**Comment by Sphiinxx** [comment]
+1

**Comment by adrianvoica** [comment]
+1

**Comment by oriolblanc** [comment]
+1

**Comment by edennis** [comment]
+1

**Comment by dagfinnr** [comment]
I looked for a workaround and discovered that you can have emojis in GitHub's description field. So you can do something like this. The color helps to draw attention to it.

⛔️  [DEPRECATED]

**Comment by damianh** [comment]
https://github.com/blog/2309-introducing-topics

Tag your repo `deprecated` \ `obsolete` etc.

@dylang I think you can close this issue now.

**Comment by dagfinnr** [comment]
I'm thinking a topic for non-deprecated repos, so I can search only for the repos that are still current.

**Comment by dagfinnr** [comment]
Reading the documentation, it looks to me as if `-topic:deprecated` should select all non-deprecated repos, but it doesn't seem to work. A bug?

**Comment by Mottie** [comment]
@damianh Sadly, the tags don't always show up when browsing a users repository list (`https://github.com/{user}?tab=repositories`)

@dagfinnr has the best work-around so far, but I think the ideal solution would be to change the color of the repository title. Or, since GitHub already has an activity and heat map, it might be nice to include a colored swatch, icon or tag to indicate activity near the title.

**Comment by crazy-max** [comment]
+1

**Comment by FernandoGarcia** [comment]
+1

**Comment by rafwell** [comment]
+1

**Comment by deimyts** [comment]
@dagfinnr I couldn't get `-topic:deprecated` to work either, but `NOT deprecated` correctly excludes the repos.

**Comment by gufertum** [comment]
+

**Comment by fjahr** [comment]
+1

**Comment by tboronczyk** [comment]
+1

**Comment by susanwilcock** [comment]
+1

**Comment by oleersoy** [comment]
+1

**Comment by refack** [comment]
Need it for https://github.com/nodejs/node-v0.x-archive/

**Comment by judgewooden** [comment]
+1

**Comment by mcouthon** [comment]
+1

**Comment by redwarp** [comment]
+1

**Comment by captn3m0** [comment]
Just noticed that the legacy-homebrew repo is now marked as read-only:

[![image](https://user-images.githubusercontent.com/584253/30387135-3ddbf294-98c9-11e7-9ee6-75307883f981.png)](https://github.com/Homebrew/legacy-homebrew)

Anyone knows how this works?

**Comment by TPS** [comment]
I don't know but http://lmgtfy.com/?iie=1&q=%22This+repository+has+been+archived+by+the+owner.+It+is+now+read-only.%22 shows it's not the only 1.…  What do these folks know that _we_ all don't?  Anyone have contacts in those orgs?

**Comment by Mottie** [comment]
Wow @TPS, they really make lmgtfy annoyingly long... why would you use that here?

**Comment by TPS** [comment]
@Mottie It's _exactly_ how I feel @GitHub is treating us, i.e., infantile, by having a feature _actually_ available & not explaining in the blog or the help docs _how_ to access it. 😤

I've updated w/ a regular Google link, in addition, anyhow. 🙇

**Comment by davidmc24** [comment]
I sent a message to GitHub support asking about the "archived" feature, and here's the response I got:

> Hi David,Thanks for reaching out, and good eye! The ability to archive a repository is still in development, so it's not available to every repository yet. Please keep an eye out on our blog for an announcement in the near future!All the best,Ari

**Comment by ericnewton76** [comment]
+1

And perhaps we'll see it sometime this year (2017)?  ::crossed_fingers::

**Comment by refack** [comment]
https://github.com/blog/2460-archiving-repositories yyyaaaaayyy 🎉 
@dylang IMHO this can be closed

**Comment by clarkbw** [comment]
I'm closing this out as I believe archiving has solved most of the original issue.  Feel free to open up followups in new issues.

**Comment by mafshar** [comment]
+1
