### ISSUE TITLE
Ability to find issues that do not have PR

### ISSUE THREAD

**Issue by exoego** [isaacs/github#1447]
# User Story
As an OSS contributor, I often browse issues on OSS repositories.

It is also quite often that, when I open an issue with intent to open PR, somebody had already opend PR for the issue. 
It is happy to know the issue is being addressed, but digging into not-well-triaged issues steals some time from OSS contributors.

I saw some OSS had labels like `has PR` or `in progress` for marking issues, but such convention are easily forgotten and get unmaintained.

# Feature Request
It would be helpful if Github add ability to filter issues that no one opens PR for it, so OSS contributors can quickly find issues to contribute.

I imagin search query like `is:issue has:PR` or `is:issue is:addressed`.

**Comment by labrose** [comment]
Hello! I'm a Product Manager at GitHub. We just rolled out search support for cross references today!

For your example here:
>It would be helpful if Github add ability to filter issues that no one opens PR for it, so OSS contributors can quickly find issues to contribute.

That would be something like:
`is:issue is:open -linked:pr`

You can read more about it in the [changelog](https://github.blog/changelog/2020-02-04-linked-search-qualifier-for-finding-issues-connected-to-pull-requests/). Give it a try and let me know if this helps you find good issues to contribute!

**Comment by exoego** [comment]
@labrose 
Great addition 👍 
Now we can see an issue is linked from PRs or not.
![image](https://user-images.githubusercontent.com/127635/73808186-5de32580-4812-11ea-98ad-cdc695ca2b2e.png)

Closing as resolved.
