### ISSUE TITLE
support for multiline suggestions

### ISSUE THREAD

**Issue by oprogramador** [isaacs/github#1452]
<img width="715" alt="screen shot 2019-01-08 at 19 14 33" src="https://user-images.githubusercontent.com/8701039/50850302-c47ce200-1379-11e9-93d5-2b21eeb7f983.png">

PR suggestions are a great feature because:
- it saves time when resolving code review comments
- as resolving comments is so simple, code reviewers don't have fear about reporting too many comments which resolving could slow down the development so we obtain a better code
- it makes a clear git history because resolving each suggestion has its own commit

So it would be great to have also a possibility of multi-line suggestions (at least up to 5 lines) because sometimes a simple piece of code is split into several lines.

**Comment by Qix-** [comment]
Possible UX: click on line number to highlight, shift-click on another line to create range (identical to regular file views) and an add comment button appears with the suggestion already populated in a comment when clicked.

**Comment by w01fgang** [comment]
GitLab supports multiline suggestions.
This will replace 2 lines above and 11 lines below the line.
<img width="844" alt="Снимок экрана 2019-05-25 в 10 08 00" src="https://user-images.githubusercontent.com/8686751/58367223-195e6680-7edd-11e9-8eb0-4408dc7faedc.png">
But the UX is not very good, to see the range you need to go to the preview tab. It would be great to highlight the selected range.

**Comment by FabioPinheiro** [comment]
@w01fgang can you point to a PR that have a multiline suggestion?
I would be grateful. I can not make it work.

**Comment by ehsankhfr** [comment]
What's the status of development/review for this issue?

**Comment by Qix-** [comment]
@ehsankhfr This isn't an official tracker, and Github doesn't generally publicize their progress on anything nor do they confirm or deny even checking this tracker. However, history has shown a lot of the things suggested here make their way to mainline GH (see https://github.com/dear-github/dear-github which they _did_ respond to).

I'm sure this will happen. But don't count on status updates.

And please stop asking the "status of things". This is OSS, things are done when they're done. Most OSS is done on our free time.

**Comment by glyn** [comment]
> And please stop asking the "status of things". This is OSS, things are done when they're done. Most OSS is done on our free time. If it gets implemented it'll be supported here. There's no secret society where we track stuff outside of github for our own amusement.

IMO it's reasonable to ask about status of an issue in OSS when you thinking about working on it and want to avoid duplicating someone else's work. @ehsankhfr: I don't suppose you were stepping forward to implement this were you? ;-)

**Comment by Qix-** [comment]
@glyn This isn't something that anyone from the public could implement, so that point is moot.

**Comment by glyn** [comment]
Oops. Sorry.

**Comment by oprogramador** [comment]
Response from GitHub:
```
Thanks for writing in to GitHub Support!

We really appreciate feedback on how we can make GitHub even better and the best way to report any feature requests is directly to us through our community channels: https://github.community/

Please note that GitHub doesn't have an open feature request tracker and while https://github.com/isaacs/github/issues is a community resource, and as you have mentioned it's not officially supported by GitHub.

I'll go ahead and add your +1 for this feature to our internal list :)

I can’t make any promises as to if or when we may implement any changes, but I have shared your suggestion with the team for review and consideration.

Our roadmap is not publicly visible, so we recommend that you keep an eye on the GitHub Blog for the latest announcements about new features.

If you have any other questions, please do let us know.
```

So maybe each of use should send them an email in order to increase the probability of delivering this feature.

**Comment by Qix-** [comment]
That's a mostly canned response. I don't think GitHub really does anything with feature requests.

**Comment by jim-mason-dmxio** [comment]
hopefully this will be implemented soon

**Comment by fisher6** [comment]
> GitLab supports multiline suggestions.
> This will replace 2 lines above and 11 lines below the line.
> <img alt="Снимок экрана 2019-05-25 в 10 08 00" width="356" src="https://user-images.githubusercontent.com/8686751/58367379-c4235480-7ede-11e9-9c83-9ff75d98a313.png">
> 
> But the UX is not very good, to see the selected range you need to go to the preview tab. It would be great to highlight the selected range.

I hope GitHub will soon implement this feature! I tend to give multiline refactor suggestion that just looks bad when the suggestion of code to refactor has only one line of code.
Thanks GitHub devs!

**Comment by chrisnevers** [comment]
Please implement this feature, GitHub!

**Comment by phanib** [comment]
Much needed feature.

**Comment by chang** [comment]
GitHub has a short survey out where you can submit feedback on suggested changes: https://www.research.net/r/SuggestedChanges - this is probably the best way to be heard.
(from https://github.blog/2018-11-01-suggested-changes-update/)

**Comment by Qix-** [comment]
Multi-line comments are here, but the diffing still only supports the last line. Pretty shocking this is being missed lol. Feels like it'd be a natural feature to add...

**Comment by beatngu13** [comment]
@Qix- I wouldn't describe this as "shocking", multi-line comments are already a great improvement I think.

However, [according to Nat Friedman (GitHub's CEO)](https://twitter.com/natfriedman/status/1179100120626819072), multi-line suggestions are "[c]oming early next year".

**Comment by Qix-** [comment]
Thanks for the link @beatngu13, glad to see it's on their radar.

**Comment by hernimen** [comment]
what's the state of this?

**Comment by Qix-** [comment]
@hernimen This is neither an official Github tracker nor is there a way for us to track the internal issues repository that Github uses. The only updates available in _this_ issue tracker are those that are announced by Github.

What you see here is the most updated information the _public_ is aware of.

**Comment by ferdnyc** [comment]
> @Qix- I wouldn't describe this as "shocking", multi-line comments are already a great improvement I think.

It's pretty shocking, IMO they could've waited on debuting multi-line comments until they got suggestions working with them. As things stand right now we have this weird situation where you can _either_ use multi-line comments, or suggestions — but not really together.

(Actually, suggestions have been pretty broken since the start, for always being limited to single-line changes. It's kind of pointless that they even offer a button that commits suggestions, when so many of them can't be committed as-is without breaking the code. That they brought out multi-line comments _without_ first fixing **THAT**... I also find pretty shocking. You don't, I guess, and that's fine too.)
 
> However, [according to Nat Friedman (GitHub's CEO)](https://twitter.com/natfriedman/status/1179100120626819072), multi-line suggestions are "[c]oming early next year".

Good news, I suppose.

**Comment by jdatskuid** [comment]
@ferdnyc Code suggestions are usually not untested and "from the hip". It's not the right place for significant changes. Code suggestions are for very minor changes, such as fixing a typo in a string or adjusting whitespace. Something that doesn't significantly alter the logic and doesn't require a fresh round of testing. Significant changes should be described by the reviewer in general terms and then implemented by the submitter, otherwise you might as well just add your own commit to the branch (which I have done before).

Multiline suggestions will be great and I'm looking forward to them but it's totally reasonable that, in a PR review, you would want to keep those suggestions small and limited.

**Comment by oprogramador** [comment]
@jdatskuid 

I agree PR suggestions shouldn't be too big but very often a very short and simple piece of logic is divided into 2 or 5 lines.

**Comment by anton-matosov** [comment]
@fdatskuid commit from suggestions become part of PR and go through same checks as other commits in it. So if you have CI check it will run tests for suggested edits commit.

**Comment by jdatskuid** [comment]
To be clear, I understand the there is significant value in multi-line code suggestions. Indenting a whole block of code is great. Rewording an entire comment block, or fixing the order of JSDoc comments, is might useful.

I was mostly responding to:

> It's kind of pointless that they even offer a button that commits suggestions, when so many of them *can't be committed as-is without breaking the code*.

(emphasis mine)

If you have code suggestions that could break the logic, then maybe you aren't using code suggestions properly. It's not wise to make logic-changing suggestions in a PR and just hope and pray that your CI tools are good enough to pick up subtle changes that weren't intended. Heaven knows I've done this enough times in my own branch and the subtle change was too minor or edge-casey for the tests I had written. (Does that mean that my tests weren't sufficient? Yes, absolutely. Are yours? Are your colleagues'?)

If a PR requires significant changes, such that partially applied suggestions would be incompatible, then you should probably be making those changes in the branch and running the code and tests locally to make sure you aren't accidentally introducing breaking behavior.

Even if your CI tools are perfect, do you really want to start adding a flurry of commits via code suggestions to fix bone-headed and obvious bugs? You're just asking for an ugly and fractured git history. If you need to change the logic, then make the changes locally and push a commit when your tests pass.

**Comment by Qix-** [comment]
@jdatskuid The alternative is to create a branch off of a branch and PR into another pending PR. Quite the overhead for a two line change suggestion.

**Comment by navarr** [comment]
It would appear that you can make suggestions off multiline comments _manually_, but they cannot be automatically applied at current.

You select the lines like making a multi-line comment, and then type the suggestion format:
```
```suggestion
code
```

and it works as expected.  Preview does not show it, but posting it does.

**Comment by flow-control** [comment]
@navarr is right, just tried it out. In my case it even showed correct in the preview. All you have to do is to manually add the `suggestion` block

**Comment by ferdnyc** [comment]
@flow-control 

Yes, that absolutely does work, but those comments are exactly the ones I was referring to when I said they "can't be committed as-is without breaking the code". 

Fortunately, the "Commit Suggestion" button is (no longer?) active for suggestions in multi-line comments, so there's no danger of that happening.

But part of the value of structured suggestions — as opposed to simply leaving a comment saying:
<blockquote>Why don't we do this, instead?
<pre><code> ```language
// Suggested alternative
// More code
```</code></pre></blockquote>

...is the machinery that allows them to be quickly incorporated into the PR. That's something that's currently lost with "forced" multi-line suggestions, so there's effectively very little difference from the "manual" version above.

**Comment by JeHuiPark** [comment]
> @navarr is right, just tried it out. In my case it even showed correct in the preview. All you have to do is to manually add the `suggestion` block

Thanks!! 
However, the proposal cannot be automatically accepted.

**Comment by beatngu13** [comment]
[Tweet from Nat Friedman](https://twitter.com/natfriedman/status/1232727363626029056):

>Shipping today on GitHub: multi-line suggestions!

**Comment by scottrigby** [comment]
Finally! 🤩 👏 

![Screen Shot 2020-02-27 at 11 44 36 AM](https://user-images.githubusercontent.com/407675/75466449-363a3580-5958-11ea-8de8-fb9b372e265f.png)

![](https://help.github.com/assets/images/help/commits/hover-comment-icon.gif)

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request

**Comment by Qix-** [comment]
@clarkbw this can be closed. :)

**Comment by oprogramador** [comment]
@Qix- 

I forgot so I close it now.
Thanks for reminding.

**Comment by oprogramador** [comment]
@isaacs @cirosantilli 

could you add the `implemented` label?
I don't have such permissions

**Comment by trygveaa** [comment]
I tried this, but it seems like adding suggestions when one of the lines is deleted is not supported?

When you have a suggestion for multiple lines, those lines will very often include deleted lines, since all changed lines show up as a pair of deleted and added, so this severely limits the usefulness of multiline suggestions.

**Comment by benmoss** [comment]
Anyone else who is going as insane as I just was: you have to select the lines going from top to bottom, and you have to click the "+" button next to the bottom-most line of your selection :facepal

**Comment by trygveaa** [comment]
Yeah, not the most intuitive. If you drag on the plus instead of the line numbers, you don't have to click after dragging though.

**Comment by SuperV1234** [comment]
I just ran into an issue on a Markdown project. I attempted to create a multiline-suggestion around some text which contained a code block:

``````

Example blah blah

```cpp
foo bar
```

``````

This is not automatically detected, and requires me to manually change the triple backtick to a sextuple backtick to avoid a collision.

**Comment by Qix-** [comment]
@SuperV1234 Send a message via the contact form at the bottom of any GitHub page - GitHub doesn't actually check this issue tracker (not officially, anyway).

**Comment by mastef** [comment]
@SuperV1234 how did that work for you? I can't seem to be able to add a suggestion with a codeblock in it. It removes the ending triple backticks.

**Comment by GMNGeoffrey** [comment]
It would be nice if the generated suggestion block from GitHub did what mastef discovered above. Right now it will create invalid suggestion blocks when you click the button for any region containing codeblocks
