### ISSUE TITLE
Mobile search

### ISSUE THREAD

**Issue by ianks** [isaacs/github#1456]
The only feature that I really would love to see in GH would be the ability to search on a mobile device. Much of my job has become reviewing and research, so I end up talking mobile Safari to "Request Desktop Site" very often. If mobile search was a thing, then I would never have to do that 😀

**Comment by clarkbw** [comment]
![2ca28132-0011-4798-8b0b-c6fbdc45d1ec](https://user-images.githubusercontent.com/2134/53448378-1cc07f80-39cc-11e9-8cb9-76f9c3f28285.jpeg)

This doesn’t appear from the 3 bar menu?

**Comment by nolanhergert** [comment]
Seems to work for me from the 3-bar menu on my phone.

**Comment by nolanhergert** [comment]
Seems to work for me from the 3-bar menu on my phone.

**Comment by ianks** [comment]
🙇‍♂️
