### ISSUE TITLE
Add The Ability To Watch For README.MD Changes Only 

### ISSUE THREAD

**Issue by Neltherion** [isaacs/github#1466]
I want to follow and keep tabs on many projects but the only thing I need is to see if the README.MD has changed or not. Whenever the project is updated with new goods, the Author usually ends up modifying the README file about the new changes. Getting notified of these changes to the README file is enough for me.

This is something that not the "Watching" nor the "Releases Only" buttons can deliver. Following a repository by clicking on the "Watching" button is too cumbersome: You end up with lots of irrelevant emails about a new issue or a problem someone else has. The "Releases Only" button doesn't work on lots of repositories since they don't include any releases.

You can take this idea even further and add the ability to follow changes for certain files or folders (and not the README.MD file only).

Thanks

**Comment by cirosantilli** [comment]
possible subset of: https://github.com/isaacs/github/issues/1198

**Comment by Neltherion** [comment]
@cirosantilli it is... I'm going to close this issue. Thanks...
