### ISSUE TITLE
Mark files as "reviewed" in pull requests

### ISSUE THREAD

**Issue by aa403** [isaacs/github#1474]
With big pull requests, reviews are done over multiple days, by multiple people; and things can be complex

It would be great if there was a way to say "this file has been reviewed by me" on the ui; just as a way of tracking progress; and even better if reviewed / unreviewed files could be filtered

this is similar to "changes since you last viewed" but servers a different purpose

If there is a way to do this already then please let me know !!

**Comment by Pyton** [comment]
I would love this. The best would be to mark each diff "reviewed" and by default next time show only changes which were not reviewed.

**Comment by kimobrian** [comment]
I think this feature just rolled in. You can mark files as viewed.

![image](https://user-images.githubusercontent.com/22055697/60675772-d604f980-9e85-11e9-9466-c62071f747e9.png)

**Comment by aa403** [comment]
awesome :)
