### ISSUE TITLE
Can't Mark as read a notification about deleted release

### ISSUE THREAD

**Issue by pravic** [isaacs/github#1476]
This guy https://github.com/0xd4d/dnSpy/releases created and then deleted a release tag. 

Those who were subscribed to release only notifications now permanently have an unreal notification which can't be marked as read, because there's no such release anymore.

It isn't even listed among notifications, just a blue dot.

**Comment by pravic** [comment]
![img_20190126_083449](https://user-images.githubusercontent.com/724639/51783098-c5698e00-2145-11e9-8184-9f7fcd6b24ad.jpg)

**Comment by wizzup** [comment]
Duplicate of #1222 ?

**Comment by pravic** [comment]
Seems so. Thanks!
