### ISSUE TITLE
Global variables available to readme's

### ISSUE THREAD

**Issue by ericwooley** [isaacs/github#1477]
It would be awesome if some things were automatically replaced in the markdown. Maybe something like `$_GH_COMMIT_HASH` -> `3f3b7a9d29faaec6ff663b7ae835752cdd3e11d4`

So in links I could redirect to things like 
```md
[The docs]($_GH_REPO_URL/docs/$_GH_COMMIT_HASH/mydoc.md)
```

**Comment by mcouthon** [comment]
Merge with #1716?

**Comment by ericwooley** [comment]
@mcouthon  

Sure, why not
