### ISSUE TITLE
"Try again" redirect issue

### ISSUE THREAD

**Issue by 4rtuu** [isaacs/github#1478]
After commiting files on to my own project as a branch for some reason the upload fails with an error text "**Committing the files to the repository failed.**" with a button "**Try again**".
![tryagain](https://user-images.githubusercontent.com/6810192/51865673-b524ff00-234f-11e9-9c4c-cac9a30de6a1.PNG)
No clue what's that about but that's another story.

The button "**Try again**" redirects to _master_ branch uploads instead of the _intended_ one.

**Comment by TPS** [comment]
@4rtuu This isn't @GitHub support!  Try contacting them @ link below!
