### ISSUE TITLE
API to hide comments

### ISSUE THREAD

**Issue by mwarkentin** [isaacs/github#1480]
There doesn't appear to be an API to hide comments (like you can through the UI). It would be nice if this was available so that tools like [atlantis](https://github.com/runatlantis/atlantis) could mark outdated comments as hidden and clean up the PR greatly.

**Comment by iansan5653** [comment]
https://github.com/runatlantis/atlantis/issues/126#issuecomment-458726972

**Comment by dcabasson** [comment]
We ended up using the mutation that is available in the Github v4 API to do that:
https://developer.github.com/v4/mutation/minimizecomment/

**Comment by mwarkentin** [comment]
I think a graphql api counts, thanks!
