### ISSUE TITLE
Syntax highlighting for .es6 files looks very broken

### ISSUE THREAD

**Issue by dalexj** [isaacs/github#1499]
.es6 files on github are strangely highlighted to look like a diff file where the background of a line is red to show the part of the line that was deleted.

![image](https://user-images.githubusercontent.com/2790993/53272564-e377cf00-36ae-11e9-8fd6-43450934ebef.png)

It's extremely hard to read a diff with this syntax highlighting, since lines that havent changed are completely marked up and draw attention

**Comment by clarkbw** [comment]
You can file issues with syntax highlighting in the linguist repo https://github.com/github/linguist

**Comment by oprogramador** [comment]
@dalexj 

Maybe you could close this issue as it's to be reported on https://github.com/github/linguist .
You can also post the link to that new issue here.

**Comment by TPS** [comment]
Which from https://github.com/github/linguist/issues?q=es6 is correct?

**Comment by TPS** [comment]
Seems that https://github.com/github/linguist/pull/910 implemented this.
