### ISSUE TITLE
nested tables

### ISSUE THREAD

**Issue by aster94** [isaacs/github#1517]
Who would like to see nested tables?
example from wikipedia:
![immagine](https://user-images.githubusercontent.com/21184718/53695207-b024f680-3db8-11e9-95a5-cb0e7d210c2c.png)

**Comment by TPS** [comment]
Sorry, @aster94, @GitHub has already spoken @ https://github.com/vmg/redcarpet/issues/394.…

**Comment by aster94** [comment]
ok!

**Comment by aster94** [comment]
P.S: in case someone would ever come here you can use html to make nested tables
example from the web:
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th colspan="2">Telephone</th>
  </tr>
  <tr>
    <td>Bill Gates</td>
    <td>55577854</td>
    <td>55577855</td>
  </tr>
</table>
