### ISSUE TITLE
Select commit email when merging 

### ISSUE THREAD

**Issue by negebauer** [isaacs/github#1521]
When editing a file from Github's UI you can select which email to use for the commit

![image](https://user-images.githubusercontent.com/11860880/54306202-9dc06f00-45a7-11e9-9ad5-00287ff4b4f0.png)

But when merging a PR you can't, it should also be an option (to use the work email for merging prs in work related repos for example)

<img width="416" alt="image" src="https://user-images.githubusercontent.com/11860880/54306325-e0824700-45a7-11e9-820a-19c256e8799c.png">

**Comment by TPS** [comment]
https://github.blog/changelog/2019-03-15-creating-a-commit-on-behalf-of-an-organization/ → https://help.github.com/en/articles/creating-a-commit-on-behalf-of-an-organization seems very similar to this.

**Comment by negebauer** [comment]
this can now be done!
