### ISSUE TITLE
Email notification sender name schizophrenia 

### ISSUE THREAD

**Issue by jidanni** [isaacs/github#1522]
Let's say an average person makes an [average comment](
https://github.com/libssh2/libssh2/issues/300#issuecomment-473347008).

OK, this generates an email to the other people in the thread, using the
user's name (here Daniel Stenberg.)

They see
```
From: Daniel Stenberg <notifications@github.com>
Subject: Re: [libssh2/libssh2] ...
```
However, when those other users visit the page, they only see the
commenter's username, Bagder.
```
bagder commented 20 hours ago
```
Going back to the email generated, there is no mention of Bagder
anywhere.

And only via mouseover can users equate Badger with Daniel Stenberg.

You see how terrible this is?

**Comment by TPS** [comment]
Duplicates #278
