### ISSUE TITLE
Support Unicode in Project Names

### ISSUE THREAD

**Issue by Phrogz** [isaacs/github#1538]
Tried to create a project named "onǣlan" today. GitHub instead created a project named "on-lan". The Unicode description of "ǣ" is [LATIN SMALL LETTER AE WITH MACRON](https://www.fileformat.info/info/unicode/char/01e3/index.htm). Perhaps we don't want every Unicode glyph to be supported in project names, but I think it reasonable to allow "letters".

**Comment by TPS** [comment]
@Phrogz I think this issue should be closed in favor of reopening #101, as this is a specific instance of https://github.com/isaacs/github/issues/101#issuecomment-230692159. What do you think?
