### ISSUE TITLE
Convert existing PR into drafts

### ISSUE THREAD

**Issue by alerque** [isaacs/github#1547]
The new Draft PR feature (#416) is a great concept, but it is very difficult make use of without being able to change the status of existing PRs. It was mentioned in that issue that conversion was needed, but since the issue is closed (with the main feature implemented) I guess it's time for an issue specifically to track this addition.

**PR owners and project maintainers should be able to change the status on existing PRs to mark them as drafts.**

According to both the previous PR and [this Twitter thread](https://twitter.com/nesl247/status/1096095698796322816), this request has come to the attention of at least one product manager and Github.

**Comment by clarkbw** [comment]
Working on it

**Comment by alerque** [comment]
@TPS This and #1551 are really not even related to all the other issues that have the `saved / draft` tag, I would suggests that is a miss categorization. Drafts of comments and other messages are a completely different animal (and only visible to end users) from the draft status on PRs.

**Comment by TPS** [comment]
_OT: [We collaborators are having a dialogue re: best use of labels](https://github.com/isaacs/github/issues/1549), but my rule-of-thumb is try to use label combinations that best express what the issue's_ about, _so [saved/draft][PR] makes sense, IMHO._

**Comment by Xerus2000** [comment]
any progress on this? I have quite a few WIP PRs in my repos and it would be great if I could just switch them to be Drafts!

**Comment by wcox13** [comment]
I am also curious whether this is still in progress. It would definitely be useful.

**Comment by TomasVotruba** [comment]
I accidently created PR and wanted to go draft. Now I get lot of unwanted feedback :/

**Comment by priyankapatel1289** [comment]
> draft

You should at least remove the reviewers.

**Comment by priyankapatel1289** [comment]
> I accidently created PR and wanted to go draft. Now I get lot of unwanted feedback :/
> This feature could save my time and time of willing feedbackers.
You should at least remove the reviewers.

**Comment by priyankapatel1289** [comment]
@TomasVotruba You know you can still remove the reviewers? Then maybe change the title and add "Draft" to it

**Comment by rubenramos4** [comment]
+1

**Comment by TomasVotruba** [comment]
@priyankapatel1289 I can, but that won't stop feedback from people, that I don't want now

**Comment by Sajjon** [comment]
+1

**Comment by radrow** [comment]
Labels and adding "[draft]" to PR title won't block merging, which is imo the coolest feature of drafts. I don't think this issue is very hard to solve...

**Comment by mrgilman** [comment]
Hi! We just shipped this feature today. Here's the changelog entry: https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft

**Comment by karenetheridge** [comment]
@mrgilman You are a prince among men! thank you very much.

**Comment by mrgilman** [comment]
@karenetheridge I prefer princess, but I'll take it 😁

**Comment by karenetheridge** [comment]
oops sorry, I didn't mouseover to get an expansion of your name. so sorry! :> :> :>

**Comment by cjw296** [comment]
@mrgilman - any idea when this is coming to GHE?

**Comment by cjw296** [comment]
@mrgilman - also, headsup, that TPS bot looks to have a bunch of weird spam in its description...

**Comment by TPS** [comment]
@cjw296, @mrgilman:  Umm, I'm _not_ a 🤖.…

**Comment by samirmh-dev** [comment]
> Hi! We just shipped this feature today. Here's the changelog entry: https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft

Wow! Nice to hear it!

**Comment by mrgilman** [comment]
@cjw296 it'll either be in the upcoming release or the following one, not sure yet.

**Comment by antodoms** [comment]
Yay... this is released finally!!

**Comment by benwinding** [comment]
Was delighted to see this feature subtly introduced!
![image](https://user-images.githubusercontent.com/11782590/79523533-95d1d900-809d-11ea-858f-3caed20da2df.png)

**Comment by vvval** [comment]
This option is not presented in one of my PRs. I had to close the PR and reopen it (and choose "draft" in the dropdown section)

**Comment by mcolyer** [comment]
> This option is not presented in one of my PRs. I had to close the PR and reopen it (and choose "draft" in the dropdown section)

Can you provide any more detail around this? Has it happened more than once?

**Comment by timotheecour** [comment]
this feature only seems to work when there are some reviewers requesting changes (not just comments but comments marked as review comments, eg requesting changes through github UI), eg:
* appears here: https://github.com/nim-lang/Nim/pull/14025
* doesn't appear here: https://github.com/nim-lang/Nim/pull/14043

**Comment by mcolyer** [comment]
@timotheecour thanks, we'll take a closer look and see if we can figure out what's going on.

**Comment by mr-feek** [comment]
Just wanted to share that I'm loving this feature!

**Comment by EmilyRosina** [comment]
Does anyone know of a github action where we can change labels when the draft status is changed?

Ideally we'd be able to:
- **When converted to draft** add "wip" label, remove "ready" label
- **When converted to ready to review** remove "wip" label, add "ready" label

**Comment by jinmayamashita** [comment]
@EmilyRosina
> When converted to ready to review remove "wip" label, add "ready" label

my action is still a work in progress, but I hope it helps you.
https://github.com/marketplace/actions/ready-for-review.

**Comment by EmilyRosina** [comment]
@jinmayamashita oh wow that's awesome, thank you :tada:
