### ISSUE TITLE
Allow full text search of project wikis

### ISSUE THREAD

**Issue by eugeneware** [isaacs/github#155]
The wiki functionality is awesome, but they currently can't be searched. We were all prepared to move to github for our team wikis, but this lack of functionality is a bit of a deal breaker.

**Comment by willthemoor** [comment]
+1. Would love to see it integrated into the main repo search (code, issues, +wiki).

For now, there is https://github.com/linyows/github-wiki-search

**Comment by swrobel** [comment]
:+1:

**Comment by chrismwendt** [comment]
Wikis are now searchable :tada: https://github.com/blog/2219-search-wiki-pages

**Comment by eugeneware** [comment]
Thank You! Thank You! Thank You!

**Comment by davidebbo** [comment]
@chrismwendt awesome! And thanks for taking the time to respond on this unofficial tracker :)

**Comment by TPS** [comment]
@eugeneware If https://github.com/blog/2219-search-wiki-pages solves this issue for you, close FTW. :smile: Else, mention what's missing.
