### ISSUE TITLE
Completely removing code from codebase with the new force-push feature

### ISSUE THREAD

**Issue by pbassut** [isaacs/github#1552]
So, this happened a while ago: https://twitter.com/github/status/1063498022963699712?lang=pt

I accidentally committed something I didn't want to to the codebase. And now when trying to force-push in order to completely erase it's contents, github gives me this link to diff from the new state to the very thing I rebased, force-pushed in order to remove. 
It's essentially a link to a compare between two commits' SHA1. Meaning commits are still there somewhere(at least until it's garbage-collected by github's backend https://github.com/isaacs/github/issues/997)

My question: **How to truly remove a commit from the internet?** Or how long should I wait until I'm sure I'm completely safe?

Looks like this was possible even before the UI for force-pushes. As stated in https://github.com/isaacs/github/issues/998. 
But now that's way more accessible with the UI for force-pushes.

**Comment by clarkbw** [comment]
Here's the related help page https://help.github.com/en/articles/removing-sensitive-data-from-a-repository 

GitHub support can help you.

**Comment by pbassut** [comment]
That is indeed helpful. Sorry for not looking so thoroughly.
