### ISSUE TITLE
How to switch to GitHub mobile website?

### ISSUE THREAD

**Issue by neoql** [isaacs/github#1554]
While browsing GitHub from chrome on Android I switched to desktop version of the website through buuton on the footer. Now I couldn't find way to switch back to mobile version. When I use my account to access github, it's always desktop version. How could I bring mobile GitHub back?

**Comment by ayan-b** [comment]
Here https://github.com/settings/admin you can update your mobile settings.

**Comment by neoql** [comment]
@ayan-b Thank you!

**Comment by twlz0ne** [comment]
Nothing changed when I clicked the `Update mobile settings`:

![212E77EC-C259-479A-9398-F7CDD6F21E16](https://user-images.githubusercontent.com/2653486/78465182-c40dfb00-7724-11ea-9e04-c96da5dfbe33.png)

**Comment by ayan-b** [comment]
@twlz0ne Not all pages are mobile optimized. See this repo page (i.e., https://github.com/isaacs/github) and you should be able to see the mobile version.

**Comment by twlz0ne** [comment]
@ayan-b All repository pages don't have mobile view on my phone (I'm using iOS&Safari):
![A897805B-DA35-4523-9C7C-D992867237F7](https://user-images.githubusercontent.com/2653486/78465523-544e3f00-7729-11ea-8044-1a96e8342902.png)

I remember once there was a `Switch to mobile version` button (like this: http://mhmd.us/ZNrx+ ) on the top of page, but it was gone.

**Comment by ayan-b** [comment]
> 
> 
> @ayan-b Nothing changed when I clicked the `Update mobile settings`:
> 
> ![212E77EC-C259-479A-9398-F7CDD6F21E16](https://user-images.githubusercontent.com/2653486/78465182-c40dfb00-7724-11ea-9e04-c96da5dfbe33.png)

@twlz0ne You are opting out, instead you should opt-in. So uncheck the checkbox.
