### ISSUE TITLE
Linking private repo to user Project redirects to "What‽" page

### ISSUE THREAD

**Issue by ErikHumphrey** [isaacs/github#1558]
It seems you can now create projects on your user profile, rather than projects in a repository. However, linking private repositories brings me to the "What‽" error page instead of the Project page. The project is still created.

### Steps to reproduce

1. Navigate to your profile.
2. Click on the Projects tab.
3. Click the **New project** button.
4. Fill in a valid project board name and link a private repository. The visibility of the project itself does not matter.
5. Click the **Create project** button.

**Comment by clarkbw** [comment]
thanks for the steps. 

I wasn’t able to reproduce this, I created a public project linked to a private repo. https://github.com/users/clarkbw/projects/1

**Comment by ErikHumphrey** [comment]
It seems all that the Projects are actually created successfully, but I'm brought to the "What‽" page on creation.

**Comment by ErikHumphrey** [comment]
@clarkbw It seems that you just can't link archived repositories to Projects now. Well, that's one way to do it.
