### ISSUE TITLE
Remove the bug emoji from the bugs label in this repo

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#1580]
Emoji in labels is a bad idea IMHO since labels appears in URLs and search querries: https://github.com/isaacs/github/labels/bug%20%F0%9F%90%9B

Let's keep the URLs and search clean and sane :-)

**Comment by oprogramador** [comment]
@cirosantilli 
I like this bug emoji but for I understand your point.

**Comment by captn3m0** [comment]
Sounds reasonable.

**Comment by cirosantilli** [comment]
People in https://github.com/isaacs/github/issues/1549 seemed to agree as well, so I did it.
