### ISSUE TITLE
Allow the merge button to be removed

### ISSUE THREAD

**Issue by xvfionn** [isaacs/github#1583]
In repository settings, the functions available to the merge button are selectable. However, when attempting to deselect all options, the final one remains selected and a notice saying "You must select at least one option" is displayed.

I would like to disable merging via the UI entirely. This is desirable for a couple of reasons -- in my case because I want to assert that the PGP signatures on all commits were made by keys in a certain set (that doesn't include GitHub's web-flow key).

<img width="735" alt="Screenshot 2019-05-27 at 12 33 31" src="https://user-images.githubusercontent.com/29530803/58396166-1058cb00-807e-11e9-9b48-17c9492ffe25.png">

**Comment by xvfionn** [comment]
GitHub's response.

> It isn't currently possible to disable merging via the UI completely. I can see how it would be useful in your scenario though, so I'll pass this suggestion on to our team to consider!

**Comment by TPS** [comment]
Duplicates #5
