### ISSUE TITLE
Filter cards by no milestone on a project board

### ISSUE THREAD

**Issue by SanderSmitEvry** [isaacs/github#1601]
We can filter for specific milestones on a project board using milestone:name, but not which cards have no milestones yet. Would be handy if we could use the no:milestone search query in this filter in the same way that we can use it when searching through issue.

Filter cards with no milestone by using: no:milestone

**Comment by gwu1** [comment]
Any update?

**Comment by labrose** [comment]
👋Hi there! GitHub Projects PM here. Thanks for pointing out that we forgot to include support for `no:milestone` when we added milestone filtering support to Project boards. If you take a look, you should be able to filter by `no:milestone` now!
