### ISSUE TITLE
Add shrug reaction to display indifference or uncertainty

### ISSUE THREAD

**Issue by ErikHumphrey** [isaacs/github#1608]
Using `:confused:` 😕 doesn't work in as many situations.

See also: #1228

**Comment by MarcGab** [comment]
A shrug stands for 

> being indifferent about something or not knowing an answer to a question.

If a user does not care or has no answer why should he get invovled?
So how would a shrug   ¯\_(ツ)_/¯  emoticon be helpfull?

**Comment by ErikHumphrey** [comment]
🤷

* To indicate that you do not know the answer (in response to a mention) without explicitly writing a comment 
* When two sides are arguing in a public repository and someone's comment has both good points and bad points, but you don't feel it is necessary to create a coment explaining that you're in between
* To indicate confusion

It probably has more practical uses than 😕, including its existing uses.
