### ISSUE TITLE
"Featured" Issues

### ISSUE THREAD

**Issue by brock** [isaacs/github#161]
Repos with a lot of activity can generate the same questions over and over. However, once those issues get closed, they fall off the screen, and new users don't see them.

I'd propose the ability to set a "Featured" Issue (or "Sticky", though a "sticky issue" has a different connotation), one that stays on the Open Issues page, even after it is closed:

![](http://f.cl.ly/items/0h2S2i1n0h3H1g073t0d/featured_issues.png)

I'm using the Slate repo in this screenshot, highlighting this particular issue as the example: https://github.com/slate/slate/issues/80

**Comment by lukehefson** [comment]
Hello to those still watching this 👋! We just shipped something that we hope you like: https://blog.github.com/changelog/2018-12-13-pinned-issues/

Thanks for your feedback! 💛

**Comment by clarkbw** [comment]
Take a look at the new pinned issues feature and let us know if there are any other changes you'd like to see!  Thanks!
