### ISSUE TITLE
Ability to add 'due date' to tickets

### ISSUE THREAD

**Issue by TonyRutherford1** [isaacs/github#1626]
This is such a basic but key missing feature :-)

**Comment by clarkbw** [comment]
Duplicate of https://github.com/isaacs/github/issues/432 ?

**Comment by TonyRutherford1** [comment]
Yes, but as that is from 2015 looks like its dead... So trying to bring some light back to this feature :-)

**Comment by oprogramador** [comment]
As it's a duplicate, IMO it should be closed.

@TonyRutherford1 you can:
- mark the original issue with 👍or ❤️
- comment the original issue
- share the original issue on Slack (of your organization or some Open Source community), Facebook, Twitter or head-to-head ask for voting in your company office, your university building or at some meetup.
