### ISSUE TITLE
Allow forking only the default branch

### ISSUE THREAD

**Issue by zypA13510** [isaacs/github#1631]
Usually, when I create a fork, I only need the default branch (master). But GitHub, by default, copies all the branches to the fork. Having them prevents me from finding my own branch (patch) easily - there are repositories having 30+ branches. So I usually end up deleting all of them manually, if I know I will work on the fork for a long time. And if I really need them later, I can always add the upstream as a remote in my local clone and then fetch them, but this is very rare. Most of the time I never use those non-default branches at all.

I would suggest that a new forking option - only fork the default branch - to be added, favorably as an account-level option. Users with this option enabled will only have the default branch of upstream copied to their fork, other branches will be automatically discarded.

**Comment by TPS** [comment]
@zypA13510 Per https://github.com/isaacs/github/issues/1246#issuecomment-519464284, I'll close this duplicate, as I've reopened that original issue.  Please do replicate the above there. 🙇🏾‍♂️
