### ISSUE TITLE
Visitors and git clone insights traffic stats on all repos shows as zero since the 21st August 2019

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#1650]
Either the 50 daily people I had on my top two repos suddenly became zero, or you have a bug:

- https://github.com/cirosantilli/linux-kernel-module-cheat/graphs/traffic
- https://github.com/cirosantilli/x86-bare-metal-examples/graphs/traffic

My bet is on your IP update 11 days ago: https://github.com/cirosantilli/china-dictatorship/issues/33#issuecomment-520726444

![Screenshot from 2019-08-24 07-41-16](https://user-images.githubusercontent.com/1429315/63633593-e98d3f00-c642-11e9-9a70-ae9e68616a76.png)

**Comment by nondanee** [comment]
Same issue

![image](https://user-images.githubusercontent.com/26399680/63637514-63f3a880-c6af-11e9-9d02-9e87445c4adc.png)

**Comment by nealvis** [comment]
same issue on all my repositories

**Comment by GoldenChrysus** [comment]
Same issue.
![image](https://user-images.githubusercontent.com/17366720/63638672-7216da00-c659-11e9-8d24-7d12204688c2.png)

**Comment by intxcc** [comment]
Same issue
![grafik](https://user-images.githubusercontent.com/17449580/63639666-71506900-c696-11e9-8a6e-b3f6656d6df3.png)

**Comment by mviereck** [comment]
I think we have enough #metoos.

**Comment by cirosantilli** [comment]
@mviereck wrong, you can never have enough metoos, bring it on plebs :metal: :metal: :metal: :metal: :metal: :metal: :metal: :metal: :metal:

**Comment by hfawaz** [comment]
Metoo

**Comment by haydoooke** [comment]
Same here...

**Comment by dan-da** [comment]
me too.  seriously github...?   2+ days without any traffic reporting?

**Comment by breck7** [comment]
Same issue....

**Comment by or-else** [comment]
Classy response from github support:

> Thanks for reaching out to GitHub Support, and sorry for the trouble.
>
> We're currently investigating similar reports regarding this issue, and I've added your report to our list.
>
> While we can't share a specific ETA just yet, we'll be sure to update you as soon as there's any news to share.
>
> I hope this helps, but just let us know if there's anything more we can do in the meantime!

**Comment by ddnexus** [comment]
Can you feel the Microsoft influence after 5 days without solutions? :rofl:

**Comment by breck7** [comment]
Also many reports of this on Twitter: https://twitter.com/search?q=github%20traffic&src=typed_query

But don't worry everyone, "All Systems Operational": https://www.githubstatus.com/

**Comment by dan-da** [comment]
not to mention that github only provides data/chart for past week (clones, visitors), and doesn't provide download data at all for tagged releases.  Even Sourceforge was providing better reporting in 2002.

**Comment by seancfoley** [comment]
me too

**Comment by limlimlim-study** [comment]
same issue

**Comment by we684123** [comment]
me too!

**Comment by remkop** [comment]
me too

**Comment by skypjack** [comment]
me too

**Comment by or-else** [comment]
How about instead of saying yet another "me too" you would give a like to one of the identical posts above?

**Comment by v0devil** [comment]
me too

**Comment by ivanpaulovich** [comment]
Hey all,

It seems to be fixed today:

![ivanpaulovich-github](https://user-images.githubusercontent.com/7133698/63696629-6d9a1f00-c81b-11e9-9ad2-1e824dbfd144.png)

**Comment by plokhotnyuk** [comment]
@ivanpaulovich thanks! great news! it is getting better on our repos too...

**Comment by cirosantilli** [comment]
It's back. Fun's over boys and girls.

**Comment by MikhailTymchukDX** [comment]
Is missing data recoverable?

**Comment by mviereck** [comment]
> Is missing data recoverable?

Of course. But it will take about 2 weeks.

**Comment by skypjack** [comment]
It's gone... again. Should we re-open this or create a new issue?

**Comment by ddnexus** [comment]
Today is down again, but the old data that was showing as 0-0 is now back. One piece at the time Microsoft. :smiley:

**Comment by skoruba** [comment]
Today it is wrong again.

**Comment by gykovacs** [comment]
I think the issue should be reopened, github is not recording traffic again.

**Comment by seancfoley** [comment]
Mine was gone yesterday, back today.  Seems they are moving repos around inside the company, and the tools that record the traffic against the repos are not being updated to the new IP addresses at the same time that the things are moved.

**Comment by breck7** [comment]
What is everybody talking about? Clearly by https://www.githubstatus.com/ everything is working properly. https://www.githubstatus.com/ couldn't be wrong. GitHub has been perfect for weeks.

\s
