### ISSUE TITLE
Allow issue file image upload with an upload button without drag and drop

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#1651]
I'm on a laptop. All my windows are fullscreen. I never use my file manager, only terminal. You force me to open file manager small, minimize my browser, and do the thing.

Instead, do like every other upload UI and add a button with file search. Users have also found this dangerous: https://github.community/t5/How-to-use-Git-and-GitHub/Drag-and-drop-file-upload-seems-hazardous/td-p/16521

**Comment by douph1** [comment]
same here .. I don't want to open a "file manager" just to drag and drop .. please consider adding an "upload" icon
Thanks

**Comment by cirosantilli** [comment]
Noticed they added the button at some point now.
