### ISSUE TITLE
Sort our projects in the profile page

### ISSUE THREAD

**Issue by brenoc** [isaacs/github#166]
As discussed here: [https://news.ycombinator.com/item?id=7567002](https://news.ycombinator.com/item?id=7567002)

I don't want to give that much importance for college repos. I would like to sort the projects that are important to me and for my career.

**Comment by ffsantos92** [comment]
:+1:

**Comment by clay-to-n** [comment]
Will this ever become real?  This issue was opened a year ago.

**Comment by ludo237** [comment]
@clay-to-n I guess no

**Comment by ajwl** [comment]
+1

**Comment by mandeepbhutani** [comment]
This is a much needed feature.

**Comment by vdubedout** [comment]
:+1:

**Comment by blitzprog** [comment]
:+1:

**Comment by vdubedout** [comment]
Why you don't use Github Organisation system to sort important stuff to you

**Comment by brenoc** [comment]
Fixed https://github.com/blog/2191-pin-repositories-to-your-github-profile
