### ISSUE TITLE
Add setting to automatically block +1 comments

### ISSUE THREAD

**Issue by pascalwhoop** [isaacs/github#1685]
People often react with :+1: by posting a comment. It's always frowned upon but people actually need to teach each and every newcomer that that is not desired. These comments usually get a bunch of :-1: reactions and then somebody says "yo don't do that" which gets :+1:  again.

Instead, the frontend could just block people from posting a comment which only contains :+1: and give a small feedback educating about the fact that this is not desired

![2019-11-07_12-06-26](https://user-images.githubusercontent.com/2284951/68384060-b12fd400-014e-11ea-8074-e6d4d4ea6cad.jpg)

**Comment by TPS** [comment]
Duplicates, e.g., #640
