### ISSUE TITLE
GH pages does not serve /.well-known directory (per RFC 5785)

### ISSUE THREAD

**Issue by mikesamuel** [isaacs/github#1688]
Github Pages does not server content in directories that start with dot, presumably because these are [hidden per UNIX file conventions](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory#Unix_and_Unix-like_environments).

This affects serve a [custom domain](https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site) that wants to serve content under `/.well-known` per [RFC 5785](https://tools.ietf.org/html/rfc5785) which says

> this, this memo defines a path prefix in HTTP(S) URIs for these "well-known locations", "/.well-known/".  Future specifications that need to define a resource for such site-wide metadata can register their use to avoid collisions and minimise impingement upon sites' URI space.

I'd like `https://`*mydomain*`/.well-known/security.txt` to serve the file under `tree/master/.well-known/security.txt` per [securitytxt.org](https://securitytxt.org) which says

> security.txt defines a standard to help organizations define the process for security researchers to disclose security vulnerabilities securely.
>
> For websites, the security.txt file should be placed under the /.well-known/ path (/.well-known/security.txt) [RFC5785]. It can also be placed in the root directory (/security.txt) of a website, especially if the /.well-known/ directory cannot be used for technical reasons, or simply as a fallback.

I'd rather not rely on security researches knowing about the fallback path (/security.txt).

It'd be sufficient if `/.well-known` was recognized as not a regular dot file, or if there was a project configuration option that allowed listing dotfiles to serve.

Details on my site configuration which prompted this:
https://stackoverflow.com/questions/58699725/how-can-one-get-github-pages-to-serve-dot-files-like-rfc5785s-well-known

**Comment by mikesamuel** [comment]
The . directory ignoring is due to Jekyll preprocessing.

https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/ has a workaround.

**Comment by EdOverflow** [comment]
Here is a quick workaround for the time being. Create a `_config.yml` file and add the following lines:

```
include:
- .well-known
```

Example: https://github.com/securitytxt/securitytxt.org/blob/master/_config.yml

**Comment by mikesamuel** [comment]
@EdOverflow, thanks.  That's more elegant than turning off jekyll entirely.

And thanks for your work on security.txt.

**Comment by yoannchaudet** [comment]
Closing this one since two solutions were proposed.
