### ISSUE TITLE
Add search syntax token for my own username 

### ISSUE THREAD

**Issue by patcon** [isaacs/github#1694]
I wish to create shared links that work for many people in meeting notes. For example:

https://github.com/issues?q=org:hyphacoop+sort:updated-desc+involves:YOU

Currently, there's no search token, and so the person is expected to just see the "YOU" and know to update that once they arrive on page.

It would be nice if there was a designated token in the search syntax :)

Potential suggestions: `@you @self @myself`

Thanks for considering! And thanks a ton for all you do

**Comment by patcon** [comment]
If someone could add the `search` label, that'd be rad!

**Comment by jmarshall** [comment]
See also #1293.

**Comment by clarkbw** [comment]
I feel like this is a duplicate of #1293.

**Comment by patcon** [comment]
Agreed! Thanks. +1'd
