### ISSUE TITLE
500 on adoc infinite header xref recursion

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#1718]
Edit: I'm having so much fun right now, with the addition of [GitHub profile READMEs](https://dev.to/m0nica/how-to-create-a-github-profile-readme-1paj) I can now 500 my profile page:

- https://github.com/cirosantilli is now a 500 ([archive](http://web.archive.org/web/20200715095116/https://github.com/cirosantilli))
- https://github.com/cirosantilli/cirosantilli/commit/737eac61d340c94760ae4017376e4749ccd19191 has a sample adoc file
- me being happy: https://twitter.com/cirosantilli/status/1283339613814370304 | https://news.ycombinator.com/item?id=23843125

Reproduction on non profile:

- https://raw.githubusercontent.com/cirosantilli/test-git-web-interface/04e8a440ed7a2db6815c7d3eff51358584f4d48d/xref-header-infinite-loop.adoc ([archive](http://web.archive.org/web/20200118142043/https://raw.githubusercontent.com/cirosantilli/test-git-web-interface/04e8a440ed7a2db6815c7d3eff51358584f4d48d/xref-header-infinite-loop.adoc))
- https://github.com/cirosantilli/test-git-web-interface/blob/04e8a440ed7a2db6815c7d3eff51358584f4d48d/xref-header-infinite-loop.adoc ([archive](http://web.archive.org/web/20200118142118/https://github.com/cirosantilli/test-git-web-interface/blob/04e8a440ed7a2db6815c7d3eff51358584f4d48d/xref-header-infinite-loop.adoc))

On adoc tracker: https://github.com/asciidoctor/asciidoctor/issues/3543

cc. @mojavelinux :-)

**Comment by mojavelinux** [comment]
Can you please file this in the Asciidoctor project?

**Comment by cirosantilli** [comment]
https://github.com/asciidoctor/asciidoctor/issues/3543

**Comment by mojavelinux** [comment]
Thanks. I'll have a look.

**Comment by cirosantilli** [comment]
They deployed it :-(
