### ISSUE TITLE
Better Build Status Integration

### ISSUE THREAD

**Issue by 0xcaff** [isaacs/github#172]
Many projects use CI to build and test their project on every commit. GitHub currently has the [Build Status API](https://developer.github.com/v3/repos/statuses/)

> The Status API allows external services to mark commits with a success, failure, error, or pending state, which is then reflected in pull requests involving those commits.

In many of these projects there is a badge: [![Build Status](https://travis-ci.org/caffinatedmonkey/caffinatedmonkey.github.io.svg?branch=source)](https://travis-ci.org/caffinatedmonkey/caffinatedmonkey.github.io) in the README. It would be nice if GitHub had this functionality. Here are some examples:

![Failing](https://cloud.githubusercontent.com/assets/3277097/2751347/f76ee2ba-c8c6-11e3-863a-899f5e6b839a.png)

![Passing](https://cloud.githubusercontent.com/assets/3277097/2751346/c8824b0e-c8c6-11e3-990d-a2aa22f8f7b5.png)

![Error](https://cloud.githubusercontent.com/assets/3277097/2751345/be4f0d84-c8c6-11e3-90d2-3a1deea808d6.png)

![Running](https://cloud.githubusercontent.com/assets/3277097/2751342/85429204-c8c6-11e3-9a5f-12eebbb8d505.png)

Clicking on the build status will take you to the build logs and mousing over the build status will show some information about the build, like duration.

Also in the commits list: `github.com/<user>/<repo>/commits/<branch>`

And in the commit view: `github.com/<user>/<repo>/commits/<commit id>`

And in the large `repo-list` view:

![repo list](https://cloud.githubusercontent.com/assets/3277097/2751399/c8725aa0-c8cb-11e3-9084-858ef16d9764.png)

![repo list](https://cloud.githubusercontent.com/assets/3277097/2751408/2341cdf8-c8cc-11e3-93b8-398504518176.png)

A way to view a more detailed ci status @ `github.com/<user>/<repo>/<ref>/ci`

**Comment by aureooms** [comment]
+1

**Comment by 0xcaff** [comment]
wow we have this now 
![image](https://user-images.githubusercontent.com/3277097/63220463-25616980-c156-11e9-96ca-ec1f38b38e50.png)
