### ISSUE TITLE
Allow Triage access rights to manage issues properly

### ISSUE THREAD

**Issue by szymonmichalik** [isaacs/github#1728]
Currently every user with `Triage` access rights can only create issues without a possibility to assign them, change labels, manage projects or add to milestones.

The first available access level offering this is `Write`

As a Triage access group is a perfect match for project managers who don't need `Write` rights to a repository, it would be good to allow such for `Triage` users as well.

**Comment by clarkbw** [comment]
https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level

The Triage role does have access to assign, change labels, (I believe) manage projects, and milestones.

Repository action | Read | Triage | Write | Maintain | Admin
-- | -- | -- | -- | -- | --
Pull from the person or team's assigned repositories | X | X | X | X | X
Fork the person or team's assigned repositories | X | X | X | X | X
Edit and delete their own comments | X | X | X | X | X
Open issues | X | X | X | X | X
Close issues they opened themselves | X | X | X | X | X
Reopen issues they closed themselves | X | X | X | X | X
Have an issue assigned to them | X | X | X | X | X
Send pull requests from forks of the team's assigned repositories | X | X | X | X | X
Submit reviews on pull requests | X | X | X | X | X
View published releases | X | X | X | X | X
View GitHub Actions workflow runs | X | X | X | X | X
Edit wikis | X | X | X | X | X
Report abusive or spammy content | X | X | X | X | X
Apply labels |   | X | X | X | X
Close, reopen, and assign all issues and pull requests |   | X | X | X | X
Apply milestones |   | X | X | X | X
Mark duplicate issues and pull requests |   | X | X | X | X
Request pull request reviews |   | X | X | X | X
Push to (write) the person or team's assigned repositories |   |   | X

**Comment by szymonmichalik** [comment]
So we have a bug here. At least within our organization. I will contact the Support team on this. Thanks!
