### ISSUE TITLE
pug is recognized as HTML

### ISSUE THREAD

**Issue by Shinigami92** [isaacs/github#1734]
![image](https://user-images.githubusercontent.com/7195563/74678667-f470f880-51bb-11ea-8039-4fcaf2006e00.png)

https://github.com/prettier/plugin-pug

I don't think I have a single HTML file in my project ^^

**Comment by erkinalp** [comment]
File a bug on linguist.
@isaacs close this

**Comment by Shinigami92** [comment]
This one? https://github.com/github/linguist

**Comment by Shinigami92** [comment]
https://github.com/github/linguist/issues/4506
https://github.com/github/linguist/issues/4291#issuecomment-428197378
