### ISSUE TITLE
Why the number of git clones is bigger than the number of visitors on git traffic?

### ISSUE THREAD

**Issue by harlanc** [isaacs/github#1744]
![image](https://user-images.githubusercontent.com/10411078/75495418-7271a280-59f9-11ea-9595-67615837cdb1.png)

It's strange...

**Comment by MichaelDimmitt** [comment]
‾\_(ツ)_/‾

**Comment by Asgavar** [comment]
Well, you don't necessarily have to visit the web UI in order to clone a repo, you can guess the URI/get it from somewhere else as well

**Comment by harlanc** [comment]
thanks
