### ISSUE TITLE
Avatar's quality is too low on explore page

### ISSUE THREAD

**Issue by yohix** [isaacs/github#1747]
**Avatar's quality is too low on explore page**

https://github.com/explore

![Screenshot](https://user-images.githubusercontent.com/61746440/75875715-3c3d8400-5e3a-11ea-9d92-dc77fa87bfb4.png)

**Comment by ohitsmekatie** [comment]
👋 @yohix, thanks for the feedback! 

We just deployed a fix for this. I just checked it out on /explore and everything looks good to me, but can you give it a look when you have a free minute? If everything looks good to you 🙏 go ahead and close this out.

Thanks again!

**Comment by yohix** [comment]
:heart: Thanks @ohitsmekatie! It is fixed now :clap:
