### ISSUE TITLE
Squash merge is changing authorship of code

### ISSUE THREAD

**Issue by cristiadu** [isaacs/github#1750]
Hi, It seems this issue started today (04 Feb 2020), but now every time a Pull-request gets merged with the SQUASH approach all the changes have their "author" changed to whoever merged the given Pull-request.

Before the behavior was to show "authored" and "commited" as two separate things, which was better as the company I work for relies on automerging of Pull-requests, and we are ending up on situations where the commit is going to have as an author the automation user, which is not ideal.

Did anything changed on Github? I wasn't able to find anything else but this: https://github.com/chdsbd/kodiak/issues/300

Which seems to correlate with what I just described.

**Comment by davidsiu** [comment]
Yup, happening to us as well. Luckily it is I who is getting the credit for everyone's work. ;-P

Please Github fix this!

**Comment by gharlan** [comment]
It is an intentional change :(
https://github.community/t5/How-to-use-Git-and-GitHub/Authorship-of-merge-commits-made-by-Github-Apps-changed/m-p/48924/highlight/true#M10707

**Comment by Conduitry** [comment]
Well that's fairly disheartening. I get that it's hard to find The Right Answer when a PR can contain commits by any number of people, be opened by a different person, and merged by yet another different person. But I don't think that means you then go for The Consistent Answer that's wrong even more of the time.

**Comment by cristiadu** [comment]
They seem to be reverting it: https://github.community/t5/How-to-use-Git-and-GitHub/Authorship-of-merge-commits-made-by-Github-Apps-changed/m-p/48960#M10715

**Comment by cristiadu** [comment]
Closing this as it was reverted
