### ISSUE TITLE
Commits history overflowing on small screens

### ISSUE THREAD

**Issue by aguingand** [isaacs/github#1752]
This bug appeared in a recent version of this page where the timeline line/dot where added in XS viewports

![B1A5C76A-0D5C-45F6-9566-36ED7FF2CDD8](https://user-images.githubusercontent.com/17453506/76197596-be3bfd00-61ec-11ea-8815-f8e00066f7e9.png)

**Comment by kevinsawicki** [comment]
@aguingand This issue should be fixed now, can you please confirm?

**Comment by aguingand** [comment]
Yes it's fixed, I close
