### ISSUE TITLE
getting error:504 suddenly

### ISSUE THREAD

**Issue by kgu-a10** [isaacs/github#1770]
kgu@dev64-build34:~/sandbox/gaacos/devops_cm$ git pull
fatal: unable to access 'https://github.com/a10networks/devops_cm.git/': The requested URL returned error: 504

Is this related to my local repo or github cloud repo?

**Comment by crfrolik** [comment]
https://www.githubstatus.com/incidents/80d0cs6kpsps

This repo is probably not the right place to report outage problems.
