### ISSUE TITLE
highlight a line or a block of lines in markdown

### ISSUE THREAD

**Issue by oprogramador** [isaacs/github#1771]
With a JavaScript file, I can use such a link https://github.com/oprogramador/joi-us-zipcode/blob/master/src/tests/index.js#L42 which highlights a line or such a link https://github.com/oprogramador/joi-us-zipcode/blob/master/src/tests/index.js#L43-L54 which highlights a block of several lines.

I'd like to be able to highlight e.g. this:
<img width="1077" alt="Screenshot 2020-04-10 at 12 29 12" src="https://user-images.githubusercontent.com/8701039/78984640-0d948680-7b27-11ea-9b82-8637f225f0f0.png">
in a similar way but it seems that I cannot.

**Comment by cirosantilli** [comment]
Possible prerequisite: https://github.com/isaacs/github/issues/297

**Comment by oprogramador** [comment]
@cirosantilli 

thanks, IMO #297 should fulfill the need for highlighting markdown so I close this issue
