### ISSUE TITLE
New "owner / repo" html prevents from correct copying

### ISSUE THREAD

**Issue by bl00mber** [isaacs/github#1772]
When you copy owner / repo, previously you were able to just copy and paste it. Now you get the string with newline breaks.

![Peek 2020-04-11](https://user-images.githubusercontent.com/16987322/79036627-983abb80-7be3-11ea-8b96-c1677a8c13f1.gif)

**Comment by cirosantilli** [comment]
https://github.com/isaacs/github/issues/1765
