### ISSUE TITLE
Copying repository names in the "Danger Zone"

### ISSUE THREAD

**Issue by ravenclaw900** [isaacs/github#1775]
I don't think that we should be able to just copy the repository name to make sensitive actions to our repos.  If `user-select: none;` was just added to the CSS to style that, some people would actually think about deleting, making private, etc. their repositories.

**Comment by matthijskooijman** [comment]
IMHO, if you want to save trouble and/or "bypass" this safety feature by copying, that's your own choice. I believe this feature exists to prevent accidentally clicking too fast and forcing people to at least doublecheck *which* repo they are deleting. I would not consider it GH's job to prevent people from copying the repo name (in fact, preventing that might be problematic, when you need to delete a few dozen of repos or so, you're probably glad that you *can* copy the name...).

**Comment by ravenclaw900** [comment]
That's a good point.  I might close this issue soon anyway, as I haven't gotten a response from GitHub.
