### ISSUE TITLE
Github Dark Theme

### ISSUE THREAD

**Issue by neev123** [isaacs/github#1793]
I can recommend this theme if you are a 24x7 worker
https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp/reviews?h1=en

**Comment by hoshihz** [comment]
Dupe of #66

**Comment by neev123** [comment]
what do you mean

**Comment by Rexogamer** [comment]
He means that this issue is the sam as #66 (ie the same feature request)

**Comment by TheTechRobo** [comment]
@Rexogamer @hoshihz uhm but its not a feature request, it's a suggestion, saying if you want GitHub Dark Theme try this extension, it didnt ASK for the dark theme

**Comment by Rexogamer** [comment]
1. This repo is specifically focused on feature requests.
2. That thread contains a lot of suggestions for extensions that will add dark mode for you so he should’ve just posted it there.
3. This thread is named poorly (_almost like it’s a suggestion_).

**Comment by TheTechRobo** [comment]
@Rexogamer Good points, I never thought about it that way.
