### ISSUE TITLE
Github search does not find "flask-compress" repo

### ISSUE THREAD

**Issue by tscheburaschka** [isaacs/github#1794]
I am trying to find the sources for the Python package "flask-compress".
First, I was using the search bar on github.com to search for "flask-compress". That returned a list of 13 repositories, none of which seemed the actual repo for the package I was looking for.
So I turned to pypi.org to search for the package and there it tells me the sources are here: https://github.com/colour-science/flask-compress
And indeed, this repository is well alive and the one I was looking for.

ISSUE: Why is the repo https://github.com/colour-science/flask-compress not in the list of search results when I search for "flask-compress" in the search bar on github.com?

Btw, when searching with google for "flask-compress", the first hit is the package entry on pypi.org and the second entry is the github-repo I was looking for.

**Comment by TPS** [comment]
A specific example for #908.  Perhaps chime in there?
