### ISSUE TITLE
Search is incomplete, turns up zero results for some tokens and missing results for others

### ISSUE THREAD

**Issue by silverbacknet** [isaacs/github#1864]
I've seen for a while that online github search didn't always match offline results, but here's confirmation: Search for the token `listdir_windows_no_opendir` in python/cpython turns up zero results: https://github.com/python/cpython/search?q=_listdir_windows_no_opendir

But the token is defined right there at https://github.com/python/cpython/blob/master/Modules/posixmodule.c#L3771 and it's used twice more in the same file.

Likewise, searches for any other tokens that appear in the file mysteriously skip over it. Other files in the same folder don't seem affected.

**Comment by TPS** [comment]
@silverbacknet Isn't this issue just instances of #908?  I'm leaning toward closing this in favor of that.

**Comment by silverbacknet** [comment]
I might not have found that because it's a bit more vulgar. 😅 You're right.

**Comment by TPS** [comment]
https://github.blog/changelog/2020-12-17-changes-to-code-search-indexing/ was announced that same day.  Maybe _this_ is _that_?

**Comment by silverbacknet** [comment]
> https://github.blog/changelog/2020-12-17-changes-to-code-search-indexing/ was announced ~that same day~ Dec 17 2020. Maybe _this_ is _that_?

I think that's more for global searches, and cpython/python gets near-daily commits anyway. It would be really bad if search within repository for older ones was just eliminated entirely, but I presume that's not what they mean.
