### ISSUE TITLE
GitHub syntax checker displaying the incorrect syntax for files? 

### ISSUE THREAD

**Issue by sancarn** [isaacs/github#1868]
I've got a [repository](https://github.com/sancarn/stdVBA/search?l=tex) which is currently displaying TeX files. The files are clearly Visual Basic 6 class files (headers, vb attributes etc.). Understand that VB6 isn't strictly supported, but I'd like them to be highlighted with VBA/VB.NET at least.

Does github use a syntax checker library which we can fix to ensure our files are displayed in the correct syntax highlighter?

Alternatively is there a file where we can specify what syntax highlighter to use for the repository for different types of files?

**Comment by TPS** [comment]
Per https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks, you're probably looking to file a note @ https://github.com/github/linguist/pull/4725 &/or https://github.com/github/linguist/issues/2418

**Comment by sancarn** [comment]
@TPS It isn't about VBA vs VisualBasic. It's VBA vs TeX.
