### ISSUE TITLE
A secret gist can be access from everyone

### ISSUE THREAD

**Issue by dan0705** [isaacs/github#1873]
I have a gist on [https://gist.github.com/](https://gist.github.com) it is secret but everyone can still access it and read the content.

For example, a gist which created by VSCode Setting Sync extension. It is secret but everyone can see.
I wonder whether this is a bug.
Thanks for supporting!

**Comment by cbrt64** [comment]
That's normal behavior. "Secret" just means others can't search for it, but you can still share the link, which could of course possibly be "leaked". From https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-gists:

> Secret gists aren't private. If you send the URL of a secret gist to a friend, they'll be able to see it. However, if someone you don't know discovers the URL, they'll also be able to see your gist. If you need to keep your code away from prying eyes, you may want to create a private repository instead.

FWIW, https://gist.github.com/dan0705 only shows me the one keybase gist, whether I'm signed in or not.

**Comment by dan0705** [comment]
Thank for your answer!
