### ISSUE TITLE
75 GB .gitignore file

### ISSUE THREAD

**Issue by akash-258** [isaacs/github#1883]
I just looked and my home directory was almost filled 80% even though the installation was new and I didn’t download anything. So I checked using disk usage and found a “.gitignore” file which was 75Gb.
After I deleted the file everything was normal again.
Now I don’t know whom to report this issue.

Before deletion : https://ibb.co/QbLHQVv
After deletion : https://ibb.co/xLc09ZJ

**Comment by cirosantilli** [comment]
Is this linked to GitHub? If not, better ask somewhere else. It will be hard to get any help without determining how that file got created somehow.

**Comment by akash-258** [comment]
@cirosantilli Thanks, will look into that, but I guess we can only monitor present events, not past.
