### ISSUE TITLE
checkout after partial clone with `git clone --depth 1 --filter=blob:none --no-checkout` is extremelly slow when there are many files

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#1888]
Instantaneous (10k files small files):

```
git clone https://github.com/cirosantilli/test-github-many-issue-templates
```

Takes forever, seems to fetch one file at a time:

```
git clone   --depth 1   --filter=blob:none   --no-checkout   https://github.com/cirosantilli/test-github-many-issue-templates
cd test-github-many-issue-templates
git checkout master -- .github/ISSUE_TEMPLATE
```

because you can see in the stdout files coming out one at a time every 0.5s:

```
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 67 bytes | 67.00 KiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 67 bytes | 67.00 KiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 68 bytes | 68.00 KiB/s, done.
remote: Enumerating objects: 1, done.
```

This makes partial clones unusable for most cases, even 100 files would be almost unbearable.

Tested with git version 2.27.0.

Context: https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/52269934#52269934

cc. @derrickstolee due to recent related blog post: https://github.blog/author/dstolee/ I have only read the blog very in passing, sorry if already addressed.

**Comment by derrickstolee** [comment]
You should drop the `--depth 1` from your clone. That makes the clone be shallow, in addition to the partial clone.

**Comment by cirosantilli** [comment]
Thanks for the reply. I updated to 2.30, and removed `--depth 1` (are shallow and --filter blob incompatible somehow, in theory I'd guess no), and I still reproduce.

**Comment by derrickstolee** [comment]
I'm not sure what else you are doing, because this is what I get:

```ShellSession
/c/_git/t
$ git clone --filter=blob:none --no-checkout https://github.com/cirosantilli/test-github-many-issue-templates
Cloning into 'test-github-many-issue-templates'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), 233.91 KiB | 25.99 MiB/s, done.

/c/_git/t
$ cd test-github-many-issue-templates/

/c/_git/t/test-github-many-issue-templates (master)
$ git checkout origin/master
remote: Enumerating objects: 10001, done.
remote: Counting objects: 100% (10001/10001), done.
Receiving objects:  99% (9901/10001)d 10001 (delta 0), pack-reused 0
Receiving objects: 100% (10001/10001), 370.16 KiB | 13.71 MiB/s, done.
Updating files: 100% (10001/10001), done.
```

**Comment by cirosantilli** [comment]
Note that my checkout command has `-- .github/ISSUE_TEMPLATE`.

The goal is to be able to checkout only a single directory efficiently without fetching the rest of the repo (In this repo it does not matter because all files are in that directory.)

Without that extra part, the problem does not happen, but I'd be forced to fetch all blobs I believe.

**Comment by derrickstolee** [comment]
Ah. Likely there is a batch download thing that needs to be done to assist with these pathspec-scoped checkouts.

You probably actually want to use sparse-checkout.

```ShellSession
/c/_git/t
$ git clone --filter=blob:none --sparse https://github.com/cirosantilli/test-github-many-issue-templates
Cloning into 'test-github-many-issue-templates'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0R
Receiving objects: 100% (4/4), 233.91 KiB | 58.48 MiB/s, done.

/c/_git/t
$ cd test-github-many-issue-templates/

/c/_git/t/test-github-many-issue-templates (master|SPARSE)
$ git sparse-checkout init --cone

/c/_git/t/test-github-many-issue-templates (master|SPARSE)
$ git sparse-checkout set .github
remote: Enumerating objects: 10001, done.
remote: Counting objects: 100% (10001/10001), done.
Receiving objects: 100% (10001/10
Receiving objects: 100% (10001/10001), 370.16 KiB | 16.09 MiB/s, done.
Updating files: 100% (10001/10001), done.

/c/_git/t/test-github-many-issue-templates (master|SPARSE)
$ ls -al
total 20
drwxr-xr-x 1 NORTHAMERICA+dstolee 4096 0 Jan 14 15:34 ./
drwxr-xr-x 1 NORTHAMERICA+dstolee 4096 0 Jan 14 15:34 ../
drwxr-xr-x 1 NORTHAMERICA+dstolee 4096 0 Jan 14 15:34 .git/
drwxr-xr-x 1 NORTHAMERICA+dstolee 4096 0 Jan 14 15:34 .github/

/c/_git/t/test-github-many-issue-templates (master|SPARSE)
$ ls .github/
ISSUE_TEMPLATE/
```

We might update the `--sparse` option in `git clone` to automatically enable "cone mode", but for now that `git sparse-checkout init --cone` is necessary (or equivalently in this situation `git config core.sparseCheckoutCone true`).

It is better to use sparse-checkout than to have an "empty commit" that pulls a directory from another "real" commit.

**Comment by cirosantilli** [comment]
OK, with your commands it works!

I wish my commands would work, I feel they are more intuitive, sparse checkout seems to add even more state to git, which does not feel intuitively needed given that I'm already saying `--filter` on the clone :-)

One day I might stop to understand what's actually going on.

**Comment by derrickstolee** [comment]
> OK, with your commands it works!

I'm glad that works.
 
> I wish my commands would work, I feel they are more intuitive, sparse checkout seems to add even more state to git, which does not feel intuitively needed given that I'm already saying `--filter` on the clone :-)

Any time you try to modify a working directory in a "not checked out" state (like `git clone --no-checkout` specifies) you are going to have issues when pulling data from other commits. You're putting Git in a state it does not expect to be in.

You were creative to use pathspec-scoped checkout to ask for the paths you care about, but you're essentially assembling the state that sparse-checkout provides for you. That "extra state" allows Git to do things like batch object requests in a partial clone in a sane way.

Sparse-checkout and partial clone are actively being developed to work more closely together, so you're more likely to have success in that direction.
