### ISSUE TITLE
Results of search for filenames are broken

### ISSUE THREAD

**Issue by doublep** [isaacs/github#1896]
Example: https://github.com/search?q=filename%3AEldev+language%3A%22Emacs+Lisp%22+path%3A%2F

I used to use this query to estimate how often my build tool is used by searching for file named `Eldev` in repository roots. It used to give good results, but now results are certainly incorrect. There are tens of files that should match ([1](https://github.com/bbatsov/projectile/blob/master/Eldev), [2](https://github.com/clojure-emacs/cider/blob/master/Eldev), [3](https://github.com/doublep/logview/blob/master/Eldev)...), but they are not listed in the results.

This used to work at least most of 2020, probably became broken at some point between October 2020 and January 2021.

**Comment by Nixinova** [comment]
Yeah it would be good to have an option for an exact match for filenames in search.

**Comment by doublep** [comment]
While a good idea, it's not even that. It simply doesn't work correctly at the moment.

**Comment by Nixinova** [comment]
Would it be because they're not classified as Emacs?

**Comment by doublep** [comment]
Gah, you are right. Interesting that it used to work before.
