### ISSUE TITLE
Issues list: Show all issues that *lack* a tag/milestone/assignee

### ISSUE THREAD

**Issue by isaacs** [isaacs/github#19]
It'd be nice to be able to view all the issues that *don't* have an assignee, label, or milestone, so that a project maintainer can more easily triage new issues, without having to sift through those that have already been categorized.

**Comment by TPS** [comment]
@cirosantilli I think this should be closed (implemented) or equivalent.

**Comment by cirosantilli** [comment]
Closing as implemented based on other people's comments, I haven't checked myself.

**Comment by StoneCypher** [comment]
@cirosantilli - this is not actually implemented.

the community comment shows how to search on something that is missing a specific label.

this does not allow you to do what the base request is asking for, which is to show things that don't have a milestone at all.

the notation `-milestone` does nothing

please re-open

**Comment by StoneCypher** [comment]
also please remove the `implemented` flag

**Comment by TPS** [comment]
@StoneCypher This _is_ implemented; 1 just has to know the [syntax](https://help.github.com/articles/searching-issues/#search-by-missing-metadata-on-an-issue-or-pull-request):
>## Search by missing metadata on an issue or pull request
>
>You can scope issues and pull requests to those missing certain metadata using the no qualifier. That metadata includes:
>
>- Labels
>- Milestones
>- Assignees
>- Projects
>
>#### priority no:label
> Matches issues and pull requests with the word "priority" that also don't have any labels.
>#### sprint no:milestone type:issue
> Matches issues not associated with a milestone containing the word sprint.
>#### important no:assignee language:java type:issue
> Matches issues not associated with an assignee, containing the word "important," and in Java repositories.
>#### build no:project
> Matches issues not associated with a project board, containing the word "build."

Clear enough, @StoneCypher?

**Comment by StoneCypher** [comment]
@TPS - sure is, thanks
