### ISSUE TITLE
'Load more' button in Pull Request page not working with error code 400

### ISSUE THREAD

**Issue by inbaeyoon7** [isaacs/github#1900]
'Load more' button in pull request page is not working with error code 400.
I tried several times but it still occur.
 
![Screen Shot 2021-01-28 at 11 21 23 AM](https://user-images.githubusercontent.com/62872665/106080781-18261800-615b-11eb-9623-8c2622f359f2.png)

**Comment by majakusber** [comment]
Getting this as well, can't see my PR comments because of it...

**Comment by inbaeyoon7** [comment]
@majakusber It fixed🙌🏻 🙌🏻 🙌🏻  I try just before and it works!

**Comment by majakusber** [comment]
@inbaeyoon7 I just tried on my PR too and it works again. Thanks :+1:
