### ISSUE TITLE
Should we use Github's official feedback repo?

### ISSUE THREAD

**Issue by markcellus** [isaacs/github#1955]
Hey @isaacs! Really love this repo and the feedback and conversations have been awesome. But now that we have https://github.com/github/feedback/discussions, does it make sense to retire this repository?

**Comment by TPS** [comment]
@markcellus [This has been answered @ the canonical issue.](https://github.com/isaacs/github/issues/6#issuecomment-787084645) In short, you missed the description of that repo: "Public feedback discussions for: GitHub Mobile, GitHub Discussions, GitHub Codespaces and GitHub Sponsors" _(only)._

**Comment by markcellus** [comment]
Who is this @TPS person and why can I not  add a confused reaction to the comment left here?

**Comment by TPS** [comment]
@markcellus 
I'm a collaborator on this repo (so, essentially, a volunteer moderator).

As for your reaction, I was able to add <kbd>😕</kbd> to your comment.  If you can't add such to comments, maybe try https://support.github.com/?

**Comment by TPS** [comment]
@markcellus You're getting your wish: Per #1967 & #1985, this is _exactly_ what's happening.  But leaving this issue closed duplicate, in favor of those. 🙇🏾‍♂️
