### ISSUE TITLE
Heads up! Changes to this repository coming soon...

### ISSUE THREAD

**Issue by isaacs** [isaacs/github#1967]
In the time since this repository was created, GitHub has changed, a lot.  The perception of GitHub's attitude back when this repository was created was one of "We know best, do it the GitHub way, if it doesn't work for you, you're doing it wrong."  (This was likely not a principled choice by GitHub, but they were a new startup with way too much to do, and managing feedback is hard.)

Since then, GitHub has grown, going through multiple metamorphoses, most notably in their approach to feedback.  They even hired me, one of their most annoying users, who never shuts up and even created a repo just to track all his annoying complaints :)  It's quite fun playing the resident "grumpy lazy OSS dev" in product meetings these days.

When I started at GitHub last year, I was inundated with emails from threads in internal GitHub repos mentioning issues on this tracker.  JS devs at the company may know me as "isaacs from npm", but quite a few hubbers have greeted me as "wait, you're _the_ isaacs?? from the feedback repo!?"  Which is kind of weird, since I haven't been very active here in a long time.  The main things that got me started with this (issues being broken and useless on active projects, no project management, no way to lock issues that get out of control, PRs without any way to do code reviews or provide feedback, completely opaque CI integrations, the list went on) all got fixed, and I sort of moved on.

Suffice to say, the attitude towards feedback _has_ changed significantly in the last decade, and now the challenge is how to make the most of it, and efficiently get things done and know what will have the biggest impact on our userbase.

I don't know exactly what that will look like, but @michellemerrill is going to take inventory of the items here, and the other myriad ways that we send feedback to GitHub, make a plan, and share it with us.

This repo has value, and no one wants to lose the value it provides.  That said, one of my earliest complaints (and part of the reason for creating this channel!) was that feedback to GitHub tends to be fragmented, and so it's hard to know what pieces of feedback are being accepted, what are rejected, etc.  From the other side, trying to _make_ informed product decisions, that fragmentation can be even more challenging.  Right now, this repo being external is somewhat contributing to that problem.  So I can only imagine that incorporating these things into a coherent story will improve things for GitHub development teams and all GitHub users.

I'll keep this issue open for bit for anyone who wants to weigh in on it, but thought it was best to just let y'all know that this forum will grow into something newer and better fairly soon, so you're not shocked when it starts happening.

I'm extremely grateful to all the users who participated here in good faith, and helped moderate and organize these issues, and I hope that this machine can keep running even better, with more impact to guide GitHub towards doing the right thing for their users.  I know that the product teams at GitHub have benefitted, and appreciate it as well.

**Comment by Levi-Lesches** [comment]
It's a simple mechanic, but I've seen a couple of repos that simply have a giant project with columns: 
- triage
- discussing
- formalizing 
- ready to work on, 
- in development
- done.

This way ideas can go from vague requests to complete features, and GitHub staff can start working on features that are in the "ready to work on" column and move them to the "in development" column so we can all see their status. Hope that's helpful.

**Comment by AraHaan** [comment]
I would love it if this repository gets moved to @github as opposed to being owned by @isaacs so that way all the github staffs can moderate it better (and so they get nag emails every time someone posts a new issue / posts so they know what are the high traffic issues / things that needs fixed or done ASAP).

**Comment by erkinalp** [comment]
@AraHaan But https://github.com/github/github is *the* repository that stores the GitHub source code itself. How would you have public issues in a private repository?

**Comment by AraHaan** [comment]
> @AraHaan But https://github.com/github/github is _the_ repository that stores the GitHub source code itself. How would you have public issues in a private repository?

I think github would not be dumb enough to store github source codes on github in case github goes down. I would hope they would be hosting it on an internal git only server like a gitlab clone for example.

Even if they did they probably have it at https://github.com/github/github.com

**Comment by Rexogamer** [comment]
I'm pretty certain github/github *is* a real (albeit private) repo, so if this was going to move to their org it would probably be renamed to something like github/feedback

**Comment by isaacs** [comment]
I can confirm that GitHub does indeed already use this repo as a source of info, and things get moved through a very large number of project boards for various teams, with links to issues in this repo all over the place.  I get pinged on a lot of them, which is weird, since I usually had nothing to do with the issue being created or the work being done, but whatever, after 2 decades in OSS, my inbox is a tire fire anyway :joy:

I don't want to speculate on where this repo is going to move, or what'll happen to it.  But it'll be out of my hair once and for all, and keep helping GitHub improve and respond to feedback better, and that's the important thing ;)  Given the initial goals of creating this repo in the first place, I'd say it's been a much bigger success than I could have hoped at the time.

**Comment by TPS** [comment]
@isaacs Considering you may have never imagined the influence you'd eventually have with `npm`, _this_ repo has had _@ least_ as much effect on the GitHub ecosystem.  All that to say, _thank you_ for not quenching that tire fire the many times (I'm sure) you were tempted to, which allows the many of us to have a voice when we felt unheard & frustrated.

**Comment by isaacs** [comment]
@TPS thank you, that comment made my day 🥇

**Comment by TPS** [comment]
@isaacs You helped make our GitHub experience for _years_.  You certainly deserve all the appreciation we can give.

**Comment by TPS** [comment]
@All I'd also like to give a shoutout to my fellow collaborators & all the issue authors.  Altogether, we're helping influence GitHub to a direction where we all benefit.

**Comment by fluteds** [comment]
> I don't want to speculate on where this repo is going to move, or what'll happen to it. But it'll be out of my hair once and for all, and keep helping GitHub improve and respond to feedback better, and that's the important thing ;) Given the initial goals of creating this repo in the first place, I'd say it's been a much bigger success than I could have hoped at the time.

Even if the repo gets transferred, the original/new repo can always be live cloned, whatever happens here, happens there. 
Thank you for creating this repo. I'm looking forward to seeing it grow and picked up by GitHub staff, including yourself!
I always love going through this and mentally seeing what could work in the future.

If this repo needs maintaining during the transition or in general I'm more than happy to help you and @TPS out.

**Comment by TPS** [comment]
It occurs to me that, assuming this becomes an _official _ repo of some sort, GitHub might _not_ want non-staff moderators _(essentially what the collaborators here **are**, I think)_.  We'll await developments on these details, also.

**Comment by TPS** [comment]
Major official announcement @ https://github.com/isaacs/github/issues/1985!  Please chime in there!

**Comment by isaacs** [comment]
Update: https://github.com/isaacs/github/issues/2035#issuecomment-972974259
