### ISSUE TITLE
Resolve merge conflicts through the web interface.

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#200]
If GitHub wants to be usable by non-programmers, this is a must.

I want this to help non-programmers to write books on GitHub as in https://github.com/booktree/booktree

Seems possible with the GitHub client: https://help.github.com/articles/resolving-merge-conflicts , but this should be doable from the web UI: requiring people to download things is a huge turn off.

Possible implementation: a per file ours / theirs / actual view like Penflip does:

![sync cirosantilli1 version penflip](https://cloud.githubusercontent.com/assets/1429315/3128629/1f0d8af4-e7d7-11e3-973d-f9892d9ff252.png)

GitLab accepting pull requests: http://feedback.gitlab.com/forums/176466-general/suggestions/5590496-resolve-any-merge-request-conflict-from-the-web-in

I'm considering a Javascript interface that interacts through the API to do that. Does such thing exist already?

**Comment by erkinalp** [comment]
:truck:

**Comment by gbinal** [comment]
Just throwing out a +1 on this.  It would go a ways in my efforts to get newbies using GitHub.

**Comment by cirosantilli** [comment]
@gbinal exactly why I attempted this on the first place: https://github.com/booktree/booktree What is your use case? If you have a lot to say about it, let's move to: https://github.com/cirosantilli/chat/issues

**Comment by lostsnow** [comment]
+1

**Comment by TPS** [comment]
Perhaps something like [Wikipedia's interface for edit conflicts](https://en.m.wikipedia.org/wiki/H:EC) would be useful as a beginning point for the basic merge-conflict interface.

**Comment by gregjd** [comment]
This would be an enormously helpful feature to have. It would go a long way to making GitHub friendlier to people who are just starting to use it.

**Comment by cirosantilli** [comment]
Done!!! https://github.com/blog/2293-resolve-simple-merge-conflicts-on-github

**Comment by pegasusearl** [comment]
uhm excuse me, I can't see the button.
take a look http://imgur.com/a/xnCLJ

**Comment by akostadinov** [comment]
wow, saves a lot of effort for simple conflicts

FYI everybody, you can add more than one  reaction - e.g. I added +1 to all - hearth, thumb up, smile and hooray emojis at the same time.

**Comment by probonopd** [comment]
Not really... button is not showing up. https://github.com/isaacs/github/issues/200
