### ISSUE TITLE
Support office file preview and online edit with office online

### ISSUE THREAD

**Issue by oxygen-dioxide** [isaacs/github#2009]
When opening an office file (docx, xlsx or pptx), we can't preview this file. We can only download it and open it locally.

![image](https://user-images.githubusercontent.com/54425948/124421893-f88fbd00-dd94-11eb-9800-d700ba9a670b.png)

I hope that when opening an office file, an office online page can show up and provide a preview of this file. If in my own repo, I can edit it online.

---
Microsoft owns both [office online](https://www.office.com/) and [github](github.com), so they should integrate better, like google drive and google colab.

**Comment by oxygen-dioxide** [comment]
https://github.com/github/feedback/discussions/4768

**Comment by michellemerrill** [comment]
Closing this issue in favor of tracking it here: github/feedback#4768
