### ISSUE TITLE
Sort user and organization repositories by star count on the repositories tab and org home page

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#201]
I want to sort repositories by star count on URLs:
- `/<username>?tab=repositories`
- `/<organization-name>`

The user case is a bit less serious as I can see the top 5 under "Popular repositories" at URL `/<username>`, but what if he has more interesting repositories?

For orgs, when I see they have 9 pages of repositories I just err... give up, or wish I had the patience to write or look for an API solution =(

As a workaround, search can do it:
- https://github.com/search?q=user%3Agitlabhq+&s=stars&type=Repositories
- https://github.com/search?q=user%3Acirosantilli+&s=stars&type=Repositories

but it requires too much brainpower / clicks.

---

Robert Sese replied:

Thanks very much for the feedback - I believe the current sort for repositories is most recently updated, but I can see how sorting by stars (in addition to other repository metadata) could be useful.  We'll go ahead and add this to our feature request list for the team to consider.

**Comment by cirosantilli** [comment]
As a workaround, search can do it:

- https://github.com/search?q=user%3Agitlabhq+&s=stars&type=Repositories
- https://github.com/search?q=user%3Acirosantilli+&s=stars&type=Repositories

**Comment by gbrlsepulveda** [comment]
+1

**Comment by softwaredoug** [comment]
:+1:

**Comment by Maximilianos** [comment]
+1

**Comment by Yiabiten** [comment]
+1

**Comment by brennanhm** [comment]
+1 !

**Comment by ChannelJuanNews** [comment]
+100000000

**Comment by stephen-cernota** [comment]
:+1:

**Comment by tberghuis** [comment]
+1

**Comment by AndreiMaz** [comment]
+1

**Comment by The-Penultimate-Defenestrator** [comment]
please.

**Comment by EverLoSa** [comment]
+1

**Comment by NSDeveloper** [comment]
+1 Very useful when having lots of repositories. Hope github can add this feature.

**Comment by bauen1** [comment]
+1 As said above, very useful when you have lots of repositories especially if you have ones that are less interesting and you don't want the visitors attention drive away by them

**Comment by The-Penultimate-Defenestrator** [comment]
[Here](https://gist.github.com/The-Penultimate-Defenestrator/bfbe6a75c43aae827f76a7abbf6e2570) is a Python gist that will print out an organization's repos sorted by star count. Doesn't support user repos, since you can see the most popular repos on a user's front profile. 

It's written in Python, using [`requests`](http://docs.python-requests.org/en/master/). 

To use this you have to replace `USERNAME` and `PASSWORD` with your GitHub credentials. That's in place to avoid rate limit issues. Make sure you have [`requests`](http://docs.python-requests.org/en/master/) installed, then run with Python.

**Comment by lbmn** [comment]
+1

**Comment by flaviomicheletti** [comment]
+1

**Comment by lbmn** [comment]
+1

**Comment by controversial** [comment]
Ok, there's a way to do this natively, actually. You can perform a search and sort that by star count. Example: if you search for `org:mozilla` and sort by star count, you get all the repos sorted by stars.

**Comment by pretodor** [comment]
@controversial the workaround you provided is included in OP's [post](https://github.com/isaacs/github/issues/201#issue-34790996):

> As a workaround, search can do it:
> - https://github.com/search?q=user%3Agitlabhq+&s=stars&type=Repositories
> - https://github.com/search?q=user%3Acirosantilli+&s=stars&type=Repositories

Note, however, by using only the `user:` flag (`user:` can be used for both users and organisations) the user's forked repositories won't show up. If you would like to see them too, you'll have to add the `fork:true` flag.

**Comment by controversial** [comment]
Ah, thanks.

**Comment by appsparkler** [comment]
This is what worked for me:

In the `search bar`, we can enter the usual search criteria.  For ex `stars:>20` - This will no only give us a list of repos that have more than 20 stars but will also sort them in descending order.

![image](https://user-images.githubusercontent.com/12084821/30011818-77ec8b7e-9158-11e7-9a24-ccd8c85920ba.png)


Good Luck.

**Comment by MasterTuto** [comment]
How can I sort by views?

**Comment by appsparkler** [comment]
Hi @MasterTuto,

The `views` information is not tracked on GitHub.  I am aware of `forks`, `stars` and `watches`.  

Thanks

**Comment by walidstark** [comment]
+1

**Comment by milesfrain** [comment]
@appsparkler 

`stars:>20` is good for filtering, but it's not consistently sorting.

![image](https://user-images.githubusercontent.com/3578681/50234819-be47a700-0373-11e9-8bc1-a3f2bb73fe07.png)

**Comment by appsparkler** [comment]
Hi @milesfrain,

I am seeing them sorted by # of stars :

![image](https://user-images.githubusercontent.com/12084821/50534330-29a62b80-0b61-11e9-9e45-8f3e14d341ad.png)

Also, if you want a customized search, you can try the `Github API` and programmatically modify the results:
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwi_opfutMTfAhWIKY8KHVfMDBIQFjAAegQIBBAC&url=https%3A%2F%2Fdeveloper.github.com%2Fv3%2F&usg=AOvVaw0ZLcrC9kHFI9ae0GbyeqbP

Good Luck...

**Comment by milesfrain** [comment]
@appsparkler
This seems to be a github inconsistency in search behavior where sorting by stars only works in global search and not in local user search.
For example, if I go to a [user's repository tab and filter by stars](https://github.com/junegunn?utf8=%E2%9C%93&tab=repositories&q=stars%3A%3E20), the results are not sorted.
But if I [use global search to find a user](https://github.com/search?p=1&q=user%3Ajunegunn), the results are automatically sorted by stars.

**Comment by appsparkler** [comment]
Hi @milesfrain,

Yes, thats right and thats where the `Github API` comes in handy.  I made a small app that works with this API and sorts the repos as per the stars.  This is only a small example, you can do much more with the `data` that is received with the `API`:

`JSFiddle` http://jsfiddle.net/appsparkler/m3dy641s/27/

DEMO: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12084821/51425374-35858a80-1c01-11e9-9421-8628508969f8.gif)

**Comment by dwaltrip** [comment]
It's absolutely dumbfounding that github doesn't have this feature.

**Comment by tim-phillips** [comment]
It does exist! It's called [Advanced Search](https://github.com/search/advanced).

In Advanced Search, enter the user or org name and press enter to search. Then in the top right dropdown menu, you can select "Sort: Most stars".

**Comment by botatoes** [comment]
Hi all, pm @ github here 

We recently shipped this feature. Please see https://github.blog/changelog/2021-04-09-sort-repos-in-user-and-organization-profiles-by-star-count/

**Comment by TPS** [comment]
@botatoes Thanks very much for releasing this also for the mobile _site_.  Any info when such (really, _any_ repo sorting) would be released for the mobile _app_?
