### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by sh1nes-1** [isaacs/github#2011]
Problem: Problem with UI on Issues and Pull requests pages if you open it from repository Actions pages.

Steps to reproduce:
1. Open any of these links:
[https://github.com/sh1nes-1/Java_Labs/runs/303660956](https://github.com/sh1nes-1/Java_Labs/runs/303660956)
[https://github.com/sh1nes-1/Java_Labs/actions/runs/19963118](https://github.com/sh1nes-1/Java_Labs/actions/runs/19963118)

2. Click on Issues or Pull requests section of repository
3. Observe that padding on this page is not correct

Screenshot of this bug:
![image](https://user-images.githubusercontent.com/22298009/125615155-46713fd1-3e60-4dd7-8bfd-9586e9904aa6.png)

**Comment by michellemerrill** [comment]
https://github.com/isaacs/github/issues/2011#issuecomment-879821031 - Closing this issue.
