### ISSUE TITLE
Showing GitLab contribution on the GitHub contribution graph

### ISSUE THREAD

**Issue by himel-biswas** [isaacs/github#2013]
Is it possible if users contributes to private repo hosted on **GitLab.com**, the contribution count will show up on their **Github** contribution graph?

**Comment by reneroth** [comment]
That doesn't make sense, but if you truly felt like this needs to be done on your account, a solution would be to create a private Github repo and have a script running that checks your GitLab contributions, creating dummy interactions with your private Github repo to mirror the activity.

**Comment by Levi-Lesches** [comment]
> if users contributes to private repo hosted on GitLab.com

I don't use GitLab, but I assume they'd have API-level protections for private repositories. Like @reneroth said, it wouldn't make sense for GitLab to allow third parties to access private user data.

**Comment by himel-biswas** [comment]
okay, thank you, i have got the idea. i was just looking if there are any third party API for these kinds of scenario.
