### ISSUE TITLE
Sorting git code repository

### ISSUE THREAD

**Issue by theDreamer911** [isaacs/github#2019]
Recently I was making a repository that track my daily challenge. But I had a problem, that the order is not like I expected like this

![image](https://user-images.githubusercontent.com/71202864/127994959-10936d37-bd66-4341-80e0-4abda4950408.png)

Is anyone know how to make the order in the GitHub repository to be right like this

![image](https://user-images.githubusercontent.com/71202864/127995141-6401dbac-081a-4b4e-956b-84b981d81592.png)

I think there should be some way to sort what file we upload in GitHub, Is anybody know the solution? 

Thanks

**Comment by Levi-Lesches** [comment]
Interesting. Maybe try naming them `day01`, `day02`, etc. so this doesn't happen? Currently, I don't know of any way to change the sort order.

**Comment by theDreamer911** [comment]
Thanks @Levi-Lesches, I just got into day67 of day180, so if I follow your advice, I should change it all manually right?

My assumption is when it come into day101 this will be placed below day10? Is there any better way or how to change dictionary into day001, day002, and so on more automatically

That was a little overwhelming, but again, thank you

**Comment by Levi-Lesches** [comment]
Yeah you're right, when you hit the triple digits, it will mess up every number less than 100. Sorry, I don't know of any way to fix that, unless you consider storing your data some other way. I agree it's a bit confusing, but at least it doesn't impact any automatic data retrieval 🤷‍♂️.

**Comment by theDreamer911** [comment]
Actually your idea is brilliant, perhaps I will do it in the free time and yeah I also can fixing the files name to make it more great

Thanks @Levi-Lesches

**Comment by Levi-Lesches** [comment]
Glad to help! 

If you want this request to make it to GitHub though, be sure to open a discussion at https://github.com/github/feedback

**Comment by michellemerrill** [comment]
Closing per https://github.com/isaacs/github/issues/2019#issuecomment-893650712
