### ISSUE TITLE
Ease of switching between bulleted and numbered lists

### ISSUE THREAD

**Issue by xavier630** [isaacs/github#2020]
**Issue**

When drafting a Github PR or issue, if I highlight a bulleted list and click the `numbered list` button (intending to convert it to a numbered list), it adds the numbers before the bullet symbols (`-`) which results in a broken list with both bullets and symbols (perhaps there's a niche use case where this is desirable).

In my opinion, the button should delete the bullet symbols so that your entire list gets converted rather than broken. This is what Slack does.

**Context**
I often make bulleted lists since they're easier to start, but then swap them to numbered lists since they're easier for others to respond to.

![image](https://user-images.githubusercontent.com/9077250/128022620-16533cbd-0433-48bd-8332-ff4294f7bca1.png)

**Comment by michellemerrill** [comment]
Closing per https://github.com/isaacs/github/issues/2020#issuecomment-891842858
