### ISSUE TITLE
Image as hyperlink doesn't work in GitHub's render of .ipynb file

### ISSUE THREAD

**Issue by martinm07** [isaacs/github#2021]
**Describe the bug**
When using an image as a hyperlink (e.g. `[![alt text](image.jpg)](https://www.example.com)`) in a jupyter notebook, and displaying that notebook in GitHub's online viewer, trying to click on the link (i.e. image) will (instead of bringing you to that hyperlink) just do nothing. Or on Chrome, it also replaces the entire notebook with a gray box saying "This content is blocked. Contact the site owner to fix the issue.".<br>
![Screenshot (4)](https://user-images.githubusercontent.com/87369973/128146949-5f17c7f3-464b-4a59-838b-332b60a6aaa3.png)

**To Reproduce**
Make a .ipynb file that contains the following in a markdown cell:
```
[![alt text](https://via.placeholder.com/150)](https://google.com)
```
Then, upload the file to GitHub in a repository, open the file in GitHub, and try to click on the image.

**Expected behavior**
When clicking on the image hyperlink, it should take you to that link.

**Additional context**
If you right-click on the image and select "Open link in new tab", it works, opening the correct link the new tab.
Also, if you try click on the link but not on the image (the link is bigger than the image), then it also works, bringing you to the correct link.

**Comment by michellemerrill** [comment]
Closing per https://github.com/isaacs/github/issues/2021#issuecomment-892485043
