### ISSUE TITLE
Web UI Deletion

### ISSUE THREAD

**Issue by YSabarad** [isaacs/github#2026]
Hello everyone! Hope I'm doing this correctly, still a bit fresh to GitHub. But basically, I've been using the delete file option via the GitHub website for a repo of mine and thought to point out that we drastically **need a way to delete multiple files at once**. 

**Context:**
I was working within a local repo, as I said, as the CLI just wasn't working and kept telling me about network issues. After a few hours or troubleshooting, I decided to just use the Web interface. I was uploading lots and lots of files, nearly 2 gigs worth. Since GitHub doesn't let you have empty folders AND doesn't let you upload more than 100 files at a time, I was uploading 100 at a time. Then I found out you CAN create folders on the Web interface but you just need to make them house a non-empty file. So I did this, and once all my project data was up, I went back to delete the files I had uploaded without a folder. And these numbered nearly 200.

**Actual Issue:**
It took forever to delete my files one by one. Nearly 2 hours. There has to be an easier way to do this (on the web, I understand it's easier to push/pull and edit the repo locally but as I established that wasn't working).

**Comment by michellemerrill** [comment]
Closing per https://github.com/isaacs/github/issues/2026#issuecomment-902131852
