### ISSUE TITLE
A little UI bug on GitHub

### ISSUE THREAD

**Issue by booleanrecep** [isaacs/github#2031]
I found a inconsistency on GitHub UI and I think it's a bug. On the right panel, clicking on a LANGUAGE that used in the  project, naturally  routes to the files which that clicked language was used. That's normal and expected. But after clicking BROWSERS BACK BUTTON, previous page comes but with inconsistent UI . With the photos it can be seen clearly. In the first photo there is user nickname / project name,  but in the second photo there isn't. But that is totally the same page. Also header a bit under-flowing as seen

### Before
![first.png](https://github.zendesk.com/attachments/token/eY5ZfiDOgKvAqj2bVwXjSuaa9/?name=first.png)

### After
![second.png](https://github.zendesk.com/attachments/token/0lADDnjaH8hyfO6kncSDuqI4X/?name=second.png)

**Comment by michellemerrill** [comment]
Closing per https://github.com/isaacs/github/issues/2035
