### ISSUE TITLE
Issues <--> Discussions

### ISSUE THREAD

**Issue by barkerja** [isaacs/github#22]
A dedicated feature for discussions would be great. `Issues` has the connotation of being directly tied to your codebase (bugs, feature requests/changes, etc.)

My company, being that we are primarily a distributed team, use issues as more of a hodgepodge for everything and it can be quite cumbersome. I know there are tools for this; basecamp, sprint.ly, etc. but having everything under one roof is ideal.

Currently we separate things by milestones and/or labels, but having separation of actual issues and discussions would be spectacular.

**Comment by clarkbw** [comment]
I'm going to call this fixed by the release of team discussions https://github.com/blog/2471-introducing-team-discussions more stuff to come there.
