### ISSUE TITLE
move issues from main project to sub project

### ISSUE THREAD

**Issue by Sajaki** [isaacs/github#227]
In an organisation, the main project is often overcrowded with issues that belong to side projects of that organisation. 
It would be nice to be able to move the issue around in your organisation projects; because now i have to close them with a note.

**Comment by kevinSuttle** [comment]
I'm not nearly as original as I thought. https://github.com/kevinSuttle/github/issues/37

**Comment by gpadak** [comment]
Today GitHub shipped issue transfers as a public beta on GitHub.com https://blog.github.com/changelog/2018-10-30-issue-transfer/. This allows a repository administrator to transfer an issue to another repository where the user also has repository administration privileges.

Check out the Help Docs for more details: https://help.github.com/articles/transferring-an-issue-to-another-repository/.
