### ISSUE TITLE
Show number of forks that actually have changes

### ISSUE THREAD

**Issue by twe4ked** [isaacs/github#24]
Lot of projects have a large number of forks with no changes on them. It would be great to have the number next to the fork button show the number of forks with changes.

**Comment by nealmcb** [comment]
This does seem like a duplicate of #562, which has more discussion as well as a link to the cool-looking "Lovely Forks", a Chrome/Firefox extension.

**Comment by TPS** [comment]
@twe4ked Did you close this in favor of #562, as mentioned above?

**Comment by twe4ked** [comment]
I hasn't had much attention in around 5 years. I was going though old issues of mine and some of them. Feel free to re-open if you feel it's still relevant.

**Comment by TPS** [comment]
@twe4ked #562 will do just fine.
