### ISSUE TITLE
Don't bury my starred repos in 'explore'

### ISSUE THREAD

**Issue by necolas** [isaacs/github#245]
This… https://github.com/stars …is buried in explore -> stars. Would like a link either on the newsfeed page, or any (inc. my own) user profile page – quick access to find my bookmarked repos. Took me forever to find it in explore and it feels unrelated to the rest of that section.

cc @mdo

**Comment by Mottie** [comment]
In case anyone is interested, I created a userscript that allows you to customize the header links

https://greasyfork.org/en/scripts/20830-github-custom-navigation

GitHub
![github-custom-navigation-after](https://cloud.githubusercontent.com/assets/136959/16217335/1aaa6970-3738-11e6-9791-4e1c1f61f8d3.png)

Gist
![github-custom-navigation-gist-after](https://cloud.githubusercontent.com/assets/136959/16217822/bc0b27f6-373c-11e6-861c-33dedd68a0c2.png)

Drag and drop to customize
![github-custom-navigation-usage](https://cloud.githubusercontent.com/assets/136959/16253396/eac0039a-37fb-11e6-8200-5e727915297c.gif)
