### ISSUE TITLE
Allow me to create a default set of labels for my repos

### ISSUE THREAD

**Issue by mehulkar** [isaacs/github#281]
Really want this site wide for my Github Enterprise install, but just for my (or my organizations) repos would be a great start. E.g. `docs` should be a default label IMO. 

**update in 2019**

- closed #371 in favor of this. 

Adding need for

- default set of labels for the user when they create a repo
- default set of labels for an Org
- default set of labels for an entire GHE org. 

You can choose what the fallback order should be, as long as there's a way to force one set over the other when creating a repo.

**Comment by nunorafaelrocha** [comment]
+1

**Comment by andreimarin90** [comment]
+1

**Comment by Frug** [comment]
:+1:

**Comment by cho-is** [comment]
+1

**Comment by erikpmp** [comment]
[Cross-posted from #371](https://github.com/isaacs/github/issues/371#issuecomment-263883297).

--

We use this shell script to delete the default GitHub labels and add our own. You can modify as needed for your purposes.
https://github.com/80-20/ProcessManagement/blob/master/set-github-lables.sh

**Comment by usmanismail** [comment]
Dead link on https://github.com/80-20/ProcessManagement/blob/master/set-github-lables.sh

**Comment by erikpmp** [comment]
Sorry about. The update URL is at:
https://github.com/thisisarray/GitHub-Issues-Process/blob/master/set-github-labels.sh

I'll update the above comment too to correct the URL.

**Comment by desrosj** [comment]
Color and label consistency across repositories would be very helpful and useful.

**Comment by patcon** [comment]
This should be accomodated by https://github.com/apps/settings now! :tada: 

Related: https://github.com/probot/settings/issues/80

Does this make this issue good to close? :)

**Comment by nunorafaelrocha** [comment]
IMHO, the probot/settings app it's really good, but the lacking of permission restrictions makes it only usable for organization/repository where everyone as the admin role.

I would say that this should be a core feature under github enterprise first.

**Comment by mehulkar** [comment]
nice, that's pretty cool @patcon. But not sure how I could use that in an GHE install.

**Comment by patcon** [comment]
> IMHO, the probot/settings app it's really good, but the lacking of permission restrictions makes it only usable for organization/repository where everyone as the admin role.

The warning that I think you're alluding to (on the plugin install page) is perhaps a little overbearing, as I believe its concerns are accommodated by properly setting up protected branch settings on the default branch. And with this PR incoming, that will be possible to configure via the plugin itself soon :)
https://github.com/probot/settings/pull/76

**Comment by nhooyr** [comment]
I think another reason why probot/settings doesn't close this issue is because it'd be hard to keep a large number of repositories's labels in sync. If you make a single sync, it'll be annoying to update it everywhere.

**Comment by oprogramador** [comment]
@mehulkar 

this seems to be a duplicate of https://github.com/isaacs/github/issues/371

**Comment by dgw** [comment]
@oprogramador If anything, #371 is a duplicate of this, not the other way around.

But this issue talks about "my repos", and #371 is for "per organization". While closely related, the two issues aren't strictly duplicates at all.

**Comment by Levasseur-Sp** [comment]
> Sorry about. The update URL is at:
> https://github.com/thisisarray/GitHub-Issues-Process/blob/master/set-github-labels.sh
> 
> I'll update the above comment too to correct the URL.

Following this I made a [repo](https://github.com/Levasseur-Sp/Github_Labeling). I plan on going further than just adding labels. Label descriptions are also supported! 😄

**Comment by sypets** [comment]
> this seems to be a duplicate of #371

> But this issue talks about "my repos", and #371 is for "per organization". While closely related, the two issues aren't strictly duplicates at all.

Strictly, this issue **does** talk about "my repos" **and** "my organizations repos":

> just for my (or my organizations) repos

I would agree, it is a duplicate of #371. 

But I suggest, change the title:

Allow me to create a default set of labels for my repos

&rightarrow; Allow a default set of labels for user / organization.

**Comment by mehulkar** [comment]
Closed #371 since I probably meant the same thing in both. Added some more details in the top comment that should cover all the cases. Feel free to have more Thoughts and Opinions™ and comment here!

**Comment by labrose** [comment]
👋 Hi! PM for GitHub here. We recently [launched a new setting](https://github.blog/changelog/2019-10-17-create-default-labels-at-the-organization-level/) that will allow you to set the default labels that are created for **new** repositories in an organization. Right now it does not modify existing repositories, but we are considering ways that you can further standardize labels.

Let me know if you try this out and how it works for you! As we continue to improve label administration across multiple repositories, any and all feedback is appreciated.

**Comment by mehulkar** [comment]
@labrose awesome! is this available in GHE yet?

**Comment by labrose** [comment]
We try to keep dotcom and GHES in feature parity as much as possible and ship GHES updates roughly every 3 months. Org label defaults haven't been released in a GHES version yet, but keep an eye on or subscribe to our [release notes](https://enterprise.github.com/releases) 😄

**Comment by ZeldaIsThePrincess** [comment]
Awesome ! 
Is there any easy way to spread modifications to repositories ?

**Comment by labrose** [comment]
Right now the labels don't apply back to existing repositories.

Could you elaborate more on what types of modifications you would want to spread and to which repositories?

**Comment by sypets** [comment]
@labrose It would be very convenient if there was a way to apply the default labels to specific repositories or to all repositories. The solution https://github.com/apps/settings provided a way to migrate existing labels by defining a relation "old label" -> "new label".

**Comment by mehulkar** [comment]
Closing this down as it seems the main feature is done! Thanks for the updates @labrose!

**Comment by Zebiano** [comment]
This issue is in my opinion still not 100% resolved, as "default labels" has only been integrated for repositories inside organizations, and not for user repositories. I'd love to have the same feature for users, as it's exactly what I've been searching for.

Since that hasn't been implemented yet, I've decided to develop a small CLI that makes use of the GitHub API to automatically upload custom labels to any repository you have access to. 

Posting this in hopes of helping others out so long the feature doesn't get implemented user-wide.
