### ISSUE TITLE
Generate hyperlinks to definition of source code identifiers like free-electrons.com / opengrok / IDEs

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#292]
**EDIT** implemented: https://help.github.com/en/articles/navigating-code-on-github !!!!!!!

Something like: http://lxr.free-electrons.com/source/fs/compat.c for known file types, so that you can click on definitions and get redirected to it.

This is uber hard, but also uber useful.

Should be doable, since http://ctags.sourceforge.net/ essentially implements the source code parsing: all that is left is the HTML generation.

Yes, there are tag conflicts, but it works 97% of the time. We could start dealing with tag conflicts by simply linking to the first match to start with.

If you think it would take too much CPU, one option is to do it only for Releases.

OpenGrok is doing this, and is amazing: https://github.com/OpenGrok/OpenGrok

Related:
- https://github.com/isaacs/github/issues/705
- https://github.com/isaacs/github/issues/624
- https://github.com/isaacs/github/issues/889

EDIT: we are getting closer: https://help.github.com/articles/finding-changed-methods-and-functions-in-a-pull-request/

**Comment by capablemonkey** [comment]
Until GitHub implements this feature, I hacked up a little chrome extension that effectively does this!  https://github.com/capablemonkey/github-go-to-definition
