### ISSUE TITLE
Url for opening file editing at a specific line number

### ISSUE THREAD

**Issue by hayd** [isaacs/github#295]
At the moment there is a single link for making an edit, e.g.

https://github.com/JuliaLang/julia/edit/master/base/base.jl

It would be great to be able to advertise a link to edit a part of a file (e.g. the line number for a docstring of a specific function). IMO the whole point of the edit button is lowering the barrier for entry for contributions and this would help!

_Similar to how you can access line numbers in a file, diff or a PR._

**Comment by ptomato** [comment]
You can append something like `#L12` to the edit URL to place the editor cursor at that line. It's not overly obvious but it works!

**Comment by hayd** [comment]
Nice! I'm sure you didn't use to be able to, good job github!
