### ISSUE TITLE
Add images from clipboard using Firefox

### ISSUE THREAD

**Issue by LukeOwlclaw** [isaacs/github#300]
When posting a new issue I would be great if one could just press CTRL+V to paste the screenshot just taken. This would avoid having to save the image on HDD, then opening a file explorer and navigation to the file, and then dragging it back to the browser. So a http://snag.gy/ inside github would be nice.

Edit: For Chrome this already works but not for Firefox.

**Comment by frabcus** [comment]
:+1:

**Comment by RickMohr** [comment]
+1

**Comment by Delapouite** [comment]
https://hacks.mozilla.org/2015/03/using-the-firefox-devtools-to-debug-fetch-on-github/

**Comment by LukeOwncloud** [comment]
For everybody who is wondering what @Delapouite's link above is about: It is about a Firefox bug when adding an image by drag&drop, and how to debug it. Nice video but nothing to do with this issue.

**Comment by ViliusKraujutis** [comment]
For me, as well, pasting image from clipboard to github does not work. Firefox 41.0.2, Ubuntu 15.04.

**Comment by ViliusKraujutis** [comment]
Switching back to Chrome Browser. Primarily, because of this issue.

**Comment by fireattack** [comment]
Any news on this? Since we can do that on multiple site (imgure, snaggy etc.) I don't think it's not possible on Firefox, just gihub used some Chrome only code here.

**Comment by jaustin** [comment]
If anyone's found a workaround for this in the meantime, please let us know. I wasn't expecting a site like GitHub to be the reason I'd be unable to move exclusively to Firefox!

**Comment by jaustin** [comment]
Turns out this is fixed in Firefox 50 (works for me!). Thanks to GitHub support for explaining this and showing me this link too:

https://bugzilla.mozilla.org/show_bug.cgi?id=906420

The text at the bottom of the textbox isn't updated yet but  cmd+v works on MacOS

**Comment by fireattack** [comment]
Yeah, tested on Windows, works flawlessly!
