### ISSUE TITLE
Add ability to write descriptions for labels

### ISSUE THREAD

**Issue by sharwell** [isaacs/github#304]
I'd like to be able to explain the meanings of various labels in my repositories, especially where they differ in meaning when applied to a pull request vs. an issue.

**Comment by am11** [comment]
:+1: 

Please add a description field associated with label.

The admin would be able to edit it at `https://github.com/o[wner/rganization]/repo/labels` and then it would be rendered for the viewer at `https://github.com/o[wner/rganization]/repo/labels/Label%20Text` like follow:

![-label-description-proposal](https://cloud.githubusercontent.com/assets/3840695/6546625/8e6e6a60-c5c3-11e4-996c-613cdf0b6ae8.png)
<br/><br/>
*(inspired by stackoverflow tags description concept; e.g. http://stackoverflow.com/questions/tagged/velocity.js)*

**Comment by jmm** [comment]
+1 on being able to describe labels. I think management of that should happen via the existing labels interface. In the meantime another workaround would be to list them in a wiki that's only editable by contributors.

**Comment by patcon** [comment]
This is a thing now! https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/

Good to close!
