### ISSUE TITLE
 Add Tags to enable better organization of very long lists of Repositoies.

### ISSUE THREAD

**Issue by AnneTheAgile** [isaacs/github#306]
With more and more use of Github, it's harder and harder to see one's projects the way one wishes. I would love tags and/or foldering to help out. The given solution of buying/making new organizations doesn't make sense to me.

My thinking is that Tags might be faster/easier to implement?
AnneTheAgile

References;
[1] Discussion of this problem at SO.
http://stackoverflow.com/questions/11852982/arrange-repositories-in-folders-on-github
[2] Pivotal tells why it's hard to have a second inbox.
http://pivotallabs.com/the-beauty-and-curse-of-github-issues/
[3] Issue #6 in this repo, public place ticket, explains that this is where non-employees can list desired features/fixes.
[4] Sister ticket here,  Add Foldering to enable better organization of very long lists of Repositoies. #302 
[5] The repository hierarchy request is hugely popular on gitlab: http://feedback.gitlab.com/forums/176466-general/suggestions/3867903-allow-project-groups-to-be-organized-in-a-hierarch

**Comment by ebousse** [comment]
+1

**Comment by Armienn** [comment]
+1

**Comment by Kaixhin** [comment]
+1 for organising things which may not be hierarchical (in the same way that issues can have multiple labels).

**Comment by Odonno** [comment]
I was thinking about that too. A system of labels for repositories, like we have for issues.
My first objective was to set state of repo (created, in progress or done).

**Comment by cirosantilli** [comment]
Implemented: https://github.com/blog/2309-introducing-topics

**Comment by ebousse** [comment]
Thanks! Do you plan to allow filtering by topic when on the page of an organization?

**Comment by cirosantilli** [comment]
@ebousse this is not an official repo, open a new issue and send an email to github as explained on readme :-)

**Comment by Odonno** [comment]
That's good!

**Comment by jonorthwash** [comment]
I don't think topics as they're currently implemented is quite what @AnneTheAgile was requesting.  The difference is that clicking a topic should be able to show only user- or org-specific projects with that label.  Otherwise it's not so useful for organising one's own projects.
