### ISSUE TITLE
README rendering doesn't handle relative/local SVG images

### ISSUE THREAD

**Issue by stuartpb** [isaacs/github#316]
See https://github.com/litl-license/litl-license/tree/e50196aa3dba3f667728483eb801022d9c113925 - I had to switch the inline image here to PNG for it to display on GitHub, which is lame and means that it's going to look lousy on Retina displays. (I would later go on to fix this by passing it through a gh-pages URL, which gives the added benefit of the code working when copied to repos that _don't_ have this image.)

**Comment by GreLI** [comment]
What security concerns are you talking about? Browsers are already limiting scripting and other security-related SVG features in an ``<img>`` tag. See for example [SVG as an Image](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image) on MDN.

**Comment by stuartpb** [comment]
@GreLI That's what I said:

> Coming back to the security question, there's no actual security problem to displaying SVGs. As the links on that question mention, SVG images don't run scripts, and even if they did, it would be in a sandboxed document no more dangerous than visiting the image separately/in an iframe.

**Comment by drewnoakes** [comment]
A workaround for others hitting this issue from a search engine (as I did) is to use the `cdn.rawgit.com` service.

Before:
https://raw.githubusercontent.com/zeromq/netmq/master/docs/Images/NetMQLogo.svg

After:
https://cdn.rawgit.com/zeromq/netmq/master/img/NetMQLogo.svg

**Comment by ioquatix** [comment]
+1

**Comment by Bigous** [comment]
+1

**Comment by carsy** [comment]
:+1:

**Comment by Kubuxu** [comment]
:+1:

**Comment by DraTeots** [comment]
+

**Comment by 4shome** [comment]
The bugs hasn't been fixed yet?

**Comment by hickeng** [comment]
+

**Comment by rtens** [comment]
+

**Comment by sbruton** [comment]
+

rawgit not a workaround for private repos

**Comment by doug-wade** [comment]
👍

**Comment by thewizardplusplus** [comment]
Please forgive me for a flooding above. I used git-rebase few times. And every time GitHub created a record of a link. I'm very sorry!

**Comment by markgaensicke** [comment]
👍

**Comment by seagreen** [comment]
It would be great to get some attention on this (especially since it's getting close to a two year old bug report). I'd like to move more of my writing to GitHub but this is actually a bigger sticking point than it looks like.

**Comment by seagreen** [comment]
At minimum the link should still show up as text instead of disappearing entirely. Content appearing in a slightly more inconvenient form is alright, content appearing nonsensical due to entirely missing images is a bigger deal.

**Comment by sbruton** [comment]
+

**Comment by rektide** [comment]
Adding `?raw=fixyourshitgithub` is a workaround that will still break local editing but may be less gnar than using fully specifying the sin-ugly `https://raw.githubusercontent.com` url.

**Comment by piranna** [comment]
> Adding ?raw=fixyourshitgithub is a workaround that will still break local editing but may be less gnar than using fully specifying the sin-ugly https://raw.githubusercontent.com url.

Could you be able to provide an example of that?

**Comment by rektide** [comment]
oh sorry, is there is ticket for image urls in general, not SvG specific?

**Comment by sorenmortensen** [comment]
+1

**Comment by LeoAref** [comment]
👍

**Comment by ioquatix** [comment]
Apparently this is now being worked on!!

**Comment by jaydenseric** [comment]
@ioquatix Where did you hear that?

**Comment by ioquatix** [comment]
@jaydenseric https://github.com/github/markup/issues/556#issuecomment-288581799

**Comment by stuartpb** [comment]
Just to reiterate my exasperation at this noise that's coming up again in github/markup#556 where people misunderstand the issue being with *repository-local paths* as being a problem, somehow, with SVG (as if there need to be *extra steps to accommodate it*), here is an example of an SVG image being displayed in GitHub Markdown *right now*:

![tiger](https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg)

**Comment by hickeng** [comment]
@stuartpb For what it's worth, that SVG is _not_ being displayed right now (I'm assuming from your comment I should actually see the tiger inline). Doesn't necessarily invalidate your point but does add confusion:
![image](https://user-images.githubusercontent.com/3923729/28544060-ca0e8c2a-7076-11e7-905f-aedf941a1b7d.png)

**Comment by sorenmortensen** [comment]
@hickeng That's strange, because for me, both Safari 11.0 and Chrome 59.0 currently display it perfectly fine inline. What version of Chrome breaks it for you?

**Comment by hickeng** [comment]
@sorenmortensen `Version 59.0.3071.115 (Official Build) (64-bit)` - opening the image directly in a new tab functions as expected so it's not directly a firewall or content filter issue. In fact, having just reloaded the page I now see it inline and no variant of opening via different links is causing the failure :( Not a fan of transient failures.

**Comment by hassanazimi** [comment]
How about base64 in a img tag?

**Comment by MonsieurDart** [comment]
@stuartpb Is it possible to find the camo.githubusercontent.com path of an SVG file hosted in a private GitHub repo? How to do so? Thanks in advance for you help. 😊

**Comment by cederom** [comment]
+1 :-(

**Comment by Potherca** [comment]
I might be mistaken but doesn't this issue resolve the problem?

**Fix relative SVG rendering** https://github.com/github/markup/issues/556

**Comment by seagreen** [comment]
@Potherca: Yep, it's solved. You can see [in my test](https://github.com/seagreen/svg-on-github-test) that both the PNG and the SVG appear now.

**Comment by mikemol** [comment]
In which version of GitHub Enterprise is this fixed?

**Comment by stuartpb** [comment]
I was going to close this, but https://github.com/github/markup/issues/556#issuecomment-399336652 suggests it's still an issue.

**Comment by gucu112** [comment]
@stuartpb #556 was closed recently and I believe it is not an issue anymore.

**Comment by franklinyu** [comment]
I think this issue can be closed. Embedding SVG in Markdown is officially supported by GitHub. If there is still any issue, it would be considered *bug* instead of *lack of feature*, so user should report in https://github.com/github/markup.

**Comment by TPS** [comment]
Per above & https://stackoverflow.com/a/16462143, this is solved
