### ISSUE TITLE
Repository Traffic Analytics API

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#320]
Is there an API for https://github.com/blog/1672-introducing-github-traffic-analytics , https://github.com/cirosantilli/test/graphs/traffic ? I would like to get a cross repository traffic overview. If you feel like implementing that in GitHub that would be cool as well :)

Things that it would make possible:
- https://github.com/isaacs/github/issues/399
- https://github.com/isaacs/github/issues/447

**Comment by peterflynn** [comment]
+1, it would be great to be able to get things like:

* Visitor count for a specific page, rather than just a listing of the top 10 as shown in the UI
* Separate visitor counts for each issue/PR - currently, they're all merged into one "Issues" category in the UI
* Separate referrers for each page - currently, you only get a combined list of referrers for the whole repo.  For example: if you're seeing a lot of hits on some random stale wiki page (e.g. info on a deprecated feature or an older version), it would be good to know what's driving all the traffic to the obsolete info

**Comment by aoberoi** [comment]
+1

**Comment by snaga** [comment]
+1

**Comment by vfxwiki** [comment]
+1

**Comment by bshyong** [comment]
+1

**Comment by jashandeep-sohi** [comment]
+1

**Comment by nitinmotgi** [comment]
+1

**Comment by zoharbabin** [comment]
+1 any update on that front?

**Comment by jebpublic** [comment]
+1

**Comment by jfrederich** [comment]
+2

**Comment by alicenguyen** [comment]
+3

**Comment by drsii** [comment]
+1

**Comment by jeremyschlatter** [comment]
+1

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by jashandeep-sohi** [comment]
I'd like to add that an easier alternative might be allowing users to associate a Google Analytics tracker id with each repository and sending metrics to Google Analytics using the Measurement Protocol. This would effectively outsource the analytics part of Github to a dedicated analytics platform and save Github the hassle of maintaining & developing yet another analytics platform that would probably never be able to provide as detailed metrics as a dedicated platform would.

The downsides are you are relying on a 3rd party and popular repositories might run into Google API limits (more than 10 million hits per month on a free account).

**Comment by vincentlaucy** [comment]
:+1: for @jashandeep-sohi

**Comment by NickWoodhams** [comment]
+1

**Comment by adamwulf** [comment]
+1

**Comment by gwongz** [comment]
+1 Any update on timeline?

**Comment by methnen** [comment]
I'll put in my vote for this one as well.  Especially like the idea of being able to associate a Google Analytics id with a repository.

**Comment by Codesleuth** [comment]
+1

**Comment by cirosantilli** [comment]
@jashandeep-sohi proposed at: https://github.com/isaacs/github/issues/446 Bitbucket already does it.

**Comment by hortinstein** [comment]
would love to have this!

**Comment by neeasade** [comment]
+1

**Comment by Lorenzo45** [comment]
+1

**Comment by FreeAssoc** [comment]
+1 -- any updates on this?

**Comment by cirosantilli** [comment]
@FreeAssoc if there are ever any, I'll ping thread and update the question.

**Comment by burhanloey** [comment]
+1, no wonder I can't find it.

**Comment by dtolb** [comment]
+1

**Comment by zoharbabin** [comment]
+1, so sad to see GitHub is not making any progress or even slightest effort to participate on that crucial issue.

**Comment by cadesalaberry** [comment]
:+1:

**Comment by harshavardhana** [comment]
:+1:

**Comment by phawxby** [comment]
+1

**Comment by mjbrender** [comment]
+1, please and thank you.

**Comment by eduard93** [comment]
+1

**Comment by geeeeeeeeek** [comment]
+1, hope to see it soon

**Comment by brianmc** [comment]
+1

**Comment by lcguerrerocovo** [comment]
+1

**Comment by felipegtx** [comment]
+1

**Comment by geeeeeeeeek** [comment]
A year passed...and we heard nothing...I'm wondering if it's actually in progress.

**Comment by ealonsodb** [comment]
+1

**Comment by realityking** [comment]
+1

**Comment by prozanne** [comment]
:+1:
Is there any updates about it?

**Comment by sanyamc-msft** [comment]
+1 there are many people in my team who dearly want this data. Currently we manually parse the data into a csv and power our charts on a forthnightly basis. Would really appreciate api/ json data, even if its for 14 days.

**Comment by acrodrig** [comment]
+1

**Comment by joeljfischer** [comment]
:+1:

**Comment by pthivierge** [comment]
+1

**Comment by MaciekLesiczka** [comment]
+1

**Comment by nathairtras** [comment]
+1

**Comment by vietj** [comment]
+1

**Comment by taylorm10** [comment]
+12

**Comment by snaow** [comment]
+1

**Comment by andipavllo** [comment]
+1

**Comment by mcoles** [comment]
+1

**Comment by erisu** [comment]
+1

**Comment by phlax** [comment]
+1

**Comment by v-braun** [comment]
+1!!!111

**Comment by AntonAleksandrov** [comment]
+1 !!!

**Comment by cwsmith** [comment]
+1

**Comment by arfoll** [comment]
+1

**Comment by YannChemin** [comment]
would love to just download a csv of all traffic data...

**Comment by gibbok** [comment]
+1

**Comment by MarioZG** [comment]
+1

**Comment by realityking** [comment]
The Traffic API is no longer in Preview: https://developer.github.com/changes/2016-12-28-end-traffic-api-preview/ 🎉 

I think this one can be closed @cirosantilli
