### ISSUE TITLE
"Contributing" to a repo should require more than just a PR

### ISSUE THREAD

**Issue by stuartpb** [isaacs/github#332]
See https://github.com/torvalds/linux/pull/148#issuecomment-69055722 - spammers / fraudsters can make it look like they're a "contributor" to any major project by just filing some junk pull request against it.

(This has been the first crossposted issue I've performed using https://github.com/ghes/isaacs-github-contact-xposter. Hooray!)

**Comment by awilfox** [comment]
I believe that a PR can be considered a contribution only after it is merged and not while it is still open.  There are other reasons besides spam/fraud that PRs may be closed (perhaps the code quality just isn't there) and allowing it to be considered a contribution before being reviewed by the project's actual team members seems a bit insulting.

**Comment by jruderman** [comment]
You can also "contribute" to a repository by submitting a bug report – and I think that's a good thing!

Rather than putting repo owners in the position of policing what counts as a "contribution", how about renaming the column from "contributes to..." to "participates in..."?

**Comment by cirosantilli** [comment]
issue +1 https://github.com/isaacs/github/issues/9 and doing metrics on it is a possible solution... but in the end, merged pull requests under `graphs/contributors`, e.g. https://github.com/gitlabhq/gitlabhq/graphs/contributors, will always be a much stronger metric.

**Comment by quasipedia** [comment]
The question seems to me quite philosophical.  Are bug report contributions? Are translations contributions? Are testing contributions? Are feature requests contributions?  Are rejected pull requests contributions?

I think that the current model of considering participation to a discussion as "contributing" goes well with what GitHub stands for: _social coding_ (emphasis on _social_, in this case, in which any interaction with others count).

I have no problem with it, and when I evaluate GitHub profiles prior to interviews, I always check what kind of contribution the candidate did to various projects, so it never misled my judgment so far.

That's not to say that I don't see the point of the OP, though.  I just wanted to point out why I don't see the present model as "broken" but just as one of the possible alternatives.

**Comment by TPS** [comment]
@stuartpb I'm leaning toward closing this "invalid," as the premise of the issue seems wrong — a PR _does_ need to be ___merged___ (as @awilfox already noted) before "contributor" is assigned.  What do you think?  Or do you mean to say something different?

**Comment by awilfox** [comment]
At the time this issue was created, you could become a "contributor" by simply opening a PR, _even if it wasn't merged_.  That seems to be fixed, so rather than 'invalid', perhaps it should be considered fixed.

**Comment by TPS** [comment]
Ok!  Just as a clarification, though, currently opening a first-time (in a repo) pull request _does_ show <kbd>First-time contributor</kbd> __only__ in that PR, but won't be converted to <kbd>Contributor</kbd> in whole repo until it's _merged_.
