### ISSUE TITLE
make branch names in a pull request clickable links

### ISSUE THREAD

**Issue by benatkin** [isaacs/github#334]
It would be nice if I could go to a branch by clicking the branch name in the header of a pull request. For example, if I could click `iojs:v1.x` to go to the v1.x branch, it would save me some time.

![screen shot 2015-01-08 at 1 07 29 pm](https://cloud.githubusercontent.com/assets/4126/5670730/7c94d3c0-9737-11e4-93ae-8eb0dbf51d24.png)

One reason I can think of why the GitHub developers haven't made these tags into links is because they may not exist (if a branch has been deleted). I think going to a 404 if a branch didn't exist would be fine.

**Comment by joshdifabio** [comment]
Seems to be a duplicate of #34.

**Comment by benatkin** [comment]
@joshdifabio haha. quite a coincidence (34, 334)

**Comment by benatkin** [comment]
closing coz this is a duplicate of #34
