### ISSUE TITLE
Integrate CHANGELOG.md Viewing Capability (similar to README.md)

### ISSUE THREAD

**Issue by eriklharper** [isaacs/github#339]
I think it would be cool to see Github implement a pretty way to view any repository's CHANGELOG.md, much like it currently does with README.md.  With things like http://keepachangelog.com/ out there, as more open source projects adopt a convention like this, the better off users of open source projects will be!

**Comment by cirosantilli** [comment]
That is an interesting project, but I'm not sure GitHub could render it much better than standard markdown rendering.

What could be done is add a more visible link to it, but not sure it's worth the UI space. To have a greater change of being accepted, I'd propose you make a mockup / more precise description.

**Comment by stuartpb** [comment]
GitHub already has a system for Releases.

**Comment by TPS** [comment]
#882?
