### ISSUE TITLE
"svn co" fails to see "trunk" of a repository

### ISSUE THREAD

**Issue by boutell** [isaacs/github#345]
This repository:

https://github.com/drak/doctrine1

Has a "master" but it cannot be seen via this svn URL:

https://github.com/drak/doctrine1/trunk

If I check out the entire thing with svn:

https://github.com/drak/doctrine1

I do get "branches", "tags" and "trunk" subdirectories.

If I check out the "branches" folder, or the "branches/dev" branch, with a direct URL to those, all is well.

Only the trunk/master refuses to be checked out individually.

**Comment by boutell** [comment]
This article:

https://help.github.com/articles/support-for-subversion-clients/

Suggests at one point checking out the trunk of a repository directly, so it appears it is supposed to work.

**Comment by mkopinsky** [comment]
Works for me...
```
$ svn checkout https://github.com/drak/doctrine1/trunk doctrine -q
$ ls doctrine
CHANGELOG		LICENSE			UPGRADE_TO_1_2		build.xml		lib			tests
COPYRIGHT		README.md		build.properties.dev	composer.json		package.xml		tools
$
```

**Comment by boutell** [comment]
Aaaand now it works for me too. How bizarre. Closing.

**Comment by boutell** [comment]
(I wonder if that particular repo was in a specific state when this happened.)
