### ISSUE TITLE
can't build qt3d project

### ISSUE THREAD

**Issue by deepgadhia** [isaacs/github#362]
g++ -c -include .pch/Qt53DRenderer -pipe -O2 -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT3DRENDERER_LIBRARY -DQT_BUILD_3DRENDERER_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_3DCORE_LIB -DQT_OPENGLEXTENSIONS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/home/deep/Qt5.4.0/5.4/gcc_64/mkspecs/linux-g++ -I. -I../../include -I../../include/Qt3DRenderer -I../../include/Qt3DRenderer/5.5.0 -I../../include/Qt3DRenderer/5.5.0/Qt3DRenderer -Ibackend -Ibackend/framegraph -Ibackend/jobs -Ifrontend -Ifrontend/framegraph-components -Iio -Idefaults -I../../include/Qt3DCore/5.5.0 -I../../include/Qt3DCore/5.5.0/Qt3DCore -I../../include/Qt3DCore -I/home/deep/Qt5.4.0/5.4/gcc_64/include/QtGui/5.4.0 -I/home/deep/Qt5.4.0/5.4/gcc_64/include/QtGui/5.4.0/QtGui -I/home/deep/Qt5.4.0/5.4/gcc_64/include -I/home/deep/Qt5.4.0/5.4/gcc_64/include/QtOpenGLExtensions -I/home/deep/Qt5.4.0/5.4/gcc_64/include/QtGui -I/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/5.4.0 -I/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/5.4.0/QtCore -I/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore -I.moc -o .obj/qrenderaspect.o backend/qrenderaspect.cpp
In file included from /home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qobject.h:48:0,
                 from /home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qabstractanimation.h:37,
                 from /home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/QtCore:4,
                 from ../../include/Qt3DRenderer/Qt3DRendererDepends:3:
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qmetatype.h: In instantiation of ‘constexpr int qMetaTypeId() [with T = QSurface*]’:
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qvariant.h:678:44:   required from ‘static T QtPrivate::QVariantValueHelper<T>::metaType(const QVariant&) [with T = QSurface*]’
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qvariant.h:105:39:   required from ‘static ReturnType QtPrivate::MetaTypeInvoker<Derived, Argument, ReturnType>::invoke(Argument) [with Derived = QtPrivate::QVariantValueHelper<QSurface*>; Argument = const QVariant&; ReturnType = QSurface*]’
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qvariant.h:817:64:   required from ‘T qvariant_cast(const QVariant&) [with T = QSurface*]’
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qvariant.h:343:36:   required from ‘T QVariant::value() const [with T = QSurface*]’
backend/qrenderaspect.cpp:346:39:   required from here
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qmetatype.h:1648:5: error: static assertion failed: Type is not registered, please use the Q_DECLARE_METATYPE macro to make it known to Qt's meta-object system
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qmetatype.h: In instantiation of ‘static constexpr int QMetaTypeId2<T>::qt_metatype_id() [with T = QSurface*]’:
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qmetatype.h:1649:44:   required from ‘constexpr int qMetaTypeId() [with T = QSurface*]’
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qvariant.h:678:44:   required from ‘static T QtPrivate::QVariantValueHelper<T>::metaType(const QVariant&) [with T = QSurface*]’
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qvariant.h:105:39:   required from ‘static ReturnType QtPrivate::MetaTypeInvoker<Derived, Argument, ReturnType>::invoke(Argument) [with Derived = QtPrivate::QVariantValueHelper<QSurface*>; Argument = const QVariant&; ReturnType = QSurface*]’
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qvariant.h:817:64:   required from ‘T qvariant_cast(const QVariant&) [with T = QSurface*]’
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qvariant.h:343:36:   required from ‘T QVariant::value() const [with T = QSurface*]’
backend/qrenderaspect.cpp:346:39:   required from here
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qmetatype.h:1509:97: error: ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<QSurface*>’
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qmetatype.h:1509:100: error: body of constexpr function ‘static constexpr int QMetaTypeId2<T>::qt_metatype_id() [with T = QSurface*]’ not a return-statement
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qmetatype.h: In static member function ‘static constexpr int QMetaTypeId2<T>::qt_metatype_id() [with T = QSurface*]’:
/home/deep/Qt5.4.0/5.4/gcc_64/include/QtCore/qmetatype.h:1509:100: warning: control reaches end of non-void function [-Wreturn-type]
make[2]: *** [.obj/qrenderaspect.o] Error 1
make[2]: Leaving directory `/home/deep/install/qt3d/src/render'
make[1]: *** [sub-render-make_first] Error 2
make[1]: Leaving directory `/home/deep/install/qt3d/src'
make: *** [sub-src-make_first] Error 2

**Comment by cirosantilli** [comment]
How is this related to how GitHub works? You should open a bug on that project instead.
