### ISSUE TITLE
Ability to set default issue labels per organization (colors and names)

### ISSUE THREAD

**Issue by mehulkar** [isaacs/github#371]
It would be nice if each Organization could set a default set of labels for their issue lists. The default list provided by GH does not fit our needs and we do a large part of our project management via GH issues. Having consistency across projects would make it much easier to manage and schedule work, and also communicate progress to the rest of the team.

**Comment by stuartpb** [comment]
This could be done by an app, actually: I know waffle.io does it whenever I add a project to waffle.io/plushu/plushu (or at least whenever I drag a card for that project).

**Comment by mehulkar** [comment]
Yeah, probably. I'm sure there's an API for it. I think it would be a good feature for project management capabilities though.

**Comment by nunorafaelrocha** [comment]
+1

**Comment by TPS** [comment]
#281 for orgs?

**Comment by erikpmp** [comment]
We use this shell script to delete the default GitHub labels and add our own. You can modify as needed for your purposes. 
https://github.com/80-20/ProcessManagement/blob/master/set-github-lables.sh

**Comment by jwir3** [comment]
:+1:

**Comment by joeflack4** [comment]
+1

**Comment by mikejoyceio** [comment]
+1

**Comment by sypets** [comment]
Gitlab provides possibility to promote labels to "group labels". That way you have a set of group (or organization labels), but can also have specific labels for one repo.

GitHub does offer the "project" functionality by organization (as well as by repo). You can manage **all** organization-wide issues in projects. So, having a set of labels for an organization as well seems like the sensible next step to me.

**Comment by sypets** [comment]
I sent request to GitHub support about this and got answer:

> Thank you for getting in touch with GitHub Support!

> I believe adding support for Organisation level labels is something we'd like to implement. I'm not sure when we'll add this but we'll pass your feedback onto our Product Team consider.

**Comment by rosibaj** [comment]
Agree, agree, agree. consistency in labels is key for github project management across many teams at one org!

**Comment by iMazed** [comment]
Working in a team that has over 600 repos, I can only echo the need for this!

**Comment by coltenkrauter** [comment]
I agree

**Comment by clarkbw** [comment]
👋Hello! 

I don't think this ask is going to get traction by itself. 

I'm seeing a lot more asks for a system like #281 with the ability to have a central place for label standardization which would _also_ act as the default set. The problem of org level labels is a larger scope problem but would have the effect of fixing this.

Wanted to make that known and perhaps it makes sense to merge this into the other.

**Comment by rosibaj** [comment]
I think org wide similar to this implementation is best: https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

Per repo creates a lot of extra work for managers

**Comment by mehulkar** [comment]
I can't remember now if I just opened the same issue twice or if I meant something different for each. Looks the same to me now. Closing this one i favor of the older issue. Please go 👍 that one!

**Comment by nunorafaelrocha** [comment]
@mehulkar care to share a link?

**Comment by dgw** [comment]
@nunorafaelrocha He's referring to https://github.com/isaacs/github/issues/281#issuecomment-508272778.

**Comment by displague** [comment]
Here's yet another tool to take a labels.json file and create all of those labels against all of the repositories in your organization. 
https://github.com/displague/github-labeller

I hope this helps!
