### ISSUE TITLE
@about, @pricing, @home, @features , @pages generate at mentions even though they are reserved

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#375]
For most reserved usernames, no link gets generated. Why is that no the case for @about and @pricing?

Edit 2015-04-28: @home , @features , @pages are also inconsistent. @mention and @mentions are likely intentional, although insane :-) Screenshot: https://web.archive.org/web/20150428112427/https://github.com/isaacs/github/issues/375

Edit 2015-04-28 a few hours later: home and features already fixed! https://web.archive.org/web/20150428143800/https://github.com/isaacs/github/issues/375

Edit 2015-04-30: James Dennes replied, and `@pages` is down as well.

Stuff that I've tried:

- reserved GitHub usernames which don't 404

    - the at mention link gets created as of 2015-04-01 (now fixed): @about @pricing
    - blacklisted that don't 404 and don't generate links and were not on the employee list below: @account @c @explore @help @jobs @login @logout @plans @security @settings @shop @signup @status @styleguide @wiki  @integrations @developer @new @notifications @mac @windows @showcases @trending @stars @training @contact @press
    - blacklisted that 404 (AKA possible future usage or too close to existing reserved words): @linux @cloud @site @editor @offer
    - invalid usernames that don't 404 @README.md @CONTRIBUTING.md @500 @404
    - sample valid username no on has taken: @qxufdnpeswbugaowkwlkrgqxlweindawoykzzrc
    - taken usernames which might get bumped some day :-) : @download

- Blacklist as of 2010 by an employee: http://www.quora.com/How-do-sites-prevent-vanity-URLs-from-colliding-with-future-features/answer/Kyle-Neath GitHub simply renames squatters.
    - still blacklisted: @account @admin @api @blog @cache @changelog @codereview @compare @enterprise @gist @help @hosting @jobs @jobs @lists @login @logout @mine @news @organizations @plans @popular @projects @security @shop @signup @status @stories @styleguide @tour @translations @wiki 
    - unblacklisted as of 2015-04-01: @better

Screenshot 2015-04-04:

----
![screenshot from 2015-04-04 22 25 44](https://cloud.githubusercontent.com/assets/1429315/6994420/9936e56a-db19-11e4-88af-98642feaf5e2.png)
----

**Comment by cirosantilli** [comment]
James Dennes:

> Tiny little minor "bug": for most reserved usernames, no link gets generated. Why is that no the case for @about and @pricing?

Thanks for letting us know. We'll open an issue to investigate.

> Is there an up-to-date of reserved github usernames?

No.

**Comment by cirosantilli** [comment]
James told me they've fixed it, and it's true :)

**Comment by cirosantilli** [comment]
Edit: @home is also inconsistent.

**Comment by Download** [comment]
"taken usernames which might get bumped some day :-) : @download"

Is that a Good Thing?  Or not??   :)

**Comment by Download** [comment]
Ouch.

I've been reading this and it's making me worried:

    At GitHub, we don't.  There have been squatters on almost every top-level feature we've eventually implemented (like /explore) — but that's just it. These are squatters and the likelihood of someone having a *real* username of "explore" is astronomically small.
    
    So when there's a collision, we rename the accounts and take it over.
http://www.quora.com/How-do-sites-prevent-vanity-URLs-from-colliding-with-future-features

I'm _not_ a squatter. I have an actively used, paid account. Please don't bump me!
I *love* my GitHub username and don't want to change it  :(

**Comment by cirosantilli** [comment]
@Download I wouldn't be worried, you don't look like a squatter, I don't think they'd displace you :-)
