### ISSUE TITLE
Ability to ignore +1 comments

### ISSUE THREAD

**Issue by ferrouswheel** [isaacs/github#377]
I've been following #156 for a while now, and while it's great that people can register their interest in a feature/bug, getting notifications whenever someone ":+1:"'s the issue is really tiresome. I don't want to unsubscribe because I want to hear ASAP about any change in development, but the ":+1:" is just a constant stream of noise.

**Comment by ahmadnassri** [comment]
agreed, perhaps may not be a core feature of github itself, but rather a browser extension or something that you can set rules to ignore people or matching regex of content ....

**Comment by ljharb** [comment]
I think it'd be easier if Github simply provided a "vote" button that could let people publicly indicate their interest (as separate from "subscribe" which is private, and "comment" which is public + subscribe + notification).

**Comment by dancancro** [comment]
If you want GitHub to add a feature, the best thing to do is to [send a message](https://github.com/isaacs/github/issues/9#issuecomment-87450477) to support@github.com.

@ljharb, I'm with you. Adding a feature that provides useful votes makes a lot more sense to me than a feature to ignore useless votes.

**Comment by cirosantilli** [comment]
The eternal issue upvote feature request: https://github.com/isaacs/github/issues/9

**Comment by ralphcallaway** [comment]
+1

**Comment by bweston92** [comment]
+1

**Comment by eddiemonge** [comment]
don't ignore the +1's but instead convert them to an upvote as proposed in #9

**Comment by ferrouswheel** [comment]
@eddiemonge Thanks - I'd be happy with #9 so closing this as a duplicate.

**Comment by rgbkrk** [comment]
:+1:

**Comment by TPS** [comment]
Since people aren't playing nice by using reactions (#9) properly, I filed #640 to solve this in a more complete fashion.  :godmode: 😉

**Comment by mspiegel** [comment]
I've implemented this feature as a GitHub App. Looking for beta-testers. Check out https://github.com/apps/always-be-closing if you're interested. Any feedback would be appreciated at https://github.com/thoughtdealership/abc-users.
