### ISSUE TITLE
Link the "compare" and "base" repo/branch combinations in Pull Request pages to their respective repo/branch

### ISSUE THREAD

**Issue by andyperlitch** [isaacs/github#378]
These blue boxes should be links. It is really annoying to have to manually go to the fork:

![image](https://cloud.githubusercontent.com/assets/1390651/7035675/12e98430-dd40-11e4-9f3e-e1e7cdf8dd70.png)

**Comment by OliverJAsh** [comment]
Duplicate of https://github.com/isaacs/github/issues/34?

**Comment by andyperlitch** [comment]
@oliverjash, yep. sorry, tried searching a few times but didn't find that
