### ISSUE TITLE
disable further commenting on an issue or pull request

### ISSUE THREAD

**Issue by tjfontaine** [isaacs/github#38]
Sometimes issue comments can devolve into a mess of trolls complaining after a repository maintainer has decided against an issue, it would be helpful if a repository could disable new comments on an issue.

The reopen case can be handled by cross linking in a new issue.

**Comment by Nate-Wilkins** [comment]
@tjfontaine could you close this issue?
I think the only thing missing is the ability to close commits. Maybe a new issue?
Thanks!

**Comment by stuartpb** [comment]
Closing comments on commits is ***the*** thing this issue is about, though. This issue was pretty much raised due to a *very specific* controversial commit in Node. It's not ready to be closed until that feature lands.

**Comment by stevemao** [comment]
Please lock this. Thanks.

**Comment by cirosantilli** [comment]
Closing as done for issues. For other types of comments like commit comments, please open separate specific issues.
