### ISSUE TITLE
Repo status banner (Abandoned, no longer active, active)

### ISSUE THREAD

**Issue by KP** [isaacs/github#382]
Oftentimes, it's not immediately clear that a project has been abandoned or deprecated. I propose a prominent banner that could warn users a repo is no longer actively maintained. It could also display other statuses like:

Red banner: Abandoned
Yellow banner: No longer in active development. Minor fixes.
Green banner: Active development. Stable.
Light green banner: Early development. Unstable.

Users would control the categorization of the repo but if a repo had little activity over time, they would be prodded to confirm the repo's status.

**Comment by KP** [comment]
From Github:

>Hi Kenton,

>Thanks for the suggestion. We're always looking for ways to improve GitHub so I will add your idea to our internal Feature Request List. No promises, but the team will discuss it.

>Cheers,
>Scott

**Comment by captn3m0** [comment]
Duplicate of #144 I think.

**Comment by KP** [comment]
Closing as it closely resembles #144
