### ISSUE TITLE
StackOverflow-like live preview for comments

### ISSUE THREAD

**Issue by livibetter** [isaacs/github#388]
I found myself switching between *Write* and *Preview* way too often as I commenting. I hope @github would add an option to bring *Preview* right below *Write* just like StackOverflow's editing box.

I am only talking about comments on

* issues
* commit pages and line comment for commits

I don't think this would be helpful for online editing `README.md` or those Markup files, because their source codes usually are longer the screen height in editor.

The comments usually short, at least, mine were short enough to be within my screen size with Markdown code.

A switch option next to *Preview* would be nice, you click and *Preview* is gone and a live preview is brought below editing area, click again, it's back as before and you can switch to *Preview* tab.

**Comment by cirosantilli** [comment]
+1

I would add: "live preview updated as you type" to the title.

Related on GitLab for analogous blob editing: http://feedback.gitlab.com/forums/176466-general/suggestions/5799911-preview-as-you-type-for-markdown-blob-file-edit

**Comment by livibetter** [comment]
Super late update, this was the reply what I got from GitHub Support on the same day I opened this issue and emailed them:

>  Thanks for the suggestion. We'll keep this in mind.

Just a one-line response.

**Comment by cirosantilli** [comment]
@livibetter no worries, they always reply. I don't even repost their standard "ACK" message :-)

**Comment by erkinalp** [comment]
> "ACK" message
:citybus:

**Comment by cirosantilli** [comment]
@livibetter Why close?

**Comment by livibetter** [comment]
@cirosantilli because I don't want it hanging in my issues list, GitHub is aware of it, that's enough for me to close it.

**Comment by cirosantilli** [comment]
@livibetter sorry, but this is not a personal issue list: it is meant to be useful to the entire community. If we close, it looks like it has already been solved. Do you mind if we keep it open?

**Comment by livibetter** [comment]
@cirosantilli Yes, I do, but I apologize. I shouldn't have tried to open this issue in the first place, email GitHub support is all I should have done.

I have to partially disagree with you about the usefulness. There is no official responses here, all you can do is wait for something that you have no idea if it ever comes or not. I need an answer, but not even an ambiguous one here.

And the most important for an issue is to have discussions with the people who have the ability to implement. Yes, we can talk, even design, but in the end, GitHub is only one can actually act on it.

I'm sorry, I just don't want to let an issue to hang around my issues list, which I can't be sure if I'd ever get an answer, even a WONTFIX would do. If this was an official issue tracker, one year probably is my limit. An issue drags that long is pretty much dead to me. This unofficial, four month, I think I've been patient enough.

Sorry, but someone else would have to re-create this if one wants whatever this can achieve.

**Comment by cirosantilli** [comment]
@livibetter I have cloned this as a one off at https://github.com/isaacs/github/issues/457 and proposed a policy at https://github.com/isaacs/github/pull/458

I suspect this is a common problem for repositories that use the never close policy, which is a common one. It might be worth a feature request (here? :-) )

You could create a puppet livibetter-noclose account and use it for such issues. Talking openly about issues is a win-win for everyone.

**Comment by livibetter** [comment]
@cirosantilli Sometimes, I do dream about issue transfer. Never close policy is fine, but without resolution certainty, I honestly don't see the point of having stuff lying around.

I believe that violate GitHub ToS, one person can only have one free account, at least months ago when I read it, and that's why I created an organization to store the repositories I've lost interests. Yep, still is a violation:

> One person or legal entity may not maintain more than one free account.

Too me, it's just talking, no real actions. On 2013-07-15, I emailed the support, asking if there is a possibility for having an official tracker, well, you can guess the answer.

**Comment by cirosantilli** [comment]
@livibetter 

> I believe that violate GitHub ToS

I think their ToS is silly :-)

But as long as you don't do evil, I think it's fine. E.g., it is fundamental for testing purposes: https://github.com/cirosantilli-puppet 

> On 2013-07-15, I emailed the support, asking if there is a possibility for having an official tracker, well, you can guess the answer.

Official tracker issue request at: https://github.com/isaacs/github/issues/6

> Too me, it's just talking, no real actions.

I don't think this repo is totally useless:

- it can save time from reporting issues twice
- it increases the probability that similar products like GitLab will implement it

Of course, it is not certainty of action.

But that is basically the case for any feature request, even in open source, unless you are willing to fork a project, which means huge overhead.

I agree with Gandhi's quote: http://www.goodreads.com/quotes/50584-your-beliefs-become-your-thoughts-your-thoughts-become-your-words

:heart:

**Comment by livibetter** [comment]
@cirosantilli 

> I think their ToS is silly :-)

Email them, you tell them.

Nonetheless, that doesn't matter even if it's created with goodwill, a violation is a violation. They might not take action on you, but if they do, they have every right to do so. You should try to clear with them, I am sure they'd give you a green light, before continuing violating. It's out of respect, especially now you are aware of that.

> Official tracker issue request at: #6 

I knew I wasn't the first one.

> I don't think this repo is totally useless:

I said "partially."

> it can save time from reporting issues twice

This was one of points in my email, but let's just said they don't *mind* receiving the same thing over and over again.

> I agree this quote: http://www.goodreads.com/quotes/50584-your-beliefs-become-your-thoughts-your-thoughts-become-your-words

Good quote, but sometimes, it's not up to your whatsoever, no matter how hard you try. To me, issues for GitHub, it's about *let go*. We email and let go, forget it, if it's implemented one day, it's like a birthday gift and make your day and be proud of yourself for suggesting something they do work on.

I've emailed them several times, well, I haven't received any gifts, yet.

**Comment by cirosantilli** [comment]
I understand :-)
