### ISSUE TITLE
i'd like to be able to +1 commits

### ISSUE THREAD

**Issue by jovo** [isaacs/github#389]
when somebody on my team addresses a bug that was previously listed as such in issues (or even if not), i'd like to be able to :+1:  their commit.  note that many members of our team have commit privileges, so we tend to not make merge requests (which would defacto result in implicit :+1: 's).
i also don't really know how to search the issues previously posted here for one like this, 
so i'm not sure if this has already been suggested.  
if so, please point me to it, so that i can :+1:

**Comment by cirosantilli** [comment]
please add "commit" to the title, or readers think at first that you mean https://github.com/isaacs/github/issues/9 for issues / PRs

**Comment by Mottie** [comment]
I've been using [ZenHub](https://www.zenhub.io/). It has a nice +1 feature. Sadly, the browser extension is currently only available for Chrome.

There are other [GitHub integrated project management tools](http://www.quora.com/Which-project-management-tools-are-deeply-integrated-with-GitHub) available that I haven't checked out yet.

**Comment by TPS** [comment]
Also solved via https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments.
