### ISSUE TITLE
Links into submodules (hosted at github) are untracked

### ISSUE THREAD

**Issue by wherget** [isaacs/github#391]
When linking from `example-repo` to `[Some File](submodule/file.txt)` the link that is generated is relative to the containing repository, i.e. `https://github.com/example/example-repo/blob/example-revision/submodule/file.txt`. 
I would have expected it to link to `https://github.com/example/submodule/blob/submodule-revision/file.txt`

I got given this reply:

> Thanks for getting in touch. I am afraid we don't pick up relative submodule
> URLs currently, but we are tracking this and hopefully we may improve this in
> the future. Thanks again for taking the time to improve this.
> 
> Cheers,

Obviously this need not work for submodules which live outside github (where a suitable URL might not even be available to link to).

**Comment by siminapasat** [comment]
👋 PM at GitHub here. We shipped a fix for this - git submodules defined using relative paths are now clickable in the UI, making it easy to navigate to the linked repository. Happy linking!

**Comment by wherget** [comment]
Works like a charm! 👍 Thank you (and the team involved) for adding this feature, as well as getting back to me about it.
