### ISSUE TITLE
New github design doesn't show last touched author of a file.

### ISSUE THREAD

**Issue by captn3m0** [isaacs/github#40]
Here is the old design:

![selection-1](https://f.cloud.github.com/assets/584253/667194/e1d8333a-d7e9-11e2-8f02-5d234f053100.jpg)

Compared to the new one:

![selection-e](https://f.cloud.github.com/assets/584253/667196/e9716b48-d7e9-11e2-8343-6ff416e1c794.jpg)

The [new design](https://github.com/blog/1529-repository-next) doesn't include the _last modified by_ information. It used to be a quick way to review which contributor is affecting which files, but now we only get the commit message and its time.

**Comment by TPS** [comment]
@clarkbw Iff <kbd>wontfix</kbd> is @GitHub's official response to this, could this be:
- [ ] replied to, saying so explicitly?
- [ ] closed &/or locked?

**Comment by clarkbw** [comment]
There are no plans to revert back to the old design or add the author to the current view. This is a wontfix; or it is highly unlikely we’ll do this. 

However knowing why people want the author shown is always valuable, we may address those concerns in another way. Appreciate the feedback as always. ✨
