### ISSUE TITLE
Squash merges from UI

### ISSUE THREAD

**Issue by jantman** [isaacs/github#406]
Similar to #88 but more pointed...

A lot of projects on GitHub request that PRs are squashed down to one commit, mainly to keep a clean history. This poses a number of problems:

1. I've seen quite a few PRs submitted by casual contributors that forgot to do this, or never made the requested changes. When this happens, the level of effort for maintainers is quite high - pull the contributor's work into a branch of their own, then squash it all down, then open a new PR and close the old one (which may well have valuable commentary in it).
2. Unless the contributor cuts a *new* branch with the squash and then changes the PR to use that new branch, the commit history is effectively lost.
3. This is essentially saying "don't work the way GitHub lets you."

It would be much more helpful if PRs offered this option, i.e. "Squash Merge". It would perform a ``merge --squash``, but allow leaving the source branch intact. Ideally, the person who merges would be able to specify the commit message, which would default to "{title} (PR {num})" where title is the title of the PR, and num is the PR number. This would allow quick reference to the original pull request (and commit history).

**Comment by cirosantilli** [comment]
GitLab with infinite upvotes: http://feedback.gitlab.com/forums/176466-general/suggestions/5662794-provide-squash-option-when-merging-merge-requests

**Comment by sparrc** [comment]
+1

**Comment by edouard-lopez** [comment]
+1

**Comment by beckclib** [comment]
> A lot of projects on GitHub request that PRs are squashed down to one commit, mainly to keep a clean history. 

Ditto. Often `git pull --rebase` needs to be done too.

+5

**Comment by cirosantilli** [comment]
https://github.com/blog/2141-squash-your-commits

**Comment by necrose99** [comment]
I'd be happy with a Conslidate today's commits or last FEW Minor commits...  10am---5pm  now smash@5pm 

namily docker can be trial and error with gentoo ,  emerge fob/booby  ... deps is not installed it wines.. 
fix , ok working .....  broken ...  so get mad and hammer out commits , fixes 1 by 1 quay.io building FINALLY ...   however be nice to smash the last few typo fixes etc into fewer commits. 
however the docker image for building will do just fine... as far as keep on keeping on ,  package updating etc.. just trying to unbork 100 commits to just a few or consolidate out a plus.
