### ISSUE TITLE
Support for protected branches

### ISSUE THREAD

**Issue by icyflame** [isaacs/github#411]
- Have fine-grained permissions within a repository
- Owners and Collaborators, instead of everyone being just collaborators
- Only owners can push to some of the important branches like `master`, `staging`, etc.
## Why should this be there at all?
- This will ensure that we can actually assign an issue to someone without granting them push access to the major branches such as `master`
- Become very important if `auto-deploy` using something like Travis CI is setup. (A wrong push will deploy a breaking change to the production application! :-1: to that)

**Comment by isair** [comment]
+1

**Comment by renan** [comment]
+1

**Comment by pvkleef** [comment]
+1

**Comment by Garethp** [comment]
:+1:

**Comment by erkinalp** [comment]
At least ability to mark a branch read-only for non-admins.

**Comment by pratik60** [comment]
Would love this

In private repos, small ones, forking seems overcomplicated, and the only reason I seem to be doing it is because I don't want to give interns write access to a few branches. Github should really introduce this feature.

**Comment by aspiers** [comment]
I think this can be closed now: https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by TPS** [comment]
> @aspiers commented:
I think this can be closed now: https://github.com/blog/2051-protected-branches-and-required-status-checks

Whaddya think, @cirosantilli?

**Comment by pratik60** [comment]
+1 to close this issue
