### ISSUE TITLE
Allow work-in-progress and ready status on pull requests

### ISSUE THREAD

**Issue by ismay** [isaacs/github#416]
I often see [WIP] and [Ready] prefixes in the titles of pull requests, and everyone at my work (including myself) uses this convention as well. It's a good way to begin getting feedback on something that's still under construction.

However, it would be great if this could be integrated a little further into the github UI. For example, a [WIP] status could give a warning when someone's trying to merge the related PR. Or changing to a [Ready] status could send a notification to the repo owner. Stuff like that.

I'd say that it deserves its own place in the UI, since so many people tend to use it. Right now it's just not as integrated as it should be if you ask me (since we're misusing the title tag for it). Curious to hear what others think..

**Comment by cirosantilli** [comment]
GitLab did it recently.

**Comment by dagwieers** [comment]
Gitlab supports both `WIP: ` as well as `[WIP] `, however it now promotes using "WIP: " only.

Documentation still refers to both `WIP: ` as well as `[WIP] `, see: http://doc.gitlab.com/ce/workflow/wip_merge_requests.html, however the newer Gitlab releases promote Work-In-Progress using the message: "**Start the title with `WIP: ` to prevent a Work In Progress merge request from being merged before it's ready.**" for more consistency. So preferably only promote the use of `WIP: `.

**Comment by kingmaiku** [comment]
we recently had to move from gitlab to github and I am missing this a ton!!
we still use the wip labels in the title of the pull request but the human error factor makes me nervous.

**Comment by FredyC** [comment]
Definitely something I would like to see too.

**Comment by yzhong52** [comment]
Moving from GitHub to GitHub, I would love to see this feature as well.

**Comment by Gaket** [comment]
Hi! Any updates on this feature?

**Comment by bfred-it** [comment]
I doubt they'll add an actual status, but perhaps blocking the merge via title or tag would be good, like this extension does https://chrome.google.com/webstore/detail/do-not-merge-wip-for-gith/nimelepbpejjlbmoobocpfnjhihnpked

**Comment by Alxandr** [comment]
@bfred-it this puts the requirement on the user though. A better solution would likely be to make a GH integration that responts to events on PRs and uses the status API to set it as "failed" if it has a WIP tag or similar.

**Comment by bfred-it** [comment]
Well, yeah, I was just describing its behavior and offering an alternative for the time being.

**Comment by hoangthanh1234** [comment]
Status = In Progress, Progress = 0%

**Comment by TheReincarnator** [comment]
@hoangthanh1234 Does not work for me. Even with "in progress", the merge button is still functional. The main aspect of the feature request is to disable the button to prevent errors.

**Comment by styfle** [comment]
@gr2m made this: https://github.com/apps/wip

We are trying it out at @markedjs and so far so good.

**Comment by AuthorOfTheSurf** [comment]
https://github.com/apps/wip Mentioned above by @styfle works great!

Main requirement for me is something that's built-in to Github--a browser addon is NOT good enough.

If you add the WIP app to your project and you already have PR's with "WIP" in the title, you will need to edit and save the title to get it to register with WIP.

**Comment by RoxaneM** [comment]
Any update on the feature? 
Same story here: migrated from GitLab and was really disappointed when didn't find this feature on GitHub :(

**Comment by willbattel** [comment]
I was surprised to not see this feature in GitHub after using GitLab, seems like such a no-brainer QoL feature. Hope to see this someday! :)

**Comment by graingert** [comment]
FYI, adding a reviewer removes the WIP: from PR titles

**Comment by lukehefson** [comment]
We (GitHub) shipped https://github.blog/2019-02-14-introducing-draft-pull-requests/ the other day! 🎉 

It might not solve for all the problems in this thread – but we'd love to know what you think!

**Comment by mattcopas** [comment]
I'm likiing this feature - very useful!

Would it be possible to make a non-WIP PR into a WIP PR?

**Comment by lukehefson** [comment]
> I'm likiing this feature - very useful!

Yay! I'm so glad to hear it @mattcopas!

> Would it be possible to make a non-WIP PR into a WIP PR?

We've been hearing more and more of this feedback since launching and are definitely looking to iterate. Can I ask you what your use case(s) would be @mattcopas?

**Comment by Alxandr** [comment]
@lukehefson You thought you were done, you got back feedback about things that needs changing, and it will take some rewriting, so you transition back to WIP, work on it for a while, and then flag it as ready for review again.

**Comment by dagwieers** [comment]
>> Would it be possible to make a non-WIP PR into a WIP PR?

>We've been hearing more and more of this feedback since launching and are definitely looking to iterate. Can I ask you what your use case(s) would be @mattcopas?

Not so difficult use-case. You are working on something and deem it perfect, so you remove the WIP status. Then you find a showstopper, and you want to restore the WIP status.

**Comment by mattcopas** [comment]
@lukehefson Sure - there are a couple of use cases
- If I simply forget to create the PR as a WIP
- I need to make more, non-trivial, changes to my PR after it has been reviewed
- I'm out of office for a few days, but don't want a PR merged until I return
- I don't want it merged yet for other reasons (dependent on other work, waiting to merge after a release, etc etc)

For the first case, it's far to say that I could just close/re-create the PR, but once the PR has been commented on at all, it's certainly not desirable to do this

**Comment by TPS** [comment]
According to https://github.community/t5/How-to-use-Git-and-GitHub/Draft-Pull-Requests-not-available/m-p/19212/highlight/true#M5733 , this is now live!
> If you are not seeing this feature, it is probably because the repository that you're working in does not meet that criteria. If you believe that your repository does meet these criteria and you're still not seeing the feature, please contact GitHub Support directly so that we can investigate.

  Specifics @ https://help.github.com/articles/about-pull-requests/#draft-pull-requests

If any problems, please comment!

**Comment by TPS** [comment]
Further news from https://github.blog/changelog/2019-03-08-expand-ready-for-review-permissions-for-draft-pull-requests/:
>The GitHub Blog
March 8, 2019
>
># Expand ready for review permissions for draft pull requests
> Any user with repository write permissions will now be able to click the `Ready for review` button on a draft pull request in order to enable mergeability.

**Comment by kellyarwine** [comment]
Hi, everyone! [This feature shipped today.](https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft). Thank you for all of the feedback.

**Comment by sysarcher** [comment]
@kellyarwine if there are no reviewers, can we still create "draft" PRs?

**Comment by kellyarwine** [comment]
@willsmythe ^^
