### ISSUE TITLE
allow voting on issues and merge requests without comment

### ISSUE THREAD

**Issue by technorama** [isaacs/github#429]
Create an upvote and downvote buttons for each issue / merge request.

Having to write a new comment when you only want to upvote / downvote without saying anything only clutters the comments.

A list of issues should show the total number of upvotes and downvotes.

**Comment by cirosantilli** [comment]
Dupe: https://github.com/isaacs/github/issues/9

And I think I've seen that request before somewhere with the same words? http://feedback.gitlab.com/forums/176466-general/suggestions/5379851-vote-issues-merge-requests-without-comment

:-)
