### ISSUE TITLE
[Meta] Proposal to add @cirosantilli as repo collaborator

### ISSUE THREAD

**Issue by captn3m0** [isaacs/github#430]
I think this repo could do a lot with an active collaborator who works on triaging and labelling the issues. I asked @cirosantilli (who is quite active in the discussions) and he agreed.

Thoughts everyone?

**Comment by cirosantilli** [comment]
Gotta +1 this one. :clap:

**Comment by TPS** [comment]
You probably should have mentioned @isaacs directly, else he may be not quite be following the entire flood of activity coming from all these issues.…

**Comment by isaacs** [comment]
Done.

**Comment by cirosantilli** [comment]
yay!

**Comment by TPS** [comment]
@cirosantilli :congratulations: :clap:
