### ISSUE TITLE
Merging Issue with vms repository between Release-15.0 and Release 15.1 branch

### ISSUE THREAD

**Issue by rgandhizc** [isaacs/github#440]
Hi 

Repository: zerochaos\vms (https://github.com/zerochaos/vms)

Today we found that changes from branch Release-15.1 are available in Release-15.0 branch which is not expected. We tried to see how it happened so we can revert it but unfortunately we are not able to do so.

Can you please suggest how to resolve this quickly and without impacting Release-15.0?

As per observation, it happened yesterday(10-Aug-2015) after 6:30 AM EST. 

Is there any way to get Push date time along with commit date time?

I need push log from yesterday morning till today. Request you to consider this as priority and provide solution. If required I will be available on phone.

Thank you very much for consideration in advance.

Let me know if you need more information.

Rajendra Gandhi

**Comment by erkinalp** [comment]
Off topic here. This is not official github issue tracker.

**Comment by cirosantilli** [comment]
I cannot see that repository: is it private?

If so, I consider this off topic: please make a minimal example on an public repository and focus on a single issue.

Feel free to reopen if you provide the minimal example.
