### ISSUE TITLE
Provide a dedicated "+1" button to allow people to upvote issues/PRs 

### ISSUE THREAD

**Issue by jaredsinclair** [isaacs/github#450]
This would reduce the `+1` noise that ruins otherwise good discussions while still providing a means for interested observers to show their support for a feature/issue/etc.

**Comment by sxgao3001** [comment]
Hey @jaredsinclair just saw you mention this on #18. 

You should give www.zenhub.io a look. ZenHub uses a lightweight Chrome extension to inject task management features (e.g. kanban board, burndown charts) into GitHub's UI so you can stay on GitHub. It also includes a +1 button to GitHub's UI for issues and PRs.  

Right now people need the ZenHub extension to see the +1's.

Full disclosure, I work on ZenHub.

**Comment by jchamberlain** [comment]
+1

**Comment by hadrienl** [comment]
+1

**Comment by cirosantilli** [comment]
Dupe https://github.com/isaacs/github/issues/9
