### ISSUE TITLE
Add ability to fork and edit files from external URL

### ISSUE THREAD

**Issue by stiemannkj1** [isaacs/github#460]
Github has a wonderful feature to fork a repo via a URL:

    https://github.com/user/repo/fork

I would like to request that adding a path to a file to the end of the URL would cause the user to navigate to that file in edit mode in their newly forked repo:

    https://github.com/user/repo/fork/path/to/edit/file

It would work similarly to the way that the edit button works inside Github.

<img width="314" alt="screen shot 2015-09-02 at 9 09 00 am" src="https://cloud.githubusercontent.com/assets/3483874/9649447/2b30e252-51c3-11e5-8954-e4b181f7c4ea.png">

[Related StackOverflow question in case this feature already exists.](http://stackoverflow.com/questions/32354482/github-fork-and-edit-button-from-an-external-site)

**Comment by cirosantilli** [comment]
I don't understand: why not just give the link for the edit button, e.g.: https://github.com/creationix/nvm/edit/master/CONTRIBUTING.md

If the user commits, that already generates the fork if not yet forked.

Can you explain the exact use case?

**Comment by stiemannkj1** [comment]
@cirosantilli, that does exactly what I want. Thanks!
