### ISSUE TITLE
Adding collaborators to a repo should require them to accept

### ISSUE THREAD

**Issue by silverwind** [isaacs/github#463]
To prevent a kind of abuse which aims to draw attention through adding high-profile people as collaborators to a repo and in turn spamming the activity stream of their followers:

https://twitter.com/sindresorhus/status/640910860190248960

**Comment by jacklin213** [comment]
I lol'ed at this. +1 should implement, very abusive !!!

**Comment by sindresorhus** [comment]
:+1:

**Comment by cirosantilli** [comment]
+1. Had to unfollow @schacon because of that.

**Comment by silverwind** [comment]
They fixed it! https://github.com/blog/2170-repository-invitations
