### ISSUE TITLE
Non-http URI-s in Markdown

### ISSUE THREAD

**Issue by szepeviktor** [isaacs/github#474]
It would be nice to linkify non-http URI-s:

```html
<a href="abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2Fszepeviktor%2Flean-filter%2Fmaster%2Fleanfilter.txt&amp;title=Lean%20filter">Subscribe</a>
```

HTML: <a href="abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2Fszepeviktor%2Flean-filter%2Fmaster%2Fleanfilter.txt&amp;title=Lean%20filter">Subscribe</a>

Markdown: [Subscribe](abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2Fszepeviktor%2Flean-filter%2Fmaster%2Fleanfilter.txt&amp;title=Lean%20filter)

**Comment by kenorb** [comment]
Please report that issue at [GitHub markdown repo](https://github.com/github/markup) instead, so this can be closed.

**Comment by szepeviktor** [comment]
Thank you.
