### ISSUE TITLE
OpenSSL TLS versions

### ISSUE THREAD

**Issue by srikantchonnad** [isaacs/github#478]
Hello,
Does OpenSSL 1.0.1e support TLS 1.1 and 1.2?

Regards,
Srikant.

**Comment by erkinalp** [comment]
Off topic as it is. Can you expand it a bit?

**Comment by srikantchonnad** [comment]
We are using Salesforce Mobile SDK 3.x which internally uses OpenSSL 1.0.1e for secure communication. (https://developer.salesforce.com/page/Mobile_SDK_Release_Notes)

Since Salesforce is disabling TLS 1.0 support, I wanted to know if the current mobile SDK (which uses OpenSSL 1.0.1e) supports TLS 1.1 and 1.2.

**Comment by erkinalp** [comment]
Off topic again.  This repository is dedicated to github feature requests.

**Comment by 304NotModified** [comment]
Vote for close of this issue.

**Comment by cirosantilli** [comment]
Closing as off topic. Please re-ask on an OpenSSL specific forum.
