### ISSUE TITLE
Copy git.io link directly from repo's page

### ISSUE THREAD

**Issue by jamen** [isaacs/github#483]
I wish there was a way to get a short link right from a repo's page provided GitHub has it's own link-shortening service...

Perhaps a field could be added, for example:

![capture](https://cloud.githubusercontent.com/assets/6251703/10293276/dde78b78-6b70-11e5-8261-65003ad3b38f.PNG)

**Comment by pravj** [comment]
As a temporary fix, this can be achieved by a browser extension.
GitHub has changed the page layout, now it's not like the image you have posted, though.

Ideally, the short URL should be generated *on-demand*, not for all the repositories.

**Comment by jamen** [comment]
Yeah, I suppose it's more of an opt-in feature, and I don't really see anywhere it would look good on the new UI anyways.  I'll just close this.  Thanks for your input.  :)
