### ISSUE TITLE
Placing repo's short description in `.git/description`

### ISSUE THREAD

**Issue by jakirkham** [isaacs/github#485]
It would be nice if the repo description was also placed `.git/description` when the repo is cloned. There may be other opportunities for this to be synced up, as well.

**Comment by cirosantilli** [comment]
For those that didn't know like me, that is a gitweb specific file: http://stackoverflow.com/questions/6866838/what-should-be-in-the-git-description-file

**Comment by jakirkham** [comment]
I got a response from GitHub and would like to roughly summarize it here.

The `.git/description` is managed locally and its content is not shared. In short, this would require a change to `git`.
