### ISSUE TITLE
Suggestion: Direct link to file in history

### ISSUE THREAD

**Issue by hisuwh** [isaacs/github#495]
I find it quite tiresome currently that if I want to see a historical version of a file, I have to:
* Find the file
* Click 'History'
* Find the commit
* Click on the commit
* Find the file again within that commit
* Click view on the file

It would be very helpful that if on the file history view there was a link or button to view the full file at that point.

**Comment by cirosantilli** [comment]
The link you want does seem to exist at the `<>` button for each commit. E.g.: https://github.com/cirosantilli/test-git-web-interface/commits/master/issue-md.md

Yes, it is one of those overly implicit UI choices they sometimes make. They should just write "view file".

**Comment by cirosantilli** [comment]
Closing as resolved, feel free to reopen if I'm mistaken, or open a new issue for better UI ;-)

**Comment by rstarkov** [comment]
How does the `<>` button help when it just takes you to the repository root at that commit? You have to find the file again, which can range from mildly inconvenient to very hard depending on repo size.

**Comment by hisuwh** [comment]
@rstarkov `<>` did take you to the file when @cirosantilli posted his comment - seems they've broken this since 😢
