### ISSUE TITLE
Additional granularity in Protected Branches settings

### ISSUE THREAD

**Issue by dylanpyle** [isaacs/github#496]
The "required status checks" setting is great when enforcing discipline around certain branches. However, it would be great to have an additional setting along the lines of "require status checks for everyone when merging branches into [default branch], but still allow administrators to directly push (not force push) commits to this branch".

Without this, you can't let certain classes of desirable commits through - e.g. version number bumps (in our organization, this means a commit to update a metadata file with a new version number, tagged with the release version).

**Comment by dylanpyle** [comment]
... more thoughts ...

The detailed rule is described as:

> When enabled, commits must first be pushed to another branch, then merged or pushed directly to [default branch] after status checks have passed.

There might be some way to set up a workflow where a version bump gets pushed to an ephemeral branch to enforce that it passes tests/lint, then rebased into the default branch and pushed directly once that's done. Is anyone using a setup like that?

**Comment by cirosantilli** [comment]
Recommend that you summarize in the issue title the modification you propose.
