### ISSUE TITLE
"The entity type Document is not part of the model for the current context"

### ISSUE THREAD

**Issue by denkyira5544** [isaacs/github#506]
I am using EF6, MVC 5 and UnitOfWork with code first from an existing database. I can query using unitofwork and my repository but when I try to insert into the database, I get the error below:
'_dbSet.Local' threw an exception of type 'System.InvalidOperationException'	System.Collections.ObjectModel.ObservableCollection<Mynamespace.DAL.Models.Documents> {System.InvalidOperationException}
"The entity type Document is not part of the model for the current context"

I am getting error on this line of code

  public virtual void Insert(TEntity entity)
    {
        entity.ObjectState = ObjectState.Added;
        _dbSet.Attach(entity);
        _context.SyncObjectState(entity);
    }

I am not sure if I should Implement
 public override void Insert(Document entity) method before I can insert

**Comment by cirosantilli** [comment]
Please open an issue on the repository that implements that, this is for GitHub issues.
