### ISSUE TITLE
Collapse/Expand files in the Files Changed view of a Pull Request

### ISSUE THREAD

**Issue by dalpert-korewireless** [isaacs/github#514]
As a developer participating in a Code Review for a large Pull Request
I want the ability to collapse individual files in the Files Changed view
So that I can ignore code that I've already reviewed
And navigate a large number of changes more easily.

**Comment by dalpert-korewireless** [comment]
````
-----Original Message-----
From: Ivan Žužak [mailto:support@github.com] 
Sent: November-10-15 3:41 AM
To: David Alpert
Subject: Re: Feature Request - Collapse/Expand files in the Files Changed view of a Pull Request

Thanks for expressing interest in this, David -- yeah, I agree that'd be very useful. I'll pass your suggestion to the team working on pull requests, but can't promise anything.

If there's anything else you'd like to see improved -- let me know.

Cheers,
Ivan
````

**Comment by ProLoser** [comment]
@dalpert-korewireless this feature has been partially added to Github Omnibox for chrome: https://chrome.google.com/webstore/detail/github-omnibox/jbfhklldhgbomclinhlgbmjjiimafolo?utm_source=chrome-ntp-icon
There's a control to expand/collapse all files, and then a control on each file. Although it's hard to see in this video, you can also `shift`+`click` on an individual file's collapse button and it will collapse all siblings while expanding the target file. 

The extension has a lot of other features too such as personalized searching in the chrome address bar and CI server status badges (we're still porting the badges to the new github layout).

![Screen](http://g.recordit.co/WGdGUh2yg5.gif)

**Comment by yoyobbi** [comment]
+1

**Comment by JeroenDeDauw** [comment]
Now that the list of files changed into this stupid thing:

![failui](https://cloud.githubusercontent.com/assets/146040/13841998/4237f68a-ec2c-11e5-9bf4-6cd3d17a365e.jpg)

it's nearly impossible to get a quick high level overview of where a PR changes things. Being able to collapse files would help mitigate this problem.

**Comment by sindresorhus** [comment]
The [`refined-github`](https://github.com/sindresorhus/refined-github) browser extension adds [support](https://cloud.githubusercontent.com/assets/170270/13954167/40caa604-f072-11e5-89ba-3145217c4e28.png) for this.

**Comment by bkothe-rm** [comment]
+1

**Comment by bbadeaux-ias** [comment]
+1

**Comment by jrhie** [comment]
+1

**Comment by dustinrohde** [comment]
+1

**Comment by TrentBrown** [comment]
+1

**Comment by joeysino** [comment]
For userscript lovers (Greasemonkey or Tampermonkey), my [Github Notifications Dropdown](https://openuserjs.org/scripts/joeytwiddle/Github_Notifications_Dropdown) script includes this feature as an extra.

The feature only activates on page load, so you may need to reload the page if you navigated there from within the Github site (because Github uses a lot of `pushState` aka "Single Page App").

**Comment by joeytwiddle** [comment]
For userscript lovers (Greasemonkey or Tampermonkey), my [Github Notifications Dropdown](https://openuserjs.org/scripts/joeytwiddle/Github_Notifications_Dropdown) script includes this feature as an extra.

The feature only activates on page load, so you may need to reload the page if you navigated there from within the Github site (because Github uses a lot of `pushState` aka "Single Page App").

**Comment by conalsmith49** [comment]
+1 on this much needed functionality.

**Comment by noplanman** [comment]
GitHub has implemented this not long ago:
![file-collapse](https://cloud.githubusercontent.com/assets/9423417/24326040/f5922562-11a5-11e7-8d2b-327042a2a8e9.png)

My user script [GitHub Tweaks](https://github.com/noplanman/GitHub-Tweaks) has had this feature for quite some time, also for comments in conversations 👍 

As GitHub adds features natively, I'm happy to lighten my script 😊

**Comment by bbi-yggy** [comment]
@noplanman The new triangle toggle in GitHub is nice, but there is no easy way (that I can find) to collapse _all_ the files in the review. Do you know if this is possible, maybe I'm overlooking something?

**Comment by noplanman** [comment]
No you're not missing anything from GitHub's core features.
My userscript that I linked to in my comment above gives you that functionality though, just have a look at the readme to see what else it offers.

**Comment by bbi-yggy** [comment]
That's what I figured / feared. Thanks for the clarification. :)

**Comment by eanhuddleston** [comment]
+1

**Comment by yardensachs** [comment]
Also, you can run this at the console:
```javascript
$$('div.file-header > div.file-actions > button').map(function(x){ x.click()});
```

**Comment by drbergeron** [comment]
+1 for creating a "Collapse All" option, or even starting collapsed if number of files is over some threshold/parameter.

**Comment by benjamincharity** [comment]
I'll add on to @yardensachs with this:

```javascript
// Close all open
$$('div:not(.Details--on) > div.file-header > div.file-actions > button').map(function(x){x.click()});
```

Was useful to speed up the browser when halfway through a PR with tons of files.

**Comment by sharpdot** [comment]
+1

**Comment by Brian-Clement** [comment]
+1

**Comment by KayakinKoder** [comment]
This can't be real life. Just considering switching our enterprise app from bitbucket to github but....I can't easily see a list of files changed?

**Comment by larsxschneider** [comment]
based on @yardensachs and @benjamincharity 's solutions I created a bookmarklet: https://gist.github.com/larsxschneider/c024d7308683eefe2704dffe0b706549

**Comment by truongnguyen-ntq** [comment]
Alt + click to expand/collapse all :)

![image](https://user-images.githubusercontent.com/25791883/39615210-37f24346-4f9f-11e8-9371-5890ed03d12c.png)

**Comment by Brian-Clement** [comment]
@truongnguyen-ntq I'm not seeing that option...is that a new feature rolling out?  Otherwise @larsxschneider 's bookmarklet is working well for me.

**Comment by truongnguyen1912** [comment]
@Brian-Clement ah, `refined-github` browser extension adds support for it. It is not original github feature :(

**Comment by emilygdavis** [comment]
+1 here too. It would be great to have this as a native feature of Github and not just part of an extension!

**Comment by elpiel** [comment]
+1 as well.

**Comment by wedgiebee** [comment]
+1 !!! ;)

**Comment by xnlcasad** [comment]
+1

**Comment by SimKennedy** [comment]
+1

**Comment by picheli20** [comment]
You can check my chrome extension: https://chrome.google.com/webstore/detail/github-code-tree/caffoilocbbhnkdlpdcfanpbeholjdii

It helps me a bit for checking commits or pr's :) If anyone wants to contribute: https://github.com/picheli20/github-code-tree

**Comment by s2t2** [comment]
```js
Array.from(document.getElementsByClassName('js-details-target')).forEach(function(element){element.click()})
````

**Comment by natron2244** [comment]
+1

**Comment by lukehefson** [comment]
Hello all 🙋‍♂️. I'm a Product Manager at GitHub and I though you all might like to know that [we just shipped this](https://blog.github.com/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/) on the site. Thanks everyone for your continued feedback and support 😻

**Comment by TPS** [comment]
@dalpert-korewireless @isaacs @cirosantilli If satisfied, close FTW? :bow:

**Comment by cirosantilli** [comment]
@TPS thanks for the ping.

@lukehefson if you or any other GitHub Staff finds such issues, you can @ mention me directly and I will close them for you.

**Comment by lukehefson** [comment]
Thanks, @cirosantilli (and @TPS) that's great to know 😄!

**Comment by codesimplicity** [comment]
@lukehefson this is a good improvement but one thing that annoys me even more is that deleted files show up just like normal diffs. But from my point of view it is a huge difference if lines have been deleted from a file or if the file was deleted; for the latter I usually only need to know the file name (while it is good to still be able to see the old content).
Therefore I'd be very happy to see something like "Deleted: path/to/file" instead of the deleted lines; similar to the 'large diff' display but maybe taking less vertical space. It could behave like a collapsed file so you could open it if needed.
In a PR with a lot of deleted files this would dramatically reduce the number of lines to look at without collapsing anything.

I hope that makes sense for you as well. 
I did not find any existing issue but this (though #587 mentions something similar).

**Comment by lukehefson** [comment]
@codesimplicity This is great feedback and definitely something (or at least something similar) that we've got in mind!

**Comment by hellopablo** [comment]
@lukehefson I agree this is a great feature, and one I use all the time! I'd love to see the state be maintained between page reloads though, often I'm reviewing large PRs and close the window (sometimes by accident). I collapse files once I've dealt with them as a way of tracking how far through the review I am, so I lose this context if the window is closed.

**Comment by lukehefson** [comment]
@hellopablo Nice idea and interesting workflow! I'll take it to the team for investigation!

**Comment by codesimplicity** [comment]
@lukehefson I really like the feature 👍 👍 👍  
But IMHO it can be improved:
For me the display is too similar to the 'large diff' display; I need to actually read what is written to distinguish both. Some icons for both could help to make that more obvious - I'd like to use my brain's capacity for the important content!
Regarding collapsed files: once you've collapsed a file, you loose the 'diff not shown' view as you can only expand the file afterwards. Reload solves that but then you may loose your progress overview.
This is closely related to @hellopablo's point above: would be cool if you could mark files as done, just as you've recently introduced it for conversations 😻 
Looking forward to more improvements for reviews!

**Comment by psawbridge** [comment]
@abyss7 

Any workaround on this? Or is absolutely every single (hipster) github user in the world using a macbook air ;-)

**Comment by nicolasap-dm** [comment]
@abyss7 @psawbridge Shift+Alt+Click should work (at least on Unity and Gnome DEs)

**Comment by tarunbelagodu** [comment]
> Hello all raising_hand_man. I'm a Product Manager at GitHub and I though you all might like to know that [we just shipped this](https://blog.github.com/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/) on the site. Thanks everyone for your continued feedback and support heart_eyes_cat

Doesnt work for me - using Firefox on Gnome. Is it only supported on Chrome?

**Comment by codesimplicity** [comment]
@tarunbelagodu do you have the problem that "Alt + click to expand/collapse all" does not work as already mentioned in https://github.com/isaacs/github/issues/514#issuecomment-441030058?
Than the suggestion from https://github.com/isaacs/github/issues/514#issuecomment-463201570 may help:
> Shift+Alt+Click should work (at least on Unity and Gnome DEs)

Not using it and also not near my Linux machine currently, so I cannot tell if it would work on Firefox 🤷‍♂️

**Comment by tarunbelagodu** [comment]
> @tarunbelagodu do you have the problem that "Alt + click to expand/collapse all" does not work as already mentioned in [#514 (comment)](https://github.com/isaacs/github/issues/514#issuecomment-441030058)?
> Than the suggestion from [#514 (comment)](https://github.com/isaacs/github/issues/514#issuecomment-463201570) may help:
> 
> > Shift+Alt+Click should work (at least on Unity and Gnome DEs)
> 
> Not using it and also not near my Linux machine currently, so I cannot tell if it would work on Firefox man_shrugging

shift+alt+click doesnt work either, tried both firefox and chrome. Do I need any extensions?

**Comment by lukehefson** [comment]
Hey @tarunbelagodu! Could you [report the issue you're having to our awesome support folk](https://github.com/contact) – they should be able to help better than I can 😄

**Comment by PedroQuintas** [comment]
Yeah Shift, Alt, any combination of them does not work sadly. :( This is indeed a really useful feature.

**Comment by EdMerriman** [comment]
'Shift + Alt + Right click' seems to collapse/expand in Firefox, but not Chrome on Linux (Cinnamon desktop).
