### ISSUE TITLE
Unable to commit to Heroku git

### ISSUE THREAD

**Issue by AshutoshPradhan** [isaacs/github#515]
I modified the code base and commit the code to git but when I am trying to build, I am getting following error. Can Anybody help ASAP.
To https://git.heroku.com/xxx.git
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/xx.git'

Thanks in Advance

**Comment by cirosantilli** [comment]
This does not seem to be about GitHub, so closing as off topic.
