### ISSUE TITLE
topSomething(...) off by one?

### ISSUE THREAD

**Issue by mmakaay** [isaacs/github#524]
Maybe it is by design / dictated by lua internals, but looking at the following output from dnsdist -c:

    > topQueries(3)
       1  mail.makaay.nl.                           678 26.7%
       2  gitaar.net.                               293 11.5%
       3  ns3.gitaar.net.                           276 10.9%
       4  Rest                                     1290 50.8%

I would have expected to see the top 3, not the top 4.
It feels like an off-by-one issue.

**Comment by cirosantilli** [comment]
I think you've posted on the wrong repo by mistake :-)
