### ISSUE TITLE
Feature Request: Have Sorting for +1 of issues by amount of +1s

### ISSUE THREAD

**Issue by cookiengineer** [isaacs/github#527]
The Sorting feature sadly has no item to sort by +1s of issues ascending/descending. This would be an uberawesome feature as it reflects priority of issues (and would fit into the scrum development workflow of backlog priorization), so POs can have it much easier to manage github issues.

![Screenshot of what I mean](https://cloud.githubusercontent.com/assets/592637/11604947/293326e8-9af4-11e5-8ac7-8e60161e0136.png)

**Comment by cirosantilli** [comment]
Would be better after and likely implied by https://github.com/isaacs/github/issues/9

**Comment by TPS** [comment]
@cookiengineer @cirosantilli As I mentioned in https://github.com/isaacs/github/issues/600#issuecomment-200659017, now solved!
