### ISSUE TITLE
Non-resolvable parent POM: Could not find artifact org.apache.httpcomponents:httpcomponents-client:pom:4.4.1-SNAPSHOT 

### ISSUE THREAD

**Issue by sameta** [isaacs/github#529]
Hi All,

We are trying to build httpclient-osgi for resolving issue "java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLContexts"  for getting  patch of 'SSLContexts' . 

we are getting below exception ... 
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.httpcomponents:httpclient-osgi:4.4.1-SNAPSHOT (/home/httpclient-trunk/httpclient-osgi/pom.xml) has 1 error
[ERROR]   Non-resolvable parent POM: Could not find artifact org.apache.httpcomponents:httpcomponents-client:pom:4.4.1-SNAPSHOT 
and 'parent.relativePath' points at wrong local POM @ line 28, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] 
Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and 
possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Please suggest us any way for resolving the issue .

**Comment by cirosantilli** [comment]
same: https://github.com/isaacs/github/issues/528
