### ISSUE TITLE
Broken code highlighting for Python 3.5 with type hints

### ISSUE THREAD

**Issue by DheerendraRathor** [isaacs/github#530]
I'm handling a repository with Python code. This repository is based on Python 3.5 which enabled type hints for python. But Github code highlighting tool is unable to correctly highlight that python code. 

An example of incorrect highlighting:
https://github.com/DheerendraRathor/Python-Algorithms/blob/4d53160b23371824ea3e42f16a62cc4a7c92f607/mergesort.py

An example of correct code highlighting:
https://github.com/DheerendraRathor/Python-Algorithms/blob/bf8cae040b02d5892f9fd353a41ba742a79d9ee3/mergesort.py

**Comment by jmarshall** [comment]
GitHub's syntax highlighting is via [github/linguist](https://github.com/github/linguist) and its submodules, which happily tend to be open source and have bug trackers etc.  (In particular, see [CONTRIBUTING#fixing-syntax-highlighting](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting).)

This is atom/language-python#68.

**Comment by cirosantilli** [comment]
Tips:

- make the example more minimal
- link to fixed versions instead of master

**Comment by jmarshall** [comment]
I believe this was fixed by github/linguist#2796.

**Comment by DheerendraRathor** [comment]
Yeah, Now I don't see any problem in code highlighting. Closing now 😄
