### ISSUE TITLE
API issue count

### ISSUE THREAD

**Issue by Mottie** [isaacs/github#536]
There does not appear to be a way to get the actual number of open issues from the API. If I get the [issues from a repository](https://developer.github.com/v3/issues/#list-issues-for-a-repository) it returns a maximum of 30 items. I really don't need all that data, just the number of open issues.

**Comment by Mottie** [comment]
GitHub responded saying it is available, but not from the issues api... 

Get all repos from the user `https://api.github.com/users/:user/repos`, then look for `open_issues_count` in the named repo.

It's still a lot of data to load for a single number, but it works.

**Comment by herkyl** [comment]
Is there any way to get the total issues count or closed issues count?

**Comment by Mottie** [comment]
You can now use GraphQL...

* Go to https://developer.github.com/v4/explorer/
* Log in
* Enter the following to get the open issue count:

    ```
    query { 
      repository(owner:"isaacs", name:"github") { 
        issues(states:OPEN) {
          totalCount
        }
      }
    }
    ```

* Closed count

    ```
    query { 
      repository(owner:"isaacs", name:"github") { 
        issues(states:CLOSED) {
          totalCount
        }
      }
    }
    ```

* Total count

    ```
    query { 
      repository(owner:"isaacs", name:"github") { 
        issues {
          totalCount
        }
      }
    }
    ```

**Comment by herkyl** [comment]
@Mottie thank you so much! This looks very promising 🎉

**Comment by sodik82** [comment]
hi, is there a way to get total issue count with v3 API?

**Comment by KaroHovhannisyan** [comment]
HI, when you get issues by page like `issues?page=0&per_page=5`  `number` property from first element will be count of issues.

**Comment by fuhrmanator** [comment]
> HI, when you get issues by page like `issues?page=0&per_page=5` `number` property from first element will be count of issues.

I think it is not always working... trying it on https://api.github.com/repos/ReactiveX/RxAndroid/issues?page=0&per_page=5 returns an empty response '[  ]' (it's working on other repos).

**Comment by carbontwelve** [comment]
@fuhrmanator that endpoint only returns open issues and because that repo has none it returns an empty array.

I would first check https://api.github.com/repos/ReactiveX/RxAndroid/issues?page=0&per_page=1 and if its an empty array returned then check https://api.github.com/repos/ReactiveX/RxAndroid/issues?page=0&per_page=1&state=closed. Note the `state=closed`, that tells the api you are only interested in closed issues. In both requests I changed the `per_page=1` to be one as you don't need more than one record returned for this method to work.

In either case `response[0]['number']` will equal the issue count regardless of closed/open status.
Neither of these requests will tell you how many open issues there are for a project. For that alternative methods must be used.

**Comment by secsilm** [comment]
> You can now use GraphQL...
> 
> * Go to https://developer.github.com/v4/explorer/
> * Log in
> * Enter the following to get the open issue count:
>   ```
>   query { 
>     repository(owner:"isaacs", name:"github") { 
>       issues(states:OPEN) {
>         totalCount
>       }
>     }
>   }
>   ```
> * Closed count
>   ```
>   query { 
>     repository(owner:"isaacs", name:"github") { 
>       issues(states:CLOSED) {
>         totalCount
>       }
>     }
>   }
>   ```
> * Total count
>   ```
>   query { 
>     repository(owner:"isaacs", name:"github") { 
>       issues {
>         totalCount
>       }
>     }
>   }
>   ```

Thank you! But how to get these done at once?

**Comment by Mottie** [comment]
Combined them:

```
query { 
  repository(owner:"isaacs", name:"github") { 
    open: issues(states:OPEN) {
      totalCount
    }
    closed: issues(states:CLOSED) {
      totalCount
    }
  }
}
```

you'll end up with a result similar to this:

```
{
  "data": {
    "repository": {
      "open": {
        "totalCount": 1317
      },
      "closed": {
        "totalCount": 542
      }
    }
  }
}
```

**Comment by secsilm** [comment]
> Combined them:
> 
> ```
> query { 
>   repository(owner:"isaacs", name:"github") { 
>     open: issues(states:OPEN) {
>       totalCount
>     }
>     closed: issues(states:CLOSED) {
>       totalCount
>     }
>   }
> }
> ```
> 
> you'll end up with a result similar to this:
> 
> ```
> {
>   "data": {
>     "repository": {
>       "open": {
>         "totalCount": 1317
>       },
>       "closed": {
>         "totalCount": 542
>       }
>     }
>   }
> }
> ```

Thank you!
