### ISSUE TITLE
inline username autocomplete is up too high

### ISSUE THREAD

**Issue by chadwhitacre** [isaacs/github#54]
Chrome 27.0.1453.116 / Mac OS 10.6.8

I can't see what I'm typing because the listing is in the way:

![screen shot 2013-07-03 at 12 02 35 pm](https://f.cloud.github.com/assets/134455/744309/03c08a3a-e3fa-11e2-8b7f-570d908dea10.png)

**Comment by clarkbw** [comment]
This has been fixed
