### ISSUE TITLE
Link to Dear Github?

### ISSUE THREAD

**Issue by larsbrinkhoff** [isaacs/github#551]
https://github.com/dear-github/dear-github/

**Comment by cirosantilli** [comment]
Ha, just read it on Reddit as well https://www.reddit.com/r/programming/comments/40ztxe/dear_github/

 Yeah we should. And they should link back as well. Send a PR, or I will do it later.

**Comment by ArtskydJ** [comment]
There is a PR on dear-github to add a link to isaacs/github. See dear-github/dear-github#54 and dear-github/dear-github#66

**Comment by cirosantilli** [comment]
@ArtskydJ nice research!

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by TPS** [comment]
#558 officially merged, just FYI.

**Comment by axd1967** [comment]
I initially wanted to create an issue, but then found this one... So I'll leave my intended issue content here as an indented comment.

> let's join forces, instead divide and reign.
> I have no easy solution, because usually neither side wants to give in...
> see also
> * #551
> * https://github.com/dear-github/dear-github/issues/207

**Comment by MNF** [comment]
Can link to Dear GitHub on readme https://github.com/isaacs/github/blob/master/README.md#see-also be extended with some clarification which repository is recommended to use for new issues - one or another or both?
@maestersid, do you have any preference, which repository to use?
