### ISSUE TITLE
"Download ZIP" to provide the right file rights

### ISSUE THREAD

**Issue by fenollp** [isaacs/github#552]
A project's "Zip Archive"'s files are all chmod +x, while Git supports POSIX permissions…

**Comment by cirosantilli** [comment]
Maybe related to the fact that zip had a late support for permissions apparently http://stackoverflow.com/questions/13633488/can-i-store-unix-permissions-in-a-zip-file-built-with-apache-ant, but would be definitely good.

**Comment by rpiotaix** [comment]
My comment is maybe dumb but why not also provide a tar.gz/bz2/xz/other in addition of zip?

**Comment by fenollp** [comment]
@rpiotaix [There is more than just `zip` support](https://developer.github.com/v3/repos/contents/#get-archive-link)

**Comment by rpiotaix** [comment]
:-o I was not aware of it. Thanks for the link!

**Comment by dagwieers** [comment]
Permissions between .tar.gz and .zip files are different.
Example:
- zip: https://github.com/dagwieers/dstat/archive/0.7.3.zip
- tgz: https://github.com/dagwieers/dstat/archive/0.7.3.tar.gz

```
[dag@moria tmp]$ unzip -Z 0.7.3.zip | grep '/dstat$'
-rwxr-xr-x  2.3 unx    97428 tx defN 16-Mar-18 14:03 dstat-0.7.3/dstat
[dag@moria tmp]$ tar -tvzf 0.7.3.tar.gz | grep '/dstat$'
-rwxrwxr-x root/root     97428 2016-03-18 14:03 dstat-0.7.3/dstat
```

**Comment by fenollp** [comment]
Fixed thanks to @dagwieers's light: use tarballs instead of zipballs.
