### ISSUE TITLE
Social links from the Web back to the project

### ISSUE THREAD

**Issue by fenollp** [isaacs/github#557]
On project page add a column for "Talked About On…" websites, such as HN, reddit, …

That's a good way to learn more about the project, seeing it discussed by the community.

**Comment by cirosantilli** [comment]
Ha, you had quite a list waiting of requests waiting for submission! Great!

Would this be much different than https://github.com/isaacs/github/issues/448 ?

**Comment by fenollp** [comment]
Hehe ;)

Not related to #448 in that it's to automatically put links talking about the project somewhere on the project page.

Somebody talking about your project on Reddit? It'll show up on github.com/you/yourproject on a tab somewhere.

**Comment by cirosantilli** [comment]
I don't understand, isn't that just what https://github.com/isaacs/github/graphs/traffic does, except it is only viewable by collaborators?

**Comment by fenollp** [comment]
Ah yes! You're absolutely right!

If this list is be longer and viewable by all I would be happy happy happy

**Comment by cirosantilli** [comment]
Longer list requested at: https://github.com/isaacs/github/issues/399 Shall we close this?
