### ISSUE TITLE
Cannot send a direct message to a user.

### ISSUE THREAD

**Issue by lemenkov** [isaacs/github#565]
User cannot send a quick direct message to another user even if both of them are mutual followers.

**Comment by cirosantilli** [comment]
Reminds me of GitLab's IM move https://about.gitlab.com/2015/08/18/gitlab-loves-mattermost/

**Comment by oprogramador** [comment]
@lemenkov @cirosantilli @isaacs 

this duplicates https://github.com/isaacs/github/issues/651
