### ISSUE TITLE
BUG: Anchor links do not work in mobile browsers

### ISSUE THREAD

**Issue by hwdsl2** [isaacs/github#577]
On mobile browsers such as Safari/Chrome on iOS, GitHub anchor links to the same page do NOT work. For example, use any mobile browser (e.g. on iOS) to visit https://github.com/jakiestfu/himawari.js , view README.md then try to click on links from table of contents. Nothing happens.

I checked the page sources and noticed that GitHub appends the prefix "user-content-" to every "id" of html elements. I learned that there are javascripts that handle this and make the anchor links work despite the prefix. However it is not working on mobile browsers.

Related: github/markup#716 and github/markup#425

**Comment by kenorb** [comment]
There is no point opening issue here, if there is official repository for reporting that which you've posted the related links. If you still have the problem, report the new issue at [github/markup](https://github.com/github/markup) instead, so this can be closed.

**Comment by hwdsl2** [comment]
Thanks. This has been previously reported at github/markup#870, but got ignored there. Also reported to GitHub Support a few months ago. They acknowledged the problem but never took any action to fix it.

To reproduce the issue, simply use any mobile phone browser to visit https://github.com/jakiestfu/himawari.js/blob/master/README.md and click on the anchor links in the table of contents. Nothing happens.
