### ISSUE TITLE
Configure CNAME with DNS

### ISSUE THREAD

**Issue by jacksonhoyt** [isaacs/github#588]
Hello,

I have been going in circles trying to get my purchased domain name to act as a custom domain for my site github is hosting. This is my first time setting up a web page through github.

I've attached 2 screenshots of my DNS settings. I have configured A records for the following IP addresses as suggested by one help document I found on github:
192.30.252.153
192.30.252.154

The settings were re-saved at least 48 hours ago, after speaking with support@github.com.

The final screenshot is the settings page of my repo, that confirms the CNAME file I created is working and my site will be published at www.mydomain.com

IF YOU KNOW WHAT I'M MISSING, PLEASE HELP!

THANKS!

![screen shot 2016-03-01 at 6 00 06 pm](https://cloud.githubusercontent.com/assets/16477804/13446259/7c5a10ac-dfd7-11e5-88b7-06763e545634.png)

![screen shot 2016-02-29 at 10 34 14 am](https://cloud.githubusercontent.com/assets/16477804/13446191/f4ffcebc-dfd6-11e5-832a-998c0ec2d6cf.png)
![screen shot 2016-02-29 at 10 34 21 am](https://cloud.githubusercontent.com/assets/16477804/13446192/f500ee96-dfd6-11e5-85d3-58fa6edc2cfb.png)

**Comment by jacksonhoyt** [comment]
ISSUE RESOLVED.

Not long after posting this support@github sent some more advice that resolved my issue.

In my DNS settings, I correctly had the A records set up. However, a CNAME record needed to be set up. I completed using the following fields/entries.

NAME: www
TYPE: CNAME
ADDRESS: username.github.io

It was working within 30 minutes of saving my DNS settings.

Hope this helps anyone else finding themselves in my earlier position.

**Comment by TPS** [comment]
@jacksonhoyt You should probably close this.  It won't delete the issue, & can be found easily enough when needed.  Thanks for the detailed reporting!
