### ISSUE TITLE
[bug] Pull Requests aren't updated when their refs are

### ISSUE THREAD

**Issue by strugee** [isaacs/github#591]
I'm trying to rebase a collection of PRs sent to `e14n/pump.io`. Here's what I've done:

1. In the `[remote "origin"]` section of `.git/config`, add `fetch = +refs/pull/*/head:refs/remotes/origin/pr/*`
2. Run `git fetch -a` to download all PR refs from GitHub
3. Run `git checkout origin/pr/1140` to checkout the work being done in PR #1140
4. Run `git rebase master` in order to rebase the commits in the PR on top of the current e14n/pump.io master
5. Run `git push -f origin HEAD:refs/origin/pull/1140/head` in order to force-push the updated commits to the remote PR ref

I know for sure that the commit made it to GitHub's servers, because I can manually visit [the commit URL][1]. However, when I visit the PR, it's not updated to reflect the new, rebased commit. Also, I somehow deleted my `origin/pr/1140` ref and when I re-fetched it, it didn't have the rebased commit.

It is my belief that this is a bug in GitHub or possibly Git. Depending on the expected behavior, GitHub should have either:

* Updated the PR and corresponding ref to reflect the new commit that I force-pushed, or
* Rejected my force-push as being unauthorized.

Thanks.

 [1]: https://github.com/e14n/pump.io/commit/807f148a72dfe8353fc900b87e93d1d621ff13cb

**Comment by strugee** [comment]
From GitHub Support earlier today:

> Hi Alex,
> 
> Thanks for sharing your feedback. I have added this to our list for investigating further. If we have any questions or updates, we'll get back to you.
> 
> Cheers,
> Petros

**Comment by strugee** [comment]
From GitHub Support yesterday:

> Hi Alex,
> 
>  >  It is my belief that this is a bug in GitHub or possibly Git. Depending on the expected behavior, GitHub should have either:
>  >
>  >  * Updated the PR and corresponding ref to reflect the new commit that I force-pushed, or
>  >   * Rejected my force-push as being unauthorized.
> 
> 
> Thanks for your patience while we looked into this a bit. It sounds like the confusion is stemming from what the PR diff is showing.
> 
> We show what's called a "three-dot diff" which is the difference between the latest commit on the HEAD branch and the *last common ancestor commit* with the base branch. So if you forked off of a repo a while ago and things have changed in the parent repo since then, or if you opened a PR from the master branch and then the master branch changes in the meantime, the diff wouldn't show that.
> 
> It sounds like you'd rather see a "two-dot diff", which would show the changes between the two most recent commits on each branch. If you'd like, you can merge the base branch back into the HEAD branch. That updates the last common ancestor and would be more likely to show you what you're expecting to see there.
> 
> As for rejecting the force-push as being unauthorized, the only reason we would do that is if the branch you're force pushing to is protected. You can read more about protected branches here:
> 
> https://help.github.com/articles/about-protected-branches
> 
> Hope that helps clear up some of the confusion!
> 
> All the best,
> Rachel

**Comment by cirosantilli** [comment]
I don't get the GitHub reply.

Your question is that it does not update the PR if you push to the internal  `refs/origin/pull/1140/head` ref rather than the more common `git push origin HEAD:feature-branch` action right?

**Comment by strugee** [comment]
@cirosantilli I don't get it, either.

>Your question is that it does not update the PR if you push to the "internal" `refs/origin/pull/1140/head` ref rather than the more common `git push origin HEAD:feature-branch` action right?

Yep. I'm pushing to the ref because that's contained in the repository I have write access to, but the feature branch is not (since it's a PR, it's in someone else's fork). It's a dirty hack at best, which is why I think that GitHub probably should have rejected the push, although for this particular use-case, it'd be nice if they allowed it.

My impression is that the support person didn't quite understand my bug report. Just sent this off to GitHub:

> On 2016-03-08 22:20, Rachel Berry (GitHub Staff) wrote:
> 
> > Thanks for your patience while we looked into this a bit. It sounds
> > like the confusion is stemming from what the PR diff is showing.
> >
> > We show what's called a "three-dot diff" which is the difference
> > between the latest commit on the HEAD branch and the *last common
> > ancestor commit* with the base branch. So if you forked off of a repo
> > a while ago and things have changed in the parent repo since then, or
> > if you opened a PR from the master branch and then the master branch
> > changes in the meantime, the diff wouldn't show that.
> >
> > It sounds like you'd rather see a "two-dot diff", which would show the
> > changes between the two most recent commits on each branch. If you'd
> > like, you can merge the base branch back into the HEAD branch. That
> > updates the last common ancestor and would be more likely to show you
> > what you're expecting to see there.
> 
> Greetings! Thanks for getting back to me.
> 
> I think you're misunderstanding what I'm saying. This bug isn't about
> what the line-by-line diff shows, it's about what commit SHA1s actually
> show up in the PR.
> 
> I'm a collaborator on e14n/pump.io. There are a bunch of PRs open to
> that repo created by other people, and I'd like to rebase them. In other
> words, I'm trying to modify PRs opened by people other than me, but sent
> to a repo I have write access to.
> 
> > As for rejecting the force-push as being unauthorized, the only reason
> > we would do that is if the branch you're force pushing to is
> > protected. You can read more about protected branches here:
> >
> > https://help.github.com/articles/about-protected-branches
> 
> The reason I thought I maybe should have been rejected is because even
> though I was technically working with *refs* (not branches) in a repo
> that I have write access to, those refs really represent other
> people's work in other people's forks.
>

**Comment by strugee** [comment]
From GitHub Support:

> Hi Alex,
> 
> > I think you're misunderstanding what I'm saying. This bug isn't about
> > what the line-by-line diff shows, it's about what commit SHA1s actually
> > show up in the PR.
> 
> You're right, I didn't quite catch what you were trying to do the first time.
> 
> So this scenario is pretty interesting. You're right that you will be able to push a commit up to the repository that way, but you're pushing to a ref that we use just for the PR metadata.
> +That's also the reason you didn't get a permission denied area, since the *PR ref* is in the repo you have access to, even though the branch the PR is based on isn't.
> 
> The reason that won't update the PR is that we would only ever update the PR if the actual *branch* the PR is opened for changes. In this case, you can't push to that branch because it's
> +someone else's PR, which seems to be why you were trying to push to the PR ref itself instead. I don't think I've ever actually come across someone doing that, so you definitely get points
> +for creativity there :D
> 
> If you're trying to incorporate changes that other people proposed, the easiest way to do that is to fetch down the PR like you did, but then use that to create a new branch. Then open a PR
> +for that new branch with "Closes #1140" in the PR body so that when you merge it, the other one will close. The original committer will still get credit in the repository for their work as
> +well. You can find more information about that process here:
> 
> https://help.github.com/articles/checking-out-pull-requests-locally/#modifying-an-inactive-pull-request-locally
> 
> Hope that helps clear things up!
> 
> All the best,
> Rachel
>

**Comment by strugee** [comment]
And my response:

> On Mon, Mar 14, 2016 at 09:20:21AM -0700, Rachel Berry (GitHub Staff) wrote:
> 
> > So this scenario is pretty interesting. You're right that you will be able to push a commit up to the repository that way, but you're pushing to a ref that we use just for the PR metadata. \
> That's also the reason you didn't get a permission denied area, since the *PR ref* is in the repo you have access to, even though the branch the PR is based on isn't.
> >
> > The reason that won't update the PR is that we would only ever update the PR if the actual *branch* the PR is opened for changes. In this case, you can't push to that branch because it's so\
> meone else's PR, which seems to be why you were trying to push to the PR ref itself instead. I don't think I've ever actually come across someone doing that, so you definitely get points for \
> creativity there :D
> 
> Heh, thanks :)
> 
> > If you're trying to incorporate changes that other people proposed, the easiest way to do that is to fetch down the PR like you did, but then use that to create a new branch. Then open a PR\
>  for that new branch with "Closes #1140" in the PR body so that when you merge it, the other one will close. The original committer will still get credit in the repository for their work as w\
> ell. You can find more information about that process here:
> 
> Yeah, I knew I could create a new branch, but I figured I'd try to keep it in the same PR. Seemed more elegant.
> 
> Since the refs thing won't work, I'll just go ahead and do it the normal way.
> 
> > https://help.github.com/articles/checking-out-pull-requests-locally/#modifying-an-inactive-pull-request-locally
> 
> Thanks. So the "tips" section at the bottom of that page says:
> 
> > The remote refs/pull/ namespace is read-only. If you try to push any commits there, you'll see this error:
> >
> >     ! [remote rejected] HEAD -> refs/pull/1/head (deny updating a hidden ref)
> >     error: failed to push some refs to 'git@github.local:USERNAME/REPOSITORY.git'
> 
> Unless this behavior was implemented since I submitted this request, there seems to be a bug. Since I didn't get that message.
> 
> (As an aside, that says `github.local`, not `github.com`.)

**Comment by strugee** [comment]
From GitHub Support:

> Hi Alex,
> 
>  > Unless this behavior was implemented since I submitted this request, there seems to be a bug. Since I didn't get that message.
> 
> Hmmm, that is interesting... Is there any chance you could reproduce that by trying to push to that branch again? If you can, a copy/paste of the full commands and output would be super helpful :) If not, no worries!
> 
> Thanks,
> Rachel

**Comment by strugee** [comment]
And my monstrosity of a reply:

On Thu, Mar 17, 2016 at 04:46:33PM -0700, Rachel Berry (GitHub Staff) wrote:

> Hmmm, that is interesting... Is there any chance you could reproduce that=
 by trying to push to that branch again? If you can, a copy/paste of the fu=
ll commands and output would be super helpful :) If not, no worries!

Sure thing!

    % uname -a # Just in case
    Darwin Alexs-MacBook-Pro 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
    
    % git --version
    git version 2.7.2
   
    % git clone git@github.com:e14n/pump.io.git
    Cloning into 'pump.io'...
    remote: Counting objects: 19844, done.
    remote: Total 19844 (delta 0), reused 0 (delta 0), pack-reused 19843
    Receiving objects: 100% (19844/19844), 8.67 MiB | 1.93 MiB/s, done.
    Resolving deltas: 100% (12526/12526), done.
    Checking connectivity... done.
   
    % cd pump.io
   
    % nano .git/config
   
    % cat .git/config
    [core]
    	repositoryformatversion = 0
    	filemode = true
    	bare = false
    	logallrefupdates = true
    	ignorecase = true
    	precomposeunicode = true
    [remote "origin"]
    	url = git@github.com:e14n/pump.io.git
    	fetch = +refs/heads/*:refs/remotes/origin/*
    	fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
    [branch "master"]
    	remote = origin
    	merge = refs/heads/master
    	rebase = true
   
    % git fetch -a
    remote: Counting objects: 1113, done.
    remote: Total 1113 (delta 556), reused 556 (delta 556), pack-reused 557
    Receiving objects: 100% (1113/1113), 3.14 MiB | 1.67 MiB/s, done.
    Resolving deltas: 100% (682/682), completed with 218 local objects.
    From github.com:e14n/pump.io
     * [new ref]         refs/pull/1001/head -> origin/pr/1001
     * [new ref]         refs/pull/1006/head -> origin/pr/1006
     * [new ref]         refs/pull/1007/head -> origin/pr/1007
     * [new ref]         refs/pull/1013/head -> origin/pr/1013
     * [new ref]         refs/pull/1024/head -> origin/pr/1024
     * [new ref]         refs/pull/1040/head -> origin/pr/1040
     * [new ref]         refs/pull/1046/head -> origin/pr/1046
     * [new ref]         refs/pull/1047/head -> origin/pr/1047
     * [new ref]         refs/pull/1058/head -> origin/pr/1058
     * [new ref]         refs/pull/1065/head -> origin/pr/1065
     * [new ref]         refs/pull/1073/head -> origin/pr/1073
     * [new ref]         refs/pull/1086/head -> origin/pr/1086
     * [new ref]         refs/pull/1088/head -> origin/pr/1088
     * [new ref]         refs/pull/1089/head -> origin/pr/1089
     * [new ref]         refs/pull/1106/head -> origin/pr/1106
     * [new ref]         refs/pull/1111/head -> origin/pr/1111
     * [new ref]         refs/pull/1112/head -> origin/pr/1112
     * [new ref]         refs/pull/1113/head -> origin/pr/1113
     * [new ref]         refs/pull/1114/head -> origin/pr/1114
     * [new ref]         refs/pull/1119/head -> origin/pr/1119
     * [new ref]         refs/pull/1125/head -> origin/pr/1125
     * [new ref]         refs/pull/1126/head -> origin/pr/1126
     * [new ref]         refs/pull/1129/head -> origin/pr/1129
     * [new ref]         refs/pull/1134/head -> origin/pr/1134
     * [new ref]         refs/pull/1135/head -> origin/pr/1135
     * [new ref]         refs/pull/1136/head -> origin/pr/1136
     * [new ref]         refs/pull/1138/head -> origin/pr/1138
     * [new ref]         refs/pull/1139/head -> origin/pr/1139
     * [new ref]         refs/pull/1140/head -> origin/pr/1140
     * [new ref]         refs/pull/1144/head -> origin/pr/1144
     * [new ref]         refs/pull/1146/head -> origin/pr/1146
     * [new ref]         refs/pull/1147/head -> origin/pr/1147
     * [new ref]         refs/pull/1148/head -> origin/pr/1148
     * [new ref]         refs/pull/1149/head -> origin/pr/1149
     * [new ref]         refs/pull/384/head -> origin/pr/384
     * [new ref]         refs/pull/396/head -> origin/pr/396
     * [new ref]         refs/pull/427/head -> origin/pr/427
     * [new ref]         refs/pull/491/head -> origin/pr/491
     * [new ref]         refs/pull/493/head -> origin/pr/493
     * [new ref]         refs/pull/498/head -> origin/pr/498
     * [new ref]         refs/pull/533/head -> origin/pr/533
     * [new ref]         refs/pull/546/head -> origin/pr/546
     * [new ref]         refs/pull/550/head -> origin/pr/550
     * [new ref]         refs/pull/573/head -> origin/pr/573
     * [new ref]         refs/pull/590/head -> origin/pr/590
     * [new ref]         refs/pull/591/head -> origin/pr/591
     * [new ref]         refs/pull/598/head -> origin/pr/598
     * [new ref]         refs/pull/625/head -> origin/pr/625
     * [new ref]         refs/pull/630/head -> origin/pr/630
     * [new ref]         refs/pull/631/head -> origin/pr/631
     * [new ref]         refs/pull/636/head -> origin/pr/636
     * [new ref]         refs/pull/641/head -> origin/pr/641
     * [new ref]         refs/pull/645/head -> origin/pr/645
     * [new ref]         refs/pull/647/head -> origin/pr/647
     * [new ref]         refs/pull/648/head -> origin/pr/648
     * [new ref]         refs/pull/682/head -> origin/pr/682
     * [new ref]         refs/pull/696/head -> origin/pr/696
     * [new ref]         refs/pull/697/head -> origin/pr/697
     * [new ref]         refs/pull/705/head -> origin/pr/705
     * [new ref]         refs/pull/709/head -> origin/pr/709
     * [new ref]         refs/pull/726/head -> origin/pr/726
     * [new ref]         refs/pull/740/head -> origin/pr/740
     * [new ref]         refs/pull/747/head -> origin/pr/747
     * [new ref]         refs/pull/749/head -> origin/pr/749
     * [new ref]         refs/pull/757/head -> origin/pr/757
     * [new ref]         refs/pull/791/head -> origin/pr/791
     * [new ref]         refs/pull/807/head -> origin/pr/807
     * [new ref]         refs/pull/815/head -> origin/pr/815
     * [new ref]         refs/pull/824/head -> origin/pr/824
     * [new ref]         refs/pull/829/head -> origin/pr/829
     * [new ref]         refs/pull/842/head -> origin/pr/842
     * [new ref]         refs/pull/850/head -> origin/pr/850
     * [new ref]         refs/pull/853/head -> origin/pr/853
     * [new ref]         refs/pull/863/head -> origin/pr/863
     * [new ref]         refs/pull/867/head -> origin/pr/867
     * [new ref]         refs/pull/869/head -> origin/pr/869
     * [new ref]         refs/pull/870/head -> origin/pr/870
     * [new ref]         refs/pull/871/head -> origin/pr/871
     * [new ref]         refs/pull/880/head -> origin/pr/880
     * [new ref]         refs/pull/882/head -> origin/pr/882
     * [new ref]         refs/pull/888/head -> origin/pr/888
     * [new ref]         refs/pull/891/head -> origin/pr/891
     * [new ref]         refs/pull/892/head -> origin/pr/892
     * [new ref]         refs/pull/893/head -> origin/pr/893
     * [new ref]         refs/pull/902/head -> origin/pr/902
     * [new ref]         refs/pull/903/head -> origin/pr/903
     * [new ref]         refs/pull/906/head -> origin/pr/906
     * [new ref]         refs/pull/909/head -> origin/pr/909
     * [new ref]         refs/pull/911/head -> origin/pr/911
     * [new ref]         refs/pull/926/head -> origin/pr/926
     * [new ref]         refs/pull/984/head -> origin/pr/984
     * [new ref]         refs/pull/989/head -> origin/pr/989
     * [new ref]         refs/pull/991/head -> origin/pr/991
     * [new ref]         refs/pull/995/head -> origin/pr/995
     * [new ref]         refs/pull/997/head -> origin/pr/997
     * [new ref]         refs/pull/998/head -> origin/pr/998
     * [new ref]         refs/pull/999/head -> origin/pr/999
    
    % git checkout origin/pr/1140 # A random open PR
    Note: checking out 'origin/pr/1140'.
   
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
   
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
   
      git checkout -b <new-branch-name>
   
    HEAD is now at b5311e4... Small fix in CSS, to break long contents in multiple lines
   
    % git rebase master
    First, rewinding head to replay your work on top of it...
    Applying: Small fix in CSS, to break long contents in multiple lines
   
    % git push -f origin HEAD:refs/origin/pull/1140/head # Note that I pass -f
    Counting objects: 5, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (3/3), done.
    Writing objects: 100% (5/5), 506 bytes | 0 bytes/s, done.
    Total 5 (delta 4), reused 2 (delta 2)
    To git@github.com:e14n/pump.io.git
     + 807f148...056a625 HEAD -> refs/origin/pull/1140/head (forced update)
    
    % git push origin HEAD:refs/origin/pull/1140/head
    Everything up-to-date

**Comment by JeremyWeir** [comment]
Was there any resolution to this?

**Comment by strugee** [comment]
Whoops, sorry! Totally forgot to post the reply from GitHub Support. Here it is, from March 17th, 2016:

> Hi Alex,
> 
> So this was a fun one! I spoke with one of our Git engineers about this, and I learned a thing or two as well. Happy to pass on my learnings!
> 
> So when you ran this command:
> 
> `git push -f origin HEAD:refs/origin/pull/1140/head`
> 
> you used `HEAD` as your source and `refs/origin/pull/1140/head` as your destination. That destination designation doesn't quite do what we though it does though, because the dest. is supposed to be from the perspective of the *remote*, and you had it written out from the perspective of the *local* repository.
> 
> (As a side note, my colleague pointed out that the local perspective was also a bit off, it would have been `refs/remotes/origin/pull/1140/head`, with `remotes` added in.)
> 
> Since you needed the dest. to be from the remote perspective, the command would have been:
> 
> `git push origin HEAD:refs/pull/1140/head`
> 
> And *that* version should definitely be rejected :D
> 
> So it turns out that you pushed to a somewhat random spot in the remote repo that wasn't really related to the PR at all. We don't block pushing to arbitrary refs because we don't really need to, so your push went through just fine.
> 
> Hope that clears up some of the confusion! And thanks for the learning opportunity!
> 
> All the best,
> Rachel
