### ISSUE TITLE
SMTP Configuration using Powershell in Windows 2012 server

### ISSUE THREAD

**Issue by ankush-ain** [isaacs/github#595]
I want to develop a power shell script for widows server 2012 that I can install at startup so once anyone power it up the SMTP configuration for email in outlook is automatically done....

**Comment by ankush-ain** [comment]
need to configure outbound security, check the TLS encryption, Configure the outbound Connection, setting TCP port as 587
Also the advance button configuration in Delivery tab. fullqualified domain name as "smtp.gmail.com" and enter the Smart host field <TLS Enabled Mail Relay>

**Comment by cirosantilli** [comment]
github questions only please
