### ISSUE TITLE
Github Search should search in private repositories as well

### ISSUE THREAD

**Issue by emrehan** [isaacs/github#599]
https://github.com/search doesn't search in private repositories of the logged in user. But it should.

**Comment by TPS** [comment]
I _think_ adding `is:private` to that box will allow 1 to search only the accessible private repos, but, if so, this should be exposed, & is still missing a combined public/private search.

**Comment by emrehan** [comment]
It seems like it's working even without that flag now

**Comment by TPS** [comment]
If this can be confirmed, close & take the win!  :smiley:

**Comment by emrehan** [comment]
It's confirmed, I'm closing this!
