### ISSUE TITLE
Change the target branch of a pull request

### ISSUE THREAD

**Issue by dideler** [isaacs/github#604]
This is a duplicate of #18, which is no longer viewable. It has 1400+ comments and the request times out.

**Comment by TPS** [comment]
@isaacs @cirosantilli @all Is there anything you all can do to close #18 in favor of this?

**Comment by cirosantilli** [comment]
@TPS I can't view that either, 500. I'm very curious to what happened to it. Not on wayback machine either.

**Comment by TPS** [comment]
It still officially exists in the _listing_ (https://github.com/isaacs/github/issues?page=19&q=is%3Aissue+is%3Aopen as of right now),  but it looks like the 1300 or so :+1:  posts killed something on the @Github backend, if I had to guess.…

**Comment by cirosantilli** [comment]
@TPS lol, GitHub is no paging comments. I'm so gonna try this out with the comments API.

**Comment by TPS** [comment]
For the record, Github doesn't page most webpages, e.g., https://github.com/cirosantilli?tab=repositories.  Is there an issue someplace for that? Else, make 1 & move this (off-topic) discussion there?

**Comment by cirosantilli** [comment]
@TPS the repository tabs limits repos, and if you click show all it paginates.

We should make an issue for that, but I'm lazy, feel free to. I'd rather produce an example with a script first for maximum effect :-)

#370 may have been different, I think the problem was calculating stuff internally, now displaying too much of it.

**Comment by Mottie** [comment]
That is interesting... GitHub does collapse very long timelines - see `https://github.com/nodejs/node/pull/5020#issuecomment-178095373`.

![2016-03-12 11_07_34-adding core support for promises by chrisdickinson pull request 5020 nodejs](https://cloud.githubusercontent.com/assets/136959/13724183/b4e75d3a-e842-11e5-9c3a-a836daaed405.png)


Did anyone report this problem to GitHub?

**Comment by Mottie** [comment]
So GitHub is aware of the problem of not being able to load issue 18. Interestingly, you can load the page if you aren't logged into GitHub. It's mostly a wall of +1's.

**Comment by TPS** [comment]
@dideler @cirosantilli @Mottie I filed #640 (& GitHub response) to fix #18's root meta-problem. ☺

**Comment by TPS** [comment]
@dideler @cirosantilli @isaacs Now that #18 is again visible via @GitHub implementing issue-comment-collapsing via <kbd>1546 items not shown
View more</kbd>, can we close to not fragment the issue further?
