### ISSUE TITLE
Allow videos to be attached (and previewed) to issues

### ISSUE THREAD

**Issue by markbao** [isaacs/github#606]
I use videos a lot to show bugs and it's really annoying to have to upload to a third party and then add a link. It'd be much better, both for submitters and triagers, to allow videos to be uploaded directly to an issue, like images, and to be previewed in an HTML5 container. Maybe GitHub doesn't want to do the video processing necessary for that, but at least let us attach videos that people can download.

**Comment by anko** [comment]
Workaround: [record GIFs](http://unix.stackexchange.com/q/113695/16404).

**Comment by markbao** [comment]
Yep! Sometimes works, but often gifs aren't high enough resolution and are too choppy... workable for now though.

**Comment by Pzixel** [comment]
@anko you probably have never tried to watch 600mb gif which is just 10mb MP4 video after convertation...

**Comment by Pikamander2** [comment]
+1 to this

I'm amazed that Github still doesn't support attaching MP4 files.

**Comment by kush-daga** [comment]
Probably a solution that should be implemented to this would be to automatically convert an mp4 file to GIF (trim to first 6 seconds) while uploading automatically.

**Comment by TPS** [comment]
This is now in public beta per https://github.blog/changelog/2020-12-16-video-upload-public-beta/!

**Comment by TPS** [comment]
Per the note below attached to the comment boxes, I assume this is out of beta. ![GitHub Videos Note](https://user-images.githubusercontent.com/185902/103970047-4f457280-5135-11eb-835b-26ae0f1f2abe.png)
