### ISSUE TITLE
Provide web-upload function.

### ISSUE THREAD

**Issue by espress0** [isaacs/github#609]
1. Some people don't want to install git.
2. Sourceforge.com and bitbucket.com allow users to upload their data directly from webpage.
3. [Bitbucket - Download section] Owner can select a file and click upload. So simple.

**Comment by Pablo-Ivan** [comment]
@espress0 I'm glad to tell you...now this is possible!

**Comment by espress0** [comment]
> now this is possible!

Care to provide a source? (how to do it?)

**Comment by Pablo-Ivan** [comment]
![the github blog github 19_03_2016 10_25_10 p m](https://cloud.githubusercontent.com/assets/10409758/14072121/e69e4742-f479-11e5-8de8-f4c1e164588b.png)

**Comment by Pablo-Ivan** [comment]
![isaacs_node-glob_ glob functionality for node js 28_03_2016 12_13_10 a m](https://cloud.githubusercontent.com/assets/10409758/14072124/f0786612-f479-11e5-9dcd-d4f05c2b25bc.png)

**Comment by Pablo-Ivan** [comment]
See? Right to the New File button, there is the Upload files button

**Comment by espress0** [comment]
> New File button

Oh... looks like Github added it recently... Thanks.
