### ISSUE TITLE
Support custom (per repository) og:image thumbnails.

### ISSUE THREAD

**Issue by bvaughn** [isaacs/github#612]
### **Edit** Please upvote this issue with a 👍rather than leave a "+1" comment. GitHub [sorts issues by reactions and not by the number of comments](https://github.com/isaacs/github/issues/612#issuecomment-375159258).

Github currently sets the `twitter:image:src` and `og:image` meta tags for each of my repositories to be that of my main profile picture. This seems like a reasonable default. But it would be useful if there were a way to override this setting on a per-repository basis. (Perhaps a convention that uses a specially-named file in the root of a repository? Or something in the project settings?)

It's a minor issue but it would be nice when I share a link to a new version release on sites like Twitter, Reddit, etc. if the thumbnail was a project logo rather than my profile picture.

I realize that I can _sometimes_ link to my own `gh-pages` branch and set any meta tags I want but I usually prefer the simplicity of linking directly to the GH repository landing page. Other times it's not even an option, like when linking to a wiki page with upcoming release notes ([example](https://github.com/bvaughn/react-virtualized/wiki/Version-6-Roadmap)).

**Comment by edgr-sanchez** [comment]
Great idea

**Comment by itaibh** [comment]
Not only this is a great idea, I don't think this is a reasonable default.

**Comment by zzgab** [comment]
Any update about this great feature request?

**Comment by edgr-sanchez** [comment]
Also wondering if there's been any development on this. I like having a profile photo of myself but it's a bit weird when I share a link to a repository and it shows a huge thumbnail of my face.

**Comment by zzgab** [comment]
All I could come up with, is making a *gh-pages* branch for my project https://github.com/zzgab/uiwebagent 
This *gh-pages* contains an *index.html* file in which I declare the <meta> that I like (useful for FB og, Twitter etc.) but then the body only forces a JS redirect to the GitHub master repository...
Not happy with this workaround...

**Comment by hdjirdeh** [comment]
I think this would be a great idea, and I agree, that is a bit much of a workaround @zzgab

**Comment by edgar-sanchez-is** [comment]
There really should be a place within the repo settings to assign a repo thumbnail just like you can for organization pages or profile pages.

**Comment by theiliad** [comment]
Any updates here?

**Comment by JustineWin** [comment]
I guess a custom og: still isn't available. Tried creating a new website this week and put all those og: meta tags but nothing works :D Still hoping github considers this feature :)

**Comment by i-h** [comment]
Seconding this, posting with a collaborator's (who made the repository) face on Twitter feels kind of rude.

**Comment by edgariscoding** [comment]
Is there any development on this? Even a simple setting to disable the use of a custom thumbnail altogether would be sufficient in the meantime.

**Comment by lucidvillain666** [comment]
pls gitahubb do dis 4 us

**Comment by daattali** [comment]
Great idea!

**Comment by haideralipunjabi** [comment]
This should be added ASAP

**Comment by chetcuti** [comment]
Yes please.

**Comment by Almenon** [comment]
this would be a very nice feature.

**Comment by michaelashore** [comment]
This feature would be great and I suspect would encourage more sharing of repos across Facebook and Twitter.

**Comment by clarkbw** [comment]
> Perhaps a convention that uses a specially-named file in the root of a repository? Or something in the project settings?

@bvaughn So you'd be ok to set a specific repository image? Perhaps it might default to your user image as it does now if not already set.

(this is a mockup, just wanted clarify; no promises)

<img width="1012" alt="screen shot 2017-11-13 at 7 52 02 pm" src="https://user-images.githubusercontent.com/2134/32762115-456cd63c-c8ac-11e7-96e0-9f1ebaf92df2.png">

**Comment by edgariscoding** [comment]
>So you'd be ok to set a specific repository image? Perhaps it might default to your user image as it does now if not already set.

>(this is a mockup, just wanted clarify; no promises)

@clarkbw I'm not speaking for @bvaughn but yes, that would be amazing.

**Comment by bvaughn** [comment]
Hey @clarkbw! Nice to hear from you. 😄

Honestly, I would be okay with almost _any_ way to do this. An option in the project settings area would be great. That seems the most backwards-friendly way of approaching this, and avoids bloating the repo with an unnecessary image file. 👍

**Comment by spcfran** [comment]
Can I have this for Xmas? Trying to add a link to a repo to my LinkedIn profile for showcase/portfolio purposes and my face is all over it! 😅 

+1 for the project scoped setting rather than a file in the repo - it's a very 'meta' thing after all

**Comment by zzgab** [comment]
@spcfran All in all, despite its tweaky-tricky-hacky aspect, we've got nothing but my workaround here : https://github.com/isaacs/github/issues/612#issuecomment-247837278
I've been using it successfully all this time, but it's a pain in the back.

**Comment by edgariscoding** [comment]
@zzgab that’s a pretty clever workaround. The bad thing is that it only works for the repo owner because other people sharing the repo won’t care to jump through hoops, they’ll just share the direct link to the repo.

Does anyone know if Github actually confirms when they’re working on a new feature before it’s released?

**Comment by zzgab** [comment]
@edgariscoding You're right.

**Comment by clarkbw** [comment]
Can this issue be labeled `social` or something similar? Categorizing these issues really helps with the clutter.  kthx!

**Comment by valentinchrt** [comment]
It would be great @clarkbw, really. 
Tell us that this feature will be release soon! 🎁

**Comment by edgariscoding** [comment]
@clarkbw, is setting a label on this issue something that @bvaughn can do or were you commenting so that someone with admin rights on the repo can do it?

**Comment by clarkbw** [comment]
> commenting so that someone with admin rights on the repo can do it?

It requires admin rights which I don't have and I don't believe @bvaughn has either.  I emailed @isaacs about it a while ago but I never heard back 😭

**Comment by clarkbw** [comment]
And FYI, I don't have anyone actively working on this right now.  I'm hoping to convince the marketing team to pick this up with some other work they are planning for the coming year. We'll see.

**Comment by KelvinShadewing** [comment]
Gah, marketing always gets in the way of useful development. Ironic here, since the target audience is developers. XP I, too, would love to have this feature. It would certainly help repos stand out from one another, especially if someone has a bunch of them in one account.

**Comment by shangyilim** [comment]
+1 on this idea as well. Would love to show some more interesting thumbnail pictures, rather than my profile picture.

**Comment by actuallyaswin** [comment]
@KelvinShadewing this is important for developers too! When sharing your Github projects with recruiters or employers, you'll want the metadata to look nice and fancy. Same goes with sharing projects on Facebook or Twitter!

**Comment by KelvinShadewing** [comment]
@actuallyaswin Which is exactly why we need per-repo thumbnails.

**Comment by edgariscoding** [comment]
Maybe we should go to different developer communities and forums and ask them what they think and to come comment if they agree.

**Comment by ahsouza** [comment]
We need this!
My situation to have this feature is when we add our repositories on LinkedIn media and is boring see all links with same image (user avatar)

**Comment by lucasmafra** [comment]
This is a really important feature! Any updates on that?

**Comment by igalbn** [comment]
During write post on LinkedIn. When attaching the link to repository. LinkedIn show as thumbnail my big and streched photo. Instead prefer, use image of my program.

**Comment by izgeri** [comment]
Just popping by to join the chorus and say it would be great if this feature were added! I don't love seeing my face in my tweets about my gh repo - I wish I could set a repo-specific image to use instead!

**Comment by clarkbw** [comment]
Thanks for the feedback here!

Friendly reminder to always 👍 the first comment (I don't know if you also did that @izgeri) because I sort these issues by reaction and not by most commented.

**Comment by iamciera** [comment]
I also would LOVE to have this feature.

**Comment by edgariscoding** [comment]
Make sure to “like” the main post


Edgar Sanchez

Sent from my iPhone

On Mar 23, 2018, at 4:15 PM, Ciera Martinez <notifications@github.com<mailto:notifications@github.com>> wrote:


I also would LOVE to have this feature.

**Comment by mikedeshazer** [comment]
PLEASE. To this feature

**Comment by jmarshall** [comment]
> Perhaps a convention that uses a specially-named file in the root of a repository? Or something in the project settings?

:+1: but definitely via something in the project settings. Using a specially-named file in the repository would mean that your image was automatically propagated to other people's forks, which would often not be desirable.

**Comment by edgariscoding** [comment]
@jmarshall good point regarding the image being automatically propagated to other people's forks. I think a setting in project settings would be ideal.

**Comment by itaibh** [comment]
I don't see the problem with it being propagated to other forks. After all,
the thumbnail needs to represent the repo, not the user, so copying the
repo icon seems like a reasonable default.

**Comment by jmarshall** [comment]
@itaibh: There's a number of possibilities as to what different projects might want a thumbnail to represent:

* A customised personal or institutional avatar. Must not be automatically propagated to other forks, just as today's user or organisation avatar is not.

* A project logo with a firefox/iceweasel trademark situation. If it's automatically propagated to other forks, the original org will choose not to use this facility.

* An unencumbered logo representing the project. Propagation to other forks would be acceptable in this case, though make it harder to recognise the canonical source at a glance.

A file in the repo is pretty much all or nothing. A project setting allows for an implementation where (1) on forking, the new forker is asked whether to propagate the source custom avatar — provided (2) the source fork has not set the do-not-propagate-avatar option. That sort of complexity would be needed to handle all the possibilities I've listed.

**Comment by KelvinShadewing** [comment]
The only way to reliably verify canon is to look at the URL the project is hosted at, so you might as well leave the file in the repo. Though for browsing, you could have the user's icon appear in the lower corner for a quicker identifier. Maybe GitHub could generate a thumbnail with an icon overlay for use in OG tags.

**Comment by 0biWanKenobi** [comment]
Please, pretty please do this GitHub team ❤️

**Comment by AnthumChris** [comment]
What about specifying images in `.gitattributes` file similar to how we already [configure Linguist using gitattributes](https://github.com/github/linguist#using-gitattributes)? This could offer better scalability as preview image specs change:

```
images/logo-200x200.png preview-image=twitter-small
images/logo-600x300.png preview-image=twitter-large
images/logo-1200x630.png preview-image=facebook
images/logo-1200x627.png preview-image=linkedin
```

**Comment by edgariscoding** [comment]
Love this idea

**Comment by nonoesp** [comment]
Looking forward to using this when it's implemented!

**Comment by v-braun** [comment]
Could not wait longer for this feature ☺️

Inspired by @zzgab *proxy page* solution, I built a webapp on that!  
- webapp: [share-my-repo](https://share-my-repo.vibr.app/)  
- source: [v-braun/share-my-repo]/https://github.com/v-braun/share-my-repo

I hope this is only a temporary solution and we could get one of the above ideas implemented.

**Comment by matmiranda** [comment]
Until today they did not solve?

**Comment by Luc45** [comment]
Any news on this?

**Comment by JoGall** [comment]
Fed up of seeing my face every time I link to a repo on Twitter; would love to see this implemented!

**Comment by rsodre** [comment]
come on!! Let's us configure it at least...

**Comment by Paulinakhew** [comment]
I would love to see this change happen!

**Comment by benoit-dumas** [comment]
A quick and dirty solution would be great too. We really need that one.

**Comment by sblunt** [comment]
Pretty please!

**Comment by TonyMezzolesta** [comment]
Just hit this myself.  Went to share a repo on LinkedIn and got my profile picture.  Googled how to do it and came across this.  Would like to also request this feature.

**Comment by zzgab** [comment]
@tonymezzolesta, @sblunt, did you +1 on the initial post? This is the only way to make it go up in GH's todo list.
Thx!

**Comment by sblunt** [comment]
Yup.

**Comment by TonyMezzolesta** [comment]
Yeppers

**Comment by Luc45** [comment]
## Microsoft owns GitHub, and they do not look at this issue.

We must focus our effort on the right place to get answers from them.

https://github.community/

If someone create a topic there, let me know and I will update this link pointing to it.

**Comment by clarkbw** [comment]
> Microsoft owns GitHub, and they do not look at this issue.

This isn’t true. I watch this entire repo and participate here.

We’ve made progress on a prototype for this, it’s not my team working on it so I don’t have a good date when we might see the solution roll out.

**Comment by TonyMezzolesta** [comment]
@clarkbw Thank you for responding to this issue thread.  Please pass along a heartfelt thank you to the team currently working on adding this feature.  Much appreciated.

**Comment by drewswaycool** [comment]
Need this also. Here's my... +1.

**Comment by espinielli** [comment]
Do it! Please

**Comment by michaelmoussa** [comment]
> Using a specially-named file in the repository would mean that your image was automatically propagated to other people's newly-created forks, which would often not be desirable.

What about baking this into the naming convention of the file, e.g. `.github/og-image.<user/organization name>.png`?

Let's take the repository we're all discussing in right now as an example: `isaacs/github`.

* Link to https://github.com/isaacs/github shared:
    * Display `.github/og-image.isaacs.png` if it exists.
    * Display giant picture of his head if it doesn't.

* Link to https://github.com/<user-who-forked-it>/github shared:
    * Display `.github/og-image.<user-who-forked-it>.png` if it exists.
    * Display giant picture of the user who forked it if it doesn't.

This prevents preview images from propagating to forks, keeps the current default behavior for what forks display, and gives forks the ability to add their own preview image.

**Comment by zzgab** [comment]
@michaelmoussa Nice! But then the forks would contain the parent's pic file too?

**Comment by michaelmoussa** [comment]
@zzgab Yes, but forks contain the parent's `CONTRIBUTING.md`, `LICENSE.md`, `ISSUE_TEMPLATE.md`, `PULL_REQUEST_TEMPLATE.md`, etc., already anyway, so I wouldn't consider propagating a teaser image to be a problem.

**Comment by rsodre** [comment]
What about as simple as Repository Settings, Add Thumbnail?

**Comment by hzoo** [comment]
Intial support is out now: https://twitter.com/github/status/1118562875830882304

https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/

**Comment by zzgab** [comment]
Congrats! Thanks. Let's see!!

**Comment by clarkbw** [comment]
Thanks for all the excellent feedback that helped make this!  💥 

If you have additional features you'd like to see on top of this or in addition please try to open a new issue and link back to this.  If you have feedback or find bugs you can leave comments directly in here or contact support directly via the link 👇

**Comment by JayShoe** [comment]
I like that we can set a custom image for a "og:image" metatag. 

But what about setting a custom "project image" that would be featured at the top of the repository, as the "main project photo" or "logo"...???

**Comment by N02870941** [comment]
Is there a public API for this so I can reference these photos in an app that currently consumes the GitHub user repo API?

**Comment by remorses** [comment]
i am also searching for an api to get the repo image

**Comment by dan-ignat** [comment]
The `og:image` functionality works great, but not on mobile devices.

I sent a URL to a GitHub repo (which has an image set in its _Settings_) from one iPhone to another, and it didn't unfurl.  I dug into it a bit, and in Chrome I used DevTools to [view my GitHub repo as a mobile device](https://superuser.com/questions/1214829/how-can-i-view-the-mobile-version-of-a-webpage-in-google-chrome-for-desktop).  This let me view the source, and I confirmed that the `og:*` tags do **not** appear in the HTML sent to clients by the **mobile** GitHub site.  (I also did a negative test, to confirm that the tags **do** appear on the non-mobile GitHub site.)

So this means that any repo links sent on mobile devices will not unfurl.

**Comment by overclockedllama** [comment]
@N02870941 @remorses 
Hi
It is not too difficult to scrape this with node using axios and cheerio:
```js
let url = repo.html_url; // <- this is the URL of your repo
axios(url).then((response => {
    const html = response.data;
    const $ = cheerio.load(html);
    const metas = $("meta");
    for (let i = 0; i < metas.length; i++) {
        const meta = metas[i];
        if (meta.attribs.property == "og:image") {
            let value = meta.attribs.content; // <- this is the url for the og:image
        }
    }
}))
```

Additionally, it would be really handy to have support for og:image in mobile. I find it pretty annoying that the og:image doesn't render properly on mobile messaging platforms such as iMessage, @isaacs any update on this?

**Comment by akibrhast** [comment]
Hello, I added an image to one of my github repos, but its not unfurling anywhere. But when I used the templated image provided. It instantly unfurls everywhere. Is there some kind of processing delay when I upload my own image.
