### ISSUE TITLE
Add @TPS as a collaborator

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#619]
@isaacs  @TPS

And ping for: https://github.com/isaacs/github/issues/459

**Comment by TPS** [comment]
As you said when you were nominated, @cirosantilli, _that_ I hafta :+1:, but :blush:!

**Comment by TPS** [comment]
Thanks for the support, @Mottie. ☺

**Comment by cirosantilli** [comment]
I've also tried to email @isaacs public email today i@izs.me

Hopefully it does not go to `/dev/null` :-)

**Comment by TPS** [comment]
Thanks, @Isaacs!  & for the support, @Cirosantilli @Mottie @All!
