### ISSUE TITLE
Improve discovery of forks

### ISSUE THREAD

**Issue by jcrben** [isaacs/github#621]
I submitted this message to support just now:

> Have you guys seen this blog post? http://zbowling.github.io/blog/2011/11/25/github/
> It notes that on Bitbucket you can annotate the forks to explain why they happened.
> In addition, I should be able to easily sort forks by metrics such the number of Github stars or commits ahead.

Response:

> Thanks for writing in and sharing your thoughts on annotating forks to explain why they happened as well as sorting forks by metrics (stars, commits ahead, etc). While it isn't currently possible, we've added a +1 for you to our internal Feature Request List.

**Comment by TPS** [comment]
#562?

**Comment by jcrben** [comment]
Closing this as a duplicate - thanks @TPS

**Comment by TPS** [comment]
@jcrben 🙇
