### ISSUE TITLE
XBMC-Addons/screensaver.picture.slideshow doesn't show IPTC Caption from images, if text has daicritics

### ISSUE THREAD

**Issue by Lemyola** [isaacs/github#623]
Hello, text doen't appear from IPTC info from images
If text in IPTC info in section "Caption" has diacritics (for instance "ěščřžýáíé"), it doesn't appear.

URL:
https://github.com/XBMC-Addons/screensaver.picture.slideshow

Thank you

**Comment by TPS** [comment]
@Lemyola I think you need to file this issue there....

**Comment by cirosantilli** [comment]
This repository is only for issues about GitHub itself, please open an issue on the tracker of that project instead.
