### ISSUE TITLE
Page 100 of all large repos appears as if if it's the last, even when it isn't.

### ISSUE THREAD

**Issue by shurcooL** [isaacs/github#626]
https://github.com/golang/go/commits?page=100
https://github.com/docker/docker/commits?page=100
https://github.com/django/django/commits?page=100
https://github.com/git/git/commits?page=100

They all appear to be the last page.

![untitled](https://cloud.githubusercontent.com/assets/1924134/14158584/bd3d3ce2-f685-11e5-8afd-74afb8a00e03.png)

But they're not.

https://github.com/golang/go/commits?page=101
https://github.com/docker/docker/commits?page=101
https://github.com/django/django/commits?page=101
https://github.com/git/git/commits?page=101

**Comment by shurcooL** [comment]
@cirosantilli, is this really an enhancement? I think it's more of a bug.

**Comment by cirosantilli** [comment]
Sometimes it's hard to say.

**Comment by shurcooL** [comment]
This bug no longer exists because GitHub has changed how they do commits pagination.

What used to be https://github.com/golang/go/commits?page=100 is now a link of the form:

https://github.com/golang/go/commits/master?after=m2ztkx61y95neHetz1mwpLhCIwArMzQ2NA%3D%3D

And I'm not spotting any issues with the new behavior, so closing.
