### ISSUE TITLE
Make the branch names on PR's and other places as links to branches

### ISSUE THREAD

**Issue by vipulnsward** [isaacs/github#636]
Having these link to branch views is pretty useful, to refer to branch/status of commits on the branch after commits/changes, etc.
For example, quickly view different commits on that branch, or status of the repo on that branch.

![pr](https://cloud.githubusercontent.com/assets/567626/14273715/4062baea-fb2a-11e5-81de-6837070bfe12.jpg)

**Comment by cirosantilli** [comment]
Sample URL: https://github.com/rails/rails/pull/24429

**Comment by clarkbw** [comment]
duplicate of #34
