### ISSUE TITLE
View all pull requests assigned to me in all repositories

### ISSUE THREAD

**Issue by williammorrisssc** [isaacs/github#649]
I work in multiple repositories and checking each of them for assigned pull requests is tedious. Being able to view all open&assigned pull requests (and all open&created pull requests) would facilitate work in multiple repositories.

**Comment by The-Compiler** [comment]
Sounds like https://github.com/pulls and https://github.com/pulls/assigned already does what you want?

**Comment by williammorrisssc** [comment]
lol (embarrassed)

**Comment by clodpated** [comment]
If it makes you feel any better I googled this same complaint and you fixed it for me. ¯\_(ツ)_/¯

**Comment by ericnh** [comment]
I suppose that is how we all ended up here.

**Comment by chelseatroy** [comment]
Adding my commendation! I also googled this and @The-Compiler's comment helped me too.

**Comment by sekmo** [comment]
Thanks @The-Compiler! (But how can I reach this page from GitHub's interface?)

**Comment by The-Compiler** [comment]
@sekmo "Pull requests" in the top menu -> Assigned

**Comment by Akuli** [comment]
for anyone else wondering, there's also https://github.com/issues

**Comment by digitalmaster** [comment]
This doesn't seem to surface pull requests that are assigned to you via a team that you're a part of 🤔

**Comment by MisterVector** [comment]
Is there a reason I didn't notice this for 10 years?

![image](https://user-images.githubusercontent.com/437096/104883222-4d3f9880-5919-11eb-9f3a-45afdc49b339.png)

I also googled where to find this and you answered it for me!
