### ISSUE TITLE
UI way to filter issues by label exclusion

### ISSUE THREAD

**Issue by esquevin** [isaacs/github#65]
Allowing to filter the issues that doesn't have a specific label is really powefull, especially if combined with other label filters.

It works very well with tags like "nice_to_have" "improvements" "later" that are very powerfull to help you when you start having way too many issues to handle

**Comment by prohor33** [comment]
thank you @bkeepers!!!

**Comment by AmozHouse** [comment]
+1 @sharwell

**Comment by adamjerickson** [comment]
+! @sharwell

**Comment by hawkerm** [comment]
@sharwell great tip!  Would be nice to have the quick shortcut though still in the UI, so +1 still for this issue.

**Comment by alexfarrill** [comment]
+1

**Comment by bearnard** [comment]
+1

**Comment by thgreasi** [comment]
+1

**Comment by stdao51** [comment]
+1

**Comment by tpfeiffer** [comment]
+1

**Comment by Fresheyeball** [comment]
:+1:

**Comment by naoufal** [comment]
:+1:

**Comment by Fresheyeball** [comment]
So, its debatable as to whether its a *UI way*, but this feature does already exist. The filter input in the upper right supports lucene syntax (or something like it). So you can simply negate a label like so

```
-label:myLabel
```

(note, case sensitive). The `-` before the world `label` means *negate* or *exclude*.

![captureg](https://cloud.githubusercontent.com/assets/609279/8827651/2a6e8c1e-304b-11e5-8f73-b2eb7ba9eb1e.PNG)

**Comment by hawkerm** [comment]
@Fresheyeball, yeah @bkeepers and @sharwell pointed this out.  This request is still about just having an easy way to exclude them from the labels drop down though.

**Comment by Fresheyeball** [comment]
Well. When I googled it, this thread popped up, and I didnt learn that there is already a way. So I thought leaving the current solution here would be good for other googlers.

**Comment by ChaosCrafter** [comment]
Actually, while the -label: technique seems to work, it doesn't seem to work for milestones.
I'd like to be able to pick up any pull requests that weren't in "Ready for Merge", or "Rework Required" - two of the milestones we use.
The ideal as I see it would be to extend the language to allow fieldname in:{item1,item2}

**Comment by murielsilveira** [comment]
:+1:

**Comment by mikermcneil** [comment]
@sharwell thanks for the tip about labels w/ spaces in their names!  Linked back from [here](https://github.com/mikermcneil/machinepack-github/blob/master/machines/build-github-search-string.js#L87).

**Comment by jmcmurry** [comment]
+1 to be able to have this same pattern work for milestones, please. It is important in scenarios where I want to see and triage everything that is beyond the current release, for instance.

**Comment by anfuerer** [comment]
+1

**Comment by qimingweng** [comment]
+1 for this pattern to work on milestones as well, it seems to work for up to one milestone, but you can't chain them like with labels for example `-milestone:"Milestone A" -milestone:"Milestone B"`

**Comment by dvanherbergen** [comment]
+1

**Comment by andrewhood125** [comment]
:+1:

**Comment by seadb** [comment]
:+1:

**Comment by bhaslop** [comment]
:+1:

**Comment by TelmaTlantic** [comment]
And if i want a label A or label B? How i can do that in the filter?

**Comment by TomEdwards-FLF** [comment]
+1

**Comment by schumannd** [comment]
+1

**Comment by JagCesar** [comment]
+1

**Comment by n5ac** [comment]
+1

**Comment by karliky** [comment]
+1

**Comment by lukaskuzmiak** [comment]
+1

**Comment by seadb** [comment]
did yall read sharwell's comment?

> 
> You can use the syntax -label:name to do this now. If your label has a space, then -label:"label name" works. For example, you could use the following search to find all issue which are up for grabs, except for code fixes.

> >  is:open -label:"code fix" label:"up for grabs"

> 


https://github.com/isaacs/github/issues/65#issuecomment-63971607

**Comment by hawkerm** [comment]
@seadb I think the people finding this thread learn that they can do it with the minus, but it's not discoverable until they google how to do it and find this thread.  I just forgot about the minus, and had to relook it up here too.

The ask here is to provide some way in the Label drop-down to ask to exclude the selected label.  Like having the right-side of the list be an 'exclude this' type button.

**Comment by seadb** [comment]
Yes!!! Because I always forget the syntax

**Comment by mderazon** [comment]
Anybody knows how to do this in the new Milestones view (the one that you can order the issues) ?

**Comment by benoftoolofna** [comment]
+1

**Comment by franklinyu** [comment]
@esquevin How about updating the description to reflect updates explained by @sharwell? This may save some user from adding a 👍 .

**Comment by hwilde** [comment]
So, it is odd that you can use filter   NOT keyword,   but you cannot use filter   NOT label:blah

However, once you google and reach this page and learn the minus sign can be used, that is less characters to type.

`-label:myLabel`

Adding this negative sign to the advanced search syntax page would be helpful https://help.github.com/articles/searching-issues/

**Comment by relativityboy** [comment]
@hwilde - *fewer* characters to type

**Comment by MartinX3** [comment]
+1

**Comment by RLantzr** [comment]
If using the minus sign once worked it no longer does.

**Comment by hawkerm** [comment]
@RLantzr still seems to work for me?

**Comment by LongChair** [comment]
using `-` in front of lables works for me :)

**Comment by begin-again** [comment]
How could I search for issues without any labels?

**Comment by franklinyu** [comment]
@begin-again In UI, "Labels" -> "Unlabeled". Very intuitive.

**Comment by popcorn** [comment]
I am having problems today trying to exclude issues by using `-label:`. Anyone noticed the same?

**Comment by RicGuerra** [comment]
+1 @sharwell

**Comment by hepcat72** [comment]
I've got categories of labels, e.g. component:IO, component:INTERFACE, etc.  What I'd like to do is exclude anything with a "component" label so I can find issues I haven't assigned a component to.  That way I can go through my numerous issues and create new component labels that I need.  However, you apparently can't exclude labels that match the label search string - only full labels.  I have about a dozen component labels... making it cumbersome to find issues without any of those 12 labels.  So it would be nice if I could add a wildcard to the label string, like -label:component*.

**Comment by John-Weetaker** [comment]
> So, its debatable as to whether its a _UI way_, but this feature does already exist. The filter input in the upper right supports lucene syntax (or something like it). So you can simply negate a label like so
> 
> ```
> -label:myLabel
> ```
> The `-` before the world `label` means _negate_ or _exclude_. (note, label names are case sensitive)
> 
> ![captureg](https://cloud.githubusercontent.com/assets/609279/8827651/2a6e8c1e-304b-11e5-8f73-b2eb7ba9eb1e.PNG)

please add this in official documentation :)

**Comment by hepcat72** [comment]
Still, you need to have an exact entire label to use that `-label:myLabel` search feature.  Allowing wildcards would be great.

**Comment by clarkbw** [comment]
👋I see the [searching issues & prs help docs](https://help.github.com/articles/searching-issues/) doesn't include this but the search syntax docs has examples of how to search for the negatives.  

https://help.github.com/articles/understanding-the-search-syntax/#exclude-certain-results

We're looking at how we can improve the docs in that area right now. Thx!

**Comment by tierninho** [comment]
You can also use `no:label` to exclude for example, all issues without a label. Same can be done for milestones, etc...

**Comment by lukehefson** [comment]
Hi folks 👋 

You can now use the <kbd>alt</kbd> keyboard modifier (or <kbd>⌥ </kbd> on macOS) to exclude labels using the filter 🎉 

https://github.blog/changelog/2019-03-05-exclude-labels-from-search/

Thanks for all you feedback on this – we really appreciate it!!!

**Comment by TPS** [comment]
I think I'd count this done, but if any objection (the only 1 can think of is keyboard use, which may be awkward on mobile), please comment, & I'll reopen! :bow:

**Comment by goodmind** [comment]
@TPS how to search all issues with any label, like `no:label` but `any:label`?

**Comment by TPS** [comment]
AFAICT, `-no:label` can do it, but, on mobile, I don't see a UI option for labels @ all.…

@lukehefson How about it?

**Comment by goodmind** [comment]
`-no:label` doesn't work as expected

**Comment by lukehefson** [comment]
> how to search all issues with any label, like `no:label` but `any:label`?

We currently don't support this.

@goodmind Could I ask what your use case is?

**Comment by goodmind** [comment]
Just wanted to compare number of issues with labels and without them

**Comment by lukehefson** [comment]
> Just wanted to compare number of issues with labels and without them

Interesting! Thanks for letting us know 😄 

Not ideal– but you could use `is:issue no:label ` and then take the number of open and closed from the list and add them together and then subtract that from the total number of issue. So for this repo that would currently be:

- `386 Open + 261 Closed` = `647` issues without a label
- `1067 - 647` = `420` issues with a label

**Comment by maxisam** [comment]
I just tried is:open is:issue -label:backlog in one of my private repo

Apparently there is a bug because It returns some close issues. Without is:open, it returns all close issues.

**Comment by aequasi** [comment]
`-review:changes-requested` Doesn't seem to work as expected.

**Comment by reindert-vetter** [comment]
@aequasi try `review:-changes-requested`

**Comment by hepcat72** [comment]
> I think I'd count this done, but if any objection (the only 1 can think of is keyboard use, [which may be awkward on mobile](https://github.com/isaacs/github/issues/1512)), please comment, & I'll reopen! 🙇

OK, so should I create a new issue for [this contribution to the discussion](https://github.com/isaacs/github/issues/65#issuecomment-396332170) on this issue?

**Comment by asfernandes** [comment]
Would be good to support wildcard in exclusion. For example: -label:"component: *"

**Comment by ndom91** [comment]
With a label "dependencies", for example. "-label:dependencies" did the trick 👍

**Comment by hepcat72** [comment]
> With a label "dependencies", for example. "-label:dependencies" did the trick 👍

Perhaps you aren't responding WRT the request for a wildcard, but that doesn't to the trick to find issues without "component:*" labels.  E.g. if I have a series of labels such as `component:reporting`, `component:usage`, `component:GUI`, `component:debug`, `component:options`... and I search for `-label:component` to find issues without a component label, it filters 0 issues.

**Comment by ReikaKalseki** [comment]
I just discovered this thread and oh my god does this help: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues?q=is%3Aissue+is%3Aopen+-label%3A%22Can%27t+Reproduce%22+

**Comment by bojanpotocnik** [comment]
None of this works for filtering notifications?

I would like to use `-org:myorg` or `NOT org:myorg` but I always got _Sorry, we don't support the -org:myorg filter yet_. Then I found out that the same note is displayed for any of available `repo:`, `is:`, `reason:`, `author:` and `org:` filters.

**Comment by ndom91** [comment]
> > With a label "dependencies", for example. "-label:dependencies" did the trick +1
> 
> Perhaps you aren't responding WRT the request for a wildcard, but that doesn't to the trick to find issues without "component:*" labels. E.g. if I have a series of labels such as `component:reporting`, `component:usage`, `component:GUI`, `component:debug`, `component:options`... and I search for `-label:component` to find issues without a component label, it filters 0 issues.

Yeah, the wildcard still doesn't work, what might work in your case though, is `-label:component:reporting -label:component:usage ...` I know its annoying, but you can save it as a filter in the Github notification page so you only have to type it in once.

**Comment by hepcat72** [comment]
I think when you have more than a couple categories of labels and want to do more than a simple search and combine a couple of those, then saving shortcuts doesn't seem to scale well, but thanks for the tip.  That does seem useful.
