### ISSUE TITLE
Radio buttons are not visible in latest stable version of Chrome on OS X.

### ISSUE THREAD

**Issue by shurcooL** [isaacs/github#652]
I've tested other browsers, and it's not a problem in Safari and in Firefox. However, it seems to affect latest stable version of Chrome on OS X. I've tried clearing all cache and incognito window (meaning no extensions, etc.), no effect.

Using:

- OS X 10.11.4
- Chrome 50.0.2661.75 (64-bit)

![image](https://cloud.githubusercontent.com/assets/1924134/14629809/134419fc-05be-11e6-91aa-292a84c9ae6e.png)

It's possible it's a bug/regression in Chrome itself, but I can't verify that right now.

**Comment by shurcooL** [comment]
Tried Chrome Canary Version 52.0.2712.0 canary (64-bit), same issue.

It seems that `float: left;` CSS property is the one causing it. Disabling it results in the radio buttons being visible.

**Comment by shurcooL** [comment]
Here's a minimal HTML+CSS reproduce case:

```HTML
<!DOCTYPE html>
<html>
<head>
<style>
.form-group label {
    position: relative;
}

.form-checkbox input[type=radio] {
    float: left;
}
</style>
</head>
<body>

<div class="form-group">
<div class="form-checkbox">
  <label><input type="radio" checked> foo</label>
</div>
<div class="form-checkbox">
  <label><input type="radio"> bar</label>
</div>
</div>

</body>
</html>
```

I'm not sure if it's invalid HTML/CSS usage, or a problem in Chrome browser versions 50-52.

**Comment by shurcooL** [comment]
This is indeed a bug in Chrome, versions 50 and newer:

https://bugs.chromium.org/p/chromium/issues/detail?id=603910

Reply from support@github.com:

> Sorry for the trouble!
> 
> This seems to be a bug with the new version of Chrome:
> https://bugs.chromium.org/p/chromium/issues/detail?id=603910
> 
> We also have an issue opened internally to discuss workarounds.
> 
> Hopefully this will be resolved soon and my apologies again!

Closing because it's not a bug on GitHub and it's already tracked in Chrome project.

**Comment by absolutehype** [comment]
I'm getting this same issue again running Chrome Version 67.0.3396.99

![screenshot 2018-07-19 at 14 57 27](https://user-images.githubusercontent.com/1125278/42946975-23ce06ce-8b64-11e8-80e2-9934efd084ce.png)

**Comment by alacret** [comment]
Same here, since i updated my mac and chrome app.

Current version: Version 68.0.3440.84 (Official Build) (64-bit)

I delete everything, even the app, download a fresh copy, and have this:

![screen shot 2018-08-01 at 11 09 31 am](https://user-images.githubusercontent.com/918895/43530373-65d0ccd4-957b-11e8-9241-a6f403f288a6.png)

**Comment by Eddpt** [comment]
@alacret Beta Version 69.0.3497.32 seems to fix it.

**Comment by martinlightmatter** [comment]
I am also currently seeing this with `Version 68.0.3440.106 (Official Build) (64-bit)`
