### ISSUE TITLE
Dark version of github

### ISSUE THREAD

**Issue by adius** [isaacs/github#66]
In my terminal and my IDE I use a white font on a dark background. Now everytime I open github it hurts my eyes because it is so bright. This is really annoying as my normal workflow includes a lot of switching between terminal, IDE and github.
It would be awesome to be able to switch to a dark version of github.
Is there a chance that this feature might get implemented?

**Comment by g33kidd** [comment]
+1

**Comment by balupton** [comment]
I came across this recently https://www.gunnars.com perhaps it could be a good workaround

**Comment by an-OK-squirrel** [comment]
Welp, I use https://userstyles.org/styles/37035/github-dark Works great.

**Comment by SgtSQL** [comment]
Any progress? Stylish may have been compromised by a change of ownership. I really appreciate the GitHub service, but I hate that the light code view is the only option. It hurts the eyes.

**Comment by PabloC** [comment]
+1 for this!

**Comment by Christofosho** [comment]
Adding my +1 from mobile browser. Love hitting and would love a dark theme to ease the brightness off of my eyes.

**Comment by moosichu** [comment]
+1 From me, would really appreciate this feature!

**Comment by jacobjanco** [comment]
+1

**Comment by jacobjanco** [comment]
+1

**Comment by adius** [comment]
I can recommend Midnight Lizard (https://chrome.google.com/webstore/detail/midnight-lizard/pbnndmlekkboofhnbonilimejonapojg). So far the best program I've found to automatically switch between a dark and a light theme.

**Comment by TPS** [comment]
_(&, of course, [Midnight Lizard is developed here on GitHub](https://github.com/pavel-agarkov/Midnight-Lizard).)_

**Comment by chicoxyzzy** [comment]
Any good solutions for Safari? Stylish with GitHub Dark blinks from white to dark :(

**Comment by chrislovessushi** [comment]
+1 This would be SO appreciated!

**Comment by RomaSto** [comment]
+1

**Comment by raduflp** [comment]
+1

**Comment by AlecBenzer** [comment]
Please don't reply to an issue just to say '+1': it sends a notification to everyone subscribed to the issue. Instead, just react to the issue's initial comment with the 👍 emoji.


<img width="233" alt="plus_1_github" src="https://user-images.githubusercontent.com/92369/31297680-0455e07c-aab5-11e7-81dc-d6070ca75378.png">

**Comment by brychcy** [comment]
+1 (sorry for the noise, it's hard to find issues you haven't commented on, see #283)

**Comment by rwhitcroft** [comment]
Bump. Surely the majority of devs working at github use dark themes just like the rest of us...

**Comment by macbem** [comment]
Any updates on this?

**Comment by dm-z** [comment]
With MacOS new Dark mode it is painful to look at github, please Microsoft do something.

**Comment by aquigni** [comment]
> With MacOS new Dark mode it is painful to look at github, please Microsoft do something.

Windows 10 October's update brings Fluid Design System engaged DarkSide even to classic apps such as file explorer! 
We need native GitHub night mode option as Youtube does, please, MS.

**Comment by safakgur** [comment]
[GitHub Dark][1] makes wonders in its [userscript][2] form, which should also work on Safari with [Tampermonkey][3]. Sadly, we're out of luck using mobile browsers.

[1]: https://github.com/StylishThemes/GitHub-Dark
[2]: https://github.com/StylishThemes/GitHub-Dark-Script/
[3]: https://tampermonkey.net

**Comment by tdwoodman** [comment]
Over 5 years later and still no dark theme.

Stylish is not the answer. I refuse to install extensions that log my history...

- https://arstechnica.com/information-technology/2018/07/stylish-extension-with-2m-downloads-banished-for-tracking-every-site-visit/
- https://robertheaton.com/2018/07/02/stylish-browser-extension-steals-your-internet-history/
- etc, google search

**Comment by jpike88** [comment]
Hilarious how some features are so straightforward to implement, you'd think Github/Microsoft could afford it. Comes to show that it's just a business like any other, and if they're raking in enough cash then the rest of who care about polish can get stuffed.

**Comment by elias89** [comment]
The fact of not having a dark mode in a place where you spend hours reading code...today in 2018 is unacceptable. Github should really think about this, there should be at least a formal answer to this topic.

**Comment by lobo-tuerto** [comment]
Lots of other websites are implementing a "Night mode" option. Even browsers like Chrome and Firefox now have a **dark/night** mode for their DevTools. How come **GitHub** doesn't have this?

It's really easier in the eyes. Even more so for people with hight sensitivity to WHOLE WHITE pages.

Can we expect an official answer from the **GitHub** team?

**Comment by lobo-tuerto** [comment]
Lots of other prominently white websites are implementing a _Night mode_ option (look at **YouTube** and **Reddit**). Even browsers like Chrome and Firefox now have a **dark/night** mode for their DevTools. How come **GitHub** doesn't have this?

It's a really helpful feature because it makes the website really easier on the eyes.
Even more so for people with hight sensitivity to WHOLE WHITE pages.

Can we expect an official answer from the **GitHub** team?

**Comment by thetornadotitan** [comment]
Dark mode would be cool.

**Comment by kapitanluffy** [comment]
I was reviewing a source code on Github last night. Exhausted, I tried to push a little more. I felt a slight burning sensation and my eyes got watery. I immediately closed the browser and the darkness of my desktop's wallpaper covered me. As I rest my eyes, I kept thinking why Github does not have any dark mode. I spent my night scrolling through Reddit (in dark mode) and watching Youtube videos (in dark mode).

**Comment by bancorian** [comment]
It is nigh the end of the year of our lord, 18 and 2000 years, and it doth appear that GitHub is the only bastion of sanity remaining in the web betwixt things; verily, the whole world! The deep darkness claimed all, web sites falling one by one, succumbing to the slothful comfort of ease upon the orbs. This malady known as "Dark Mode" has cast its umbric terror upon all but this one last great fortress, white and glistening as a glacier.

As I travel, a lone vagrant wandering from site to site, my eyes are ev'ry time awash with tears of joy when the dashboard of GitHub reveals itself to me, its grand white glory searing into mine very retinas, etching itself upon the essence of my soul. Afeared as I was, from all unspeakable nightmares hiding in the shadows, t'was GitHub that offered the light, the salvation that soothed me in a way that milk of the poppy never could.

I'm just kidding, the white is hurting my eyes. Please add a dark mode so my eyes can stop tearing and I don't have to rely on Stylish or lower the brightness to 0 on my phone.

**Comment by st-sloth** [comment]
I had recently asked about this on the Community forum. [Here is the answer](https://github.community/t5/How-to-use-Git-and-GitHub/Dark-theme/m-p/16378/highlight/true#M5029). People from the support feel the pain too and use extensions. It's up to the decision makers at GitHub when they are going to address this issue. Perhaps more of the direct feedback via support is going to influence this rather than an unofficial issue tracker not affiliated with GitHub.

**Comment by Steveeeie** [comment]
Please save my 👀 and my life. Implement dark mode.

**Comment by Br4nd0R** [comment]
Would love this. +1

**Comment by sbrl** [comment]
@Br4nd0R, @BlkPingu: You can utilise GitHub's [reaction feature](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to avoid leaving a comment that both clutters the issue and sends a out a notification _everyone_ subscribed.

**Comment by Jamim** [comment]
> @Br4nd0R, @BlkPingu: You can utilise GitHub's reaction feature to avoid leaving a comment that both clutters the issue and sends a out a notification everyone subscribed.

Hi @sbrl,
Please take a look at #283.
Perhaps that is why they leaved those comments.

**Comment by sbrl** [comment]
@Jamim: There's a "Subscribe" button in the right-hand sidebar that does the same job....?

**Comment by Jamim** [comment]
@sbrl
Did you really check the description of #283?

**Comment by Jamim** [comment]
> There's a "Subscribe" button in the right-hand sidebar **that does the same job**....?

No, it doesn't.

**Comment by caene** [comment]
Been waiting years for this one, can't stand adding extensions for simple things like this. +1

**Comment by mike-grinspan** [comment]
Issue open for 6 years and still getting frequent comments, can we have this?

**Comment by sarpik** [comment]
Have ya'll tried out this one? https://github.com/StylishThemes/GitHub-Dark
It requires to install the [stylus (**NOT stylish**) extension](https://github.com/openstyles/stylus) which is a fork of stylish **without** the history tracking nonsense. After that, just add the `usercss` stylus script (first option under [installation](https://github.com/StylishThemes/GitHub-Dark#installation)). 

I just found this out and it works great, please give feedback so we can all benefit from it!

![](https://i.imgur.com/gobE4D3.png)

**Comment by thany** [comment]
Until Github supports a dark mode officially, and I **really** think it should, seeing how much of a development tool it is... In the mean time we can use this browser addon called [Dark Reader](https://darkreader.org/). It's pretty darn good.

**Comment by sbrl** [comment]
That's a nice theme, @sarpik! I've tried a bunch of different ones, but none appear as complete as that one.

@thany: Yeah, it's a shame really. The user-based workarounds are ok, but there are a bunch old / incomplete ones that don't work correctly - leaving users with a considerable amount of work to do in order to find a good one.

**Comment by roccomuso** [comment]
I don't wanna install crappy extensions. Instead of adding emojii please GH add a dark mode :)

**Comment by paualberto** [comment]
Oh man, photophobia really sucks... I guess I'll always be forced to use Dark Reader or Midnight Lizard for one site or the other, you can't expect every single one to comply, but you'd think at least GH which is used by devs would have it... There's a reason why terminals are white on black by default :smile:

**Comment by ocdtrekkie** [comment]
I tweeted @nat this one and he didn't answer me. :'(

**Comment by bes89** [comment]
Often I read articles on medium (of course with dark theme) on my mobile device and I just hate it when they embed gist because they are in light theme. Horrible! In such use cases stylish etc is not a solution. Github have to support this officially 🙄
M$ please

**Comment by kasyanov-ms** [comment]
Just don't work at night. Don't strain your eyes 😎

**Comment by karolyi** [comment]
+1

**Comment by Quamor** [comment]
I know that there are add-ons for browsers to do dark mode but I would much prefer sites are done officially.  For the power grid and for our laptop batteries, and for my eyes now struck unholy, please add dark mode! :p

**Comment by duraki** [comment]
Update requested, pls @isaacs.

**Comment by oprogramador** [comment]
@adius

I like dark background but IMO there's a lot of more important features and in order to have a black background you can use a custom GitHub client or even write your own.

**Comment by scimas** [comment]
How has this still not been implemented? GitHub really does blast too much white on every single page.

**Comment by marcuswhitmore** [comment]
Midnight lizard is working for me.

https://github.com/Midnight-Lizard/Midnight-Lizard

**Comment by MadhavVij** [comment]
> How has this still not been implemented? GitHub really does blast too much white on every single page.

My thoughts exactly. It's been a while now.

**Comment by G1R-Productions** [comment]
Its crazy. It has been so many years.

**Comment by jeffymahoney** [comment]
After the security problem with Stylish was reported, I've uninstalled Stylish and am skeptical of things that are similar. Midnight Lizard looks similar and I don't have time to research it completely so I won't be using that either. I'm very sensitive to light and I code as a full time job. I can code with a nice dark mode all day (I use the JetBrains stuff, to be specific) but there's no way my eyes and brain can read the diffs and such on GitHub without a headache at the end of the day. I think most people aren't as sensitive so it's not a big deal, perhaps?

**Comment by SuperSandro2000** [comment]
@jeffymahoney try dark reader and use dynamic mode. it is really good.

**Comment by Admin9705** [comment]
would love if this would happen! github is too bright!

**Comment by glhc** [comment]
A native dark theme would be wonderful!

**Comment by alubbock** [comment]
Github Dark Mode could be implemented using the new `@media (prefers-color-scheme: dark)` CSS selector from the [CSS Media Queries 5 draft](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme). That way, the theme reflects the user's preference automatically.

According to [chromestatus.com](https://www.chromestatus.com/feature/5109758977638400), the feature has been implemented in Safari already, and is in development for both Chrome and Firefox.

**Comment by Luc45** [comment]
## Microsoft owns GitHub, and they do not look at this issue.

We must focus our effort on the right place to get answers from them.

https://github.community/t5/How-to-use-Git-and-GitHub/Dark-theme/m-p/16334

**Comment by Gennttii** [comment]
from 2013 still can't change color of background??

**Comment by nshCore** [comment]
Anyone who finds this just take a look at this repo to use dark themes for GitHub

https://github.com/StylishThemes/Github-Dark

**Comment by dullbananas** [comment]
is there any progress on this?
i just really want a blacc theme

**Comment by haykerman** [comment]
I second this. It's really a shame that a website, which is a host of billions of developers code, doesn't have a dark theme. We don't want anything big, we don't want AI, AR, VR. Give us our dark theme, and we'll be thankful and happy eternally.

**Comment by OrangGeeGee** [comment]
Google is introducing dark mode to all of its' apps. Time to pick-up slack and get going Microsoft! It is working great for you when you follow market leading practises.

**Comment by ysle** [comment]
> Github Dark Mode could be implemented using the new `@media (prefers-color-scheme: dark)` CSS selector from the [CSS Media Queries 5 draft](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme). That way, the theme reflects the user's preference automatically.
> 
> According to [chromestatus.com](https://www.chromestatus.com/feature/5109758977638400), the feature has been implemented in Safari already, and is in development for both Chrome and Firefox.

aaand that got some [progress](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#Browser_compatibility) meanwhile.

**Comment by evanjs** [comment]
> > Github Dark Mode could be implemented using the new `@media (prefers-color-scheme: dark)` CSS selector from the [CSS Media Queries 5 draft](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme). That way, the theme reflects the user's preference automatically.
> > According to [chromestatus.com](https://www.chromestatus.com/feature/5109758977638400), the feature has been implemented in Safari already, and is in development for both Chrome and Firefox.
> 
> aaand that got some [progress](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#Browser_compatibility) meanwhile.

Yeesh. Looks like all major browsers support the this now!

**Comment by cyrtophora** [comment]
If it was open source we would just fork it like how we do on github.

**Comment by yardenac** [comment]
I literally just logged in to like someone else's comment saying:

> If it was open source we would just fork it like how we do on github.

But now it's gone >.<

**Comment by anumpatel** [comment]
Considering all great git features coming up in VSCode, it would just make sense to use github-like UI in VSCode itself, which ships with dark theme!

**Comment by shahzad31** [comment]
Hey Microsoft and Github, it's 2019 and still no dark mode !!

**Comment by loganallenc** [comment]
Where is night mode

**Comment by sbrl** [comment]
## Remember people, this isn't an official forum for GitHub. I recommend instead posting on https://github.community/ instead!

**Comment by TPS** [comment]
More specifically, https://github.community/t5/How-to-use-Git-and-GitHub/Dark-theme/m-p/16378#M5029

**Comment by lucasvazq** [comment]
6 years to do an improved version of
```
html {
  background-color: black;
  color: white;
}
```

**Comment by DanieleGBX** [comment]
> 6 years to do an improved version of
> 
> ```
> html {
>   background-color: black;
>   color: white;
> }
> ```

This is quite dismissive.

**Comment by cdock1029** [comment]
Not a solution but alternative until solved natively is to use https://sourcegraph.com for public repos. They have a night mode.

Try: 

`https://sourcegraph.com/github.com/[user]/[repo]`

**Comment by xoadrian** [comment]
Any update / ETA on this, really need it as I am spending a lot of time reviewing the code.

**Comment by sbrl** [comment]
@xoadrian: ## Remember people, this isn't an official forum for GitHub. I recommend instead posting on https://github.community/t5/How-to-use-Git-and-GitHub/Dark-theme/m-p/16378#M5029 instead!

[See above](https://github.com/isaacs/github/issues/66#issuecomment-534297993)

**Comment by Zorrototo** [comment]
Just google Github Dark Theme and use any available method to skin GitHub.
Dark Reader is a good tool to do that. You also have dark theme available in your browser modules/store but I think Dark Reader is more appropriate as it does the same thing, but for every single website you can configure it all.

**Comment by faizaankhan** [comment]
WAITING FOR GITHUB TO PROVIDE DARK MODE.

**Comment by TPS** [comment]
Interestingly, [the upcoming app (now in β)](https://github.com/mobile) seems to reflect the OS default choice re: dark/light mode.

**Comment by sbrl** [comment]
Hopefully that makes it to the website too....

**Comment by skeets23** [comment]
I believe the correct place to ask for this feature is [here](https://support.github.com/contact/feedback). I didn't see any other links to the correct place in this thread.

**Comment by ret394** [comment]
stop with the pointless Android app though website exists trend. I'm trying hard to be positive while coding an Android app.

**Comment by Rexogamer** [comment]
If the mobile app(s) and Desktop both have it, surely the site is next?

**Comment by JSn1nj4** [comment]
@Rexogamer I sure hope so. I noticed that too after installing the app.

**Comment by jfhector** [comment]
macOS now switch all apps to dark mode after a certain time in the evening. 
Past that time, every time that I go from one of the macOS applications to Github, it hurts my eyes.

**Comment by odravison** [comment]
It hurts my eyes too @jfhector 
Any progress with this feature?

**Comment by fenollp** [comment]
There is hope!
![](https://github.githubassets.com/images/modules/site/workspaces/device-2.png)

Found on https://github.com/features/codespaces

**Comment by Goldsucher** [comment]
> There is hope!
> ![](https://camo.githubusercontent.com/3674e7ac8d0134bfef13221228121ca544c5894b/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f736974652f776f726b7370616365732f6465766963652d322e706e67)
> 
> Found on https://github.com/features/codespaces

well something similar already exists:

https://github.com/dferber90/githubbox

**Comment by Rexogamer** [comment]
To be fair Codespaces is essentially a cloud version VSCode and can run any VSC extension so *Codespaces* will have a lot of themes available.

**Comment by amandal1810** [comment]
guys, just use this: https://darkreader.org/
dark-ifies all websites 😍😎

**Comment by RafaelMuniz94** [comment]
Up vote to an official dark theme !!

**Comment by ruant** [comment]
> ~~Over 5 years later and still no dark theme.~~

**Soon 7 years later and still no dark theme.**
🙄🕶️

**Comment by guiramos** [comment]
When you see a simple and widely requested feature like this and they dont provide any feedback that means they dont give a shit about what we think.

**Comment by artemious7** [comment]
I use a browser extension to enable dark theme, however, they make GitHub much **SLOWER** to load pages. Painful

**Comment by mark-i-m** [comment]
Perhaps just wear sunglasses when using github? :sunglasses: :stuck_out_tongue:

**Comment by nmtitov** [comment]
Bump ☝️
Do something guys, you're so rich

**Comment by JRL101** [comment]
Dammit i thought there's be an actual solution these days, disappointing, makes using GITHUB a less appealing option for coding and sharing when it gives me a headache to have up on the side screen.

**Comment by GeraudFabien** [comment]
> Remember people, this isn't an official forum for GitHub. I recommend instead posting on the official forum https://github.community/t5/How-to-use-Git-and-GitHub/Dark-theme/m-p/16378#M5029 instead!

**Comment by NiKiZe** [comment]
Any suggestion to use an extension or anything else, you don't care about you data or privacy, stopp even suggesting such idiocricy please!

Now, GitHub, please stop killing innocent eyeballs!

**Comment by TPS** [comment]
> Interestingly, [the app](https://github.com/mobile) seems to reflect/respect the OS default choice re: dark/light mode.

[GitHub.community _just_ received a dark theme a few days ago via the Discourse update.](https://github.community/preferences/interface)

**Comment by Andre601** [comment]
> > Interestingly, [the app](https://github.com/mobile) seems to reflect/respect the OS default choice re: dark/light mode.
> 
> [GitHub.community _just_ received a dark theme a few days ago via the Discourse update.](https://github.community/preferences/interface)

Your link leads to an invalid page

**Comment by TPS** [comment]
> Your link leads to an invalid page

There's apparently no general link to that page.  I've fixed the above to _my_ interface preferences page, & am hoping Discourse is intelligent enough to reroute to 1's own.

**Comment by jack1142** [comment]
> I've fixed the above to _my_ interface preferences page, & am hoping Discourse is intelligent enough to reroute to 1's own.

Here's a link that does reroute: https://github.community/my/preferences/interface

**Comment by Newcool1230** [comment]
> 
> 
> > Interestingly, [the app](https://github.com/mobile) seems to reflect/respect the OS default choice re: dark/light mode.
> 
> [GitHub.community _just_ received a dark theme a few days ago via the Discourse update.](https://github.community/my/preferences/interface)

Github community != github.com

We have been asking this for 7+ years now and you add it to github community instead of github.com....

**Comment by TPS** [comment]
> Github community != github.com

_Incremental_ progress is _still_ a good sign.  Even GitHub Desktop has a Dark theme option now (dunno since when).   It leads me to believe the last GitHub property that _doesn't_ have it is GitHub.com.

**Comment by EpocDotFr** [comment]
It's not an "official" communication, but looks like dark mode work is ongoing: https://www.reddit.com/r/webdev/comments/hex1p5/githubs_dark_mode_is_coming/

P.S. natfriedman is the CEO of GitHub.

**Comment by TPS** [comment]
It seems _pretty_ official, as Nat Friedman (& co?) seem to be treating [that Hacker News thread](https://news.ycombinator.com/item?id=23622747) (also edited in above) kinda like a Reddit AMA, & are posting serious responses.  I'd recommend _everyone_ interested in this to jump aboard there, as the window for attention like this is probably limited.

**Comment by joecairns** [comment]
I hope they are taking it seriously.  I'm one of those quiet users who has been waiting for this feature for a long while, but not making a stink about it. The quiet phase has ended.

**Comment by binex-dsk** [comment]
having eyes was fun while it lasted

**Comment by patrickhgb** [comment]
from 2013 ignored till now OMEGALUL

**Comment by mochizuki-8** [comment]
Yikes. How do we still not have dark mode.

**Comment by Mik1337** [comment]
Hey staff of GitHub, 2020 has sucked so far; Giving us dark theme will distract us from out misery a little, kthxbai

**Comment by Dron-elektron** [comment]
The most popular site for programmers without the most important thing (dark theme) for programmers, what an irony.

**Comment by larcorba** [comment]
Yea we need this 👍🏼

**Comment by alexclst** [comment]
We really need this. Everything on my computing environment is dark mode, yet Github, which is central in my programming work, is not. Please add a dark mode options.

**Comment by Oxymoron290** [comment]
it's been over 7 years folks...

**Comment by maksimovic** [comment]
This morning I found this temporary solution that's rather simple (an extension transforminng just github into dark mode, and so far I've found no major problems): 
https://poychang.github.io/github-dark-theme/

**Comment by vizhnu** [comment]
Why isn't there an official response to this even after 7 years? In my opinion, it is a fairly easy fix. People who are more experienced than me, how much time and effort does it take to build a dark-theme for Github? I read a blog about [how StackOverflow implemented dark mode.](https://stackoverflow.blog/2020/03/31/building-dark-mode-on-stack-overflow/) Seems pretty straightforward. Can anyone clarify Github's stand on this and why it is taking too long?

**Comment by GeraudFabien** [comment]
@vizhnu 
> Why isn't there an official response to this even after 7 years? 

Two thinks. There is official reponse on the official issue https://github.community/t5/How-to-use-Git-and-GitHub/Dark-theme/m-p/16378#M5029 . Remember this repo as zero link with github i'm still not sure why all this post here since it's not the place.

There is some answer :
> It's not an "official" communication, but looks like work on dark mode is ongoing: https://www.reddit.com/r/webdev/comments/hex1p5/githubs_dark_mode_is_coming/
> 
> (Originally from https://news.ycombinator.com/item?id=23622747)
> 
> P.S. natfriedman is the CEO of GitHub.

>  Can anyone clarify Github's stand on this and why it is taking too long?

Why because : 
- it's far more complicated (It must work for all page (Home, configuration, merge request,...) and 
- There is a lot more complex view to test and fix and that must work (graph, **markdown** (With wysiwyg), **merge request**, Kanban, IDE, ...)
-  Stackoverflow describe it as straigthforward but in my understanding it take them more than a year to make it work 
- It's not top priority for them as they are a lot of plugin that provide this feature with more or less success and by stealing more or less personal info ;)
- They may want to make it gradually github is old and they may need to remake a big part of they stylesheet to make it
- As any feature in any project you can't know the real complexity before doing it. 

Last but not least Gitlab as darkmode only on some part (IDE) but nowhere else and people complain about it. When competition know one of your flow and doesn't use it. It means it's not trivial.

**Comment by Andrej730** [comment]
Please save our eyes at night. 

I don't understand why Github doesn't think this issue is important enough to prioritize it and figure it out.

**Comment by GeraudFabien** [comment]
I forget some point (on explaining why it's not there top priority) there is also many way to not use the web version : 
- https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github (Visual Studio Code)
- https://docs.github.com/en/desktop/getting-started-with-github-desktop/setting-a-theme-for-github-desktop (desktop)
- https://visualstudio.github.com/ (VisualStudio)

Don't get me wrong i want dark mode (on web version) since on my work machine i don't have the right to install plugin on my browser or github desktop or VS. So the only working solution is VS[Code] (Solution i didn't have the possibility to try yet but i will)(Solution that ask to download VSCode as zip and then install the official plugin just for working on github hoping you won't need not implemented feature or suffer from bug [preview when i wrote this]... When you work on eclipse or else it's a big trouble just to get dark mode). But i can understand it's not they're first priority.

**Comment by EramsorGR** [comment]
Damn this issue is open for 7 years now. A dark theme is literally an eye saver, I don't see why it's not been worked on

**Comment by JeffreyLeeDave** [comment]
Another vote of yes from me plz. Come on. Some CSS person do the magic! Make the Dark Mode!

**Comment by graphitemaster** [comment]
This issue has been opened for seven years. You're a developer focused platform and a majority of developers use dark themes in nearly all their applications, including IDEs and text editors. I don't understand the rationale for not having a simple option when other websites like YouTube, Twitter, Reddit, etc have given people the option, even if opt-in. While some like Discord started out with light themes and made the dark themes default when they realized that that's actually what a majority of users wanted and used despite being opt-in. This seems like such a simple yet obvious feature request that would benefit people. Half the people in this comment thread are pointing out browser-specific plugins and workarounds to get what they want which will inevitably break if you make changes and then you'll just be hit with support requests for when things are not working because they used third party website-altering plugins. So if not for any other reason than to save yourself some support ticket costs, add what is a couple line CSS toggle for us.

**Comment by GregTheHun** [comment]
Please, this needed to be implemented years ago.

**Comment by stephenwithav** [comment]
Bump.  GitLab has a great dark mode in alpha right now.  GitHub needs to catch up.

**Comment by wackbyte** [comment]
SEVEN. YEARS.

**Comment by iforgotmysocks** [comment]
Just FYI, the [Dark Reader](https://darkreader.org) extension converts github into a fantastic dark mode. Available for most browsers.

**Comment by jehrenzweig** [comment]
> 
> 
> Just FYI, the [Dark Reader](https://darkreader.org) extension converts github into a fantastic dark mode. Available for most browsers.

Yep, Dark Reader is what I use in the absence of a first-party dark theme.  https://darkreader.org

**Comment by MPieter** [comment]
Time to switch to GitLab.

**Comment by nschmeller** [comment]
I would really like to see this happen!!

**Comment by stephenwithav** [comment]
This is a pretty nice GitHub-specific extension:

https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp

**Comment by Mr-Steal-Your-Script** [comment]
Le 2021 is about to arrive, still no dark mode. This issue was created in 2013, this is so sad :(

**Comment by klarkc** [comment]
Some1 has to create a counter, it's been:

2687 days or
7 years, 4 months, 7 days or
88 months, 7 days

and still no dark mode

**Comment by oidualc** [comment]
> Some1 has to create a counter (with dark mode of course), it's been:
> 
> 7 years, 4 months, 7 days or
> 88 months, 7 days or
> 2687 days
> 
> and still no dark mode

Apparently someone did http://isgithubdarkyet.xyz/

**Comment by Mennaruuk** [comment]
Just leaving these tweets by Github CEO Nat Friedman, looks like more than just dark mode is coming! Fingers crossed, guys.
September 14:[ "**It's coming. Will be the best dark mode you ever saw.**"](https://twitter.com/natfriedman/status/1305512578311884800)
Yesterday: ["**After we are done with dark mode, we will ship accessible color modes for people with color blindness.**"](https://twitter.com/natfriedman/status/1330924323952091137)

**Comment by roselpadilla** [comment]
@Mennaruuk Nice. It only took 7 years 😅

**Comment by copremesis** [comment]
heh I was using this while reading this https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US

**Comment by Kruhlmann** [comment]
The technology is finally here

**Comment by LeonardSSH** [comment]
Greetings from 2027 (ps. cars are still driven by people)

**Comment by jodinathan** [comment]
Will I finally stop using dark theme for github extension on chrome? :D

**Comment by divinity76** [comment]
https://github.com/StylishThemes/GitHub-Dark is wonderful

**Comment by LukeSchoen** [comment]
My browser makes all pages dark theme (thanks dark reader) i litterilly never knew Github wasn't dark themed.

**Comment by clstr** [comment]
> https://github.com/StylishThemes/GitHub-Dark is wonderful

Been using for a while now, not sure why people are down voting @divinity76 post.

**Comment by Wolfkid200444** [comment]
Such wonderful *Hope*

**Comment by haze** [comment]
swag

**Comment by obito** [comment]
swag

**Comment by copremesis** [comment]
> > https://github.com/StylishThemes/GitHub-Dark is wonderful
> 
> Been using for a while now, not sure why people are down voting @divinity76 post.

I asked a few of the down voters and they are claiming that it's promoting a plugin. Seriously guys those who came to simply
response with a thumbs down at least express your frustration. There are existing alternatives plain and simple. If you would rather wait 7 more years by all means 😂 ... I'll be using a plugin in the meantime

**Comment by seanhinton** [comment]
Note for Github if they read these...

It would be excellent if you could use:

@media (prefers-color-scheme: dark) {
  // dark version css
}

My computer switches to dark mode at sunset and light mode at sunrise, this css means you can change the site accordingly. If it changed automatically I would really appreciate it.

**Comment by TGPF** [comment]
Please add dark mode.

**Comment by not-optikk** [comment]
pogchamp

**Comment by broccolini** [comment]
It’s here, _finally_. I hope you enjoy it! 🎉  https://github.com/settings/appearance

**Comment by immanuelfodor** [comment]
Holiday gifts have arrived early this year, wuhuuuuu 😍

**Comment by Mr-Steal-Your-Script** [comment]
It only took Nat 7 fucking years to implement it

**Comment by max** [comment]
> It only took Nat 7 fucking years to implement it

Don’t hate. We barrel-aged every single pixel.

**Comment by MMK21Hub** [comment]
Note that the GitHub mobile app has had Dark Theme for ages now... Reminds me of Google Photos. Glad to hear that it's in development. Dark Reader does an impressive job in the meantime.

**Comment by captn3m0** [comment]
>[parity](https://github.com/isaacs/github/labels?q=parity): Features that GitHub is missing, but competitors implement; also, see [Migration](https://github.com/isaacs/github/labels?q=migration)

**Comment by ThibaultWalterspieler** [comment]
Github just announced Dark Mode during the Github universe conference ([echo "hello, darkness"](https://www.linkedin.com/posts/github_darkmode-activity-6742128520757166080-fM4r)) 🎉🎉

The question now is when it will release 🕵️

**Comment by jack1142** [comment]
@ThibaultWalterspieler it already released, you can change it in settings.

**Comment by ThibaultWalterspieler** [comment]
@jack1142 Indeed, awesome !

**Comment by iamshreeram** [comment]
Github dark mode is too dark. It really strains my eyes. I sometimes toggle to light mode to read the text and then turn back the dark mode.

**Comment by itsme-alan** [comment]
*Me reading this thread after the official GitHub dark mode:* 🤣

**Comment by david-fong** [comment]
🎉!! Explorer and Marketplace don't yet support dark mode, though :/

**Comment by TPS** [comment]
@david-fong That's been [reported & responded to officially](https://github.community/t/147828/4?u=tps), so follow there to keep updated on that.

**Comment by SyghtGlass** [comment]
Currently we are testing our [Gaming Glasses](https://www.syghtglass.com/collections/gaming-glasses), that helps you to protect your eye strain.
