### ISSUE TITLE
.gitignore: node

### ISSUE THREAD

**Issue by dvrein** [isaacs/github#663]
Hi, I have a question. I don't know if this a bug or not.

in default .gitignore, the value is node_modules and not node_modules/

I believe the node_modules should be a directory, and not a file (node_modules).

Basically, I hope dev change node_modules to node_modules/ by default   (file to directory)

This is minor question/bug

**Comment by cirosantilli** [comment]
This repository is only for issues about GitHub itself, please open an issue on the tracker of that project instead.

**Comment by dvrein** [comment]
ty for that info
