### ISSUE TITLE
GitHub desktop suddenly stopped showing repository history and there is no sync button

### ISSUE THREAD

**Issue by joclaxton** [isaacs/github#681]
GitHub desktop no longer displays history of any of my repositories when I click the history tab. And the sync button has disappeared for every repository also. I tried uninstalling and reinstalling GitHub desktop and restarting, but to no avail. Any help would be appreciated.

**Comment by TPS** [comment]
This isn't official GitHub support, & it sounds like you need them _desperately. __After___ searching https://help.github.com/, try https://github.com/contact.

**Comment by cirosantilli** [comment]
Please make titles more precise, explaining what stopped working there. Updated with a suggestion.

**Comment by TPS** [comment]
@joclaxton Is this solved, or are you pursuing another course of support?

**Comment by joclaxton** [comment]
Thanks. After several reboots it finally displayed correctly and I was able
to commit and sync. Sorry if I was using the incorrect forum. I hadn't had
to post about an issue before and was rushing to troubleshoot.

On Wed, Jun 1, 2016 at 7:28 PM, TPS <notifications@github.com> wrote:

> @joclaxton <https://github.com/joclaxton> Is this solved, or are you
> pursuing another course of support?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/isaacs/github/issues/681#issuecomment-223179526>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKppKQZqO0un2FvyzNo9NENhA5qzMvv1ks5qHj-0gaJpZM4InCmY>
> .
>



-- 

Jo Claxton
Art Director  |  Cricket Moon Media, Inc.

p: 206-448-5854 x710
www.cricketmoonmedia.com
jo@cricketmoonmedia.com <brian@cricketmoonmedia.com>

**Comment by Bhlowe** [comment]
I see this issue is closed, but I have the same problem on my Windows github desktop where the sync button is missing. I've just sent a message to support@github.com (2/27/2017) with screenshots and my log.

**Comment by aaronbrackett472** [comment]
@Bhlowe what did you find out?

**Comment by Bhlowe** [comment]
@aaronbrackett472  I never got a reply on my bug report. 
But I haven't seen the problem in over a month.. so maybe there was an update? 
Currently using (3.3.4.0) 50415df
Quitting and restarting always seemed to fix it.
