### ISSUE TITLE
Meta: Implement & Use [Parity] Label/Flag

### ISSUE THREAD

**Issue by TPS** [isaacs/github#683]
An increasing # of issues are of the form "I wish/need/would-*{fill-in-the-blank}*-for this feature that _{fill-in-GitHub-competitor}_ has, & ___then___ I'd happily move to GitHub!!!!1!!!l!!!"  I think a <kbd>Parity</kbd> Label/Flag/Tag would be instructive to @GitHub as to where they're losing customers to the competition, & perhaps help them prioritize among the endless issues here.

https://github.com/isaacs/github/issues?q=GitLab+OR+BitBucket+OR+SourceForge+OR+LaunchPad+OR+CodePlex+OR+%22Google+Code%22 would be a great starting point as to which issues would benefit from <kbd>Parity</kbd>.

**Comment by TPS** [comment]
Thanks, @Delapouite, for your support!

@cirosantilli Would you mind tagging this <kbd>Meta</kbd>?  (If you _also_ tag this <kbd>Parity</kbd>, you might as well close it, too.… :wink:)

**Comment by cirosantilli** [comment]
;-)
