### ISSUE TITLE
Zen Mode

### ISSUE THREAD

**Issue by Mottie** [isaacs/github#686]
Am I missing something, what ever happened to [Zen Writing mode](https://github.com/blog/1379-zen-writing-mode)?

**Comment by Mottie** [comment]
Response:

> Hi Rob,

> Sorry for the trouble. We removed the zen mode feature a little over 9 months ago. We found that is was only used by a small percentage of users, and it was also the source of a few problems.

> Let us know if you have any other questions.

> Cheers,
Jamie

:cry:

**Comment by TPS** [comment]
Sorry, @Mottie (:broken_heart:), not even ***I***'m ADHD enough to miss _this_. :wave:  My condolences, though.

**Comment by cameronroe** [comment]
Ah, Zen Mode should come back. I assume it wasn't promoted enough. Did developers know about it? I think it's great!

**Comment by corysimmons** [comment]
lol, just started using Github Issues as my blogging platform and I'm stuck with a narrow Issue editor. RIP
