### ISSUE TITLE
Private GitHub Pages

### ISSUE THREAD

**Issue by jerrylopez** [isaacs/github#699]
Something I've been wanting to see for some time now is being able to host private sites that can only be viewed internally ie: members of an organization or team or even just collaborators to a single repository. The main use case I see for this is internal documentation. 
1. Is this something that has been considered?
2. How difficult would it be to implement something like this? 

I've seen [Jekyll Auth](https://github.com/benbalter/jekyll-auth), but it would be much better to have the site hosted with GitHub Pages instead of hosting elsewhere.

**Comment by kahboom** [comment]
Even just private pages on an existing repo, whether public or private, would be helpful.

**Comment by xenophenes** [comment]
Is there any kind of ETA on this?

**Comment by awkaiser** [comment]
@xenophenes not that I'm aware of.

This repo is merely an unofficial wishlist with (as of this writing) _918 ideas._ 😆

**Comment by AnthonyWC** [comment]
Come on Github; this is 2018 and we still don't have private Github pages for their paying customers.

**Comment by 1c7** [comment]
Same question

### Background
I am using [VuePress](https://vuepress.vuejs.org/guide/#why-not) to write internal API document.
and I don't want the doc be public on Github Pages

**Comment by webbrandon** [comment]
@microsoft

**Comment by brbernardo90** [comment]
@Microsoft, private pages will be great for internal documentation!

**Comment by VictorCoding** [comment]
Still want this in 2018

**Comment by mikej100** [comment]
I've found DocFX (MS) a really nice solution to auto-generating documentation of my company's C#(MS) solution.  It is nicely github (MS)  compatible and I was expecting to be able to publish on github ages as described MS DocFX documentation. But find I cannot (not in public domain). 
This seems to be an big gap in the MS experience.

**Comment by UltraVisual** [comment]
Is this still not possible? we are paying customers and still don't get this functionality...

**Comment by TylerAP** [comment]
Same boat as @mikej100 here

**Comment by TylerAP** [comment]
FYI, GitLab has done work on this subject...
https://forum.gitlab.com/t/can-i-make-gitlab-pages-private/2484/3

**Comment by rishiloyola** [comment]
It's 2019. Any plans to launch this feature? 
Come on Github and @Microsoft

**Comment by jeankvd** [comment]
@Microsoft pls

**Comment by rishiloyola** [comment]
I found the solution for myself. 
I used cloudflare to attach github auth with my domain name.

**Reference:**
https://developers.cloudflare.com/access/setting-up-access/
https://help.github.com/en/articles/using-a-custom-domain-with-github-pages

**Comment by ericraio** [comment]
@microsoft Please take a look.

**Comment by GGAnderson** [comment]
one more use case:   API documentation that lives close to source control - but requires restricted access to partners only...  ReDoc is great, and builds cleanly with GitHub Pages, but not all of us want our API documentation hanging out in public.   Come on @microsoft  this could/should be a strategic enhancement.

**Comment by martin-slater-vgw** [comment]
Just a me +1. Was looking for an easy way to publish project docs that live along side the code and though githubs page but alas no as they are public only

**Comment by captn3m0** [comment]
@rishiloyola Your solution won't be secure right, since GitHub will still let users visit the page directly if they bypass CloudFlare. (By adding the GitHub Pages in their `/etc/hosts` for eg). Even the CloudFlare docs mention that as a requirement:

>To secure your origin, you must first enable Argo Tunnel or limit connections to your origin to only allow Cloudflare IPs and verify the JWT per the instructions here.

Since GitHub doesn't support that, anyone can make request to the GitHub origin fairly easily.

**Comment by pdurbin** [comment]
I just found http://kinlane.com/2013/10/15/securing-site-that-runs-on-github-pages-with-json-backend-in-private-repository/ via https://ask.cyberinfrastructure.org/t/how-do-i-provide-authentication-on-github-pages/950 but I haven't tried it myself. It looks like you can see some of the code in action at https://github.com/api-commons/api-commons/blob/32aad829d086b3d9efed3818a7b98694f63f63f2/_includes/top.html

**Comment by captn3m0** [comment]
^ That looks like it puts your GitHub token in the URL, I wouldn't recommend using that.

Alternative solution (Not GitHub pages): https://www.netlify.com/docs/identity/

**Comment by andrewkamm** [comment]
Similar to @captn3m0's suggestion of Netlify, I've been following this ticket for quite a while and finally settled on Surge.sh to host a static project that needed basic access authentication. Auth requires a paid plan, which was fine for my situation.

**Comment by andreygrehov** [comment]
GitBook has private spaces. Isn't it the same?

**Comment by damianesteban** [comment]
Cloudflare Access is the easiest solution for now.

**Comment by playmoogley** [comment]
> GitBook

to expensive.

**Comment by renanbatel** [comment]
I was able to deploy a static site to AWS S3 with authentication through CloudFront using Lambda@Edge. I made a boilerplate for a documentation site using Gatsby and configured the deploy for AWS using Pulumi. It's a possible solution for you guys that want a private documentation site since the price for using these AWS services are really small.

https://github.com/renanbatel/gatsby-docz-mermaid

**Comment by westurner** [comment]
FWIW, GitLab now supports access control for GitLab Pages (in GitLab CE, EE, and on https://gitlab.com)

Settings > General > Visibility, project features, permissions > Pages
https://docs.gitlab.com/ce/user/project/pages/pages_access_control.html

**Comment by bpeake-illuscio** [comment]
Just want to drop in here that my company may decide to pull the trigger and move over to gitlab for the private pages so we can host documentation more easily.

It's a shame, I've been paying for github and will continue to use Azure Devops, but the lack of access controls around github pages is a bummer.

**Comment by doodirock** [comment]
We would drop Netlify entirely if we could have private pages to share with clients.

**Comment by americos** [comment]
Would be great to have this feature, Github has released a lot of good features since Microsoft acquisition, really hope they can soon include this one too.

**Comment by fqassemi** [comment]
The original post was for 2016, and it is 2020 and yet I can not find how to host my github pages privately.

**Comment by patcon** [comment]
This works with a small auth proxy hosted on heroku (only used to auth against github password or scope-less token) https://github.com/comsysto/github-pages-basic-auth-proxy

But it's served from GitHub Pages

**Comment by 1beb** [comment]
Bump

**Comment by ericraio** [comment]
I've been using gitlab because github doesn't have private pages and gitlab does

**Comment by rxcolvin** [comment]
I could really use this feature.

**Comment by bpeake-illuscio** [comment]
I've also been evaluating moving to gitlab for this feature. I've had a really good experience with github so far, but this seems to be a pretty glaring omission for enterprise tooling.

**Comment by j8r** [comment]
Hello, missing also this feature, I created a little GitHub Application to put GitHub Pages being GitHub OAuth: https://privpage.net.

**Comment by j8r** [comment]
Hello, missing also this feature, I created a little GitHub Application to put GitHub Pages behind GitHub OAuth: https://privpage.net.

**Comment by 1beb** [comment]
@j8r Some implementation details would be great. Where is the oauth happening?

**Comment by captn3m0** [comment]
@j8r I would recommend not using a shared-domain-across-all-repos, since that results in the same origin policy being bypassed along with untrusted javascript.

Sent a message on Gitter with more details

**Comment by j8r** [comment]
Thanks @captn3m0 , I already thought on this security attack and add a protection for it. Let's talk on the dedicated Chat :wink:

**Comment by j8r** [comment]
@1beb Good idea. I plan to release the source code soon, I think it is the best way to have the best and most secure service possible, and everyone could eventually host it too.

**Comment by j8r** [comment]
Good news, the site is back online:
- subdomains are used for better security (CSP)
- The source code is now available: https://github.com/Priv-Page/privpage
- A basic architecture overview is present to explain how the service works
- Feel free to chat, open issues an PRs - more importantly if security related

Thank you :slightly_smiling_face:

**Comment by galenzhao** [comment]
how can I make my organization repos private with pages enabled?
I'm using github pro now.

**Comment by j8r** [comment]
@galenzhao That's not possible, unfortunately, even being `pro`. What a shame... That's why I launched https://privpage.net.
If you are interested, you can follow the instructions here: https://privpage.net. Pro is not needed, it works for all accounts.
Only those having read access to the repository will access to the page.

**Comment by rituvesh** [comment]
Come on Github; this is 2020 and we still don't have private Github pages for your paying customers.

**Comment by jerrylopez** [comment]
Just posted a tweet regarding this issue. Might get a better response there: https://twitter.com/_jerrylopez/status/1283956440542121985?s=21

**Comment by jerrylopez** [comment]
So turns out GitHub has a roadmap repo now and I found this: https://github.com/github/roadmap/issues/77

**Comment by j8r** [comment]
@jerrylopez Note that is noted to be only available for Enterprise customers.

**Comment by Radon8472** [comment]
Basicly the should not be this difficult.
Uses simply could add a `.htaccess` file to their github repo, but the Github Server needs to provide a method how you can add the pass to the `.htpasswd` file, because it is currently there is no native way to use relative path for htpasswd only some workarrounds like you can read at [relative-path-with-authuserfile]


[relative-path-with-authuserfile]: https://stackoverflow.com/questions/6111627/how-to-use-a-relative-path-with-authuserfile-in-htaccess

**Comment by skamensky** [comment]
I would love this feature.

**Comment by yoannchaudet** [comment]
👋,

This is actually on the [public roadmap](https://github.com/github/roadmap/projects/1?card_filter_query=private+pages) and coming by the end of the year ([issue](https://github.com/github/roadmap/issues/77))!

**Comment by bpeake-illuscio** [comment]
That's excellent news!

**Comment by j8r** [comment]
Note for everyone here that is this **only** for `GitHub Enterprise` users.
> For GitHub Enterprise users, they'll be able to make their Pages sites private to the world.

This means, those on `Free` or `Team` (see [pricing](https://github.com/pricing)) won't be able to benefit from this feature.

I don't say it is good or bad; it is a fact and this choice is understandable.

**Comment by j8r** [comment]
Note for everyone here that this is **only** for `GitHub Enterprise` users.
> For GitHub Enterprise users, they'll be able to make their Pages sites private to the world.

This means, those on `Free` or `Team` (see [pricing](https://github.com/pricing)) won't be able to benefit from this feature.

I don't say it is good or bad; it is a fact and this choice is understandable.

**Comment by doodirock** [comment]
Pretty lame

**Comment by doodirock** [comment]
Only for enterprise???  Lame

**Comment by Yehonal** [comment]
Any news about the eta?

**Comment by BBI-YggyKing** [comment]
I would also like this feature. I want to be able to publish internal documentation for my organization via a GitHub repository. I want the site visibility to be broader than the repository visibility - Active Directory authentication would be ideal.

In the meantime some use cases for internal documentation can be met with either ...

- GitHub wiki pages, associated with a repository. Wiki pages are edited in the web interface, using Markdown. This is useful for project documentation related to the repository to which the wiki is attached. Note that wiki pages do not go through the usual pull request and review process.
- Creating Markdown pages (.md files) directly in the repository. This can be done directly through the web interface, which supports adding or editing files on a new branch, pull requests, etc.

I still want private site hosting, but these are my workarounds for the time being.

**Comment by yoannchaudet** [comment]
After a slight delay, the feature just shipped today. More details in the [changelog](https://github.blog/changelog/2021-01-21-access-control-for-github-pages/).

**Comment by brokenthumbs** [comment]
@yoannchaudet 

> This feature is generally available today on GitHub Enterprise Cloud.

Are there any plans to bring this feature to other plans, such as [GitHub Team](https://github.com/pricing)?

**Comment by bpeake-illuscio** [comment]
Is Github Enterprise Cloud different from Github Enterprise?

We have an enterprise account, but I do not see the Github Pages visibility setting.

**Comment by yoannchaudet** [comment]
@brokenthumbs No plans at this time, no.

**Comment by rituvesh** [comment]
Thanks a lot to team Github pages for providing such a nice feature for your users. We are using it now and really very happy. :)

**Comment by mbylstra** [comment]
🎉

**Comment by Kal-Aster** [comment]
Why is this issue still open?

**Comment by jerrylopez** [comment]
This is not an officially managed GitHub repo, but I'll go ahead and close it

**Comment by samwightt** [comment]
Super disappointing that this is only available to enterprise customers and not teams. We'd love to use this internally for hosting documentation, but we have no choice but to look elsewhere.

**Comment by Levi-Lesches** [comment]
If you want to get in touch with GitHub, go to [their official support repo](https://github.com/github/feedback/discussions/categories/general-feedback) and open a discussion there.
