### ISSUE TITLE
add new issue label in issues dropdown on issue page

### ISSUE THREAD

**Issue by isaacs** [isaacs/github#7]
When I want to tag an issue with a label, sometimes that label doesn't exist yet.  It's annoying to have to go to a separate page to create the new label, because that breaks the flow.

It would be great if it worked like the label drop-down in gmail.  You start typing into a text box, and that filters by all the labels, but also has a link at the bottom to create a new label by that name.

**Comment by bboreham** [comment]
This feature exists now.
