### ISSUE TITLE
Going back from issues to issue list

### ISSUE THREAD

**Issue by dandart** [isaacs/github#704]
Seems when I go "back" from an issue - I arrive at the home page - I was expecting to end up at the page containing the issues (i.e. the page I came from).

Emailed GitHub about this.

**Comment by cirosantilli** [comment]
How are you going back to the issue list? What is your browser version?

I don't reproduce either with browser back button on firefox 47, nor clicking on the Issues tab.

**Comment by dandart** [comment]
It must have been something very brief - it's all good now thanks
