### ISSUE TITLE
Transparent avatars have white background added

### ISSUE THREAD

**Issue by kblanks** [isaacs/github#707]
https://github.com/HungerStruck
The original image is transparent, however a background has been added to this one.

This was not previously an issue as you can see an old avatar works fine here: https://github.com/DevelopersChat

I created a test organisation and uploaded a random transparent image and the issue occurred there. Not sure how long this has been an issue however it definitely wasn't 3 months ago.

**Comment by kblanks** [comment]
Even [Twitter](https://github.com/twitter) is affected.

**Comment by cirosantilli** [comment]
Transparency somewhat changes the page "behavior", maybe it is wise to get rid of it. Not sure though.

**Comment by TPS** [comment]
@cirosantilli Why close?

**Comment by kblanks** [comment]
The issue appears to be resolved. Re-uploading the picture now works.

**Comment by chorlacher** [comment]
I'm experiencing the same issue, apparently years after it was resolved?
