### ISSUE TITLE
Allow uploading of `.log` files in comments

### ISSUE THREAD

**Issue by rattrayalex** [isaacs/github#713]
When I try to upload a file with the extension `.log` to a comment box, I get the message:

> Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

Needless to say, I simply renamed my .log file to a .log.txt and it worked. But it would be nice if .log were supported natively, as its really the same thing.

**Comment by cirosantilli** [comment]
Or maybe: server any unrecognized ASCII file as plain ASCII.

**Comment by brollb** [comment]
+1

**Comment by cirosantilli** [comment]
@brollb please use the new +1 button feature instead of comments to avoid notifying people and have an automated upvote count ;-)

**Comment by TPS** [comment]
Implemented, per https://github.com/isaacs/github/issues/373#issuecomment-749152492.
