### ISSUE TITLE
Merge status of pull requests

### ISSUE THREAD

**Issue by paulyoung** [isaacs/github#72]
Even if I don't have the ability to perform the merge, I'd still like to know if the merge is possible or not.

This would be an indicator that my branch has diverged and that I need to update it.

**Comment by cvrebert** [comment]
@paulyoung  They finally fixed this a while ago. Go look at a random PR in someone else's repo; it now shows the mergeability status.

**Comment by jonathanong** [comment]
:+1:

**Comment by paulyoung** [comment]
Confirmed :raised_hands:
