### ISSUE TITLE
PRs should link to source repo/branch

### ISSUE THREAD

**Issue by alexreg** [isaacs/github#720]
When you view a PR, you get .e.g `alexreg  wants to merge 3 commits into target-repo:master from source-repo:patch`. Unfortunately, neither the `target-repo:master` or `source-repo:patch` bits are links! This is silly, since there is no other good way to navigate to the source repo (or the `patch` branch specifically). I propose simply to make these links.

**Comment by timotheecour** [comment]
duplicate of https://github.com/isaacs/github/issues/720

**Comment by clarkbw** [comment]
duplicate of #34
