### ISSUE TITLE
Add support for attaching .log files on issues

### ISSUE THREAD

**Issue by Tarabass** [isaacs/github#733]
It would be great to have the ability to attach .log files to an issue. If npm has an error it creates a _npm-debug.log_ for me. I then could use it for a proper issue report and attach it instead of copying the whole content.

![attach_log_file_to_issue](https://cloud.githubusercontent.com/assets/462513/17226246/c56bd716-5508-11e6-8c3a-402013e27bae.gif)

**Comment by cirosantilli** [comment]
similar https://github.com/isaacs/github/issues/713
