### ISSUE TITLE
New state named "In Development" and estimation of time for each issue

### ISSUE THREAD

**Issue by HeinPauwelyn** [isaacs/github#737]
> **[Please see the image on my 3<sup>th</sup> comment.](https://github.com/isaacs/github/issues/737#issuecomment-238272500)** or see image below

> ![](https://cloud.githubusercontent.com/assets/16222780/17487957/6c24b37a-5d97-11e6-9fb3-0c16f9ac7a8a.png)

> [Please read my 2<sup>nd</sup> comment. It's an update from this comment.](https://github.com/isaacs/github/issues/737#issuecomment-238183027)

----------------------------
First of all I :heart: GitHub and build all my project with GitHub. I like all the features but there are two things I miss in GitHub namely **backlog lists** and **sprints**.

Here you got the definition of a backlog:

>A backlog is a list of features or technical tasks which the team maintains and which, at a given moment, are known to be necessary and sufficient to complete a project or a release. 
> <sub>— [www.agilealliance.org](https://www.agilealliance.org/glossary/backlog/)</sub>

and here the definition of a sprint:

> In product development, a sprint is a set period of time during which specific work has to be completed and made ready for review.
> <sub>— [searchsoftwarequality.techtarget.com](http://searchsoftwarequality.techtarget.com/definition/Scrum-sprint)</sub>

Notice that **backlog items and sprints are the most important parts of agile development!** 

-----------

For backlog items it are just three columns named "To do", "In progress" and "Done" and all your task you must do are listed under that header with an estimation of you effort you must do and the collaborators. Also by the "Issues" tab, there is a state I miss. On this moment you've got "Open" and "Closed" but for agile development, I'll add this items to the backlog list. Every issue is a new backlog item.

-----------

In the sprints you could work on a specific part of the project the sprints I prefer are:

* First sprint for pre-analyse, wire frames, information structure etc.
* Second sprint for functional and technical analyzes, UI design etc.
* Third sprint for development
* Fourth sprint for testing and finish the application

Notice that the sprints can depend in every team. In this case you could split your work and you could get a better overview for every single part you must do

-----------

Is it possible to include this features in GitHub?

**Comment by TPS** [comment]
AFAIK, these features are maintained in GitHub via [milestones](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/): backlogs via assigning milestones to issues, & sprints via assigning dates to the milestones.

If milestones don't answer your need (other than the terminology), please clarify!  Also, do realize, this isn't official @GitHub support,  just a bunch of loyal users venting & helping each other out.

**Comment by HeinPauwelyn** [comment]
OK forgot everything what I've said in my first comment. The thing I miss in GitHub is something like image below:

![image](https://cloud.githubusercontent.com/assets/16222780/17473272/d06859e2-5d4f-11e6-8108-756281ac04a9.png)

Every yellow rectangle could you use a milestone and the blue rectangles could I use an issue or pull request. It's like a board with four columns.

* The first one are the milestones
* The second and fourth are resp. open and closed issues or pull requests.
* The third is the in development column. &rarr; this state doesn't exist for this moment in GitHub.

Also by every issue or pull request I'll add an estimation of the time (in hours) of your work. For this moment is that on the milestone but's that's more difficult to estimate because an milestone got multiple issues and pull request.

**Comment by TPS** [comment]
_(I think I understand, but correct me if I'm wrong!)_ For each of these purposes, I've seen teams [create](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/) & [use] (https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) _labels_:
- For the dev column above, <kbd>Under Development</kbd>, <kbd>In Progress</kbd>, &c
- For time/difficulty estimation, actual <kbd>_[insert time estimate here]_</kbd> or <kbd>easy</kbd>, &c

Now, for neither milestones nor labels does 1 get a cute _chart_ as above, but an organized _table_ lives at `<`_`project url`_`>/milestones` & `<`_`project url`_`>/labels`, respectively.

**Comment by HeinPauwelyn** [comment]
:thought_balloon:  if you can solve it with labels and milestones for me it's good...

**Comment by TPS** [comment]
Try it & see how it goes:
- If it works well enough for you over the next while, close this issue FTW.
- Else, come back & describe what's not functional enough.

**Comment by TPS** [comment]
Try it & see how it goes:
- If it works well enough for you over the next while, close this issue FTW.
- Else, come back & describe what's not functional enough.

>Or something like this is better.

Once you get your milestones & labels in place, clicking on them will give an issues-list _exactly_ like that.  Try it out & see!

**Comment by HeinPauwelyn** [comment]
And what do you think about this table layout? _(See also my 2<sup>nd</sup> comment)_

![table](https://cloud.githubusercontent.com/assets/16222780/17618414/f7394d64-607f-11e6-8a86-8d039a2f526c.png)

It's just an idee. Each issue is now like an post-it that you could drag and drop to each column.

In the column "Milestone" stand every milestone with on the left side every issue of that milestone in the correct column "Open", "In Development" or "Closed".

**Comment by Mottie** [comment]
There are some third party systems that you can check out:

* [Waffle](https://waffle.io/).
* [YouTrack](https://www.jetbrains.com/youtrack/features/agile_project_management.html). Also see #743.
* [ZenHub](https://www.zenhub.com/).
* [Zube](https://zube.io/).

I'm sure there are more: https://www.google.com/#q=github+project+management

**Comment by animedbz16** [comment]
Or check out GitLab as a GitHub Alternative, since its  an open source project, track their issues in the open and already have implemented features such as this.

https://about.gitlab.com/solutions/issueboard/

**Comment by TPS** [comment]
Do the details of the new [Projects](https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/) feature solve this?

**Comment by HeinPauwelyn** [comment]
Yeah nice it's realy good :smile: :+1:
