### ISSUE TITLE
can't review large changes

### ISSUE THREAD

**Issue by aspiers** [isaacs/github#755]
For example, https://github.com/crowbar/crowbar-openstack/pull/498/files currently shows:

> 2,106 additions, 1,907 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

Maybe this is done to avoid overloading the browser with a huge page, or maybe to avoid overloading the servers, but there should still be some way of reviewing large PRs online, e.g. via some pagination system or similar.

**Comment by TPS** [comment]
#587?

**Comment by aspiers** [comment]
Yes, thanks - I missed that. Closing as a duplicate.
