### ISSUE TITLE
Issue reactions aren't shown on mobile

### ISSUE THREAD

**Issue by strugee** [isaacs/github#767]
(Apparently forgot to file this when I sent it off a couple days ago.)

Issue reactions are neat, but they aren't shown in the mobile view of Issues. This is unfortunate, and should probably be rectified at some point.

**Comment by strugee** [comment]
> And here's the response from GitHub support on 9/8/16:
> 
> Hey Alex,
> 
> Thanks for getting in touch - the team is continually adding features to the mobile version of the site, but like you found, it's not a 100% match to the desktop version. I can't make any promises, but we'll definitely let the team know that you'd love to see reactions on the mobile version of the site.
> 
> If you have any other questions, please let me know!
> 
> Cheers,
> Antonio
> GitHub Support

**Comment by TPS** [comment]
Specific instance of #141.

**Comment by spottedmahn** [comment]
+1

The +1 thing makes the issue so noisy.  Please implement reactions on the mobile site!

**Comment by whereisaaron** [comment]
+1 indeed, I'd love to use reaction instead here, but there is no way to do it when on my phone, the feature is entirely missing. Almost as bad, I can't see other people's reactions. (Are you reacting? "+1" if you are :-)

I like to complain about all the +1 threads, but since mobile users including myself have no better way to do it, I guess github is saying "+1" away!

If github can't make the functionality/experience consistent, just remove the reactions feature entirely.

**Comment by NobbZ** [comment]
When I'm on my mobile, I do have a link at the bottom right of the page which I can click to get to the desktop version of GitHub. It then has a bold bar at the top of the page which brings me back to mobile view. Try it.

**Comment by strugee** [comment]
@NobbZ yes, but then what's the point of having a mobile view at all? The desktop application just doesn't work that well on a small screen.

**Comment by whereisaaron** [comment]
@NobbZ @strugee plus if you click on desktop version it adds a huge banner, you can't close, that says "Switch to mobile version". Takes up 1/3 of the screen in landscape.

![image](https://user-images.githubusercontent.com/1109585/34401191-fa523448-eb66-11e7-9da1-aaa8ded6a90c.png)

**Comment by NobbZ** [comment]
It's much smaller for me, but I do portrait only...

Also it's only a workaround until GH fixes the issue, also @whereisaaron said seeing reactions on a mobile were impossible, I've just shown it's possible.

**Comment by whereisaaron** [comment]
Ok got it, if we don't use the mobile site we won't experience any problems with the mobile site. Problem solved! Thanks @NobbZ! :-)

**Comment by strugee** [comment]
Closing since GitHub did this. _Finally_.

**Comment by whereisaaron** [comment]
Noice! Looks like they did a good job too; Small things like the way it has the button is also at the bottom if the comment is a longer one. This will be a great help.

**Comment by Nhowka** [comment]
On Edge mobile I can't close the reaction pop-up. It's getting in the way and now can only read issues on the desktop mode. ☹

**Comment by whereisaaron** [comment]
I had to Google what 'Edge mobile' was @Nhowka 😄
You might need to try reporting it to Github as a new issue, as they probably don't test that browser.
