### ISSUE TITLE
A way to filter issues that are currently unassigned

### ISSUE THREAD

**Issue by rhallie15** [isaacs/github#773]
When working on projects that have a lot of issues (but also a lot of people working on different things), it would be nice to be able to type something like `is:unassigned` or `assignee:false` (first probs makes more sense) and only see issues that need to be claimed.

**Comment by hwine** [comment]
The [docs](https://help.github.com/articles/searching-issues/#search-by-missing-metadata-on-an-issue-or-pull-request) give ``no:assignee`` as the way to phrase this request.

**Comment by aspiers** [comment]
I tested this and it seems to work for me both in global searches and repository-wide searches.  So I think this issue can be closed.

OTOH, it would also be nice to be able to filter issues that are currently assigned to *anyone*.

**Comment by hwine** [comment]
@aspiers ``assignee:*`` does that I believe.

**Comment by aspiers** [comment]
@hwine Did you actually try that? I tried it before filing this issue, and it didn't (and still doesn't) work for me.

**Comment by hwine** [comment]
@aspiers yes - it works for me! 😄 The ```assignee:*``` syntax translates to this URL:
```
  https://github.com/jupyter/notebook/issues/assigned/*
```
Which currently returns (for me) 17 open, 43 closed, and there is an icon fore each line.

Contrast with the default query:
```
  https://github.com/jupyter/notebook/issues
```
Which returns 421 open, 629 closed, and only 1 icon on the first page.

Or using the ```no:assignee``` query term:
```
  https://github.com/jupyter/notebook/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no%3Aassignee
```
Which returns 404 open, 586 closed.

**Comment by aspiers** [comment]
So apparently this works in repository-wide searches, but not global searches, e.g. [user:crowbar is:pr is:open assignee:*](https://github.com/search?utf8=%E2%9C%93&q=user%3Acrowbar+is%3Apr+is%3Aopen+assignee%3A*&type=Issues&ref=searchresults).

**Comment by aspiers** [comment]
I've submitted #782 regarding that problem with global searches for assigned issues. Can someone please close this issue, since it's resolved?

**Comment by cscuderi** [comment]
I'm having trouble searching for issues that:
- Are NOT labeled with a certain label
- Are assigned to anyone

E.g., I want to search for issues that are NOT high priority and assigned to anyone so that I can run through them during our issue triage meeting. If I use this syntax: `is:issue is:open sort:updated-desc -label:"Priority: High" assignee:*` zero issues are returned.
