### ISSUE TITLE
No way to see "approved" pull requests in the list

### ISSUE THREAD

**Issue by dylanpyle** [isaacs/github#774]
The `/pulls` list shows the status of the PR checks (tests, etc) but not the status of whether a PR is approved via the new reviewing tools - makes it hard to know what needs review without building a manual solution using tags.

Here's an example - only one of these PRs has been approved, but 5 have fairly misleading green checkmarks:

![screen shot 2016-09-21 at 9 22 24 am](https://cloud.githubusercontent.com/assets/806257/18719695/4b3d0dde-7fdd-11e6-9974-f12155f4506e.png)

**Comment by thastings3** [comment]
This would be great

**Comment by fedorov** [comment]
This issue is resolved - see screenshot below, last item on the list is approved as annotated with the word "Approved"

![image](https://cloud.githubusercontent.com/assets/313942/23147454/00fdff24-f7ad-11e6-97f3-b6473a506e7b.png)

**Comment by kc-farrell** [comment]
I think the original question was similar to mine. How can I see a list of pull requests that are assigned to me, for Approval, but have not yet been approved. And additionally, how to see a list of pull requests that I have approved already, recently, etc. Or both, in the same table, that can be sorted.

**Comment by jaimemarijke** [comment]
I would also like to see this. Currently, my Pull Request dashboard shows me a list of PRs that need my approval. However, I would also like to see PRs that are still open, that I have already approved, so that I can go back and look at them if something changes in the PR and I want to review it again.
