### ISSUE TITLE
distinguish between PR reviewers and drivers

### ISSUE THREAD

**Issue by aspiers** [isaacs/github#778]
The [new PR review system](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) is a promising step in the right direction.  However it has blurred the semantics of the older "Assignees" feature, which was already somewhat ambiguous, particularly since the introduction of the ability to have [multiple assignees](https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests).  [As mentioned in #92](https://github.com/isaacs/github/issues/92#issuecomment-249160266), it's no longer clear who has been assigned the separate responsibilities of reviewing and merging the PR.

For example, if two people are assigned, does that mean:
- one is responsible for reviewing and the other for merging? or
- both for reviewing and one for merging? or
- both for reviewing, and both collectively for merging (even though ultimately only one can merge)? 

With more than two assignees, this becomes even more ambiguous.

Ideally GitHub should take a leaf out of gerrit's book, and make it possible to nominate individual reviewers for each PR (maybe even teams as well).  Of course, people can already be pinged about a review via a `/cc @username` in the PR description or comment, but this is unstructured data which cannot be easily queried via the API or UI, to satisfy use cases such as "give me a list of all PRs I have been requested to review".

If this was added, then the Assignee field could remain as a distinct way of tracking ownership of the _resolution_ of the PR, so that it's clear who's ultimately responsible for driving it to completion, whether that be by owning the final merge-or-close decision, or just ensuring that such a decision is appropriately delegated if necessary.

**Comment by aspiers** [comment]
As noted in https://github.com/isaacs/github/issues/783#issuecomment-250482249 just now, (ab)using the list of Assignees for tracking the expected reviewers of the PR, rather than tracking via a dedicated list, creates extra problems when new changes are pushed to the PR.  Again, this is something which the gerrit UI gets right.

**Comment by dirkmueller** [comment]
I guess this can be closed now?

**Comment by aspiers** [comment]
@dirkmueller Correct!  Here is the announcement of the change which addresses this issue:

https://github.com/blog/2291-introducing-review-requests
