### ISSUE TITLE
need API for protecting branches via code review approvals

### ISSUE THREAD

**Issue by aspiers** [isaacs/github#781]
As everyone knows, [GitHub recently released a new code review system](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features).  It's now possible to protect a branch so that a PR to that branch can only be merged after it has been approved by at least one reviewer and had no disapprovals.  However AFAICS it's not possible to get or set this configuration parameter via the API.  The example API response for getting branch protection still only returns the traditional required status checks, with no mention of whether approval via code review is also required: 
- https://developer.github.com/v3/repos/branches/#get-branch-protection

**Comment by scottdweber** [comment]
It's available now!!!

https://developer.github.com/changes/2016-12-08-protected-branch-pull-request-reviews/

**Comment by newdark** [comment]
Here is also a link to the update reviews proted branch https://developer.github.com/v3/repos/branches/#update-pull-request-review-enforcement-of-protected-branch

**Comment by aspiers** [comment]
@scottdweber @newdark Thanks a lot for the info!  So IIUC this can now be closed.  (If not please correct me and I'll reopen.)
