### ISSUE TITLE
Pressing <tab> after placing comment does not select post comment button

### ISSUE THREAD

**Issue by TimvdLippe** [isaacs/github#786]
It seems that GitHub has changed their focus management. Previously selecting the edit box and then hitting `<tab>` would select the post comment button. However, now 3 `<tab>`'s are required to select the button. Moreover, when creating a new issue and selecting the title input and pressing enter does not select the issue description. Instead, it directly goes to the "submit new issue" and then moves focus to the top bar.

**Comment by cirosantilli** [comment]
Note that control enter also works.

**Comment by TimvdLippe** [comment]
I am closing this as I have been using control + enter ever since and never needed to tab. Thanks @cirosantilli for the tip!
