### ISSUE TITLE
Assigning an issue to multiple milestones

### ISSUE THREAD

**Issue by mattbrunetti** [isaacs/github#797]
Our organization would like to be able to assign an issue to multiple milestones. 

In our case, this is because management wants to track some things that they require to sign off on this stage of our project, we developers also want to track some things that we require to sign off, and some are overlapping.

It seems initially that this feature is implemented...

1. I am viewing an issue.
2. I click "Milestone" in the right-hand panel, and see a drop-down where the "Management Acceptance" milestone is checked.
3. I click the "Developer Acceptance" milestone, and see that the timeline is updated with the following...
@mattbrunetti mattbrunetti modified the milestone: Developer Acceptance, Management Acceptance a minute ago

But! When I click "Milestone" in the right-hand panel again, only "Developer Acceptance" is checked, and when I view the Management Acceptance milestone, the issue is missing. 

Please fix, pretty please?

Thanks :)

**Comment by bardiharborow** [comment]
Per ["Mastering Issues"](https://guides.github.com/features/issues/):

> A milestone acts like a container for issues. This is useful for associating issues with specific features or project phases (e.g. Weekly Sprint 9/5-9/16 or Shipping 1.0).

Milestones are designed for tracking iterations in your development cycles, whether it be versions or some other system. It does not make sense to assign two milestones to an Issue. Labels are a much better system for tracking this sort of information. Something to the effect of `DevAcceptRequired`, `DevApprovalGranted`, `ManagementApprovalRequired` and `ManagementApprovalGranted`.

**Comment by mattbrunetti** [comment]
Thanks @bardiharborow .. you make a good point, and after some thought, I think that's how we'll handle it. :+1:

**Comment by mattbrunetti** [comment]
We can have hyperlinks to views of issues that show, e.g., only `ManagementApprovalRequired`, and share those with the concerned parties.

**Comment by jmakeig** [comment]
@bardiharborow:

> It does not make sense to assign two milestones to an Issue.

What if the issue is a bug that appears in two separate versions that have different release cycles, e.g. major v1 gets monthly maintenance releases, but major v2 won’t ship for another quarter? Do you create a different, duplicate issues that have v1 milestone and a v2 milestones respectively? How do you sync those issues?

**Comment by bardiharborow** [comment]
@jmakeig you make a valid point. I suppose my opinion stemmed from the fact I work mainly in continuously deployed environments where you don't have a old version to backport fixes to.

**Comment by dkozel** [comment]
This issue duplicates https://github.com/isaacs/github/issues/441

**Comment by lsh-0** [comment]
+1

In my case, our process does not match Github's anticipated usage. We have multiple teams with multiple milestones where issues occasionally overlap and the teams goals converge. When separate teams converge on issues that is an indication (and opportunity!) that greater cooperation and coordination is required.

**Comment by lsh-0** [comment]
> This issue duplicates #441

just saw this :P

this ticket should be closed in favour of #441 that has much more recent activity
