### ISSUE TITLE
[Bug] Issue actions attributed to wrong user in clahub/clahub#150

### ISSUE THREAD

**Issue by strugee** [isaacs/github#813]
What the issue title says. If you visit https://github.com/clahub/clahub/issues/150, it states that I'm the one who assigned the issue and added the "bug" label, but it was definitely @mzagaja. (There's a screenshot there.)

This is obviously a semi-serious bug.

**Comment by cirosantilli** [comment]
Interesting! http://web.archive.org/web/20161111080306/https://github.com/clahub/clahub/issues/150

I would try to reproduce if GitHub hadn't closed my test secondary account.

Can you open an issue at: https://github.com/cirosantilli/test-git-web-interface/issues ?

**Comment by strugee** [comment]
@cirosantilli sorry, forgot to do that! In any case, here's the reply from GitHub support:

> 
> Hi Alex -
> 
> Thanks for reaching out and asking us about this.
> 
> A few days ago, we had an errant update that was not properly updating that "actor", which caused it to fall back to the author of the thread. This did not affect our checks surrounding permission levels or repo access. Our team has since then pushed a fix for this.
> 
> We can confirm that this did not lead to any compromise or exposure of permissions or privileges to accounts who should not have them.
> 
> We hope this context helps, but let us know if you have any other questions!
> 
> All the best,
> GitHub Staff

So it seems resolved.
