### ISSUE TITLE
[Bug] Emoji don't show on mobile

### ISSUE THREAD

**Issue by strugee** [isaacs/github#820]
Emoji like :thumbsup: don't appear on my mobile GitHub Issues view.

I'm on a Nexus 6P running CyanogenMod 13.0-20160819-SNAPHSHOT based on Android 6.0.1. My web browser is Firefox Nightly, built 2016-11-13.

**Comment by TPS** [comment]
Duplicates #767, since official GitHub term for these is "reactions."

**Comment by strugee** [comment]
@TPS shoot, wish I'd been more clear before sending to GitHub... I'm not talking about the reactions feature, I'm talking about literally typing `:thumbsup:` in an issue body

**Comment by strugee** [comment]
For example, viewing this issue on my phone, I see a blank space in between the words "like" and "don't" in the first sentence of the description.

**Comment by TPS** [comment]
That's definitely your device.  From my experience, @Github renders using native fonts on mobile, & PNGs on desktop.  Either way, you _should_ receive graphical representation.  Do anything strange to your device?

**Comment by strugee** [comment]
@TPS it's definitely _not_ my device. GitHub emoji work in stable Firefox and Chrome and emoji rendering works in all other apps. Also frankly CyanogenMod snapshots are quite stable.

(Wish I'd thought to include that info in my original report... oh well.)

**Comment by strugee** [comment]
@TPS why'd you delete your comment?

**Comment by TPS** [comment]
@strugee Original comment was irrelevant & confused :wink: Ok, so Ff nightly probably to blame.  If stable works, file on Bugzilla, not here.

**Comment by strugee** [comment]
@TPS it's definitely Nightly. I filed here because I suspected GitHub was at fault, not Firefox, as emoji have seemed to work elsewhere. However upon further investigation, GitLab (which I was using to compare) uses images. So I'm not so sure anymore.

Let's see what GitHub says. If it's really Nightly bug, I'd be more than happy to file a bug on BMO.

**Comment by TPS** [comment]
Just to be sure, since @GitHub _doesn't_ follow here, you _did_ send a note to support@ or https://github.com/contact, right?

**Comment by strugee** [comment]
@TPS correct. And here's the response: 

> Hi Alex,
> 
> Thanks for reporting this. We don't provide support for beta or nightly releases of web browsers. Please can you try using the current stable release of Firefox and see if this issue persists?
> 
> Thanks,
> Alex

Will reply in the morning... /me is currently exhausted

**Comment by strugee** [comment]
Just about to send this off to GitHub:

**Comment by strugee** [comment]
Closing given that this isn't a GitHub issue.

**Comment by TPS** [comment]
Then probably close this FTW. :checkered_flag:

**Comment by strugee** [comment]
From GitHub support (for completeness):

> Hi Alex,
> 
> No worries!
> 
> All the best,
> Alex
