### ISSUE TITLE
foo

### ISSUE THREAD

**Issue by shafeeq** [isaacs/github#831]
[{:response {:status 200, :body {:id "08066a86-89be-4c26-a658-7c843dd0d4fd", :is-active true, :created "2016-12-02T11:56:51Z", :label "UvdF0D8JBX", :merchant-id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :merchant-pos-id "u8HwIG4B"}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "198", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "createPoSTerminal", :request {:method :post, :url "http://localhost:8080/management/pos-terminal", :body {:label "UvdF0D8JBX", :merchant-id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :merchant-pos-id "u8HwIG4B", :headers nil}}, :ts "2016-12-02T11:56:51.778Z"} {:response {:status 200, :body {:id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :name "s48pEpj", :is-active true, :created "2016-12-02T11:56:51Z", :modified "2016-12-02T11:56:51Z", :config {:providers {:vault "ibm", :payment "ibm"}}}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "201", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "lookupMerchantByName", :request {:method :get, :url "http://localhost:8080/management/merchant/name/s48pEpj", :body {:headers nil}}, :ts "2016-12-02T11:56:51.561Z"} {:response {:status 200, :body {:id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :name "s48pEpj", :is-active true, :created "2016-12-02T11:56:51Z", :modified "2016-12-02T11:56:51Z", :config {:providers {:vault "ibm", :payment "ibm"}}}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "201", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "createMerchant", :request {:method :post, :url "http://localhost:8080/management/merchant", :body {:name "s48pEpj", :config {:providers {:vault "ibm", :payment "ibm"}}, :headers nil}}, :ts "2016-12-02T11:56:51.365Z"}]

[{:response {:status 200, :body {:id "08066a86-89be-4c26-a658-7c843dd0d4fd", :is-active true, :created "2016-12-02T11:56:51Z", :label "UvdF0D8JBX", :merchant-id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :merchant-pos-id "u8HwIG4B"}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "198", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "createPoSTerminal", :request {:method :post, :url "http://localhost:8080/management/pos-terminal", :body {:label "UvdF0D8JBX", :merchant-id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :merchant-pos-id "u8HwIG4B", :headers nil}}, :ts "2016-12-02T11:56:51.778Z"} {:response {:status 200, :body {:id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :name "s48pEpj", :is-active true, :created "2016-12-02T11:56:51Z", :modified "2016-12-02T11:56:51Z", :config {:providers {:vault "ibm", :payment "ibm"}}}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "201", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "lookupMerchantByName", :request {:method :get, :url "http://localhost:8080/management/merchant/name/s48pEpj", :body {:headers nil}}, :ts "2016-12-02T11:56:51.561Z"} {:response {:status 200, :body {:id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :name "s48pEpj", :is-active true, :created "2016-12-02T11:56:51Z", :modified "2016-12-02T11:56:51Z", :config {:providers {:vault "ibm", :payment "ibm"}}}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "201", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "createMerchant", :request {:method :post, :url "http://localhost:8080/management/merchant", :body {:name "s48pEpj", :config {:providers {:vault "ibm", :payment "ibm"}}, :headers nil}}, :ts "2016-12-02T11:56:51.365Z"}]

[{:response {:status 200, :body {:id "08066a86-89be-4c26-a658-7c843dd0d4fd", :is-active true, :created "2016-12-02T11:56:51Z", :label "UvdF0D8JBX", :merchant-id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :merchant-pos-id "u8HwIG4B"}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "198", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "createPoSTerminal", :request {:method :post, :url "http://localhost:8080/management/pos-terminal", :body {:label "UvdF0D8JBX", :merchant-id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :merchant-pos-id "u8HwIG4B", :headers nil}}, :ts "2016-12-02T11:56:51.778Z"} {:response {:status 200, :body {:id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :name "s48pEpj", :is-active true, :created "2016-12-02T11:56:51Z", :modified "2016-12-02T11:56:51Z", :config {:providers {:vault "ibm", :payment "ibm"}}}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "201", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "lookupMerchantByName", :request {:method :get, :url "http://localhost:8080/management/merchant/name/s48pEpj", :body {:headers nil}}, :ts "2016-12-02T11:56:51.561Z"} {:response {:status 200, :body {:id "c0208f3a-9a70-4f2f-9bb0-35e7db86d121", :name "s48pEpj", :is-active true, :created "2016-12-02T11:56:51Z", :modified "2016-12-02T11:56:51Z", :config {:providers {:vault "ibm", :payment "ibm"}}}, :headers {"Content-Type" "application/json; charset=utf-8", "Content-Length" "201", "Server" "http-kit", "Date" "Fri, 02 Dec 2016 11:56:51 GMT"}}, :event-name "createMerchant", :request {:method :post, :url "http://localhost:8080/management/merchant", :body {:name "s48pEpj", :config {:providers {:vault "ibm", :payment "ibm"}}, :headers nil}}, :ts "2016-12-02T11:56:51.365Z"}]

**Comment by shafeeq** [comment]
wups. this was a mistake. clearly. sorry about this! 😞  😿

**Comment by erkinalp** [comment]
#253
