### ISSUE TITLE
cannot search or filter for requested reviews

### ISSUE THREAD

**Issue by aspiers** [isaacs/github#833]
GitHub has just introduced a potentially very nice feature where reviews can be requested from specific people:

https://github.com/blog/2291-introducing-review-requests

I am assuming that any such request will trigger some kind of notification.  However the feature is not very  useful unless it's possible to search globally and filter within a repo for:

- [ ] PRs for which my review has been requested by other people
- [ ] PRs for which no review has been requested (it's already possible to [search for other missing metadata](https://help.github.com/articles/searching-issues/#search-by-missing-metadata-on-an-issue-or-pull-request))

Whilst it's already possible to do [global searching](https://help.github.com/articles/searching-issues/#search-by-the-assignee-of-an-issue-or-pull-request) and [repo-wide filtering](https://help.github.com/articles/filtering-issues-and-pull-requests/) for PRs *assigned* to me or *mentioning* me, I can find nothing in the docs about the equivalent for PRs *requesting* me as a reviewer.  I even tried guessing the advanced search syntax `reviewer:aspiers` but it didn't work.

So it seems that GitHub either forgot to implement this, or it's simply still on their TODO list.

**Comment by aspiers** [comment]
Just submitted this issue to GitHub via the `Contact a human` button.

**Comment by aspiers** [comment]
Reply from GitHub:

> Hey Adam,
> 
> This isn't currently possible but we are still working on those review features.
> 
> I'll pass your request onto our team to consider for future iterations.
> 
> I can't promise if/when we would add this but thanks for taking the time to write in. We appreciate it!
> 
> Cheers
> Stacey

**Comment by osdiab** [comment]
I would also like to plug that it would be nice to see the PR's that are pending review, not just that you're a reviewer for—if I can tell the PRs that I've been labeled as reviewer for, but either a) I haven't reviewed yet or b) I have reviewed but new changes came in since my review, it would be a really useful feature!

**Comment by aspiers** [comment]
@osdiab Agreed 100%!  It's really surprising to me that GitHub did not implement this at the same time as the basic feature ...

**Comment by eliottwiener-thirdchannel** [comment]
The `involves:` filter should also be updated to return results for which the specified user is a reviewer.

**Comment by eliottwiener-thirdchannel** [comment]
@aspiers You are correct - `involves` already does work. I have strikethrough'd my previous comment.

**Comment by aspiers** [comment]
Just noticed that a week or so after pull request reviews were implemented, [GitHub released an experimental API](https://developer.github.com/changes/2016-12-14-reviews-api/) for this.  So if the API's support for new features lags slightly behind, probably their search engine suffers from a similar lag, in which case we might give reasonable hope that they'll fix this.

**Comment by aspiers** [comment]
In seveas/git-spindle#140 I suggest a CLI-based workaround for the current lack of this feature.

**Comment by ihucos** [comment]
+1

**Comment by pjlong** [comment]
As of January 23rd 2017, you can filter PRs by Reviewer!
https://github.com/blog/2306-filter-pull-request-reviews-and-review-requests

**Comment by aspiers** [comment]
Woohoo, awesome!  Thanks for reporting this :)

**Comment by aspiers** [comment]
For the record, here's the advanced search syntax guide: https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/

**Comment by skeggse** [comment]
Before I open a new issue - it seems that part of the original description for this issue hasn't been implemented:

>- [ ] PRs for which no review has been requested (it's already possible to search for other missing metadata)

Has this actually been implemented, and I'm just missing the syntax, or is it still unimplemented?
