### ISSUE TITLE
Pull Request viewer showing extra commits

### ISSUE THREAD

**Issue by laher** [isaacs/github#841]
In the past couple of weeks, we keep seeing PRs which list many extra commits than actually exist in both branches:

 * The correct commits are listed, as well as spurious (recent) commits which _do_ exist in both branches.
 * The diff itself in 'Files Changed' is correct.
 * I have double-checked that there were no 'git revert' type commits, and that the origins are up to date with my local branches.
 * These are all in private repositories (under the `Hapara` organisation), so I'm not sharing examples at this stage. I'll run it past my colleagues first.

This has been a bit maddening, because we keep thinking that we're about to push more changes than we expected.

One thing to note is that the destination branches for these PRs are 'tracking' branches, where we occasionally force-push hotfixes into. We've been doing that for a long time though and this is the first time we've encountered this problem.

**Comment by cirosantilli** [comment]
If you can produce a minimal open example, changes of resolution will increase :-)

**Comment by laher** [comment]
I don't have a public example, sorry.

I just realised that this is not github's own repo. No worries. Closing and finding the right place to post it ...
