### ISSUE TITLE
.bettercodehub.yml ignored on GitHub?

### ISSUE THREAD

**Issue by a-einstein** [isaacs/github#851]
- I have just started using Better Code Hub and added the badge to my ReadMe's.
- For one of my repositories I configured the analysis, saved this in .bettercodehub.yml and pushed it to GitHub. I had filtered out all scaffolding code, that was of course not mine. This gave a higher score.
- Now everywhere EXCEPT on GitHub I get the new score in the badge. That is: on the Better Code Hub site and in Visual Studio.
- I have also activated the push & pull switch and made some pushes. But that does not make a difference.
- This is pretty annoying, as the whole point of the badge is to show it to others.

So what is happening?
- Am I missing something?
- Is this simply a bug?
- Does the badge update at all in GitHub?
- Is the .bettercodehub.yml ignored on GitHub?

The last possible cause could be intentional, to avoid cheating or something? But my filtering is completely public in the yml file, so that is up to me, not GitHub.

To my surprise, I have found nobody that reported the problem so far.

Any help would be appreciated.

**Comment by NobbZ** [comment]
Images linked in the read me or from any other place on git hub are subject
to some caching or cdn by git hub. They do this to avoid tracking through
the image hoster.

This is a known problem.

a-einstein <notifications@github.com> schrieb am Mi., 4. Jan. 2017, 19:29:

**Comment by a-einstein** [comment]
Thanks NobbZ.

It already appeared to be. I was just promptly contacted by support. And when I looked again, the README finally had updated the badge.

All my previous attempts to force it (refresh, logout, reanalysis, push) did not work.
