### ISSUE TITLE
Add support for commit search by short identifier

### ISSUE THREAD

**Issue by monperrus** [isaacs/github#852]
One can now search commits by message content (#352) and full SHA1 identifiers (https://github.com/search?q=2aee53fd5bbae764f77d2a8fc38facdd05fcfedf&type=Commits).

However, the commit search by short identifiers is not supported: https://github.com/search?q=2aee53f

**Comment by chrismwendt** [comment]
I implemented this 😃 https://github.com/search?q=2aee53f&type=Commits

**Comment by monperrus** [comment]
Awesome! Thanks a lot Chris.

**Comment by monperrus** [comment]
Chris, would you also save the world by having a look at low hanging fruit #21?
