### ISSUE TITLE
Star and Fork button position

### ISSUE THREAD

**Issue by szepeviktor** [isaacs/github#857]
I've noticed people fork my repos and don't commit at all.

I suggest to swap the two buttons and as these persons think **the rightmost** button is the Like button.

**Comment by Mottie** [comment]
Swapping buttons won't make a difference... there are tons of people that fork repositories as a way to bookmark them; they usually don't contribute, make comments or even keep the fork up-to-date... look at the number of forks for this repo.

**Comment by szepeviktor** [comment]
You are right.
https://github.com/isaacs/github/network
