### ISSUE TITLE
Search for starred forks is not possible

### ISSUE THREAD

**Issue by szepeviktor** [isaacs/github#883]
I am looking for a repo I know I've starred called `dbug`:
https://github.com/szepeviktor?page=1&tab=stars&utf8=%E2%9C%93&q=dBug
No results.

But see: I've starred it: https://github.com/szepeviktor?tab=stars
(It is the first today. Over time it may descend.)

**Comment by jomo** [comment]
You can append `fork:true`:
https://github.com/szepeviktor?page=1&q=dBug&tab=stars&utf8=%E2%9C%93&utf8=%E2%9C%93&q=dBug%20fork%3Atrue

**Comment by szepeviktor** [comment]
> You can append fork:true:

Thank you. How have you figured it out?

**Comment by jomo** [comment]
I knew about this search parameter from the [advanced search](https://github.com/search/advanced). I guess this can be closed now?

**Comment by szepeviktor** [comment]
Yes. I thought I has already pressed <kbd>Close</kbd>
