### ISSUE TITLE
Sort repositories in an organization by alphabetical order

### ISSUE THREAD

**Issue by pllim** [isaacs/github#895]
Q: How do I sort the repository listing in a GitHub organization by alphabetical order? I can see all kinds of sort options but the one that I need.

A: Alphabetical isn't a sort order we currently support, but I'll pass this along to the team as a feature request. In the meantime, you could get the repos via the API and sort them programmatically: https://developer.github.com/v3/repos/#list-organization-repositories (by Shawna)

**Comment by mcxbain** [comment]
I also would like to sort the repository listing in a GitHub organization by alphabetical order.
Would be nice if this feature would be implemented. Maybbe in Personal Settings ->Repositorys ->Default Sorting Order -> Alphabetical DESC|Alphabetical ASC|Newest Commits First (default)

**Comment by gingerbeardman** [comment]
Would also like this so sort order reflects my local machine.

![screen shot 2017-07-03 at 13 27 29](https://user-images.githubusercontent.com/49612/27792885-aca9ed48-5ff3-11e7-823f-bdffe7fbeb78.png)

**Comment by ESG-Steven** [comment]
Can we PLEASE get this. We have prefixes on repositories specifically for this.
It seemed like an absolute no brainer that this would exist?

**Comment by gingerbeardman** [comment]
I now use a userscript to achieve this: https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content

**Comment by ESG-Steven** [comment]
A very round about way to achieve something that is a single function in most languages. I need it to work for all users in the company, not just myself (pardon me if I misunderstood, seemed like it's per-machine solution?). Still, clever considering the circumstances.

**Comment by gingerbeardman** [comment]
Yes it's not ideal, but github don't seem to be in any rush to add native support for it. 

Maybe somebody with a business account can contact support and add some weight to the request?

**Comment by jerzydziewierz** [comment]
We need this! 

I have like 70 repos in my organisation, what a waste of time to Not have them sorted!!!
Also, need easy grouping by tags. How un-githubable to not have such basic functionality!!!

**Comment by ESG-Steven** [comment]
It isn't rocket surgery. How is this not a thing?

**Comment by pllim** [comment]
I am able to get it via `pygithub` but a native web interface would have been nicer:
```python
from github import Github
g = Github('', '')  # Anonymous access
org = g.get_organization('my_org_name')
repos = org.get_repos()  # Public repos
reponames = sorted(repo.name for repo in repos)
```

**Comment by DragosRotaru** [comment]
.....Please? Can we get this?

**Comment by VinLark** [comment]
Would love this!

**Comment by mercicle** [comment]
+1e10

**Comment by phannan** [comment]
This would also help me.  I am managing a bunch of repos under an organization.  I was hunting a sort by repo option.  Sort alphabetically would do the trick.

**Comment by MCplatt** [comment]
sorting by date would be nice aswell

**Comment by smokydoke** [comment]
Sorting is good.  Please put some energy into improving sort options.

**Comment by clarkbw** [comment]
See also organizing repos via tags or folders #302

**Comment by dcmbrown** [comment]
This used to be a thing on GitHub repositories being listed by alphabetical order in some areas but now it is entirely by last contributed to/active for some reason. Someone _brilliant_ apparently decided this was how to do things. Even a search option would be great to fix this though.

**Comment by jbegleiter-sf** [comment]
Seriously, I need to review the settings of all (73) of my repositories, I'm stuck writing down the names of the ones I've visited should anyone at all decide to push a commit.

**Comment by floe** [comment]
This is somewhat OT and also a Shameless Plug (TM), but I've recently written a bulk editor for Github repos which should come pretty close to your use case: https://github.com/floe/github-bulk-editor (not entirely OT, as you can actually sort the repo list alphabetically there ;-)

**Comment by dfkotz** [comment]
+1.  Would really like to have sort options - alphabetical, last-push-time, creation-time.

**Comment by jminack** [comment]
+1. 
Please please please.

**Comment by ivanperez-keera** [comment]
> I am able to get it via `pygithub` but a native web interface would have been nicer:
> 
> ```python
> from github import Github
> g = Github('', '')  # Anonymous access
> org = g.get_organization('my_org_name')
> repos = org.get_repos()  # Public repos
> reponames = sorted(repo.name for repo in repos)
> ```

@pllim This does not work for me. It prints nothing.

**Comment by pllim** [comment]
@ivanperez-keera , GitHub might have gotten rid of anon access and requires a token now; I don't remember. Try use a token and provide an actual org name that you have access to. Feel free to modify it as it was semi-pseudo code and haven't been updated in a while.

**Comment by redtide** [comment]
Please add this feature :+1:

**Comment by mlippert** [comment]
Another vote for being able to view all the repositories belonging to an account (personal or organization) sorted alphabetically.

**Comment by antmarot** [comment]
I needed to review all our repositories and was really surprised this isn't available.
+1 for this!

**Comment by gingerbeardman** [comment]
2 years ✌️

**Comment by MatthewKing** [comment]
How is this still not solved, two years on?

**Comment by matjam** [comment]
It's not a crazy hard feature to add, guys. Come now. One of you can probably knock this out before lunch and still make it in time for your gluten free sandwich at Embarcadero Center.

**Comment by ivanlan9** [comment]
+100; please add this for personal repositories. I have 75 repoes of my own, and I'd love to see some way of displaying them other than the default, which appears to be "last touched." It shouldn't be that hard to add, and would be just as useful to those of us who are non-businesses.

**Comment by pbarton** [comment]
+1, Need to review over 200 repositories, and have to write down the ones that are done as the whole team of developers add commits and the order is continually changing throughout the day.

**Comment by danieldeusing** [comment]
needed !

**Comment by GonCarp** [comment]
Just do it!

**Comment by sigged** [comment]
This would be very welcome!

**Comment by WorldJournal-Lyu** [comment]
Cannot believe this is an actual issue AND still open! Please implement this!

**Comment by ccn-horn** [comment]
I wonder why this feature hasn't been implemented until now.

Please add this feature, it is obviously very helpful for many people.

**Comment by hopeseekr** [comment]
Confession: I chose to migrate everything to GitLab and turn on their Remote Repository Mirroring for each repository so that every change is mirrored on GitHub.

![image](https://user-images.githubusercontent.com/1125541/67162695-1ea8cb80-f32c-11e9-86b4-bd793ef6636c.png)

GitLab has had searching and sorting for ages now. And sorting my own corporation's 100+ repositories was one of the primary reasons we switched (along with mirroring, and custom repo groupings (called Groups)).

It just seems that the GitLab engineers are out developing GitHub at a rapid pace in every area except code reviews.

Vote up this comment and maybe we can shame them into adding this feature (plus Repo groupings).

**Comment by ivanlan9** [comment]
Of course I will be happy to upvote your comment.  However, I am also going to look into GitLab with an eye to moving my repositories. ...

**Comment by micheman** [comment]
I don't want to move to GitLab to get this but maybe its the only option?

**Comment by gingerbeardman** [comment]
The UserScript I mention near the top still works.

https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content

**Comment by micheman** [comment]
Thanks I will give it a try !
Mike

**Comment by redtide** [comment]
> The UserScript I mention near the top still works.
> 
> https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content

I've installed it from GreasyFork for FireFox, it sorts code and stargazers tables but it seems to not to work with repositories here.

**Comment by gingerbeardman** [comment]
It should sort repos, please report a bug at: https://github.com/Mottie/GitHub-userscripts/issues

**Comment by gingerbeardman** [comment]
@redtide @micheman I read that the UserScript is now fixed (problem was GitHub moving goalpost)

**Comment by redtide** [comment]
you will not believe me but I was about to write here for a PR, I just do it now myself adding the autosearch bit in the editor after checking the page source but you did it 7 minutes before :-D
Thanks!

**Comment by redtide** [comment]
I saw it thanks, now user and org repos and teams pages can be sorted. It does much more than expected, so I'm satisfied also if using an external script.

**Comment by GrayStrider** [comment]
bump, 2020 :tada:

**Comment by brendan-sherrin** [comment]
This would still be useful

**Comment by GrayStrider** [comment]
I was considering moving to GitLab, but ended up just neatly organizing/tagging/archiving my repos here; I only actively work on a few of them, the rest can be archived and their order doesn't really matter. Just putting this out before unsubbing, maybe I'll motivate someone else to clean up their mess ;)

**Comment by karenfuhrman** [comment]
It's infuriating that github still does not have an option to sort by name!!! I do not care about sorting by smiley faces and frowny faces - I want the basic option be able to put any list or results in GitHub in alphabetical order. Why is this such a big ask?

**Comment by karledwards1** [comment]
another bump 2020

**Comment by deploystudios** [comment]
KONY2020.... it's time for alpha sorting!

**Comment by voshwarthen** [comment]
any time now

**Comment by TomSweeneyRedHat** [comment]
Another 2020 bump.  I'd love to be able to sort by name.  If possible,b y creation date would be useful too.  I can't imagine why a name sort hasn't be done in over two years of asking for it. It doesn't seem like a name sort should be that complicated....

**Comment by rswfire** [comment]
It's impossible to understand why repositories aren't sorted alphabetically. It's a real pet peeve of mine and makes me wish I'd stayed with Bitbucket.

**Comment by gingerbeardman** [comment]
3 years and counting!

**Comment by mpremo** [comment]
Bump.

**Comment by sivakumar-j** [comment]
Any updates on this.. my repo is list is growing..its bit challenging to find the proper one

**Comment by drakulaboy** [comment]
Bump x2

**Comment by PauloPortfolio** [comment]
Whats the problem with that? this is so complicated? Why Github is lating years and years to be PROFESSIONAL and LISTEN their clients, and implement that???? this is a bad idea? this will not aggregate value in the github platform? What the problem? Please, could you guys can implement this? We love GitHub, but YEARS to implement so TRIVIAL change is not respectful with Github clients.

**Comment by Mentaleak** [comment]
Just sent this to feedback home they look at it.
![image](https://user-images.githubusercontent.com/22431171/89049060-aa6d7080-d31e-11ea-8c78-6a616b1a9fc7.png)

**Comment by jenniferskay** [comment]
Please please add sort alphabetically and by date!!!

**Comment by dcmbrown** [comment]
I do like how @Mentaleak has even provided mockups for this. :D

**Comment by gingerbeardman** [comment]
3.5 years!

**Comment by hopeseekr** [comment]
Time to see if I can automate GitHub mirroring in GitLab so you guys have a 1-to-3 click option of migrating to GitLab while keeping all your GitHub projects in sync and getting the (mostly) superior UI of GitLab.

I still can’t use GitLab for code reviews. Grossly inferior.

I’m stuck, in 2020, using both sites for diff purposes. But now that both effectively have free unlimited private repos, there’s no reason for everyone not to have auto-sync’ed projects I have, on both services.

**Comment by dissolved** [comment]
Ridiculous... GitLab here I come.

**Comment by tjwrona1992** [comment]
@pllim Nearly 4 years later this still seems to be a pretty active issue that many users are requesting. Would it be possible to get more attention on this?

Even with a relatively small organization (around 10 repos or so) the lack of a sorting feature is quite frustrating.

**Comment by JafarSadikGhub** [comment]
It's nearly 4 years. Still no such feature!

**Comment by tjwrona1992** [comment]
> I now use a userscript to achieve this: https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content

@JafarSadikGhub I just tried the userscript mentioned in the above comments and it seems to work well. It was very straightforward to use too. :)

I would still like to see this officially added to GitHub though. It is quite ridiculous that this is not a built-in feature.

**Comment by patrickgrosso** [comment]
I would like to see repos sorted by name as well

**Comment by FrankBolleri** [comment]
I'll add myself too: please add repository sort functionality by name and by date ...

Thanks

**Comment by Craig-k-p** [comment]
Guys ur coders...  You gotta DIY it!

**Comment by Akbar300** [comment]
It's stunning to see this is still an open issue in 2021

**Comment by refineddigital** [comment]
why is this not a thing?
for me it is confusing as f*** to find the repos I'm looking for

**Comment by ganamavo** [comment]
We'd like to be able to sort our repositories on github if possible. It could be very useful.

Thanks in advance!

**Comment by botatoes** [comment]
Hi all :) I'm a PM at GitHub. We just recently shipped sorting repos in orgs by name. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/7900087/110696661-33476700-81a0-11eb-8341-4b568aacac1d.png">

**Comment by pllim** [comment]
Yes, I see it. Thank you!!!

**Comment by FrankBolleri** [comment]
Thanks, but the Sort functionality is available only in certain cases?
Because I don't see it on my account.. maybe is because I am not using "Orgs"?

![Screen Shot 2021-03-11 at 08 06 07](https://user-images.githubusercontent.com/26364299/110748973-bddfa300-8240-11eb-9070-e1d241cb3600.png)

**Comment by botatoes** [comment]
@FrankBolleri yes, right now it's only available for orgs. We're working on profile sorting right now so that's coming up soon.

**Comment by ganamavo** [comment]
That's great!
We're waiting for the result of your great work.
Cheers,

**Comment by gingerbeardman** [comment]
Appreciated!!!

**Comment by AraHaan** [comment]
> @FrankBolleri yes, right now it's only available for orgs. We're working on profile sorting right now so that's coming up soon.

Thank you, btw is sorting once when an org member does it make it sorted like that for everyone in the org or even outside of said org?

**Comment by botatoes** [comment]
@AraHaan sorting will only affect your view. The default sorting is by last updated so even if you sort repos by name, if you open a new window and navigate to the same page, it should show up as last updated.

**Comment by AraHaan** [comment]
@botatoes is it possible you guys could make a button where the sorting we select now could be made permanent for everyone?

**Comment by alemens** [comment]
> Hi all :) I'm a PM at GitHub. We just recently shipped sorting repos in orgs by name.

Hi @botatoes do you plan to implement the `sorting repos by name functionality` also for personal accounts?

**Comment by botatoes** [comment]
@AraHaan I'll create an issue for it and will prioritize if we see more requests :) 

@alemens Soon!

**Comment by geozimmy** [comment]
@botatoes - any chance this sorting will be available in GitHub Enterprise?

**Comment by matthiaswenz** [comment]
@geozimmy This feature is globally available and all feature flags have been removed, so it will make its way into GitHub Enterprise automatically.

**Comment by matthiaswenz** [comment]
@geozimmy Yes, this should make its way into GitHub Enterprise in an upcoming release.

**Comment by geozimmy** [comment]
@matthiaswenz - excellent, thanks you for the quick reply.

**Comment by jnous-5** [comment]
@botatoes Would like to ask if this option is also available on the GraphQL API? Currently, I cannot see the sort repositories by name on the search query.

**Comment by Jethet** [comment]
@botatoes I would really like it if the repos in my organisation **stay** alphabetised once I have clicked the selection button. It would help our group enormously because we have a system in our projects that would put similar projects together if the repose are sorted in alphabetical order. Please improve the 'Sort' option and make it possible to set a default/preference so that the repos remain sorted by name once you have clicked that selector under 'Sort'.
