### ISSUE TITLE
[webhook] Team object has no html_url

### ISSUE THREAD

**Issue by Zopieux** [isaacs/github#907]
The `team` object (json dict) sent by [some](https://developer.github.com/v3/activity/events/types/#membershipevent) [webhook](https://developer.github.com/v3/activity/events/types/#membershipevent) [endpoints](https://developer.github.com/v3/activity/events/types/#teamaddevent) has no `html_url`, as one could expect.

```json
  "team": {
    "name": "whatever",
    "id": 42,
    "slug": "whatever",
    "description": null,
    "privacy": "secret",
    "url": "https://api.github.com/teams/42",
    "members_url": "https://api.github.com/teams/42/members{/member}",
    "repositories_url": "https://api.github.com/teams/42/repos",
    "permission": "pull"
  }
```

Indeed, while most objects have such an `html_url` property linking to the GitHub website corresponding page, teams have not, despite having such a web URL: `https://github.com/orgs/<org>/teams/<name>`

I would expect the following payload instead:

```json
  "team": {
    "name": "whatever",
    "id": 42,
    "slug": "whatever",
    "description": null,
    "privacy": "secret",
    "url": "https://api.github.com/teams/42",
    "members_url": "https://api.github.com/teams/42/members{/member}",
    "repositories_url": "https://api.github.com/teams/42/repos",
    "permission": "pull",
    "html_url": "https://github.com/orgs/foobar/teams/whatever"
  }
```

**Comment by bswinnerton** [comment]
👋 Hopefully this isn't too little too late, but we've just went ahead and added `html_url` to the Team object in both the API and webhooks.

**Comment by Zopieux** [comment]
Better late than never! Thanks. Closing.
