### ISSUE TITLE
Allow regex patterns to match JIRA issue keys

### ISSUE THREAD

**Issue by jefft** [isaacs/github#91]
I have JIRA and Github Enterprise linked up. When I reference a JIRA issue in a commit ("foo bug fixed. FOO-123 #resolve"), I'd like the issue key to link back to JIRA.

Bitbucket implemented this feature by allowing users to specify matching regexes:

https://confluence.atlassian.com/display/BITBUCKET/Use+the+JIRA+DVCS+Connector+Plugin

which would be great. A JIRA-specific alternative would be to query JIRA's REST API for a list of project keys.

**Comment by mfn** [comment]
I think this is possible with https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuring-autolinks-to-reference-external-resources ?

**Comment by jefft** [comment]
Appears so - thanks for the pointer.
