### ISSUE TITLE
Question: in GitHub, what is the color scheme used to syntax highlight PHP?

### ISSUE THREAD

**Issue by u01jmg3** [isaacs/github#922]
For example:

```php
<?php
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Exception               $exception
     * @return \Illuminate\Http\Response
     */

    public function render($request, Exception $exception)
    {
        if ($exception instanceof SomeException) {
            // return an HTTP response describing the exception...
        }


        return parent::render($request, $exception);
    }
```

---

- Does it exist as a theme for N++, Sublime or Atom?

**Comment by z3t0** [comment]
I think its just unofficially called GitHub color scheme

https://packagecontrol.io/packages/Github%20Color%20Theme
https://atom.io/themes/atom-github-theme

Search "github" on https://github.com/mbadolato/iTerm2-Color-Schemes#screenshots

**Comment by cirosantilli** [comment]
https://help.github.com/articles/creating-and-highlighting-code-blocks/ says:

> We use Linguist to perform language detection and syntax highlighting.

Then have a look into linguist if they have the CSS stylesheets.

**Comment by u01jmg3** [comment]
Thank you both

**Comment by Mottie** [comment]
GitHub syntax highlighting is performed by GitHub's own PrettyLights syntax highlighter (not released). They do provide a [PrettyLights syntax theme generator](https://github.com/primer/github-syntax-theme-generator) which produces a GitHub [light](https://github.com/primer/github-syntax-light) and [dark](https://github.com/primer/github-syntax-dark) theme.

To see which languages are actually supported, check out the linguist [languages.yml file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).
