### ISSUE TITLE
git ignore ...

### ISSUE THREAD

**Issue by redcricket** [isaacs/github#929]
It would be really nice if one could issue this command line:

```
git add something/something.py
git ignore something/something.pyc

```
Instead of having to go google how to setup a git ignore for a certain file or file pattern.
Maybe the danger would be if someone did ...

```
git ignore .

```

Maybe make so one could not use wildcards or a directory?
`

**Comment by cirosantilli** [comment]
Your issue seems to be about git only, not GitHub. Please contact Git maintainers directly.

**Comment by redcricket** [comment]
Thanks but I am having trouble find the git maintainers. Can you please
point me in the right direction?

**Comment by cirosantilli** [comment]
See: https://git-scm.com/community But a prediction: this will be ignored / declined :-)

**Comment by redcricket** [comment]
thanks :)
