### ISSUE TITLE
Support for viewing the edit history of issues

### ISSUE THREAD

**Issue by jmcmurry** [isaacs/github#954]
Issues and comments on issues get edited. In a perfect world, they wouldn't need to, but this is not a perfect world and it happens. 

Unless you dutifully receive (and keep) emails of the original issue, subsequent comments and do the diff with the version on github.com, it is nearly impossible to detect what has been edited. The occasions when you would need to do this are admittedly rare, but it would be nice to have. Notification of an edit has already been requested, however this, at least for me, would be rather annoying. There are plenty of typo edits, clarifications etc that are good to have but that do not warrant notification.

For example, this is an edit to my original comment.

**Comment by avbentem** [comment]
The title says it all, but as one cannot add reactions to just a title: here's a placeholder just for that.

(And yes, I know this is not the repository of the actual GitHub platform.)

**Comment by sompylasar** [comment]
> Notification of an edit has already been requested, however this, at least for me, would be rather annoying. There are plenty of typo edits, clarifications etc that are good to have but that do not warrant notification.

If notifications on edit existed, this annoyance could be resolved by throttling, e.g. notify in 15 minutes after last edit.

**Comment by pllim** [comment]
I have requested a similar feature:

> Currently, when an issue/PR comment is edited on GitHub (not the commit message, but the comment on the issue/PR page), there is no way to view or recover any previous iteration(s) of it. Can you please add a feature to recover or view those previous iteration(s), or at least the last one before latest edit?

Here is their reply:

> Thanks for reaching out! That's not currently possible, but I would be happy to add your +1 to the feature on our internal request list. I can't promise if or when it will be implemented, but your suggestion is definitely in the right hands!

**Comment by gthackra** [comment]
you could always use a webhook to write out the edit to a secondary db for storage/review etc. Webhooks are configurable to trigger on an issue comment edit and contain enough information to track issue comment edit history.

**Comment by jmcmurry** [comment]
For the first time today, I noticed that GitHub rolled out this feature. I don't know if it is universally present on all repos, but stay tuned.

**Comment by jmarshall** [comment]
It was recently announced on their changelog blog: https://blog.github.com/changelog/2018-05-24-comment-edit-history/

The announcement didn't mention rolling out slowly across repositories, so I've been confused that there's been no sign of it in the repos I frequent. But you're right, right here in isaacs/github is the first repo I've seen that has it present.

**Comment by pllim** [comment]
Yes, I can see it in action as well. I think we can close this finally! :tada:

**Comment by thecliguy** [comment]
@jmcmurry Today I've noticed that Gists containing a comment with at least one edit result in a dialogue box appearing to inform you that _"Comment history is now public..."_

In the latest stable build of Firefox **60.0.1** on Windows 10 Pro (Version:1709, OS Build: 16299.431), it is not possible to dismiss the dialogue. Doing so (by clicking `Got it`) produces another dialogue advising that _"You cannot perform that action at this time"_:

![image](https://user-images.githubusercontent.com/23440389/40835359-25c245c0-658b-11e8-87e9-2fec2e62b9be.png)

This is the example gist from the screenshot: https://gist.github.com/thecliguy/2867f4384dc7a1197dd3aac8a54d3315

Can this issue be reopened, or do I need to raise a separate issue?

**Comment by Chan9390** [comment]
I am facing the same issue as @thecliguy. I use firefox and see the same message when I am authenticated. (In private browsing I dont see that)

**Comment by thecliguy** [comment]
This is the response I received from Github support:

> From: Shawna Jean (GitHub Staff) <support@github.com>
Sent: 02 June 2018 19:08
Subject: Re: Comment edit history
>
> Thanks for reaching out about this! I've asked the team to take a look. I don't have a specific ETA for you, but your report is in the right hands.
>
>In the meantime, if you're still seeing that notice, you should be able to dismiss it properly from a comment on a repository.
>
>Best,
Shawna
>
>Today I've noticed that Gists containing a comment with at least one edit result in a dialogue box appearing to inform you that "Comment history is now public..."
>
>In the latest stable build of Firefox 60.0.1 on Windows 10 Pro (Version:1709, OS Build: 16299.431), it is not possible to dismiss the dialogue. Doing so (by clicking Got it) produces another dialogue advising that "You can't perform that action at this time".
>
>This was a recent change implemented by Github as announced on this blog post: https://blog.github.com/changelog/2018-05-24-comment-edit-history/
>
>I have documented the issue here (an unofficial repo for github issues): https://github.com/isaacs/github/issues/954

**Comment by thecliguy** [comment]
Yesterday (22/06/18) I received the following update from Github support to say that the issue should now been resolved:

> From: Tiara (GitHub Staff) <support@github.com>
> Sent: 22 June 2018 05:28
> Subject: Re: Comment edit history
>
> I just wanted to let you know that our engineers have recently deployed a fix for this issue, so it should now be resolved. Thanks for your patience, and for taking the time to report the trouble! Let us know if there's anything else we can do. 
> Best regards, Tiara  GitHub Support 
> 👉Find support and come learn with other GitHub users in our new  GitHub Community Forum.

**Comment by julealgon** [comment]
I just noticed this feature which is quite nice. 

I wonder though: what if someone want's to delete some sensitive information posted inadvertently in the first iteration of an entry? If the entire history is public, even if you edit the information out, now everybody will still be able to see it.

This was not the case before.
