### ISSUE TITLE
Delete forked repository on pull request merge

### ISSUE THREAD

**Issue by michaelmior** [isaacs/github#965]
It's helpful to have the delete branch button when a pull request is merged. However, sometimes I'll fork a repository just to fix a small issue and I don't expect to work on it again. I then find after deleting the branch, I have to manually navigate to the repository to delete it. It would be nice if this was offered as an option on the pull request page.

**Comment by stuartpb** [comment]
Duplicate of #673

**Comment by michaelmior** [comment]
Wow. Can't believe I duplicated myself. Thanks for noting @stuartpb . Closing this in favour of #673.
