### ISSUE TITLE
"call depth overflow" exception in  Powershell scripts on Mac

### ISSUE THREAD

**Issue by mpeneva** [isaacs/github#970]
Some of of my PowerShell scripts that I run on Mac failed with the following exception: 
"The script failed due to call depth overflow." 
After some investigation, I came to the conclusion that the allow call depth in PowerShell v6.0 alpha,
is smaller than the defined in PowerShell v5.0 (which I find is 100). 
Could you change or increase in PowerShell for Unix that fixed call depth to be at least 1000?

**Comment by jakerobinson** [comment]
Hi @mpeneva! You should post your issue here: https://github.com/PowerShell/PowerShell/issues

You have posted it in someone's fork of github. :)

**Comment by mpeneva** [comment]
Thanks Jake  :) It's now posted there.
