### ISSUE TITLE
Ordering of commits in a PR is not guaranteed after rebase

### ISSUE THREAD

**Issue by ajhyndman** [isaacs/github#974]
## Overview

I've experienced this pretty regularly lately.

I'm not sure what feature commits are sorted on in a Pull Request, but it does not always seem to be guaranteed to match branch order of that Pull Request.

## Expected behaviour:

Commit listings (in the chat history as well as the "Commits" tab) should be listed in branch order.

## Observed behaviour:

After a rebase and force-push, commits may be listed in arbitrary order.

**Comment by cirosantilli** [comment]
Commits are sorted in commit timestamp order. See: https://github.com/isaacs/github/issues/386

**Comment by ajhyndman** [comment]
Ah yeah, exactly what I'm after!  I'll close this in favour of #386.
