### ISSUE TITLE
Add "repo collab" badge to all comments, not just code line comments

### ISSUE THREAD

**Issue by ericf** [isaacs/github#98]
Comments made on lines of code have this nice feature where people who have push access to the repo get a little "repo collab" or "repo owner" badge added to their comments. And this is great!

This badge should also be applied to any comments made by collaborators or owners, including the discussion comments. This way when people are contributing to a project and they get feedback, they can see what feedback is from the project's actual owner/collaborators.

**Comment by TPS** [comment]
I believe this is now solved, as shown on this comment.
