### ISSUE TITLE
Please adjust documentation wording in open source landing page

### ISSUE THREAD

**Issue by strugee** [isaacs/github#980]
(Just submitted to GitHub support:)

Heya,

Under the "Contribute your skills" section of https://github.com/open-source, it says:

> Even asking questions or improving documentation helps.

This seems to imply that working on documentation normally would not help, or that documentation is less important than coding - when in reality, according to GitHub's own Open Source Survey, documentation is just as important and in fact often overlooked.

Please adjust the wording here to not demean people who do valuable and frankly critical work on projects' docs.

**Comment by RolandStuder** [comment]
As of now it actually says:

> Make a suggestion, fix a bug, improve documentation, or contribute code to a project. Even asking questions helps.

So I think this issue can be closed. Who to notify, that this can be closed? (I did not find anything in the readme or contributing guidelines.

**Comment by strugee** [comment]
Got this back from support yesterday:

> Hey Alex,
> 
> We've fixed this now. Thanks again for the head up!
> 
> Mike McQuaid
> GitHub Open Source Team

Thanks GitHub <3
