### ISSUE TITLE
Subscribe to issue only for certain events such as closing

### ISSUE THREAD

**Issue by CodingSpiderFox** [isaacs/github#985]
I don't want to see all the comments on issues like #283 because they are mainly "+1" comments (and I still don't see what the problem for GitHub is to implement this -.-)

There already is a subscribe/unsubscribe button for every issue. I want a dropdown for that button where I can select different events that I can click like "Closed" or "Resolved" or "Comments" so that I only get notified when one of the events selected by me has occured.

**Comment by cirosantilli** [comment]
Also to help alleviate +1 -1 https://github.com/isaacs/github/issues/968 https://github.com/isaacs/github/issues/640 https://github.com/isaacs/github/issues/967

**Comment by becca** [comment]
👋 we recently shipped [custom thread subscriptions](https://github.blog/changelog/2019-05-09-custom-thread-subscriptions/) which should help you 🙇

**Comment by cirosantilli** [comment]
Closing as I feel this is solved.
