### ISSUE TITLE
Ability to pre-fill comment of a new issue with custom bug headers

### ISSUE THREAD

**Issue by Whoaa512** [isaacs/github#99]
The idea is to allow users to create custom text that can be used to prefill the comment of a new issue. 

Ideally this custom text could be set at the repository level and at the user level. Per repo, both the owner & collaborators would be able to create a set of custom markdown files each containing a list of headers to aid with the bug report & issue tracking process. At the user level, one would be able to create their own set of custom markdown files.

On the UI end, after creating a new issue a dropdown would appear between the tabs   of the comment field and the comment about Github Markdown. 
![screen shot 2013-09-16 at 19 05 26](https://f.cloud.github.com/assets/1581943/1154343/40396d7a-1f40-11e3-85ba-96685742646a.png)

Dropdown in red, button to prefill the comment field in blue.

This came from reading through a ton of issues today on multiple repositories, which made me a little surprised there wasn't an issue for this already.

**Comment by Pithikos** [comment]
@VxJasonxV is there some documentation on what parameters are accepted and where? For example the given example doesn't work when creating new files via a URL.

**Comment by Pithikos** [comment]
@VxJasonxV you provided the example: https://github.com/isaacs/github/issues/new?title=foo&body=bar

Following that example I would expect the following link to work: https://github.com/isaacs/github/new/master?filename=foo&content=bar

However it doesn't.. I also tried with `body`, `ace_content` and `ace_text-input`.

**Comment by VxJasonxV** [comment]
I have never tried doing this with Ace. Ace is a rich editor, and I don't expect basic HTML form interactivity to work.

**Comment by Pithikos** [comment]
Thanks! That works a treat! B)

**Comment by jrgifford** [comment]
@VxJasonxV  so your recommendation is that if we want a template for github issues, we should create a form ourselves that lets someone open an issue via the API?

**Comment by patcon** [comment]
Interesting idea @jrgifford. It would seem overkill to auth an app with your account's `public_repo` scope just to create forms in your name on the very rare occassion, but perhaps it could submit under a common app account. There could be a little footnote at the bottom of the issue like *"Submitted on behalf of @patcon using [$APP_NAME](http://example.com)."*

Meh. Just a thought.

**Comment by jrgifford** [comment]
@patcon  well, so in my case, i'm trying to adapt github to be used for change control, so it really *should* be in that persons name.

**Comment by VxJasonxV** [comment]
If you want to do something on behalf of a user, even simply making a task easier for them, you use the API. Because authentication is involved, the only alternative is something client side like a local program, script, browser extension, etc. But if you want to just give them a webpage they can browse to and fill in just what they need to, there is no other alternative.

**Comment by todb-r7** [comment]
:+1: to @patcon's FrontMatter suggestion for pre-filling the issue (and pull request!) title and descriptions. I have found that I need to bonk users over the head repeatedly when filing issues over at rapid7/metasploit-framework, and now that we've moved to GitHub Issues full-time, I'd love to drop reminders directly into the body of the issue.

I will fake it in the meantime with a combination of shortlinks with the URI parameters (Thanks @VxJasonxV ) and then blessed links in CONTRIBUTING.md and README.md, but it'd be great to have this stuff available for people who navigate directly to /issues and /pulls directly, without parameter decorations.

**Comment by thockin** [comment]
This.  SO MUCH THIS.  Please

**Comment by bgrant0607** [comment]
+1

**Comment by dchen1107** [comment]
+1000

**Comment by todb-r7** [comment]
In the interest of providing an example, I use http://r-7.co/MSF-BUGv1 now. Kinda neat, but I'd rather have the configurable solution.

**Comment by marcusgadbem** [comment]
This feature would also be useful in case to pre-fill comment on open issue. Or there is already a way?

**Comment by ehausen** [comment]
How to set a label ("bug" for example) for a new issue with URL encoding? Tried a few things, but no luck? Where could I find out parameter names and syntax?

**Comment by yfdyh000** [comment]
@ehausen I think the reporters don't have necessary permission to applying labels.

**Comment by ehausen** [comment]
Yeah the permissions have to be right of course. But this would be for internal use. 
https://github.com/organisation/repository-name/issues/new?labels=Bug works! 
But I don't know how to get it to assign several labels

**Comment by thockin** [comment]
That works IF your users have permissions AND you can control what URL your
users hit.  It's not a sufficient solution, though.  We need a way to
re-assign the target of the "New Issue" button or to provide per-repo
templates.

**Comment by modest** [comment]
@ehausen In case anyone else stumbles across this... I figured out how to assign multiple labels

`&labels[]=FOO&labels[]=BAR`

**Comment by askucher** [comment]
+1

**Comment by anewuser** [comment]
@askucher You can follow issues by clicking on the "Subscribe" button on the sidebar. Typing "+1" won't make it become a reality faster. It just makes all of us receive useless emails and notifications with your "+1". If you read the frontpage, you'll see that [this isn't even an official page](https://github.com/isaacs/github):

> This is not the actual repository for the GitHub website.

**Comment by kevinSuttle** [comment]
As of today, the proper URL structure is `&labels=`

**Comment by cvrebert** [comment]
Templates for new issues is one of the features requested in https://github.com/dear-github/dear-github

**Comment by todb-r7** [comment]
@cvrebert, signed!

**Comment by kevinSuttle** [comment]
Yep. See also: https://github.com/kevinSuttle/github/issues/32

**Comment by sparrc** [comment]
+1, this would be fantastic

**Comment by Rican7** [comment]
Looks like this might actually be happening:
dear-github/dear-github#125

**Comment by Whoaa512** [comment]
Looks like this now works! Yay :yellow_heart: 

Just add a file called `issue_template.md` or `pull_request_template.md`

**Comment by amerikan** [comment]
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by bigcmos** [comment]
How do you encode a project in the URL?  I tried these:
project=<ID>
project=MyProject
project[]=MyProject

**Comment by VxJasonxV** [comment]
It doesn't appear to be possible with the way the project selector is currently implemented.

**Comment by ento** [comment]
The way to assign multiple labels seems to have changed to:

```
&labels=foo,bar
```

**Comment by Bluscream** [comment]
> 
> 
> This can be done relatively easily with simple links and URL encoding. Check out what happens when you use this link: [isaacs/github/issues/new?title=foo&body=bar](https://github.com/isaacs/github/issues/new?title=foo&body=bar)

How would one use linebreaks in that? i tried `\n` and `</br>`.

**Comment by Bluscream** [comment]
> 
> 
> URL encoded newline character.

which one exactly?

**Comment by LukePrior** [comment]
I see that it is possible to create a new issue using a URL but it is possible to set the content of a new message on an issue?
